### ISSUE TITLE
Improve "About Us" and "Contact" Sections in WordWise Project

### ISSUE THREAD

**Issue by Web-Dev-Learner** [ANSHIKA-26/WordWise#1]
I would like to  improvements to the "About Us" and "Contact" sections of the WordWise project.

Router Not Responding
Content Improvements
UI and UX Enhancements
![Screenshot 2024-10-01 172159](https://github.com/user-attachments/assets/d5c8600f-7447-4848-ab49-bfa25d6f0be7)

 - Fonts,Colors and Layout.

![Screenshot 2024-10-01 172227](https://github.com/user-attachments/assets/5e42888f-b424-47f5-8cbd-063b10926701)

I would like to contribute to this issue. Could you please assign it to me? My GitHub username is Web-Dev-Learner. Looking forward to working on the improvements.

**Comment by Sneha22072005** [comment]
Hi I would like to work on this.

**Comment by swethapadmavathimukku** [comment]
Hi @ANSHIKA-26  I would like to work on this issue of changing the fonts and colors, so could you please assign me this issue

**Comment by Web-Dev-Learner** [comment]
Thank you for assigning me as a contributor to the Project , I'm excited to start contributing and help improve the project.

Could you please add the level ,  "Hacktoberfest-accepted" label and "gssoc-ext" label to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

Best regards,
Shrinedhi.M.R

**Comment by swethapadmavathimukku** [comment]
Thank you for assigning me to this issue. I will do my best to solve the issue 
and also could you please add the labels of "level","Hacktoberfest-accepted and also "gssoc-extd" label.
