### ISSUE TITLE
Color of Sign Up button in the footer is not not looking good.

### ISSUE THREAD

**Issue by vaibhavrajharsh** [ANSHIKA-26/WordWise#1002]
![Screenshot 2024-10-15 213332](https://github.com/user-attachments/assets/03ca57c8-0a82-470e-8561-e9cfa920932a)

**redesign of signup button**
you can see that the blue color text on signup button is not looking good it should be of another color

**Comment by vaibhavrajharsh** [comment]
Hey @ANSHIKA-26 ,
Please assign me this issue.

**Comment by ANSHIKA-26** [comment]
issue already raised , someone is fixing this in a PR
