### ISSUE TITLE
Improper Alignment of elements in Sign-up & comment section

### ISSUE THREAD

**Issue by Deepak0yadav** [ANSHIKA-26/WordWise#1006]
1. ### Comments are not aligned in same order:

![Screenshot 2024-10-15 220527](https://github.com/user-attachments/assets/bae07e61-3067-4487-b049-34cc8bfeeaf8)

2. ### Elements in Sign-up page are not aligned properly 

![Screenshot 2024-10-15 220730](https://github.com/user-attachments/assets/409b014c-7063-459b-8428-9ded8e8b7756)

We should fix them

**Comment by ANSHIKA-26** [comment]
1. its for 1 comment to stand out 
2. thats not even out sign up page 
![image](https://github.com/user-attachments/assets/394bc7f4-e78c-4abe-8d3c-9bf863274f8f)

this is and its perfect ! closing issue since its already fixed
