### ISSUE TITLE
Fix Header Color Bug and Enhance UI Consistency

### ISSUE THREAD

**Issue by Ganeshmoorthii** [ANSHIKA-26/WordWise#1009]
In this contribution, I resolved a bug related to the color fill of the header in the WordWise project. The issue was causing inconsistent header styling across different browsers and screen sizes. I also enhanced the UI by ensuring proper color contrast for better accessibility and user experience.

Key changes include:

Fixed header background color issue.
Improved link visibility and hover effect for a more interactive experience.
Updated the overall UI consistency across the navigation bar.
These improvements align with accessibility standards and provide a smoother user interface for WordWise users.

![Screenshot 2024-10-15 223550](https://github.com/user-attachments/assets/197fe472-e824-4b02-b15a-5f234b5ce6c3)

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
which browser are you using in this image to open the website ?

**Comment by Kavish-Paraswar** [comment]
i would like to work on this.
