### ISSUE TITLE
BUG: Faqs Text-Color not visible

### ISSUE THREAD

**Issue by harshbhar0629** [ANSHIKA-26/WordWise#1011]
**Describe the bug**
When we click on faqs then it will show me faqs page but its text color is very bad.

**To Reproduce**
1. Go to faqs.html
2. Update its css property

**Expected behavior**
When we click on faqs then it will show a decent text-color.

**Screenshots**

![faqs](https://github.com/user-attachments/assets/4b1f068b-033b-4a12-b7e7-9c107c34734c)

@ANSHIKA-26 Please assign this issue to me with labels:)

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @ANSHIKA-26
