### ISSUE TITLE
adding social media username

### ISSUE THREAD

**Issue by Aazib-at-hub** [ANSHIKA-26/WordWise#1019]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Adding username of wordwise beside their social media icons.So, that if a user wants to follow you later on he can remember the username of wordwise.

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2024-10-16 03-15-00](https://github.com/user-attachments/assets/435ed7fc-5144-407b-b262-231050f90b71)
currently it id like this.

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion! However, since Wordwise is a project and not a real website, adding actual usernames and links isn't necessary. The focus is more on the project functionality rather than live user interaction. I appreciate your input though!
