### ISSUE TITLE
Want to improve the  look of the website

### ISSUE THREAD

**Issue by Dipanita45** [ANSHIKA-26/WordWise#1022]
**Is your feature request related to a problem? Please describe.**
Add or update the css as well html properties to make more attractive

**Describe the solution you'd like**
Increase the colour constrast, transition, and many items whenever required

![Screenshot 2024-10-16 090836](https://github.com/user-attachments/assets/3676b0d7-ca9a-4601-bc46-a25f721b71c5)

Please  assign me the issue  @ANSHIKA-26 
Thank you!!!

**Comment by ANSHIKA-26** [comment]
kindly explain what do you wish to change and where  .please be as precise as possible

**Comment by Dipanita45** [comment]
Home page

**Comment by ANSHIKA-26** [comment]
I’ve already asked for a clear description of the changes you want to make to the homepage UI. If you want this to be considered, you must provide specific details about what properties you plan to change and how. No further action will be taken on this until you do so.

**Comment by Dipanita45** [comment]
Want to add hover to the nav bar , more transition, more attractive colour
contrast and more features according to the requirements in all the page

**Comment by ANSHIKA-26** [comment]
Thanks for your suggestions, but I'm going to pass on these changes.

Hover Effects: The current simplicity of the navbar aligns with our design philosophy.
More Transitions: Adding more transitions could slow down the user experience and make the interface feel cluttered.
Color Contrast: The existing color scheme has been chosen for readability and consistency. Changing it could compromise this.
More Features: The current features meet the project's requirements, and adding more may lead to unnecessary complexity.
I appreciate your enthusiasm, but we need to maintain our current direction
