### ISSUE TITLE
Updation in feedback page

### ISSUE THREAD

**Issue by khushi1315** [ANSHIKA-26/WordWise#1031]
Contact Us and Give Feedback lands to the same page. Feedback page should be different from contact page as both serves different purpose. Feedback should focus on gathering opinions or ratings.
**A proper feedback page should include:**
Rating system (e.g., stars or thumbs up/down).
Category selection for feedback (e.g., website design, blog content, user experience).
Optional comment box for detailed input.
Optional contact info (not required for submission).
A privacy assurance note ensuring anonymity unless contact info is provided.
A thank you message after submission to show appreciation.
I can improve it using my skills .
 Kindly assign me this work under gssoc-ext , hacktoberfest and level of your choice.

**Comment by ANSHIKA-26** [comment]
we already have rating , text input , contact info , we do not wish to keep it anonymous ! 
i will be closing this issue since you do not wish to do any new significant changes to the page
