### ISSUE TITLE
text colour  in FAQ  not visible properly in dark mode 

### ISSUE THREAD

**Issue by REHAN-18** [ANSHIKA-26/WordWise#1033]
**Describe the bug**
1----faq section is not visible properly  in dark mode 
 2---change the text colour of this 

**Screenshots**
<img width="1319" alt="Screenshot 2024-10-16 at 4 57 15 PM" src="https://github.com/user-attachments/assets/aefb6eb8-a089-4a2e-8946-393f914856ce">

change & fix some bugs & ui 
 assign me !!!

**Comment by REHAN-18** [comment]
pls give level -2

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/5c5c0178-95e5-4b93-a395-d3efedb5cab8)
its perfect , maybe there is some issue at your end , kindly recheck

**Comment by REHAN-18** [comment]
yes right now its perfect👍🏻
