### ISSUE TITLE
All Pages Footer's Connect with us Section is Not Consistent

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1034]
**Describe the bug**
The "Connect with Us" section in the footer is inconsistent across different pages, as not all social media logos and links are present on each page.

**To Reproduce**
1. Go to the homepage.
2. Scroll down to the footer section and check the "Connect with Us" section.
3. Go to another page (e.g., About, Services, Contact) and scroll down to the footer.
4. Compare the social media logos and links present in the "Connect with Us" section across these pages.

**Expected behavior**
The "Connect with Us" section should include the same set of social media logos and links consistently across all pages of the website.

**Screenshots**
![Screenshot 2024-10-16 172651](https://github.com/user-attachments/assets/72e8b7f7-6645-4cfc-a0f8-83b22bd834a9)
![Screenshot 2024-10-16 172705](https://github.com/user-attachments/assets/fb396f2c-97be-4cce-81e7-1bef8f227cf8)

**Additional context**
On home page github link is absent
On Blog page twitter link is absent, etc.

**Comment by shivam8112005** [comment]
hey @ANSHIKA-26  can you please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
similar issue already exists !
