### ISSUE TITLE
Unclear visibility of button

### ISSUE THREAD

**Issue by Bhoomidhanu12** [ANSHIKA-26/WordWise#1039]
**Describe the bug**
the signup button is extended into the screen
**To Reproduce**
1. Go to '...'index.html
2. Click on '....'open in the browser 
3. Scroll down to '....'in home page

**Expected behavior**

**Screenshots**
![Screenshot (338)](https://github.com/user-attachments/assets/83aa5bc6-ce4a-44c0-990c-fdd663b63ffc)
@ANSHIKA-26 Kindly assign this issue to me

**Additional context**

**Comment by ANSHIKA-26** [comment]
i believe the issue is with using the browser you are using , not the website , the hosted link works fine

**Comment by ANSHIKA-26** [comment]
how do you plan to fix it ?

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
