### ISSUE TITLE
Add good hover effect to all buttons for better user interaction

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1041]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when buttons on the website do not have any visual feedback when hovered over. It makes the user experience less engaging and interactive.

**Describe the solution you'd like**
I would like to add a hover effect on all buttons to provide a visual indication when users hover over them. This effect could be a slight change in background color, border, or shadow to make it clear that the button is interactive.

**Describe alternatives you've considered**
Alternatives could include adding animations or transitions for a smoother hover effect, or even applying different hover styles for primary, secondary, and disabled buttons.

**Additional context**
Something like this:

https://github.com/user-attachments/assets/ab3c620d-0c1e-424e-82e2-553c4951c0a4

**Comment by ANSHIKA-26** [comment]
which buttons ?

**Comment by shivam8112005** [comment]
of category page
