### ISSUE TITLE
Improve text color 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1042]
Texts color blends with background color, which doesn't look good.

I want to Fixed this issue properly.

@ANSHIKA-26  please assign me this task.

https://github.com/user-attachments/assets/a09c03ce-9cf0-4a57-96fa-4f27550db458

![Screenshot 2024-10-16 192323](https://github.com/user-attachments/assets/71b189bb-47a0-4f63-bfb2-a21e7972c525)

**Comment by ANSHIKA-26** [comment]
i wish to remove this faq from the footer , would you like to do that ?

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 @hiteashgupta1

**Comment by ANSHIKA-26** [comment]
from the footer of the website , just this one , not the one on homepage 
![image](https://github.com/user-attachments/assets/9197eccf-00c0-4159-9499-1907ab250be2)

do NOT remove this 
remove the 
![image](https://github.com/user-attachments/assets/cd6d9174-f703-4bb6-ba76-634cc7ee92cc)

from all footers

**Comment by Subhajit-2023-44** [comment]
> from the footer of the website , just this one , not the one on homepage ![image](https://private-user-
> 
> do NOT remove this remove the ![image](https://private-user-images.githubusercontent.com/114569262/377096051-
> 
> from all footers

I didn't understand, are you saying that I just remove "FAQ" section from all footers?

![Screenshot 2024-10-16 201715](https://github.com/user-attachments/assets/7ef73dee-64a0-429f-b6f7-ad22340b9bc3)

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26
