### ISSUE TITLE
[FEATURE] Add Translation Tool 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1044]
I want to add a Translation Tool(all language) properly.

@ANSHIKA-26  PA please assign me this task.

![Screenshot 2024-10-16 193659](https://github.com/user-attachments/assets/aacd784d-2e2c-4e3a-90bd-60e3dd85dfdc)

**Comment by ANSHIKA-26** [comment]
sure , add to all pages

**Comment by ANSHIKA-26** [comment]
do it this way -
1. there should be only 1 translation button in the navbar on the homepage
2. on clicking the whole website will be translated to another language

**Comment by Subhajit-2023-44** [comment]
> do it this way -
> 
> 1. there should be only 1 translation button in the navbar on the homepage
> 2. on clicking the whole website will be translated to another language

PA Navbar is already filled with so many buttons, there is no extra space for new buttons..

![Screenshot 2024-10-16 195921](https://github.com/user-attachments/assets/879c207e-1535-449c-85ca-baff463a6177)

I want to add the translate button to the bottom left corner.  Which will make this website more beautiful..
Like this -

![Screenshot 2024-10-16 200456](https://github.com/user-attachments/assets/f5775dca-9338-4e78-8014-b997a6076b9f)
![Screenshot 2024-10-16 200440](https://github.com/user-attachments/assets/6bb95567-953f-44e4-b27e-51f714c0434a)

Can I start ??

**Comment by Subhajit-2023-44** [comment]
> sure , add to all pages

Of course

**Comment by ANSHIKA-26** [comment]
how about adding it in the drop down instead ? along with login and signup ?

**Comment by ANSHIKA-26** [comment]
it will look weird on the left , but you are right the navbar is already filled and no space , try to figure something out ?

**Comment by Subhajit-2023-44** [comment]
> how about adding it in the drop down instead ? along with login and signup ?
> it will look weird on the left , but you are right the navbar is already filled and no space , try to figure something out ?


In my opinion removing some buttons from navbar is not right because all buttons are important..

& adding it to the drop down will make it harder for users to find it, not easier

Don't get me wrong but I don't think it would look weird in the bottom left corner... because I've already add this kind of translation tool many times and they gave me Level 3 for it..

![Screenshot 2024-10-16 231121](https://github.com/user-attachments/assets/5e79fa1f-2625-4180-ae49-90a2d041e72f)
![Screenshot 2024-10-16 231016](https://github.com/user-attachments/assets/9dd69b88-0f03-4526-952e-3e1c3dd59657)
![Screenshot 2024-10-15 202728](https://github.com/user-attachments/assets/d8aed8b4-7822-41d2-9671-82ed25a4bfd6)

**Comment by Subhajit-2023-44** [comment]
& it is easy for users to find and use it

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 can I start ??

**Comment by ANSHIKA-26** [comment]
yep

**Comment by Subhajit-2023-44** [comment]
> yep

Okay 👍🏻
