### ISSUE TITLE
changing Contact Us page to the next level using good styling css

### ISSUE THREAD

**Issue by Debmallya-03** [ANSHIKA-26/WordWise#1046]
I want to change the contact us page styling by using good effects on the page.

Please assign me this issue @ANSHIKA-26 mam as it is almost ready I am attaching the demo video down.

BEFORE:
![contact](https://github.com/user-attachments/assets/3504883e-855c-47a8-a06f-4696d13c203b)

What I want to make:
![contact1](https://github.com/user-attachments/assets/cf89f847-8c04-4a6c-b85a-b781e3346360)

Demo Video Link:
https://drive.google.com/file/d/17BamyQ2RuTqV4PutPU7Q3UnWiBE-BQMe/view?usp=drive_link

**Comment by ANSHIKA-26** [comment]
Thank you for your work on the Contact Us page! While the design is good, it doesn't align with the color palette and overall theme of the website. To maintain consistency, I'll have to reject this for now.

**Comment by Debmallya-03** [comment]
@ANSHIKA-26 mam it was just a demo I was showing you .. 
I will adjust with the colour palette of the website please assign me this issue

**Comment by Debmallya-03** [comment]
I will make it according to the theme
