### ISSUE TITLE
Login/Signup not working (BACKEND)

### ISSUE THREAD

**Issue by Sourabh782** [ANSHIKA-26/WordWise#1047]
**Describe the bug**
While working on an issue ( #853 ), i noticed the login and signup functionality is not working. So i wanted to work on login and signup routes to make them functional.

**Expected behavior**
When an user login or signup, his data should be sent to backend and then stored on database.

So i wanted to work on implementation of backend working.

**Comment by ANSHIKA-26** [comment]
hey , what is the issue exactly ?

**Comment by ANSHIKA-26** [comment]
i need to make a mongo db connection , i will be making it soon and updating the env variables , anything except that ?

**Comment by Sourabh782** [comment]
No like, in backend/login-auth we are just checking data of user in local storage, I wanted to implement that function like proper backend

**Comment by ANSHIKA-26** [comment]
how exactly ? jwt ?

**Comment by ANSHIKA-26** [comment]
oh okayy , go ahead
