### ISSUE TITLE
UI Improvement of a section

### ISSUE THREAD

**Issue by sindhuja184** [ANSHIKA-26/WordWise#1049]
**Describe the bug**
The UI of the below section of the project is a bit congested especially connect with us, about us and popular tags 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/9ab8997d-02e1-4aaf-8f7a-d03d6216aa48)

I would like to make the UI more attractive.

Please assign this issue to me @ANSHIKA-26 

**Additional context**

**Comment by ANSHIKA-26** [comment]
how do you wish to do this

**Comment by sindhuja184** [comment]
I would like to rearrange them basically.

Instead of three partitions I feel 2 partitions would be better.

On to the left the feature post and on right popular tags, about us, connect with us

I would like to resize the thing that are on right side so that they are in sync with the website.

If any additions please mention @ANSHIKA-26 
Hope you like my idea...

**Comment by ANSHIKA-26** [comment]
Thank you for your suggestions! However, I’m going to stick with the current layout for a couple of reasons:

Three Partitions: The three-part layout is designed to maintain a balanced presentation of our content and enhance user engagement. I believe this setup works well for our goals.

Right-Side Resizing: The sizes of the elements on the right side have been chosen for consistency and readability across the website. Changing them could disrupt this harmony.

I appreciate your enthusiasm for improving the design, but for now, we’ll maintain the current structure!
@sindhuja184
