### ISSUE TITLE
Add a title for the list of blogs on main page

### ISSUE THREAD

**Issue by sanjanamb06** [ANSHIKA-26/WordWise#1051]
**Describe the solution you'd like**
I want to add a title for the website just below the nav bar and above all the list of blogs such as "Stories That Connect" or "Voices Unfiltered" or just a simple title "Blogs" such that when people visit the website they know what is down below

**Additional context**
![Screenshot 2024-10-16 204438(1)](https://github.com/user-attachments/assets/7b2425e2-ccde-4614-af50-91418b5998dd)

**Comment by sanjanamb06** [comment]
@ANSHIKA-26 pls assign me this task will do it immediately

**Comment by ANSHIKA-26** [comment]
we dont need a title here
