### ISSUE TITLE
Bug : Fix CORS Error in Newsletter Subscription

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1052]
### Feature Request: Fix CORS Error in Newsletter Subscription

**Description:**
There is currently an error occurring when users attempt to subscribe to the newsletter due to a CORS (Cross-Origin Resource Sharing) issue. This error prevents successful subscription and needs to be resolved to ensure a smooth user experience.

**Additional Information:**
- 
![image](https://github.com/user-attachments/assets/81b476cf-b7ae-4119-b1d5-1cf18ebbb743)

@ANSHIKA-26 
Pls assign me this issue and give me level3,gssoc-extd,hacktoberfest,etc

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Pls assign me this issue and give me a label

**Comment by Abhi0049k** [comment]
@ANSHIKA-26, Please assign me this issue

**Comment by ygowthamr** [comment]
@ANSHIKA-26 

I am working on this  and I am going to pr tmr or day after 
Pls don't take any decisions

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Give me some time I will make a pr

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
I think someone changed the logic of this code. Now it is not saving and showing the message which is hard coded.

**Comment by ANSHIKA-26** [comment]
thats okay , we already have a MERN wordwise app which is working with a better backend , lets leave this , thanks
