### ISSUE TITLE
Dark Ui for the feedback page is not working

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#1054]
**Describe the bug**
In dark mode the feedback page is not working

**To Reproduce**
1. Go to main page
2. Click on feedbakc

**Expected behavior**
Proper dark mode

**Screenshots**
![image](https://github.com/user-attachments/assets/6df9cecc-f4eb-444d-9185-e880710f53a7)

**Comment by ANSHIKA-26** [comment]
check again , its working
