### ISSUE TITLE
Improving Send button functionality on Contact us Page 

### ISSUE THREAD

**Issue by Devanshu1603** [ANSHIKA-26/WordWise#1056]
**Is your feature request related to a problem? Please describe.**
When Send button is clicked it doesn't respond properly.

https://github.com/user-attachments/assets/0d8cc134-1d30-445f-b021-64afe2594b76

**Describe the solution you'd like**
i want that on clicking submit button an alert stating that your message was send successfully and text field got cleared.

https://github.com/user-attachments/assets/48ecbce6-9d4d-4a6a-90aa-6a94de884aaa

**Comment by Devanshu1603** [comment]
@ANSHIKA-26  please assign me this issue under gssoc-extended . I have already made the changes just waiting for you to assign me and i will raise the PR.

**Comment by ANSHIKA-26** [comment]
@Devanshu1603 we are planning to club the contact us and give feedback page soon , so this issue wont exist :)

**Comment by Devanshu1603** [comment]
@ANSHIKA-26  you mean you are removing those pages.

**Comment by ANSHIKA-26** [comment]
yes ..planning to remove contact us , and integrate a part of it into feedback
