### ISSUE TITLE
Scroll to top button is not present in the contact us page.

### ISSUE THREAD

**Issue by meetarora10** [ANSHIKA-26/WordWise#1059]
**Is your feature request related to a problem? Please describe.**
Scroll to top button is not present in the contact us page.

**Describe the solution you'd like**
I want to add a scroll to top button in the contact us page similar to home page.

**Additional context**
![Screenshot (1147)](https://github.com/user-attachments/assets/13ef735a-3409-4ab8-b9c6-5cb3ee3b929a)

**Comment by ANSHIKA-26** [comment]
its a very small page , the button isnt needed there thank you !
