### ISSUE TITLE
Dark mode header color appears inconsistent when switching from light.

### ISSUE THREAD

**Issue by agarwalbhargavi** [ANSHIKA-26/WordWise#1060]
Generally people switches to dark mode while working in dark place so that their eyes does not have to suffer much strain, but the problem here is while going from light to dark mode the header tool bar is not at all affected and while it covers around 20% of the screen , I would like to make some changes to it so that the dark theme does its job properly

change of colour of header tool bar or changing the position or size might help this issue

**Additional context**
The tools in the header tool bar seems improperly aligned. i would like to work on that too. i would also like to work on the logo as it seems very monotonous

<img width="953" alt="light mode" src="https://github.com/user-attachments/assets/4018bb04-f92f-44a6-8514-91b52654fa17">
<img width="957" alt="dark mode" src="https://github.com/user-attachments/assets/6c848125-d958-4abd-886d-a92b30049bd8">
 

i would like to work on this issue and do my best to fix it. Kndly assign me this issue @ANSHIKA-26

**Comment by agarwalbhargavi** [comment]
@ANSHIKA-26  can you please assign me this issue?

**Comment by ANSHIKA-26** [comment]
the logo is fine , just make ensure you made dark mode navbar for all pages

**Comment by agarwalbhargavi** [comment]
sure.

**Comment by ANSHIKA-26** [comment]
fixed
