### ISSUE TITLE
Mobile responsiveness issue

### ISSUE THREAD

**Issue by Sourabh782** [ANSHIKA-26/WordWise#1064]
**Describe the bug**
The site is not responsive in mobile views

**Expected behavior**
Site should be responsive on all devices

**Screenshots**

![Screenshot_20241016_225129_Chrome](https://github.com/user-attachments/assets/02ee0412-7d7e-4d14-806a-d8d8a425fbff)

**Additional context**

**Comment by ANSHIKA-26** [comment]
#806 already
