### ISSUE TITLE
add language translator 

### ISSUE THREAD

**Issue by ananyag309** [ANSHIKA-26/WordWise#1066]
add language translator to provide ease and user friendly approach

**Comment by ANSHIKA-26** [comment]
same as #1044

**Comment by ANSHIKA-26** [comment]
I'm closing this issue because it is a duplicate. There’s a clear expectation to check existing issues before submitting a new one. Ignoring this not only wastes time but also clutters the repository. Please make sure to follow this guideline in the future to avoid further issues.
