### ISSUE TITLE
Excessive Size of Newsletter Section

### ISSUE THREAD

**Issue by Subham1** [ANSHIKA-26/WordWise#1074]
**Describe the bug**
The "Subscribe to Our Newsletter" section takes up too much vertical space, impacting the overall design of the webpage. The section looks oversized and does not align with the rest of the content, making the design feel unbalanced. It also fills a large portion of the page, which is not typical for a newsletter form and disrupts the flow of the layout.

**Expected behavior**
The newsletter section should be more compact, typically located in the footer area or as a smaller component within the layout. It should have medium size and better design integration, ensuring that it doesn't overwhelm the page or affect the visual balance.

**Screenshots**
![Screenshot 2024-10-17 001913](https://github.com/user-attachments/assets/851cc305-0fb8-4dc1-8d89-b6c2e51c27ea)

could you pls assign this work under gssoc ext

**Comment by Subham1** [comment]
@ANSHIKA-26  assign me the work

**Comment by priyanshasharma001** [comment]
hello Shubham assign this to me

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by ANSHIKA-26** [comment]
PR already made
