### ISSUE TITLE
Clicking on blog image does not redirect to the blog

### ISSUE THREAD

**Issue by AkshatSharma5** [ANSHIKA-26/WordWise#1078]
**Describe the bug**
On clicking on the image of a blog, nothing happens, the user is not directed to the blog the image refers to, which is quite absurd.

**To Reproduce**
1. Go to home page
2. Click on image of any blog
3. This doen't redirect the user to anywhere.

**Expected behavior**
On clicking the image it should take the user to the blog it refers to.

**Screenshots**

![image](https://github.com/user-attachments/assets/39a350f7-bf98-4781-a8d6-f69ba448852d)

**Comment by AkshatSharma5** [comment]
Please assign me this issue as I have the created issue and well motivated to resolve it.
Thanks!

**Comment by mansi066** [comment]
@ANSHIKA-26  Please assign me I want to work on this issue.

**Comment by ANSHIKA-26** [comment]
@AkshatSharma5 ?

**Comment by AkshatSharma5** [comment]
This issue was **completed** already, 3 weeks before @ANSHIKA-26 . Please close this issue now...
