### ISSUE TITLE
Frequently asked Question section is not responsive on mobile view

### ISSUE THREAD

**Issue by srivishnu2805** [ANSHIKA-26/WordWise#1086]
**Describe the bug**
Frequently Asked Question section is not responsive on mobile view

**To Reproduce**
We should add media query and meta tags for the whole website to be responsive so that every section would be responsive

**Expected behavior**
If it is not responsive the readers face the issue of scrolling left and right often to read it 

**Screenshots**
If applicable, could you add screenshots to help explain your problem?
![image](https://github.com/user-attachments/assets/a4f3bcff-c9ef-42a4-ae2e-d34437ff7d42)

**Additional context**
Please feel free to add any other context about the problem here.
Please assign me the task  to solve it

**Comment by ANSHIKA-26** [comment]
issue already exists , someone else is working on it
