### ISSUE TITLE
Adding github action workflow for PR validation

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1091]
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include Fixes #NEW

@ANSHIKA-26 
Pls assign me this issue and give me level3,gssoc-extd,hacktoberfest

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Assign me this task and give me level3

**Comment by ANSHIKA-26** [comment]
add checks for 
1. screenshot
2. fixes #issue number (the exact same format should be in description)
3. template being followed

in case the contributor has ignored any of the points , just automate it to add the comment "please follow PR template, no further action will be taken unless you follow all points of the template ! "

**Comment by ANSHIKA-26** [comment]
also add an automated check , if there is any merge conflict then it asks them to resolve conflict !
