### ISSUE TITLE
Add Twitter Link to "Leading Blog" and "Start Writing" Sections

### ISSUE THREAD

**Issue by paricharm** [ANSHIKA-26/WordWise#1092]
**Is your feature request related to a problem? Please describe.**
Yes, the absence of a Twitter link and symbol in the "Leading Blog" and "Start Writing" sections presents a problem for user engagement. Without these links, users may find it more challenging to connect with us on social media platforms. This can lead to missed opportunities for sharing content and engaging with our audience, ultimately limiting the reach and visibility of our blog and writing initiatives. By adding these links, we can facilitate easier access to our Twitter account, encouraging more interaction and promoting our content effectively.

**Describe the solution you'd like**
Add a Twitter icon and link to the "Connect with us" section, alongside the existing Facebook and Instagram icons. This will enhance user engagement by providing direct access to our Twitter profile. Ensure the icon is visually consistent and responsive across all devices.

![twitter](https://github.com/user-attachments/assets/fdee0263-e43b-4bf9-871b-d91ab13b4f40)

Name : Moumita Halder
Participant Role : GSSOC, Hacktoberfest 2024
I would like to work on this issue. Please assign it to me @ANSHIKA-26

**Comment by paricharm** [comment]
I would like to work on this issue. Please assign it to me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
@paricharm fix this issue in ALL pages

**Comment by paricharm** [comment]
@ANSHIKA-26 Yea.... sure will fix it as soon as possible

**Comment by ANSHIKA-26** [comment]
fixed already
