### ISSUE TITLE
Remove double feedback button in Home page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1094]
I want to fixed this UI issue & want to remove double feedback button in Home page

@ANSHIKA-26  please assign me this task.

![Screenshot 2024-10-17 115441](https://github.com/user-attachments/assets/5884c78a-1f32-4456-85ab-88ac7baf079c)

**Comment by ANSHIKA-26** [comment]
yep , do it in the current pr

**Comment by Subhajit-2023-44** [comment]
> yep , do it in the current pr

Okay
