### ISSUE TITLE
Scroll Not Working on Writing Page, Hamburger Menu Not Working on pages except Home Page, Navbar Adjustment & Blog Page Text Visibility 

### ISSUE THREAD

**Issue by srishti023** [ANSHIKA-26/WordWise#1097]
### Scroll Issue on Writing Page:
The **scroll functionality is not working on the writing page**, preventing users from navigating through the content.

### Hamburger Menu Issue:

**The hamburger menu is functional on the home page, but it is not working on any other pages,** such as the blog and contact pages. This breaks the navigation experience on mobile screens.

### Navbar Adjustment for Small Screens:

The **navbar requires adjustment on small screens** to provide a clean and user-friendly interface. Currently, it does not resize well and disrupts the visual flow of the page.

### Text Visibility on Blog Page:

The **text on the blog page is not clearly visible,** This affects readability, especially on smaller devices.

### Steps to Reproduce:

Open the website on mobile or small screens, 

Go to the writing page, try scrolling.

navigate to any page other than the home page, and try using the hamburger menu.

On small screens, observe the navbar's behavior.

Visit the blog page and check the text readability.

Expected Behavior:

The scroll should work on all pages.

The hamburger menu should function correctly across all pages.

The navbar should be clean, responsive, and visually appealing on all screen sizes.

The text on the blog page should be clearly visible and easy to read.

### Current problem :

https://github.com/user-attachments/assets/d54b95f3-4969-4fd6-a508-6efb74489c42

![Screenshot_2024-10-17-12-39-16-263-edit_com android chrome](https://github.com/user-attachments/assets/155297c5-6f2d-46c4-abb7-c0d99d630b16)

![Screenshot_2024-10-17-12-40-26-051-edit_com android chrome](https://github.com/user-attachments/assets/467bc311-1b9e-48fa-9f0c-c267b19b205c)

![Screenshot_2024-10-17-12-42-51-319-edit_com android chrome](https://github.com/user-attachments/assets/e03ffb41-0829-45c4-9c8f-353effe38295)

**Comment by srishti023** [comment]
please assign me this issue i want to fix it and contribute in this amazing project!

**Comment by ANSHIKA-26** [comment]
navbar under re construction , start writing page is also being re designed , kindly raise the issue if it still exists after i merge PRs from these issues
