### ISSUE TITLE
Enhancing User Experience in the FAQ Section

### ISSUE THREAD

**Issue by Anushka-200617** [ANSHIKA-26/WordWise#1100]
Issue Description: The FAQ section right now is pretty boring and doesn't have any interactive features. This can make it hard for users to stay interested. People like it when they can see changes or get feedback as they interact with a website. Without things like hover effects or transitions, users might miss out on important information because they aren’t fully engaged.

![image](https://github.com/user-attachments/assets/2406ffa3-d90c-42c7-80e3-a71c9fae0c24)
**I suggest the following solution**
1.Implement hover effects and visual feedback for enhanced engagement.
2.Add clear icons for expand/collapse functionality and smooth animations.
5.Use animations for expanding/collapsing answers to create a dynamic experience.
6.Provide immediate visual feedback through animations and color changes.

@ANSHIKA-26
Pls assign me this issue and give me level2,gssoc-extd,hacktoberfest labels

**Comment by ANSHIKA-26** [comment]
#991
