### ISSUE TITLE
Improving layout of the home page.

### ISSUE THREAD

**Issue by elinabhasin** [ANSHIKA-26/WordWise#1104]
The GAMING CHRONICLES card on the home page is a bit off grid.

**Expected behavior**
Making it inline with the rest of the cards will make the UI look neat.

**Screenshots**
![image](https://github.com/user-attachments/assets/a52db0d6-6e36-4536-8c10-ec7fa2e73d7b)

I'd like to work on this issue..so, i request you to please assign this to me and i'll start working on the PR.
Thank you!

**Comment by ANSHIKA-26** [comment]
it seems good enough to me , issue too little to fix sorry :)
