### ISSUE TITLE
Visibility and alignment of social media icons.

### ISSUE THREAD

**Issue by elinabhasin** [ANSHIKA-26/WordWise#1105]
The health and wellness page does not show the twitter (X) icon and the rest of the icons are not in place. This could be fixed to enhance the UI.

![image](https://github.com/user-attachments/assets/e004ba33-5c0b-44a7-828f-7252dbb07272)

Please assign this issue to me. I'd like to work on it. Thank you!

**Comment by elinabhasin** [comment]
This is the case with many cards. I'd like to improve it.

**Comment by ANSHIKA-26** [comment]
#1092
