### ISSUE TITLE
[BUG]: Adding the front-end files in a separate directories like `client` or `front-end`

### ISSUE THREAD

**Issue by tejasbenibagde** [ANSHIKA-26/WordWise#1109]
## **Description**
Manageable Front-end
Currently, our project has a separate directory for the back-end, but the front-end files are not organized into a dedicated directory. This lack of structure is causing scalability issues and may lead to complications in the future, particularly when establishing API connections through global state management in the front end using technologies like Redux and Redux Toolkit.

***Proposed Changes***
Create a Separate Front-end Directory:

Move the existing front-end files into a new directory to improve organization and scalability.
Establish a Clear Folder Structure:

Implement a more manageable folder structure to handle different components of the front end. The proposed structure is as follows:
```bash
Copy code
`/Backend`              # Backend Related Files
`/Frontend`             # Frontend Related Files
    ├── `index.html`    # Entry Point of the Application
    ├── `Pages`         # All Pages of the Application (e.g., Home, About, Blogs, Contact)
    ├── `Animations`    # Animation Related Files
    ├── `CSS`           # All CSS Files
    ├── `JS`            # All JS Files
    ├── `Others`        # All the other related folders...
    └── `Dist`          # Production Build
```
This restructuring will enhance the maintainability of our codebase and streamline the development process moving forward.

**Comment by tejasbenibagde** [comment]
@ANSHIKA-26 I want to hear your thoughts on this before I start working on it.

**Comment by ANSHIKA-26** [comment]
im okay , take a lot at pr #1095 , wont you encounter issues like this PR ?

**Comment by tejasbenibagde** [comment]
I won't encounter the same issues as that PR cause I have a better way of solving this problem. What I'll do is I'll keep the current files the same without changing anything in them. I'll copy all the files related to frontend and paste it inside a frontend directory and refactor that copied code instead of changing actual. So even if some changes come in the real file they won't have any merge conflicts with the front-end directory. So in the future we will start deleting the files outside of the frontend and backend directory in a way that they don't create conflicts.

**Comment by tejasbenibagde** [comment]
@ANSHIKA-26 I tried to improve the readability of the code while keeping the same features, but it's difficult due to unnecessary and confusing components in different parts of the project. So, I’ve decided to rebuild the entire frontend from scratch, keeping the same functionality but changing the UI. Don’t worry, I won’t modify the existing code. I'll create a new folder called 'Frontend' for the changes.

**Comment by ANSHIKA-26** [comment]
okay..
and you will be deleting files from outside of the frontend folder ?

**Comment by ANSHIKA-26** [comment]
@tejasbenibagde Hey, are you sure this will work out? I'm a bit worried after closing another PR related to this without merging it, and I couldn’t award points for that. Since it’s nearly the end of the contribution period, I just want to make sure you’re confident about this.

If you haven’t put in too much effort yet or aren’t 100% sure it’ll work out, no pressure from my side! If it feels too complex or challenging, feel free to unassign yourself—there's absolutely no problem with that. Thanks again for your efforts

**Comment by tejasbenibagde** [comment]
@ANSHIKA-26 I'm keeping the files outside of the frontend folder as it is for now because if I do any changes in them or even try to remove them will lead to the merge conflicts. So I want to go step by step. Like let me first create the working frontend directory. And after that little by little we can start deleting the unnecessary files outside of the backend and frontend folder. It will surely take the time but it is way better than making a huge change all of a sudden without proper planning.

**Comment by ANSHIKA-26** [comment]
yep , this makes sense , a lot of PRs are being merged everyday , so we cant just delete things from root directory altogether, just to make it clear- 
after u make completely new frontend UI folder , the site will still be hosted as a static site on github pages right ?

**Comment by tejasbenibagde** [comment]
> @tejasbenibagde Hey, are you sure this will work out? I'm a bit worried after closing another PR related to this without merging it, and I couldn’t award points for that. Since it’s nearly the end of the contribution period, I just want to make sure you’re confident about this.
> 
> If you haven’t put in too much effort yet or aren’t 100% sure it’ll work out, no pressure from my side! If it feels too complex or challenging, feel free to unassign yourself—there's absolutely no problem with that. Thanks again for your efforts

Don't worry I'll uplift your project from ground zero to the production ready full stack application just keep a little trust in me.

**Comment by ANSHIKA-26** [comment]
im confused about hosting it , since it will have 2 frontends , one inside the folder and one in root directory

**Comment by tejasbenibagde** [comment]
Nah I'm making the contributions but don't host it yet. Since it might have many bugs at first and you might want to have your own opinions about my frontend Design. We can discuss these design topics and I'll fix them in the next PR. If you like the final result you can host the frontend in the free hosting providers like netlify or GitHub sheets etc. how does it sounds?

**Comment by ANSHIKA-26** [comment]
sounds perfect ! go ahead !

**Comment by ANSHIKA-26** [comment]
That’s really awesome of you! I truly appreciate your dedication and understanding of what open source is about. It’s rare to find contributors who prioritize meaningful work over points, and it really shows your commitment. I’m glad you’re confident about this—thank you for your effort and for keeping the project’s best interests at heart !

**Comment by tejasbenibagde** [comment]
> That’s really awesome of you! I truly appreciate your dedication and understanding of what open source is about. It’s rare to find contributors who prioritize meaningful work over points, and it really shows your commitment. I’m glad you’re confident about this—thank you for your effort and for keeping the project’s best interests at heart !

At first I wanted to enter the compitition for winning but I quickly realized that the participants are just spamming the PR and Issues just for points even if it does not make project any better that what it currently is. So I gave up on contributing for points. I'm now working only because I love the OpenSource.

**Comment by tejasbenibagde** [comment]
@ANSHIKA-26 By the way I'll be opening the PR for this issue today at night.
