### ISSUE TITLE
Improve text color & add text boxes color and shadow in Leading Blog page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1110]
When you select dark mode these text color blends with background color, which doesn't look good..
![Screenshot 2024-10-17 173758](https://github.com/user-attachments/assets/0a63e0ba-5dd6-445f-b0b8-af899918f46e)

& this text box doesn't look good, I want to customize it by adding background color and shadow for both dark and light mode -

![Screenshot 2024-10-17 173924](https://github.com/user-attachments/assets/0fcb5a61-8a05-4c00-9909-93584552bed6)
![Screenshot 2024-10-17 173939](https://github.com/user-attachments/assets/3fd6f384-688a-42f9-a5eb-1d182cc5d07f)

like this -
![Screenshot 2024-10-17 174019](https://github.com/user-attachments/assets/6575503d-1e41-4b33-ab5f-addc8e52676a)
![Screenshot 2024-10-17 174026](https://github.com/user-attachments/assets/0c55c1e3-9f2a-4037-91fe-7677f8bf5c2a)

I want to Fixed all these issue properly.

@ANSHIKA-26  please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 assign me with level 2

**Comment by ANSHIKA-26** [comment]
#1099

**Comment by Subhajit-2023-44** [comment]
> & this text box doesn't look good, I want to customize it by adding background color and shadow for both dark and light mode -

@ANSHIKA-26 

this text box doesn't look good, I want to customize it by adding background color and shadow for both dark and light mode 

??
