### ISSUE TITLE
Add missing social media icon 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1111]
A social media icon is missing here on the Privacy Policy page -

![Screenshot 2024-10-17 180206](https://github.com/user-attachments/assets/fd8b2c8e-33b4-46cf-b404-8079d23fd7ec)

In others page -
![Screenshot 2024-10-17 180245](https://github.com/user-attachments/assets/371d1ca7-a3f4-48fb-b604-b8fda0699d52)

I want to Fixed this issue properly.

@ANSHIKA-26  please assign me this task.

**Comment by ANSHIKA-26** [comment]
#1092
