### ISSUE TITLE
About link is not working they redirect to category section 

### ISSUE THREAD

**Issue by rahulbamnuya** [ANSHIKA-26/WordWise#1114]
**Describe the bug**
When we click on about link in navbar they redirect to category section 

**To Reproduce**

**Expected behavior**

**Screenshots**

Uploading WhatsApp Video 2024-10-17 at 7.40.07 PM.mp4…

**Additional context**

**Comment by ANSHIKA-26** [comment]
too small an issue to raise , someone fixing the navbar UI will fix this as well , thanks tho
