### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ANSHIKA-26/WordWise#1117]
I want to add a page to showcase all the contributors of this website. @ANSHIKA-26 can you assign me this issue,

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but I’ll have to pass on adding a Contributors page. While I appreciate the idea, it’s not a priority for the project right now, and we prefer to keep the focus on core functionality. Contributors are already acknowledged through readme . Thanks for your understanding!
