### ISSUE TITLE
Navbar Not Sticky on Scroll

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1120]
**Describe the bug**
The navigation bar is not sticking to the top of the page when scrolling, even though it is expected to remain fixed in view as the user scrolls down the page.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to the homepage (or the relevant page where the navbar is implemented).
3. Scroll down the page.
4. Observe that the navbar does not remain visible at the top of the page.
5. See error: the navbar disappears as you scroll.

**Expected behavior**
The navigation bar should remain fixed at the top of the page while scrolling, maintaining visibility at all times for easier navigation.

**Screenshots**

**Additional context**
The navbar is intended to have a sticky or fixed position but appears to be incorrectly implemented or missing necessary CSS properties for it to function as expected. The issue may be related to CSS class definitions or conflicting styles elsewhere in the codebase.

**Comment by ANSHIKA-26** [comment]
also check if the redirection links on all pages are working fine

**Comment by shivam8112005** [comment]
Ohk i'll submit this till evening
