### ISSUE TITLE
Add logo to the site.

### ISSUE THREAD

**Issue by harshbhardwaj000** [ANSHIKA-26/WordWise#1121]
your site does not have logo which is quite odd so allow me to add logo.
![Screenshot 2024-10-17 211848](https://github.com/user-attachments/assets/36876320-0b15-4e23-96ab-453e20a78932)

**Comment by ANSHIKA-26** [comment]
Thank you for suggesting the addition of a logo, but at this point, we’ve decided not to move forward with it. The current design serves the project’s needs, and a logo isn’t a priority right now. I appreciate your input, though
