### ISSUE TITLE
Adding new hover feature to social icons

### ISSUE THREAD

**Issue by aditiverma-21** [ANSHIKA-26/WordWise#1122]
![image](https://github.com/user-attachments/assets/58d80de7-f6af-4fcc-b842-74ea63ead84a)

![image](https://github.com/user-attachments/assets/56684670-fd00-4caa-98a2-cb93429397da)

I want to add these hover to the icons

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 can you add level labels and assign it to me.

**Comment by ANSHIKA-26** [comment]
Thanks for the idea, but I’m going to pass on adding the hover feature for the social media icons. The current design works well, and we want to keep it simple and consistent. The proposed hover effect doesn’t align with the overall aesthetic of the site. I appreciate your input, though !
