### ISSUE TITLE
[BUG] Sign Up Page Issue

### ISSUE THREAD

**Issue by 4F24L** [ANSHIKA-26/WordWise#1126]
### **Describe the bug**
- The sign-up page has so many styling issues.
- Password input has too much padding. [ refer vid ]
- When Entering password "Sign Up" goes upward and cut by half.
- No nav bar is there.

**To Reproduce**
1. Go to https://anshika-26.github.io/WordWise/signup.html
2. Click on Inputs
3. See error

**Expected behavior**
- All inputs have the same feature.
- Sign up text fixed position.
- Nav bar should be there.

**Screenshots**

https://github.com/user-attachments/assets/83ba5dc8-c3c1-4b24-9717-377d5cdfe7e5

**Additional context**

**Comment by ANSHIKA-26** [comment]
thats not our signup page , kindly check from the main site again , its just a rough page someone was working on
