### ISSUE TITLE
[BUG] Login Page Issue

### ISSUE THREAD

**Issue by 4F24L** [ANSHIKA-26/WordWise#1128]
**Describe the bug**
- Login page inputs have padding issues.

**To Reproduce**
1. Go to https://anshika-26.github.io/WordWise/login.html
2. See error

**Expected behavior**
Standard styling should be maintained.

**Screenshots**
![image](https://github.com/user-attachments/assets/36f01820-e12b-4aa9-bcd5-872a126dca38)

**Additional context**

**Comment by ANSHIKA-26** [comment]
wrong page again :) check it 
![image](https://github.com/user-attachments/assets/c1243e83-082f-48a0-aa94-07754c36711e)
this is our design

**Comment by 4F24L** [comment]
> wrong page again :) check it . this is our design

Check this https://anshika-26.github.io/WordWise/login.html

**Comment by ANSHIKA-26** [comment]
as said in the signup issue , this is a stray file , we plan to remove it soon , its not linked to our main page , kindly navigate to https://anshika-26.github.io/WordWise/ 
click profile 
click login

**Comment by 4F24L** [comment]
![image](https://github.com/user-attachments/assets/1119248f-df89-4fbc-afc8-f382849b8782)


in footer sectiion. SIGN ME UP

**Comment by ANSHIKA-26** [comment]
okay , thanks for pointing out , this is a stray file and will be removed from this link soon !
