### ISSUE TITLE
[BUG] Footer Link Icons Jittering on About Page

### ISSUE THREAD

**Issue by 4F24L** [ANSHIKA-26/WordWise#1130]
**Describe the bug**
- Footer Link Icons Jittering refers to icons shaking or flickering on hover or load. Common causes include:

- Hover Effects & Transitions: Abrupt changes in padding, margin, or size during hover can cause icons to shift or "jump."
- Icon Size Changes: Scaling or resizing icons on hover without smooth transitions may create a jittery effect.
- Font Rendering Issues: Icons from libraries like Font Awesome may jitter due to inconsistent font rendering or alignment issues.

**To Reproduce**
1. Go to https://anshika-26.github.io/WordWise/about.html
2. Scroll down to '....'
3. See error

**Expected behavior**
Icons should not be jittery, but a hover effect should be present.

**Screenshots**

https://github.com/user-attachments/assets/e93de48e-8e1a-4ff1-8b2c-4cb82228c939

**Additional context**
Add any other context about the problem here.### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by ANSHIKA-26** [comment]
hey @4F24L instead of doing this , can you just remove this page instead ?
you would also need to change the navbar after removing it

**Comment by ANSHIKA-26** [comment]
we are thinking of not having this page , so doesnt make sense to improve it anyways

**Comment by 4F24L** [comment]
Okay.. I can remove the page.
