### ISSUE TITLE
Toggle button is too close to the user icon in the header section

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#1131]
**Description**:
In the header section of the website, the toggle button is positioned too close to the user icon. This proximity may cause confusion for users, as it can be difficult to distinguish between the two elements. Adequate spacing is needed to improve usability and visual clarity.

**Steps to Reproduce:**
Navigate to the website header.
Observe the placement of the toggle button in relation to the user icon.
Expected Behavior:
There should be sufficient space between the toggle button and the user icon to ensure that users can easily identify and interact with each element without confusion.

**Actual Behavior:**
The toggle button is positioned very close to the user icon, leading to a cluttered appearance in the header.

**Suggested Solution:**
Adjust the CSS properties (e.g., margin, padding) for the toggle button to create more space between it and the user icon.
Ensure that the new spacing maintains the overall design aesthetic of the header.
![Screenshot 2024-10-18 024440](https://github.com/user-attachments/assets/5ec703b6-1a27-4ad4-923b-4759a60985ea)

**Comment by ANSHIKA-26** [comment]
check again
