### ISSUE TITLE
Update Twitter icon on "About Us" and "Leading Blog" pages

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#1132]
**Description:**
The Twitter icon displayed on the "About Us" and "Leading Blog" pages is outdated and does not align with the latest branding guidelines. Updating the icon will enhance the visual consistency of the website and improve user recognition.

**Steps to Reproduce:**
Navigate to the "About Us" page.
Observe the current Twitter icon.
Navigate to the "Leading Blog" page.
Observe the current Twitter icon.
**Expected Behavior:**
The Twitter icon should be updated to reflect the current design standards and branding guidelines. It should be recognizable and visually appealing.

**Actual Behavior:**
The existing Twitter icon appears outdated and may not conform to the latest branding guidelines.

**Suggested Solution:**
Replace the current Twitter icon with the updated version from the official Twitter branding resources.
Ensure that the new icon is appropriately sized and styled to match the other social media icons on the pages.
![Screenshot 2024-10-18 025257](https://github.com/user-attachments/assets/38c53cd7-1f89-4bfa-b622-dbd69b545f44)

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but I'll pass on updating the Twitter icon. It's not a priority, and I can't award points for this issue. I appreciate your understanding!
