### ISSUE TITLE
Inconsistent design of "Top to Bottom" button across all pages

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#1133]
**Description:**
The "Top to Bottom" button is not uniformly designed across different pages of the website. This inconsistency can lead to a confusing user experience and diminish the overall visual appeal of the site.

**Steps to Reproduce:**
Navigate to multiple pages on the website (e.g., Home, About Us, Contact, Leading Blog).
Observe the design of the "Top to Bottom" button on each page.
**Expected Behavior:**
The "Top to Bottom" button should have a consistent design, including size, color, font, and styling, across all pages of the website.

**Actual Behavior:**
The design of the "Top to Bottom" button varies from page to page, leading to a lack of coherence in the user interface.

**Suggested Solution:**
Review and standardize the CSS styles for the "Top to Bottom" button across all pages.
Ensure that the button adheres to a single design guideline for consistent user experience.
### in main page
![Screenshot 2024-10-18 024821](https://github.com/user-attachments/assets/be6c3ecf-0a72-4f1f-9730-c1cd08f1c054)

### in leading blog page
![Screenshot 2024-10-18 025216](https://github.com/user-attachments/assets/56f21874-6171-489b-a63b-4f1aa3c10381)

**Comment by ANSHIKA-26** [comment]
@Vishwajeet594 make sure to add the main page scroll to top button on ALL PAGES

**Comment by Vishwajeet594** [comment]
ok sure

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by ANSHIKA-26** [comment]
@Vishwajeet594 ?

**Comment by 2004pra** [comment]
its still not done as it was assigned by you a  last week please allow me to do it as you have closed my issue which was in the same topic please assign this to and make it level 2 atleast mam @ANSHIKA-26
