### ISSUE TITLE
Add footer to "Start Writing" page

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#1134]
**Description:**
The "Start Writing" page currently lacks a footer, which can result in an incomplete user experience. Adding a footer will provide users with essential information, navigation links, and improve overall site consistency.

**Navigate to the "Start Writing" page.**
Observe the absence of a footer at the bottom of the page.
Expected Behavior:
The "Start Writing" page should include a footer that contains relevant information, such as copyright details, contact links, social media icons, and any additional navigation links.

**Actual Behavior:**
The page does not have a footer, leading to a lack of important information and navigation options for users.

**Suggested Solution:**
Implement a footer section at the bottom of the "Start Writing" page.
Ensure the footer includes essential elements such as:
Copyright information
Links to social media profiles
Contact information
Any additional links relevant to the site
### NO FOOTER
![Screenshot 2024-10-18 025446](https://github.com/user-attachments/assets/9beadca4-3b21-4681-8f07-315c00feebab)

**Comment by RitikaMaha** [comment]
PL. assign me this task

**Comment by itsHarsh2** [comment]
I would like to work in this project .Please assigne me this task

**Comment by Vishwajeet594** [comment]
Bro find ur own issue

**Comment by ANSHIKA-26** [comment]
@Vishwajeet594 there was a footer already , but for some reason the page isnt scrolling down , kindly fix that

**Comment by ANSHIKA-26** [comment]
@Vishwajeet594 are you working on this ?

**Comment by Vishwajeet594** [comment]
Yes mam iam working on this

**Comment by ANSHIKA-26** [comment]
fix it ASAP , you can already see how many people are creating this issue repeatedly

**Comment by ANSHIKA-26** [comment]
@Vishwajeet594 ?

**Comment by Jordian0** [comment]
@Vishwajeet594 I can work in this issue1
