### ISSUE TITLE
Add back to top button for all pages and enhance nav bar

### ISSUE THREAD

**Issue by sriraghavi22** [ANSHIKA-26/WordWise#1138]
**Is your feature request related to a problem? Please describe.**
When i navigate to other pages, I cannot find back to top button.  Also the nav bar should highlight the current page that is if i am currently viewing the category page, the category tab should be highlighted in the nav bar for better user experience.

**Describe the solution you'd like**
There should be back to top button over all the pages

![Screenshot 2024-10-18 112910](https://github.com/user-attachments/assets/63f292f1-6e59-42b9-83a5-b40f1af21dbb)

**Comment by ANSHIKA-26** [comment]
just add the button to all pages , someone else is fixing navbar

**Comment by ANSHIKA-26** [comment]
issue already assigned to someone else
