### ISSUE TITLE
[UI Enhancement] Improve Navbar Link Visibility and Aesthetics for Better User Experience

### ISSUE THREAD

**Issue by KhushiChauhan8** [ANSHIKA-26/WordWise#1139]
-> Description:
I have noticed that the navbar links (Home, Leading Blog, Start Writing, Categories, About, Contact Us, Give Feedback) could be improved for better readability and aesthetics. I suggest increasing the font size, using a darker color, and making the links bold to enhance their visibility and improve the user experience.

I would love to work on this issue and contribute to the project. Could you please assign this task to me?  
@ANSHIKA-26, please let me know if I can proceed with this enhancement!

-> Screenshots:
Here’s the current navbar for reference:
![Screenshot 2024-10-18 115435](https://github.com/user-attachments/assets/d17e3902-25a7-4000-8d95-43748d2a1e5e)

-> Suggested Changes:
- Increase the font size for better readability.
- Change the font color to a darker shade.
- Apply bold styling to the links.

**Comment by vidhi-github** [comment]
m I assigned this issue under #1171 header navbar is bit conjusted. . or is my issue closed. Kindly reply at the earliest. Thank you.

**Comment by vidhi-github** [comment]
Kindly let me know @ANSHIKA-26
