### ISSUE TITLE
UI not responsive in mobile or different size of devices 

### ISSUE THREAD

**Issue by SarangAhlawat** [ANSHIKA-26/WordWise#1142]
**Describe the bug**
Experience of the platform on different size of devices is not impressive as the size of components in the entire website got misaligned and much smaller in smaller devices.

**To Reproduce**
1. Go to 'depolyment link'
2. Using a mobile or tablet browser 
3. Check the homepage 

**Expected behavior**
Platform UI should be responsive for all size of devices to make the user experience better and seamless and the size of components on the website should be readable and interactive.

**Screenshots**
![Screenshot_2024-10-18-14-33-31-64_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/0f78768b-f231-43ef-8c76-219ccd977d3d)

![Screenshot_2024-10-18-14-33-27-83_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/324cdd38-4eb7-43b4-9f6b-02a920ad62bf)

I will make the website responsive and interactive in various size of devices. This will make the components readable for everyone even in smaller devices like smartphone or tablet.

Please assign me this issue with relevant labels so that I can improve the platform effectively.

**Comment by ANSHIKA-26** [comment]
#806
