### ISSUE TITLE
FAQ Section: No Hover Effect

### ISSUE THREAD

**Issue by neeru24** [ANSHIKA-26/WordWise#1144]
The FAQ section currently lacks a hover effect on the items, which reduces user interactivity and visual appeal. I would like to enhance the user experience by implementing a size change effect when users hover over each FAQ item. This improvement will make the section more attractive and engaging.

### Proposed Changes:

- Add a CSS hover effect that increases the size of FAQ items slightly when hovered over.
- Ensure that the transition is smooth for better visual feedback.

### Acceptance Criteria:

- The FAQ items should have a clear hover effect that increases their size.
- The transition between normal and hover states should be smooth (e.g., using CSS transitions).
- The effect should be visually appealing and improve the overall aesthetics of the FAQ section.

Kindly assign me this issue.

![image](https://github.com/user-attachments/assets/06aa7432-ba95-4658-8dee-03e06b580c69)

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but I’m going to reject the idea of adding a hover effect for the FAQ section. The current design keeps it simple and functional, and additional effects may distract from the user experience. We’ll stick with the existing setup
