### ISSUE TITLE
Font Color in Email Input Box Is Not Readable

### ISSUE THREAD

**Issue by a-n-u-vanguri** [ANSHIKA-26/WordWise#1146]
Hi ,

I just wanted to say that your project looks fantastic! I appreciate the effort that has gone into it. However, I noticed The font color in the email input box is difficult to read against the background, affecting user experience. This needs to be adjusted for better visibility. I believe improving the contrast would enhance the user experience.

I’d love to help out by addressing this issue and submitting a pull request. Could you please assign this issue to me for the GirlScript GSSOC 2024 extension?

<img width="1383" alt="Screenshot 2024-10-18 at 16 10 37" src="https://github.com/user-attachments/assets/2ec10574-e80a-4700-95b0-0717fcf2dfe3">

**Comment by ANSHIKA-26** [comment]
thanks ! but someone else already has this issue
