### ISSUE TITLE
Feat:The hover effect on "WordWise" on navbar should be smooth.

### ISSUE THREAD

**Issue by sahiladit** [ANSHIKA-26/WordWise#1149]
**Is your feature request related to a problem? Please describe.**
No,this is not related to a problem.

**Describe the solution you'd like**
I would like if the hover effect on the "WordWise" becomes smooth,it will increase User Experience.

**Comment by sahiladit** [comment]
Currently when we hover on the logo it becomes larger but there is not transition time ,so i think we  should add some transition time so that it feels smooth when we hover.

**Comment by ANSHIKA-26** [comment]
not Thanks for the suggestion, but the hover effect works just fine as it is. Adding transition time for something like this is unnecessary—it's already smooth enough. Let's not overcomplicate thing
