### ISSUE TITLE
Improve the UI Trending Post section.

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ANSHIKA-26/WordWise#1151]
improve the UI trending post section  Which was not that good enough. I would like to  improve this issue under GSSOC'24 and Hacktofest;24 
thank you.
![trending post](https://github.com/user-attachments/assets/de8485b1-a6ca-413d-a956-a7a1dada8f6e)

**Comment by Himanshu-kumar025** [comment]
@ANSHIKA-26  please  assign me on this issue .

**Comment by ANSHIKA-26** [comment]
where exactly are you viewing this section ? we removed this a long time back

**Comment by Himanshu-kumar025** [comment]
I saw this section on  Leading Blog page

**Comment by ANSHIKA-26** [comment]
recheck , i dont see it

**Comment by Himanshu-kumar025** [comment]
I am Sorry It was my mistake . there is not such kind of section
