### ISSUE TITLE
Add 3 New FAQs to the FAQ Section

### ISSUE THREAD

**Issue by Monojit-Pal** [ANSHIKA-26/WordWise#1152]
**Is your feature request related to a problem? Please describe.**
I feel that the FAQ section of the Word Wise platform could include more information to better address common user concerns. Currently, it covers some basics, but it could be enhanced to answer more technical and functional questions.

**Describe the solution you'd like**
I would like to add three new FAQs related to the platform’s features such as blog visibility settings, scheduling posts, and following other bloggers. This will help users better understand the platform's advanced functionalities.

**Describe alternatives you've considered**
I considered creating a dedicated help page, but expanding the FAQ section would keep all the essential information in one place, which is more user-friendly.

**Additional context**
![Screenshot 2024-10-18 182229](https://github.com/user-attachments/assets/a6d518fe-b5b6-4d82-8b45-7efef75af7ab)

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but I won’t be expanding the FAQ section. Adding more details would make it too long and occupy too much space on the platform. I’ll be closing this issue, but I appreciate your input
