### ISSUE TITLE
Hover : effect overlap on below text 

### ISSUE THREAD

**Issue by PREM-A261** [ANSHIKA-26/WordWise#116]
![image](https://github.com/user-attachments/assets/1e206caa-cbff-4097-93e7-7aaa3572539c)
in this img this hover effect disturbed the below text

**Comment by PREM-A261** [comment]
@PREM-A261 Please assign me this one
i want to work on this issue

**Comment by ANSHIKA-26** [comment]
you have already been assigned the issue , please go ahead
