### ISSUE TITLE
Improvement in footer 

### ISSUE THREAD

**Issue by 1754riya** [ANSHIKA-26/WordWise#1160]
Need Improvement in footer 
![Screenshot (342)](https://github.com/user-attachments/assets/dffbd805-091f-406c-9735-9a9894f8a378)

**Comment by ANSHIKA-26** [comment]
how exactly do you wish to improve ? kindly see all existing issue before commenting

**Comment by onlyymonaa** [comment]
@ANSHIKA-26 Please assign me this task for improvement in the footer. I will definitely use my HTML skills to shine your footer like a diamond.

**Comment by ANSHIKA-26** [comment]
HOW ?

**Comment by ANSHIKA-26** [comment]
@richa-k23 @monalisas21 i need clear points in what you wish to change and HOW

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
