### ISSUE TITLE
[FEATURE] Add a new page to display all contributors

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1165]
I want to add a page to showcase all the contributors of this website..

@ANSHIKA-26  please assign me this task.

![Screenshot 2024-10-19 001444](https://github.com/user-attachments/assets/353c49db-5f89-47f9-8474-c6fdf7c93a58)

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but I’ll have to pass on adding a Contributors page. While I appreciate the idea, it’s not a priority for the project right now, and we prefer to keep the focus on core functionality. Contributors are already acknowledged through GitHub contributions. Thanks for your understanding!

**Comment by Subhajit-2023-44** [comment]
> Thank you for the suggestion, but I’ll have to pass on adding a Contributors page. While I appreciate the idea, it’s not a priority for the project right now, and we prefer to keep the focus on core functionality. Contributors are already acknowledged through GitHub contributions. Thanks for your understanding!

Okay
