### ISSUE TITLE
[FEATURE] Add a ChatBot Assistant 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1166]
I want to add a ChatBot Assistant..

@ANSHIKA-26  please assign me this task.

![Screenshot 2024-10-19 001444](https://github.com/user-attachments/assets/de7344aa-d9ef-4d3a-9c17-154f9c900cb7)

**Comment by CodeVoyge** [comment]
I would like to work on this project , could you please assign this issue to me??

**Comment by ANSHIKA-26** [comment]
pr #894 is still working on it ig, so cant assign it to you

**Comment by ANSHIKA-26** [comment]
issue #215 ,

**Comment by Subhajit-2023-44** [comment]
> pr #894 is still working on it ig, so cant assign it to you

Ooo

**Comment by CodeVoyge** [comment]
???
