### ISSUE TITLE
Misleading Text "TranslationTool" Above Navbar

### ISSUE THREAD

**Issue by VidhanThakur09** [ANSHIKA-26/WordWise#1168]
**Describe the bug**
Above the navbar there is text written ( TranslationTool ), This misleading text creates a negative first impression on visitors, potentially leading them to believe that the website is not relevant to their needs or interests. It also suggests a lack of attention to user experience and a disregard for clear and informative navigation.

**To Reproduce**
1. Go to Leading blog , contact us and give feedback pages
2. above the navbar
3. text written as TranslationTool and main in navbar
4. See bug

**Expected behavior**
No text present above the navbar and the text written as main.

**Screenshots**
![Screenshot 2024-10-19 003415](https://github.com/user-attachments/assets/c4190ddd-c946-4999-aff4-5ca7c631ce58)

**Additional context**
@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" with levels,"hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.

**Comment by ANSHIKA-26** [comment]
@VidhanThakur09 make sure the whole navbar is in the same state every time we navigate to other pages as well , like if i click on leading blog , the navbar changes (its completely different ) , fix that issue as well

**Comment by ANSHIKA-26** [comment]
fix any/ all minor and obvious issues you can see with the navbar , will you be able to do so ?

**Comment by VidhanThakur09** [comment]
Yes, ma'am. It will be my pleasure to resolve all the issues related to the navbar.

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/1ee3fc94-b9e0-49b0-b233-a552a1862a5d)
space between profile and dark/light mode should be fixed 
the headings such as "leading blog " etc should be in 1 line not 2 
somewhat like -
![image](https://github.com/user-attachments/assets/c05baf7d-18bb-4867-909e-e16d00bde6e7)

**Comment by ANSHIKA-26** [comment]
> Yes, ma'am. It will be my pleasure to resolve all the issues related to the navbar.
sounds good , make sure the navbar you see at home page is the same you see while navigating to every page !

**Comment by VidhanThakur09** [comment]
Ok mam

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by ANSHIKA-26** [comment]
@VidhanThakur09 are you not done ? im waiting for this issue to be fixed before i can merge rest of the PRs , because everytime i merge a PR , it will create more problems for you , i hope you are syncing fork regularly

**Comment by VidhanThakur09** [comment]
Yes mam I will be raising the pr as soon as possible.
