### ISSUE TITLE
Give feedback page is Empty. want to add fully functional fedback form using php and sql databases

### ISSUE THREAD

**Issue by toshankanwar** [ANSHIKA-26/WordWise#1169]
**Is your feature request related to a problem? Please describe.**

Hello @say-het 
![image](https://github.com/user-attachments/assets/bb97da6a-8437-4d5c-a13a-efa307873356)

 i have noticed the feedback page is empty .so i want to add a fully functional feedback page 
I have experience of php and sql databases so please give me chance to do this.

Thanks

**Comment by meghanakn473** [comment]
@ANSHIKA-26 please assign this issue to me i can work on it

**Comment by toshankanwar** [comment]
> @ANSHIKA-26 please assign this issue to me i can work on it

@meghanakn473 i already working on this issue. can you work on different issue
