### ISSUE TITLE
header navbar is bit conjusted.

### ISSUE THREAD

**Issue by vidhi-github** [ANSHIKA-26/WordWise#1171]
**Is your feature request related to a problem? Please describe.**
would like to contain the different headlinks in in their respective divs and provide proper spacing. the divs will be having hovering effects. also would like to add a website logo or symbol related to website left to wordwise heading. this logo will be redirecting to the home page itself.

kindly assign me this issue under gssoc-extd and hacktoberfest-accepted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
#1139
