### ISSUE TITLE
Feature Implementation: Adding Multi-language Support System

### ISSUE THREAD

**Issue by Varsha-1605** [ANSHIKA-26/WordWise#1172]
I want to add this functionality so that individuals can understand the content in their native languages.

@ANSHIKA-26 I would love to work on it, Could you assign this task to me??

**Comment by ANSHIKA-26** [comment]
we already have a translator , what do you wish to add

**Comment by Varsha-1605** [comment]
@ANSHIKA-26 Just to add google translator on all the pages.

**Comment by ANSHIKA-26** [comment]
why ? we already have a translator
