### ISSUE TITLE
Ratings and Reviews page

### ISSUE THREAD

**Issue by meghanakn473** [ANSHIKA-26/WordWise#1173]
@ANSHIKA-26 please assign this issue to me i want to work on it

**Comment by meghanakn473** [comment]
@ANSHIKA-26 please assign the issue and add the level 3 label

**Comment by ANSHIKA-26** [comment]
Thank you for your suggestion to add a rating and review page, but I’ll have to reject this request as it’s not in line with the current goals of the project. Also, please don’t ask for specific labels like Level 3. Labels are assigned based on the complexity and impact of the contribution, not by request. I appreciate your enthusiasm, though!
