### ISSUE TITLE
Improve the UI of  FAQ section

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ANSHIKA-26/WordWise#1175]
In dark mode FAQ is not looking good. I would Like to work on thus issue under GSSOC'24 and Hacktofest'24 
thank you.

before:
![word wide bull](https://github.com/user-attachments/assets/2c29c478-866d-41ae-a4e0-eeabf266f307)

after:
![wordwide master piece](https://github.com/user-attachments/assets/dca2776b-743b-4031-a9b6-501d09a06221)

**Comment by Himanshu-kumar025** [comment]
@ANSHIKA-26  please assign me on this issue Officially.

**Comment by ANSHIKA-26** [comment]
what do you wish to change?

**Comment by Himanshu-kumar025** [comment]
sir I wanna to change The Styling of the the FAQ .
![Screenshot 2024-10-19 105211](https://github.com/user-attachments/assets/2786ead2-ab9d-4eeb-aa86-a40aeafd14d6)

**Comment by ANSHIKA-26** [comment]
how ? what do you wanna add ?

**Comment by ANSHIKA-26** [comment]
closing issue due to lack of response , if you still wish to work kindly open new issue with CLEAR details on what you wish to do !
