### ISSUE TITLE
Log in Discrepancy

### ISSUE THREAD

**Issue by Chinmayee-cd** [ANSHIKA-26/WordWise#1178]
I have signed up by filling out all the credentials. But when I try to login with my email id and password as I have provided in the sign up, I am not able to do so.

**To Reproduce**
1. Go to the user icon on the top right hand side of the window.
2. Click on Sign Up.
3. Register yourself as a new user by filling out all the fields.
4. Now try logging in with the same credentials.
5. It will redirect you to the Sign Up again saying that no user with that email and password exists.

**Expected behavior**
When a user logs in with the credentials used while signing up, the user must be able to log in.

**Comment by Chinmayee-cd** [comment]
@ANSHIKA-26 could you please assign me this issue?

**Comment by Chinmayee-cd** [comment]
The website link in the Girlscript Summer of Code Extended had this issue. However, once I've cloned the repository and checked it out I've realized that this error does not occur.

But there is a larger issue where the user is able to log in without signing up as there is no database in play. Shall I include MongoDB to store and validate for the login and sign up?

**Comment by ANSHIKA-26** [comment]
we already have a db , i just havent added my credentials to it yet , will do so soon , thanks for informing !
