### ISSUE TITLE
Adding map with contact us page 

### ISSUE THREAD

**Issue by Priyanshi0112** [ANSHIKA-26/WordWise#1183]
**Describe the solution you'd like**
Including a map on your "Contact Us" page provides a visual and interactive way for users to locate your business.  By embedding a map, users can see exactly where you're located, get directions, and understand nearby landmarks or streets, making it easier for them to visit.

**Benefits**

1. **SEO Optimization**: 
   Embedding a map with local information can boost your local SEO ranking. Search engines like Google prioritize businesses with verifiable location data, helping your site rank higher for local searches. This can result in increased online visibility, especially for searches involving location-specific queries like “near me.”
2.**Increased Foot Traffic**:
     With easier navigation, local customers are more likely to visit your store or office.
3.**Improved User Experience**: 
Visitors can easily find your location without leaving your site to search for it elsewhere, leading to better engagement.
4.**Convenience for Customers**:
 An interactive map allows customers to get instant directions, making it more likely they'll visit your location.

Please assign this issue to me under GSSoC-ext

**Comment by ANSHIKA-26** [comment]
its a blogging page , we dont have an address , people from various nations type in blogs , we dont need a google map !
