### ISSUE TITLE
CONTACT US 

### ISSUE THREAD

**Issue by Sakshi16175** [ANSHIKA-26/WordWise#1187]
After opening the site 2 times the contact us page is not  showing anything .
![Screenshot 2024-10-19 020932](https://github.com/user-attachments/assets/31fe36a4-0c1e-4b3d-8150-4725aa0a5a38)

**Comment by ANSHIKA-26** [comment]
check again

**Comment by ANSHIKA-26** [comment]
its there

**Comment by Sakshi16175** [comment]
i have already checked

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/25b3a427-a599-4658-b97c-4dabd1d72952)
