### ISSUE TITLE
FEEDBACK PAGE

### ISSUE THREAD

**Issue by verma2402** [ANSHIKA-26/WordWise#1188]
### DESCRIPTION
The feedback page is not complete. Its just showing the blank page. 

**Describe the solution you'd like**
I can add elements to this feedback page and create a form that would accept the feedback from the user. I can use my frontend skills to make the page attractive and align with the website theme. 

**Additional context**
![image](https://github.com/user-attachments/assets/f82c0fbf-46da-4b09-90b8-f1af5e4574f6)

Please assign this issue to me under the label gssoc and hactoberfest. I am willing to work on this.

**Comment by verma2402** [comment]
Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
fixed
