### ISSUE TITLE
FAQ enhancing

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ANSHIKA-26/WordWise#1190]
In the FAQ section, the question and the answer are not on separate lines, which makes it visually unappealing. I want to separate the question and the answer to improve readability.
![faq_separate](https://github.com/user-attachments/assets/ee713b27-9973-40d5-9fa1-060c147b6a7f)

**Comment by ANSHIKA-26** [comment]
the design right now aligns well with the theme !
