### ISSUE TITLE
Redesign the email address search bar and sign-up button

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ANSHIKA-26/WordWise#1191]
The email address search bar and the button in the footer are not visually appealing. They should be resized, and additional styling should be implemented to enhance the website's appearance.

![email_adress](https://github.com/user-attachments/assets/0b36bd84-b8ac-4e81-8c42-130b0d0fabe2)

**Comment by ANSHIKA-26** [comment]
no need for redesigning them , they are good
