### ISSUE TITLE
Extra space and an additional word occur at the top of the footer.

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ANSHIKA-26/WordWise#1192]
When we land on the blog page, the 'TranslationTool' appears above the footer, and there is some spacing from the top that looks unappealing to viewers.
![lading_page](https://github.com/user-attachments/assets/36da9696-e067-4ada-b9f8-1496a207d19d)

**Comment by ANSHIKA-26** [comment]
#1168 is working on this
