### ISSUE TITLE
Fix the overlap of the profile icon with the theme changer icon

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ANSHIKA-26/WordWise#1196]
When we land on the blog page, the profile icon and the theme changer icon in the navbar are overlapping, and there is an issue with the main text. I want to resolve this.
![ovrlap-0p](https://github.com/user-attachments/assets/dae3c97c-32d4-4d39-996f-c2ff8d128c78)

**Comment by ANSHIKA-26** [comment]
navbar under reconstruction in another issue
