### ISSUE TITLE
landing blog page twitter logo update

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ANSHIKA-26/WordWise#1198]
On the landing page of the blog, the Twitter logo needs to be updated.
![landingpage_logoupdate](https://github.com/user-attachments/assets/e2d9db4f-a306-42ac-b8ae-6281e7194182)

**Comment by mackcodes** [comment]
Name : Mayank Kumar
Participant Role : GSSOC(contributor), Hactoberfest
Please assign me this issue I can fix this up.

**Comment by ANSHIKA-26** [comment]
change it on all pages
