### ISSUE TITLE
Footer on the start writing page 

### ISSUE THREAD

**Issue by Priyanshi0112** [ANSHIKA-26/WordWise#1200]
**Describe the bug**
There is no footer on the start writing page

**Expected behavior**
Footer section must look same on all the pages of the website

**Screenshots**
![image](https://github.com/user-attachments/assets/f42774cb-53a0-446c-a09e-de7b34a8ec28)

**Additional context**

**Comment by ANSHIKA-26** [comment]
#1134 is same
