### ISSUE TITLE
Duplicate pages(both contact us and feedback pages are same)

### ISSUE THREAD

**Issue by AnishaDevi** [ANSHIKA-26/WordWise#1204]
No  need of same two page with two different options 
@ANSHIKA-26
I can delete one of the section

- [x] Gsoc contributor
- [x] Hacktoberfest Contributor

**Comment by AnishaDevi** [comment]
can you assign me with this

**Comment by ANSHIKA-26** [comment]
fixed in a new PR merge just right now
