### ISSUE TITLE
fevicon

### ISSUE THREAD

**Issue by abhi200446** [ANSHIKA-26/WordWise#1205]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
i will add fevicon for browser page for better user experience please assign me @ANSHIKA-26 
**Describe alternatives you've considered**
Using a simple text title or a default browser icon instead of a favicon
**Additional context**

**Comment by ANSHIKA-26** [comment]
already exists , you just cant see it due to github pages
