### ISSUE TITLE
NEED TO ADD "F&Q" PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [ANSHIKA-26/WordWise#1206]
**Is your feature request related to a problem? Please describe.**
A healthy website always about the user experience and the designing of the website . as i observe the designing of your work is extrs ordinary but the drawback which hits me of your website is you don't have a separate page for questions which causes unable to get reviews of your website .

**Describe the solution you'd like**
For getting the reviews of users we need a dedicated page which deals with the questions in which i make 3 section :-
1. ABOUT WEBSITE 
2. MOST SEARCHED QUESTIONS
3. FORM WHICH DEALS WITH USER PERSONAL QUESTION

**Additional context**
HERE IS THE EXAMPLE HOW THE "F&Q" PAGES LOOK LIKE :-
![Screenshot 2024-10-19 125729](https://github.com/user-attachments/assets/5ccbc4dd-cb3a-4f38-9884-38fbbaeb9674)
![Screenshot 2024-10-19 125817](https://github.com/user-attachments/assets/af39ba71-e4f0-4189-bb6b-aeac0788fa51)

I WILL CHANGE THE DESIGNING ACCORDING YOUR WEBSITE REFERENCE.

PLEASE ASSIGN ME THIS WORK UNDER GSSOC EXTD. SO THAT I WILL LOOK FORWARD TO CONTRIBUTE

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by ANSHIKA-26** [comment]
already have FAQ section , no need for page
