### ISSUE TITLE
[Style] Fix the style of Navbar in Leading blog page.

### ISSUE THREAD

**Issue by hadifarousheen** [ANSHIKA-26/WordWise#1211]
The style of Navbar is not proper.It is not placed at the right position.I want to fix the appearance of the Navbar in the leading blog page.
![Screenshot (243)](https://github.com/user-attachments/assets/18c45116-98e7-4907-87db-f78b4face2eb)

**Comment by ANSHIKA-26** [comment]
PR #1210 is for same
