### ISSUE TITLE
feedback form updated

### ISSUE THREAD

**Issue by agarwalbhargavi** [ANSHIKA-26/WordWise#1214]
<img width="956" alt="Screenshot 2024-10-19 234352" src="https://github.com/user-attachments/assets/fbfb3f26-0d2f-4532-b20a-a9b3cee5dc18">
here are some suggested changes for the feedback form

**Comment by agarwalbhargavi** [comment]
@ANSHIKA-26  could u please assign me this task.

**Comment by ANSHIKA-26** [comment]
the feedback form we have right now is nice ! we dont want this
