### ISSUE TITLE
[BUG] there is no scrollbar for "Start Writing" section

### ISSUE THREAD

**Issue by avogadroB** [ANSHIKA-26/WordWise#1216]
**Describe the bug**
There is no scrollbar, hence cannot actually submit the start writing form

**To Reproduce**
1. Go to https://anshika-26.github.io/WordWise
2. Click on 'Start Writing'
3.  Cannot Scroll

**Expected behavior**
Adding the scroll bar would enable scrolling

**Screenshots**
![image](https://github.com/user-attachments/assets/86bf4e78-4b9b-4da6-bd9c-26c02f140e67)

**Comment by avogadroB** [comment]
[ANSHIKA-26](https://github.com/ANSHIKA-26) please assign me this issue

**Comment by ANSHIKA-26** [comment]
#1134 is doing it
