### ISSUE TITLE
The login/signup option is too close to the dark mode switch

### ISSUE THREAD

**Issue by avogadroB** [ANSHIKA-26/WordWise#1218]
**Is your feature request related to a problem? Please describe.**
The sign up logo and dark mode toggle are touching, ruining the UI

**Describe the solution you'd like**
add a padding between the toggle and the login logo

![image](https://github.com/user-attachments/assets/7cf0029e-2ec3-4785-a5ef-6d730adb8084)

**Comment by avogadroB** [comment]
[ANSHIKA-26](https://github.com/ANSHIKA-26) please assign this to me

**Comment by ANSHIKA-26** [comment]
a pr is fixing this
