### ISSUE TITLE
Add Border to Each Card 

### ISSUE THREAD

**Issue by ak-0283** [ANSHIKA-26/WordWise#1219]
Issue Description:

As a contributor for GSSoC, I noticed that the cards displaying featured posts do not have a consistent border around them. Adding a border to each card would help in visually distinguishing the content and provide a cleaner, more organized layout.

Expected Outcome:

- Each card should have a uniform border to enhance the visual structure and improve the user interface (UI) design.
- The border should have appropriate styling, such as consistent thickness, color, and potentially a hover effect for interaction.

Steps to Reproduce:

1. Observe that each card currently does not have a border that separates them distinctly.

![Screenshot 2024-10-20 001432](https://github.com/user-attachments/assets/cd9e12d2-4292-4405-a95e-80b778910557)

  
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
borders become a bit too much , we did this before and it didnt work out ! sorry
