### ISSUE TITLE
add a cookie pop up

### ISSUE THREAD

**Issue by Amulya-B28** [ANSHIKA-26/WordWise#1220]
I would like to add a cookies pop up at the bottom right of the website when it loads...This feature has 3 options accept,reject and customize

![image](https://github.com/user-attachments/assets/497f6070-f851-431f-b0ef-c65bbf0e229c)

Since this website has sign up and login options, it is needed to inform the users about data privacy laws and regulations that require websites to inform users about data collection practices and obtain consent for the use of cookies.
I will also be including the "cookie-policy" file for users to read. 
Please assign this task to me.

**Comment by ANSHIKA-26** [comment]
hello , we arent a deployed project available for users to fetch right now , so we dont really need this , thanks for the input
