### ISSUE TITLE
when we put passwords, two view icons appear and the don't synchronize

### ISSUE THREAD

**Issue by Ritikabiswas** [ANSHIKA-26/WordWise#1226]
![Screenshot 2024-10-20 110604](https://github.com/user-attachments/assets/d86522d2-ea24-4784-b016-08c041635dde)

**Comment by ANSHIKA-26** [comment]
i only see 1 icon , working fine

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/ab201da5-86b6-4ef5-b252-c356f0817793)

**Comment by Ritikabiswas** [comment]
![Screenshot 2024-10-20 112631](https://github.com/user-attachments/assets/62185d92-da01-4af1-97ed-2308023ab717)
see when we type the password the two eyes appear after we press enter it shows single eye

**Comment by ANSHIKA-26** [comment]
https://anshika-26.github.io/WordWise/#login

**Comment by ANSHIKA-26** [comment]
issue on your end , hosted link works fine
