### ISSUE TITLE
the slides after loading more posts are not properly synchronized ,we are not able to be in a fix post means that circles are not filled showing the slide we are in

### ISSUE THREAD

**Issue by Ritikabiswas** [ANSHIKA-26/WordWise#1227]
Slides circles are not showing in which slide we are
![Screenshot 2024-10-20 110817](https://github.com/user-attachments/assets/5de381b3-856e-44ab-86f2-cf6d926f5b5e)

**Comment by ANSHIKA-26** [comment]
it changes after a few seconds on its own , we like it that way , we arent stuck , kindly refresh

**Comment by Ritikabiswas** [comment]
I did it but not see any changes means maybe you made it like that but it was my suggestion that it can direct us to the current slide
