### ISSUE TITLE
The div dosen't have animation to it ..

### ISSUE THREAD

**Issue by 2004pra** [ANSHIKA-26/WordWise#1229]
As i sharing you the screenshot of the div which don't have animation to it ..
this the image --->
![Screenshot 2024-10-20 125631](https://github.com/user-attachments/assets/efa2d32c-f391-4c12-a765-7532bac28725)
please assign me this issue under gssoc 24 extd, hactoberfest accepted , atleast level 2 because div enhancement are hard 
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
we do not need animation here
