### ISSUE TITLE
*Logo &  Fevicon For WordWise*

### ISSUE THREAD

**Issue by laxmikandivalasa** [ANSHIKA-26/WordWise#1232]
**Is your feature request related to a problem? Please describe.**
Its good when every website has its own unique icon which can be added as their shortcut icon or fevicon for their website
also in the home page

**Describe the solution you'd like**
I'd like to design a logo that has 2 W's  and suite the theme of the website using canva and add it to the website
This would look great

**Describe alternatives you've considered**
This would look great like no other

**Additional context**

**Comment by ANSHIKA-26** [comment]
logo - not needed
Favicon - exists , you cant see due to github pages
