### ISSUE TITLE
Request to Work on   Categories page and UI Enhancements

### ISSUE THREAD

**Issue by aashutosh585** [ANSHIKA-26/WordWise#1235]
hey @ANSHIKA-26 I would like to take on the task of updating the Categories page. Additionally, I noticed a few areas where we can improve the user experience and would like to work on the following enhancements:

**Steps to reproduce the current behavior:**
     1.Go to the website.
     2.Navigate to the 'Categories' page.
     3.Hover over the images.

**Proposed improvements:**
  > Update the hover effects on images and cards.
  > Introduce further enhancements to improve overall user experience and interactivity.

![Screenshot 2024-10-20 191006](https://github.com/user-attachments/assets/e286fb8d-6674-44df-9f08-5c8e1fab4ee1)

Please assign this task to me, So I can start working on it.
Make sure to add Lebels gssoc-ext, hactoberfest, and level1, level2, level3.

**Comment by ANSHIKA-26** [comment]
hover effect was added and removed 5 times from this page , right now it seems good as it is  ! so we dont need this thanks
