### ISSUE TITLE
adding different language options to access the whole webpage using Google API/s

### ISSUE THREAD

**Issue by Mahateaa** [ANSHIKA-26/WordWise#1240]
**Is your feature request related to a problem? Please describe.**
The application currently supports only one language, which limits its accessibility and usability for non-native speakers.

**Describe the solution you'd like**
I would like the application to support multiple languages, allowing users to change the language according to their preference. This could be achieved through a settings menu where users can select their preferred language from a list of available options.

**Describe alternatives you've considered**
An alternative approach could be auto-detecting the user's language based on their browser or device settings and defaulting the application to that language. Another option is providing a language selection modal on the first launch, allowing users to choose their language before proceeding.

**Additional context**

**Comment by ANSHIKA-26** [comment]
translator present in bottom left !
