### ISSUE TITLE
[Doc] : Visual Enhancements , Fostering Contact Channel and enabling Contributors List in README

### ISSUE THREAD

**Issue by Varunshiyam** [ANSHIKA-26/WordWise#1241]
**Is your feature request related to a problem? Please describe.**

#### Problem: A poorly structured or visually unappealing README can create confusion and hinder user engagement with a project.
----
This can lead to:

- **Difficulty understanding the project:** Newcomers may struggle to grasp

- **Reduced contributions:** Potential contributors may be deterred by a lack of clear information

- **Negative first impression:** An unprofessional README can reflect poorly on the project and discourage users from 
  exploring further.

**Describe the solution you'd like**

- To enhance communication and provide direct access to Project Guidance, I plan to include a dedicated Contact section 👤. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin⚡️ enabling contributors to readily connect with them and address any project-related queries. 

- Additionally, to improve readability and organization, I Planned to implement clear visual separations between each section of the contributor documentation, ensuring a user-friendly and easily navigable 🚏 experience. 

- Finally, to foster a welcoming 🙏🏻 and inclusive environment, I will incorporate personalized welcome messages for our Repository.

- To effectively convey the essence of our project and its objectives, I propose creating a customized cover image for the repository.

----

+ Kindly Assign me this Issue Under 🌸 Gssoc, ☘️ hacktoberfest . I'm grateful to work with Talented Crews ✨.

**Comment by ANSHIKA-26** [comment]
hey , thanks for the input but we are okay with the readme we have right now , it covers what we want !
