### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [ANSHIKA-26/WordWise#1245]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ANSHIKA-26 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by ANSHIKA-26** [comment]
auto comment on PR merges already exists , no need for auto comment on PR opening 
auto comment for issue open already exists , and there are many reasons an issue is closed so i dont wish to have auto comment on closed issues ! thanks ! closing this issue since i dont need it
