### ISSUE TITLE
Navbar layout and poor text alignment at about us section 

### ISSUE THREAD

**Issue by falak412** [ANSHIKA-26/WordWise#1246]
**Describe the bug**
Navbar is broken in two part. The buttons are not visible properly they are overlapping each other and navbar is in two parts so the layout looks in complete. The text alignment at about us section is really poor.

**Expected behavior**
Making Navbar of same colour. Making buttons of different colour so they are more visible. Changing layout of about us section to make more align.

**Screenshots**
![Screenshot_2024-10-21-07-45-56-361_com android chrome](https://github.com/user-attachments/assets/5181c5be-2d28-49f1-90de-da79917bd212)
![Screenshot_2024-10-21-07-46-27-225_com android chrome](https://github.com/user-attachments/assets/64ffde95-e74f-47db-8242-63dc02082b9c)

@ANSHIKA-26 please assign me this issue.i will try my best to make it more attractive.
GSSoC'24 Extend Contributor 🌟

**Comment by ANSHIKA-26** [comment]
this comes under making it responsive , since you are on mobile

**Comment by ANSHIKA-26** [comment]
#806 is doing it
