### ISSUE TITLE
Connect databse with newsletter form and custom message after form submit 

### ISSUE THREAD

**Issue by rahulbamnuya** [ANSHIKA-26/WordWise#1257]
![Screenshot_2024-10-21-15-29-40-90_439a3fec0400f8974d35eed09a31f914.jpg](https://github.com/user-attachments/assets/9ce58522-3775-4505-b983-31782355e59a)

**Comment by ANSHIKA-26** [comment]
the db connection will be done soon , i need to add my mongo uri for that , and a message is always displayed after we click submit , hence we do not need this issue thank you !
