### ISSUE TITLE
Improve colours combination and improve overlapping of text in footer section 

### ISSUE THREAD

**Issue by rahulbamnuya** [ANSHIKA-26/WordWise#1259]
![Screenshot_2024-10-21-15-32-30-02_439a3fec0400f8974d35eed09a31f914.jpg](https://github.com/user-attachments/assets/e1073895-4949-4445-a57e-ab0d25d95bce)

**Comment by Anushka1805** [comment]
@ANSHIKA-26 please assign me this issue

**Comment by ANSHIKA-26** [comment]
fixed already
