### ISSUE TITLE
Some texts arent visible in dark mode

### ISSUE THREAD

**Issue by Codewithmeowmeow** [ANSHIKA-26/WordWise#126]
![20241003_011622](https://github.com/user-attachments/assets/8f2d03a7-03d9-48aa-b2b7-959932ec0cec)
Hey@ANSHIKA-26 as u can see in the picture in dark mode the text under about us section is not visible. 
Assign me this issue i would love to work on it.
Kindly add labels:)

**Comment by itsshreyanigam** [comment]
Please assign me this issue.

**Comment by Codewithmeowmeow** [comment]
Hy anshika!!
This word wise website is ruined.
Earlier when i opened the website on like 2-3 ocyober it was perfectly fine
but  yesterday when i opened it ,the navbar section  was very untidy amd
messy. Kindly note this issue.
