### ISSUE TITLE
Rework the Social Icons in Footer Section

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [ANSHIKA-26/WordWise#1265]
**Is your feature request related to a problem? Please describe.**
The current Social Icons in the Footer section are looking very poor. The Twitter logo is invisible.

**Describe the solution you'd like**
I want to rework the social icons in the footer section to make them more visually attractive and scalable.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/user-attachments/assets/538b4a31-cf5c-4b60-906c-a35720d719d4)

Please assign the issue to me so that I can work on the issue

**Comment by Dishika18** [comment]
I want to work on this issue.

**Comment by rajdeepchakraborty-rc** [comment]
> Thanks @rajdeepchakraborty-rc for raising this issue! We'll look into it.We hope you have made sure that a similar issue doesnt exist , if it does, kindly ask to be assigned on that issue

@ANSHIKA-26 Please assign me the issue so that I can work on it

**Comment by jayanththalla** [comment]
please assign me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
#1092 is doing it

**Comment by rajdeepchakraborty-rc** [comment]
Ok
