### ISSUE TITLE
Making FAQs session responsive 

### ISSUE THREAD

**Issue by Dishika18** [ANSHIKA-26/WordWise#1266]
**Describe the bug**
FAQs session is not properly aligned. I can fix it and make the FAQs more responsive and impressive. 

**Screenshots**

FAQs is not aligned in center.
![Screenshot 2024-10-21 190949](https://github.com/user-attachments/assets/4ee75c9a-7efb-4d62-be30-871baaf26b72)

**Additional context**
Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
#806 is doing it
