### ISSUE TITLE
Alignment of Rate us Stars.

### ISSUE THREAD

**Issue by Kajalmehta29** [ANSHIKA-26/WordWise#1267]
<img width="725" alt="Screenshot 2024-10-21 at 7 22 16 PM" src="https://github.com/user-attachments/assets/c9ebf841-e90d-430f-9587-bc4dbf0f91cd">

The alignment of stars should be at left side.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by ANSHIKA-26** [comment]
too small an issue to be fixed , it works both ways ! i find it fine even in right hand side !
