### ISSUE TITLE
Creating Terms of Service ,Licensing pages

### ISSUE THREAD

**Issue by VidhanThakur09** [ANSHIKA-26/WordWise#1272]
**Is your feature request related to a problem? Please describe.**

The website currently lacks dedicated pages for our Terms of Service and Licensing information. This omission can lead to confusion and legal uncertainties for users and contributors. Establishing these pages will provide a clear and accessible reference point for understanding the rights and responsibilities associated with using project.

**Describe the solution you'd like**

- **Dedicated Pages:** Create two separate pages: one for Terms of Service and another for Licensing.
- **Clear and Concise Content:** Develop well-structured content for each page, outlining the terms and conditions, and usage rights related to the project.
- **Accessibility:** Ensure the pages are easily discoverable from the project's footer section.

**Additional context**
By implementing dedicated Terms of Service and Licensing pages, we can enhance the overall user experience, mitigate legal risks, and foster a more transparent and professional project environment.

@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" with level 2 or level 3 and "hacktoberfest-accepted";

**Comment by ANSHIKA-26** [comment]
we are a blogging website project , we dont need such pages !

**Comment by VidhanThakur09** [comment]
Ok mam,
