### ISSUE TITLE
Make new section for legal links

### ISSUE THREAD

**Issue by Kajalmehta29** [ANSHIKA-26/WordWise#1274]
I want to make new section for legal links like privacy policy, terms and conditions, etc.
<img width="1331" alt="Screenshot 2024-10-22 at 12 49 16 AM" src="https://github.com/user-attachments/assets/5c5968ab-feb0-4c9f-b7ae-2b68bcf246c6">

Please asssign this issue to me under gssoc-extd and hacktoberfest.

**Comment by ANSHIKA-26** [comment]
not needed !
