### ISSUE TITLE
Correct FAQ Section Text Color in Dark Theme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#1277]
In the dark theme, the FAQ section's text color is white, making it difficult to read. Adjust the text color to improve readability, ensuring it contrasts well with the background.

![image](https://github.com/user-attachments/assets/44277cd4-0817-4ae9-b0d9-25493b92e88a)

**Comment by kuheli31** [comment]
Please assign this issue to me.

**Comment by kuheli31** [comment]
@ANSHIKA-26 Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
this FAQ has been added by mistake , this needs to be removed , can you remove it ?

**Comment by ANSHIKA-26** [comment]
@AnushkaChouhan25 remove only this FAQ , not the one in home page , thanks !

**Comment by AnushkaChouhan25** [comment]
@ANSHIKA-26 Okay Sure

**Comment by AnushkaChouhan25** [comment]
@ANSHIKA-26 Done
