### ISSUE TITLE
Add Chatbot to Category Page

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#1278]
Include the chatbot functionality on the category page to ensure consistent user interaction and accessibility across all sections of the website.

![image](https://github.com/user-attachments/assets/5374064e-4f0d-4794-8940-c9c0d50f19f4)

**Comment by ANSHIKA-26** [comment]
we have one on homepage , we dont need it on every page , thats pretty bothering to the user
