### ISSUE TITLE
Create About Us Page with Website Details

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#1279]
**Is your feature request related to a problem? Please describe.**
Develop a detailed "About Us" page that provides an overview of the website's purpose, mission, and the features it offers. Include information about the team, goals, and how the platform benefits users.

**Describe the solution you'd like**
- Introduction: Brief overview of the website's mission and purpose.
- Features: Highlight key functionalities and unique aspects.
- Team Section: Introduce the team or contributors behind the project.
- Goals & Vision: Share long-term goals and impact the platform aims to achieve.
- Contact Information: Include ways users can reach out or connect.
- Visuals & Design: Add relevant images, icons, or animations to enhance readability and engagement.

**Comment by ANSHIKA-26** [comment]
we had one and it didnt work out :( , 
we had to go through a lot of conflicts to get it removed , an about us page doesnt align with the blogging theme of this website , hence we dont need one !
