### ISSUE TITLE
When Dark Theme is switched on , dark colour is not executed for the background.

### ISSUE THREAD

**Issue by kuheli31** [ANSHIKA-26/WordWise#1280]
![image](https://github.com/user-attachments/assets/a3fabcf4-298b-434f-b25d-19f125c0aff1)
**
This contribution aims to enhance the visual design and user experience of the project. Specifically, it includes the following improvements:

Background Design: The "About Us," "Feature Post," and "Popular Tags" sections will have a light-colored background, improving readability and contrast for a more polished look.
Dark Theme: Fixing the current issue where the dark theme is not executing properly, ensuring it works consistently across the website.
Profile Picture Options: Adding options such as "Log Out" and "Settings" when hovering or clicking on the profile picture. This will include a dropdown menu or wrapping features for improved navigation and accessibility.
Styling Enhancements: The use of HTML, CSS, and Bootstrap will be employed to make the overall appearance of the website more visually appealing and modern.
These changes aim to improve both the aesthetics and functionality of the project.
Looking forward to contributing to this issue!!

**Comment by ANSHIKA-26** [comment]
this page hasnt been implemented on our home page yet , so no need to change it to dark mode !
