### ISSUE TITLE
[BUG]: Start Writing Page Does Not Scroll

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#1282]
**Describe the bug**
The "Start Writing" page does not currently allow for vertical scrolling, as the content is cut off and there is no scrollbar present. It appears that the overflow: hidden property may be applied, preventing users from accessing all the content.

**To Reproduce**

1. Review the CSS properties of the "Start Writing" page.
2. Remove or modify the overflow: hidden property to allow for vertical scrolling.
3. Ensure that a scrollbar appears when the content exceeds the height of the viewport, allowing users to navigate through all the content. 

**Expected behavior**

- Users should be able to scroll down to view all content on the "Start Writing" page.
- A vertical scrollbar should appear when the content exceeds the height of the viewport, allowing users to navigate through the entire page without any content being hidden.

**Screenshots**
![image](https://github.com/user-attachments/assets/746f95f1-560b-46d0-b7d4-4118efc7bf14)

**Comment by ANSHIKA-26** [comment]
#1134 is doing it !
