### ISSUE TITLE
Website loading... 

### ISSUE THREAD

**Issue by Hemraj-7** [ANSHIKA-26/WordWise#1286]
**Is your feature request related to a problem? Please describe.**
Now the website taking load time is too much. because of jpg and png picture these picture size is big.
so please convert these picture jpg to webp. when we convert these picture and add these picture to the website then the time of loading will be reduce.

I want to do this work. Assign me with these gssoc-ext, gssoc24, level3, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted and opensource labels.
thank you

**Comment by ANSHIKA-26** [comment]
check the code , its already webp

**Comment by Hemraj-7** [comment]
Okay, but why was it showing me a JPG picture 4 hours ago?

**Comment by Hemraj-7** [comment]
These are ok but some files are already huge size so website load slowly

![Screenshot 2024-10-22 225226](https://github.com/user-attachments/assets/a136cb62-2f91-4c41-8b1a-b444efd9fc35)

see this picture size is almost 7mb

**Comment by Hemraj-7** [comment]
assign me i willl check all picture size and change picture size without reduce picture ratio
