### ISSUE TITLE
Login and signup page close button issue

### ISSUE THREAD

**Issue by swathivemula7** [ANSHIKA-26/WordWise#1288]
In the login and signup page, there are two buttons which do the same close operation...One is close icon and another is close button...I would like to fix this...

Also the forget password alignment is not proper..I would also like to fix this..

![IMG_20241022_160754](https://github.com/user-attachments/assets/1aa7fb51-7741-41fb-adf9-6daacd0236e5)

@ANSHIKA-26 kindly assign me this issue under labels gssoc and hacktoberfest....

**Comment by ANSHIKA-26** [comment]
its because we want it that way , it is not a bug , thanks !
