### ISSUE TITLE
in dark mode contact us page is not changing

### ISSUE THREAD

**Issue by Ishika-codeit** [ANSHIKA-26/WordWise#1290]
**Is your feature request related to a problem? Please describe.**
in dark mode contact us page is not changing color
**Describe the solution you'd like**
enhance and change color based on dark mode

kindly assign thi issue to me @ANSHIKA-26 as soon as possible

**Comment by ANSHIKA-26** [comment]
it is 
![image](https://github.com/user-attachments/assets/296188fe-56cf-40da-979a-f9080ea11a70)
maybe its an issue at your end ? can you share an image ?

**Comment by ANSHIKA-26** [comment]
its working fine
