### ISSUE TITLE
Improving the About us, Feature Post and popular tags section

### ISSUE THREAD

**Issue by komalnalage** [ANSHIKA-26/WordWise#1292]
Hi @ANSHIKA-26 I think the About us, Feature Post and popular tags section can be enhanced .
![image](https://github.com/user-attachments/assets/b410ec77-780d-4372-b02d-36ecc674d10a)
could you assign me this task and add labels gssoc-ext and hactoberfest-accepted?

**Comment by ANSHIKA-26** [comment]
how ? except hover effect/font change/ style change/ alignment change 
i already like the hover effect/font change/ style change/ alignment change  in this section

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
