### ISSUE TITLE
Adding popup for subscribing to newsletter.

### ISSUE THREAD

**Issue by Jordian0** [ANSHIKA-26/WordWise#1297]
**Is your feature request related to a problem? Please describe.**
Adding a popup dialog box for subscribing to newsletter.

**Comment by ANSHIKA-26** [comment]
already have one , although it doesnt come from top of the website , its still good 
![image](https://github.com/user-attachments/assets/a7833c35-4627-4b29-a4c1-190ae085088d)
I do not wish to change this ! Thanks

**Comment by Jordian0** [comment]
@ANSHIKA-26 The image you mentioned is after user is subscribed for the newsletter. But what i meant was adding a popup dialog box for subscribing to newsletter. When website will be shown first time it'll display a popup for newsletter subscription.
