### ISSUE TITLE
Bugs Found: Text under Gaming Chronicles not aligned; Dark mode toggle switch not going extreme right.

### ISSUE THREAD

**Issue by devanshaggarwal03** [ANSHIKA-26/WordWise#1299]
**Describe the bug**
Text under Gaming Chronicles not aligned; 
Dark mode toggle switch not going extreme right.

**To Reproduce**

**Expected behavior**
Text should be properly aligned.
Switch goes to extreme right.

**Screenshots**
<img width="1470" alt="Screenshot 2024-10-23 at 00 31 33" src="https://github.com/user-attachments/assets/1805fd7f-24e4-4433-9cd1-e78aeabbc0ce">

**Comment by devanshaggarwal03** [comment]
Hi @ANSHIKA-26, please assign me this issue too so that I can start working on it.

**Comment by ANSHIKA-26** [comment]
just fix the dark mode switch , the text is okay !

**Comment by devanshaggarwal03** [comment]
Created PR #1398 to resolve this issue
