### ISSUE TITLE
Add Scroll Bar to the "Start Writing" page.

### ISSUE THREAD

**Issue by Lokesh11868** [ANSHIKA-26/WordWise#1302]
**Is your feature request related to a problem? Please describe.**
The "Start Writing" page lacks a scrollbar, making it difficult to navigate through content and access text that extends beyond the visible area.

**Describe the solution you'd like**
Add a scrollbar to the page that appears when content overflows, allowing users to smoothly scroll through all text.

**Describe alternatives you've considered**
Considered customizable scrollbar CSS overflow for a quick solution.

**Additional context**
I want to add this kind of feature to the Start Writing Page.
![image](https://github.com/user-attachments/assets/87a94830-edd8-4ca3-926a-bed03a58dd78)

@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted"?

**Comment by ANSHIKA-26** [comment]
#1134 is doing this !
