### ISSUE TITLE
Improve the styling of header.

### ISSUE THREAD

**Issue by sayanp607** [ANSHIKA-26/WordWise#1303]
![Screenshot 2024-10-23 101514](https://github.com/user-attachments/assets/2d1501c5-cad4-4cb7-9a37-accd58fcd001)
the background breaks after leading blog option, i want to fix this by implementing a toggle button for small pages. The button will contain all the options. Please assign this task to me.

**Comment by ANSHIKA-26** [comment]
PR already made for the same
