### ISSUE TITLE
Add Facebook and X sign up to more atrective

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ANSHIKA-26/WordWise#1306]
**Is your feature request related to a problem? Please describe.**
there is only  one you can sign up google ..  but you can add .. like facebook and X to more  atrective website 

**Describe the solution you'd like**
![Screenshot (385)](https://github.com/user-attachments/assets/02134ad5-3c23-472b-8a5f-ab9f0114c0cd)

**Comment by RahulPrasadYadav** [comment]
@ANSHIKA-26  assign the issue

**Comment by ANSHIKA-26** [comment]
its a blogging website , we dont need a signup with FB or X , google seems good
