### ISSUE TITLE
"Email is already registered" option

### ISSUE THREAD

**Issue by sayanp607** [ANSHIKA-26/WordWise#1307]
**Is your feature request related to a problem? Please describe.**
if user signup again in place of login , this notification will be shown.

**Describe the solution you'd like**
when user sign up again with similar email id that he used previous times, then "email is already registered" notification will be shown there. Other wise, user can not make it out to login there.

Please assign this task to me, I will fix it sure.

**Comment by ANSHIKA-26** [comment]
fix this with #1304 please ! , will increase level for #1304
