### ISSUE TITLE
Add hover effects to FAQ section

### ISSUE THREAD

**Issue by sezallagwal** [ANSHIKA-26/WordWise#1309]
![image](https://github.com/user-attachments/assets/27ed9270-48fc-4e82-8e29-12bd228e74f3)
Enhance the user experience by adding smooth animations to the FAQ section. The animations should improve the interactivity and visual appeal when a user expands or collapses a question.

Apply a smooth sliding animation when expanding and collapsing the FAQ items.
The transition should be fast enough to keep the interaction responsive but slow enough for a smooth effect (e.g., 0.3s - 0.5s duration).

Icon Animation:
Rotate or change the icon next to each question when expanded and revert back when collapsed.
The icon animation should synchronize with the expand/collapse animation.

https://github.com/user-attachments/assets/528fb2ea-5935-4433-9c4a-e001a0f92c88

please assign this to me under gssoc-ext and hacktoberfest @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
not needed , we like it simple
