### ISSUE TITLE
ChatBot doesn't show up on landing page

### ISSUE THREAD

**Issue by sezallagwal** [ANSHIKA-26/WordWise#1310]
**Is your feature request related to a problem? Please describe.**
Rn the website lacks chatbot functionality, Please assign this to me I will add it @ANSHIKA-26 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/46399669-644a-490d-af96-e76470408102)
it does
