### ISSUE TITLE
[⭐FEATURE] Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1311]
I want to add a Visitor Counter feature properly.

@ANSHIKA-26  PA please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
we tried this , didnt like it , it stood out from the whole website in a weird manner , so we dont want it anymore , thanks
