### ISSUE TITLE
Improving the UI of Login/Signup dropdown menu

### ISSUE THREAD

**Issue by maliumesh1** [ANSHIKA-26/WordWise#1327]
![Uploading Screenshot 2024-10-23 185142.png…]()
Description: The login/signup dropdown on the login page is effective but aesthetically and usability-wise has room for improvement, enhancing user interaction along with giving the interface a modern look.

**Comment by ANSHIKA-26** [comment]
You raised an issue that’s exactly the same as one that was recently assigned. Despite the GitHub Actions clearly prompting you to check for similar issues, you still went ahead and raised a duplicate. This isn’t how issues should be submitted. Please take the time to check for existing issues before creating new ones. I’ll be closing this issue—let’s avoid unnecessary duplication moving forward.

**Comment by ANSHIKA-26** [comment]
its perfect the simple way it is , thanks
