### ISSUE TITLE
Hover Effect and Color Improvement for "Post Comment" Button in "Join the Conversation" Section

### ISSUE THREAD

**Issue by KhushiChauhan8** [ANSHIKA-26/WordWise#1332]
@ANSHIKA-26 
Hello,  
I was reviewing the "Join the Conversation" section and noticed that the "Post Comment" button’s hover effect could be improved. The current hover changes the button color to "light pink", which doesn’t contrast well with the "blue background", making it hard to read. Additionally, the hover effect lacks animation, and a subtle transition effect would enhance the user experience.

I would suggest changing the hover color to a more contrasting shade and adding a smooth animation. I’ve attached a screenshot below for reference.

I’d love to contribute by working on this improvement. Could you please assign this issue to me?  
Thank you!

-> Screenshot of the current page.
![Screenshot 2024-10-23 205338](https://github.com/user-attachments/assets/935cd40c-9b90-4a34-a7c4-26c87866441e)

**Comment by ANSHIKA-26** [comment]
no hovers are needed for this section
