### ISSUE TITLE
There is some misalignment in the contact us form and feedback form.

### ISSUE THREAD

**Issue by akilesh26** [ANSHIKA-26/WordWise#1333]
**Describe the bug**
There is some misalignment in the contact us form(send button) and feedback form(rate us option).

**Expected behavior**
Re-alignment of button and rate us option to look better.

I would like to fix this issue. Please assign me the same under gssoc-ext and an appropriate level.

![Screenshot 2024-10-23 at 21-18-52 Feedback Form](https://github.com/user-attachments/assets/43a85353-2934-406e-b054-44924b3aeb39)
![Screenshot 2024-10-23 at 21-18-32 Contact Us](https://github.com/user-attachments/assets/5b53f29e-1a77-4a7a-a716-f92fa91a5d7b)

**Comment by akilesh26** [comment]
Adding some images below regarding how it would look after re-alignment.

![Screenshot 2024-10-23 at 21-53-40 Feedback Form](https://github.com/user-attachments/assets/de16a432-cd8c-4992-82e0-9165517393b0)
![Screenshot 2024-10-23 at 21-50-14 Contact Us](https://github.com/user-attachments/assets/e4dcc020-fc48-418e-b9d2-87c27d96d31f)

**Comment by ANSHIKA-26** [comment]
could you also show how it looks like now ? because i feel like there is no difference

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/bd80cf9b-e3b9-4009-ac1e-776b61039c49)
this is what i see

**Comment by akilesh26** [comment]
![379351430-43a85353-2934-406e-b054-44924b3aeb39.png](https://github.com/user-attachments/assets/3ac555a6-5f1a-40cd-8131-226c29654aa1)

![379351446-5b53f29e-1a77-4a7a-a716-f92fa91a5d7b.png](https://github.com/user-attachments/assets/048ebd2d-ad27-4f7d-ab53-6270f7797a9b)

**Comment by akilesh26** [comment]
Now the issue has been resolved. Probably someone else would have noticed it and resolved it.
