### ISSUE TITLE
 Change Footer Background Colour for Improved Design Aesthetics

### ISSUE THREAD

**Issue by Poushmita** [ANSHIKA-26/WordWise#1339]
## **Is your feature request related to a problem? Please describe.**
The current footer section of the website has a light background colour, similar to the rest of the page, which makes it blend in. To improve the visual separation and overall design aesthetics, the background colour of the footer should be changed to a distinct colour that complements the website's theme but makes it stand out.

![image](https://github.com/user-attachments/assets/e468c0d0-8972-450c-a990-d5985426bd9f)

## **Describe the solution you'd like**
- Change the background colour of the footer section to a darker shade or a complementary color that contrasts with the rest of the website.

- Suggested colours:
  1. Dark grey (#2C2C2C) for a modern look
  2. Navy blue (#003366) for a more professional tone
  3. Soft pastel (e.g., pastel blue or pastel green) to maintain a lighter, more playful aesthetic

## **Describe alternatives you've considered**

**1. No change:**
    Keeping the current design, but it lacks clear visual separation from the rest of the page.

 **2.Adding a divider:**
    Using a line or border to separate the footer, but this wouldn’t be as effective in making the section distinct.

**Comment by Poushmita** [comment]
@ANSHIKA-26  Please assign me this issue.

**Comment by ANSHIKA-26** [comment]
i find the footer perfect ! we do not wish to change it sorry !
