### ISSUE TITLE
Add Chatbot for Enhanced User Support

### ISSUE THREAD

**Issue by Poushmita** [ANSHIKA-26/WordWise#1340]
**Is your feature request related to a problem? Please describe.**
   To improve user engagement and provide instant support, a chatbot should be integrated into the website. The 
   chatbot will assist visitors by answering common questions.

**Describe the solution you'd like**
-    Implement a chatbot widget in the bottom-right corner of the website.
-    The chatbot should be able to:
     1. Answer FAQs related to the website’s services, navigation, and common user queries.
     2. Offer live chat support

**Comment by ANSHIKA-26** [comment]
we already have one !
