### ISSUE TITLE
Twitter Icon Disappears in Dark Mode

### ISSUE THREAD

**Issue by Poushmita** [ANSHIKA-26/WordWise#1342]
## **Describe the bug**
While using the website in dark mode, I noticed that the Twitter icon vanishes, making it hard for users to identify and click the social media link. This issue can cause usability problems, especially for users who prefer dark mode settings.

## **Expected behaviour**
The Twitter icon should be clearly visible in both light and dark modes to ensure consistent user experience.

## **Screenshots**
- Light Mode
![image](https://github.com/user-attachments/assets/06b9cdba-a2a4-41e1-be87-962da9dfef1a)

- Dark Mode
![image](https://github.com/user-attachments/assets/925a9aee-06a3-4939-ad02-5515897ec696)

## **Proposed Solution**

- Adjust the icon colour or apply a light-coloured background to ensure it remains visible in dark mode.
- Test the changes to confirm the icon's visibility in all display modes.

**Comment by ANSHIKA-26** [comment]
PR #1348 is working on it
