### ISSUE TITLE
Improper Placement of 'Word of the Day' on Wordwise Website

### ISSUE THREAD

**Issue by Pragati1466** [ANSHIKA-26/WordWise#1345]
**Describe the bug**
The "Word of the Day" is displayed at the bottom of the Wordwise website instead of being prominently featured at the top. This placement reduces its visibility and engagement with users.

**To Reproduce**

Go to the Wordwise website.
Scroll down to the bottom of the page.
Observe the "Word of the Day" section.

**Expected behavior**
The "Word of the Day" should be displayed at the top of the page and ideally presented as a popup when users first visit the site.

**Screenshots**
<img width="1782" alt="Screen Shot 2024-10-24 at 2 28 18 AM" src="https://github.com/user-attachments/assets/03bfda9f-325d-467f-b7d7-96a190a35aca">
@ANSHIKA-26 

**Additional context**
Displaying the "Word of the Day" in a more prominent location, such as the top of the page or as a popup, would enhance user engagement and make the feature more effective.

**Comment by ANSHIKA-26** [comment]
pr #1341 is doing it
