### ISSUE TITLE
Navbar Elements Misalignment

### ISSUE THREAD

**Issue by Pragati1466** [ANSHIKA-26/WordWise#1346]
**Describe the bug**
The elements in the navbar are aligned to the left instead of being centered, which affects the overall layout and user experience of the website.

**To Reproduce**

Go to the Wordwise website.
Observe the navbar section at the top of the page.
Notice that the elements are aligned to the left.
**Expected behavior**
The navbar elements should be centered in the navbar to enhance the website's visual appeal and usability.

**Screenshots**
<img width="1774" alt="Screen Shot 2024-10-24 at 2 37 44 AM" src="https://github.com/user-attachments/assets/a3c5971b-7c89-45af-8370-22545c5b170f">

Centering the navbar elements would create a more balanced layout and improve the overall aesthetic of the website, making it look more professional and user-friendly.

@ANSHIKA-26 please review and assign it to me and add relevant labels please

**Comment by ANSHIKA-26** [comment]
PR #1343 has already done this
