### ISSUE TITLE
Feedback UI 

### ISSUE THREAD

**Issue by Dipeshdahiya** [ANSHIKA-26/WordWise#1347]
I would like to work on the UI design of the Feedback page .
I already worked on the Ui of the contact page for your website and now has a better understanding of the code , so i would like to give more contribution to your project under gssoc.
Please assign this issue to me and i will make sure to the form matches the theme as well as manages the light dark mode coloring

**Comment by ANSHIKA-26** [comment]
kindly do the changes requested on your pr -
https://github.com/ANSHIKA-26/WordWise/pull/1293
before opening new issues !

**Comment by ANSHIKA-26** [comment]
closing this issue coz #1270 is doing this
