### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Annapoornaaradhya** [ANSHIKA-26/WordWise#1349]
**Describe the bug**
the image of the gssoc banner is not visible and hacktoberfest is not included 

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/fe7b76ce-7a2c-466a-8e5d-30e2aee48b96)

@ANSHIKA-26 please assign me this under gssoc-ext level and hacktoberfest accecpted tags

**Comment by ANSHIKA-26** [comment]
not needed , we will be removing this section soon anyways
