### ISSUE TITLE
Spacing of like button is varying under each card

### ISSUE THREAD

**Issue by shreya2k3** [ANSHIKA-26/WordWise#1351]
**Describe the bug**
On home page, the like button under every card has a varying alignment. The spacing is different wrt comment button.

**To Reproduce**
1. Go to 'home page'
2. Scroll down and look at the bottom border of each card.
3. See error

**Expected behavior**
The spacing should have been equal for all cards.

**Screenshots**
![image](https://github.com/user-attachments/assets/e2a208e8-c6fc-44aa-a537-994a7a691ae6)

**Additional Comment**
Please assign this issue to me.

**Comment by vamsi4845** [comment]
@ANSHIKA-26 Can you assign this to me?

**Comment by shreya2k3** [comment]
@ANSHIKA-26 please review and assign the issue to me.
