### ISSUE TITLE
Adjust Language Change Icon and Update Copyright Section

### ISSUE THREAD

**Issue by Utkarsha156** [ANSHIKA-26/WordWise#1352]
The language change icon in the footer is misaligned and overlaps with content, causing layout issues. Additionally, the copyright text and layout should be adjusted for a cleaner and more professional appearance, ensuring the entire section is responsive and well-organized across different screen sizes.

This issue will address both the aesthetic and functional improvements needed for the language icon and the footer area of the website.

could you please assign me the issue @ANSHIKA-26 @MastanSayyad 
![image](https://github.com/user-attachments/assets/a64134c8-d114-481e-b079-b953daf98f8d)

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/690a75d9-31c1-4894-8a05-1f6157e500fa)
already fixed !
