### ISSUE TITLE
Middle Card Misalignment on Homepage

### ISSUE THREAD

**Issue by Utkarsha156** [ANSHIKA-26/WordWise#1353]
The middle card ("Gaming Chronicles") on the homepage is slightly lower than the other two cards, causing a visual misalignment. This disrupts the symmetry and uniformity of the design. The card should be adjusted to align evenly with the other two cards for a consistent layout across the homepage.

could you please assign me the issue @ANSHIKA-26 

![image](https://github.com/user-attachments/assets/14bd08fa-580d-4b1f-bc17-a317f23202db)

**Comment by Utkarsha156** [comment]
its already fixed now. Could you check once @ANSHIKA-26

**Comment by Utkarsha156** [comment]
actually 1st and 2nd rows are fine but next rows first cards aren't align properly. pls check once and if yes you can assign that to me

**Comment by ANSHIKA-26** [comment]
open another issue for the same
