### ISSUE TITLE
Scroll Bar Overlapping with Right Side Navbar

### ISSUE THREAD

**Issue by Utkarsha156** [ANSHIKA-26/WordWise#1354]
The scroll bar on the right side is overlapping with the navigation bar, which causes a visual issue and makes it harder to navigate the website smoothly. This overlap detracts from the user experience and needs to be resolved.

could you please assign me this issue @ANSHIKA-26 @MastanSayyad 

![image](https://github.com/user-attachments/assets/eff56526-3e58-4f45-885d-f3576377506a)

**Comment by ANSHIKA-26** [comment]
its not 
![image](https://github.com/user-attachments/assets/57485c14-c62c-431f-9986-be6d40fa14ee)
can you check again ?

**Comment by Utkarsha156** [comment]
yes its fixed
