### ISSUE TITLE
Enhancing nabar

### ISSUE THREAD

**Issue by AswaniBolisetti** [ANSHIKA-26/WordWise#1355]
@ANSHIKA-26 
The navbar is not matching with the website styling 
I would like to enhance it
Could you please assign it to me

**Comment by ANSHIKA-26** [comment]
Thank you for your suggestion, but we are currently happy with the current styling of the navbar as it aligns with the overall design of the website. We appreciate your enthusiasm, but at this time, no changes are needed. Thank you for understanding!
