### ISSUE TITLE
Enhancing news subscription letter

### ISSUE THREAD

**Issue by AswaniBolisetti** [ANSHIKA-26/WordWise#1356]
@ANSHIKA-26 
I would like to work on it
Could you please assign it to me

**Comment by ANSHIKA-26** [comment]
what do you wish to enhance in it and how ?

**Comment by AswaniBolisetti** [comment]
@ANSHIKA-26 
The news subscription is not looking like professional
I thought i can make it somewhat better

**Comment by ANSHIKA-26** [comment]
how ? except adding hovers/changing font etc , what do you want to change to make it better ?

**Comment by AswaniBolisetti** [comment]
I'll try to make it better, i'll raise PR if i think it is better than before, if you like it you can merge otherwise you can close it

**Comment by ANSHIKA-26** [comment]
im sorry , but i dont want your efforts to go waste , its better if you can show some example of what you wish to do first ,I honestly find the newsletter section simple enough and like it that way , and hence am not in favor to change it
