### ISSUE TITLE
Dark / Light button is not working

### ISSUE THREAD

**Issue by Sujal1201** [ANSHIKA-26/WordWise#136]
Dark / Light button is not working while changing mode

#### Dark mode
![image](https://github.com/user-attachments/assets/0afa418f-1140-46cc-b067-7bc8d4af9692)

#### Light mode
![image](https://github.com/user-attachments/assets/d4d18122-5497-4f05-92f6-b26c59054405)

**Comment by Shukla000** [comment]
I want to work upon this issue. Please assign me this.

**Comment by ruchikakengal** [comment]
I can solve this issue assign me @ANSHIKA-26
