### ISSUE TITLE
Feature: Favourite Page

### ISSUE THREAD

**Issue by Poushmita** [ANSHIKA-26/WordWise#1360]
**Is your feature request related to a problem? Please describe.**
Couldn't find the blog in which I have  added heart sign. So, a favourite page will be good for this feature.

**Describe the solution you'd like**
Want to add a page for favourites(added heart sign) blog to see user their favourite blogs later.

**Screenshot**
![image](https://github.com/user-attachments/assets/8bf52543-cc14-4653-94dc-53d9694de65e)

**Comment by ANSHIKA-26** [comment]
we already have bookmarks , we dont need a favourite page , it solves the same purpose
