### ISSUE TITLE
Scroll to top button is missing on home, start writing and feedback page

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1363]
**Describe the bug**
The scroll-to-top button is missing on the home, start writing, and feedback pages, making it difficult for users to navigate back to the top of the page after scrolling down.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to the Home page.
3. Scroll down to the bottom of the page.
4. Observe that the scroll-to-top button is not visible.
5. Repeat the same steps on the Start Writing and Feedback pages.

**Expected behavior**
I expected to see a scroll-to-top button that allows users to quickly return to the top of the page after scrolling down.

**Screenshots**
![Screenshot 2024-10-24 164303](https://github.com/user-attachments/assets/0e779801-387f-42e7-af73-832f86068799)

**Additional context**
This issue may affect user experience, especially for long pages where scrolling back to the top can be cumbersome. It would be helpful to implement this feature for better navigation.

**Comment by Bhupendrakumar20** [comment]
@ANSHIKA-26  kindly request that this issue be assigned to me, and I am confident I will address and resolve it effectively.

**Comment by ANSHIKA-26** [comment]
its not needed for rest of  the pages , they are pretty short
