### ISSUE TITLE
unstructured header page information 

### ISSUE THREAD

**Issue by Bhupendrakumar20** [ANSHIKA-26/WordWise#1369]
As in the header information section ,

- the difference between the logo and all the sections like home , leading blogs and all 
- the boundaries between the home, leading blogs, start writing, categories ,about , contact us , give feedback with proper styling make it more attractive 
- the difference between the alignment of login icon and day night toggle button 

@ANSHIKA-26 kindly assigned this issue to me .i will surely solve it

![Screenshot (70)](https://github.com/user-attachments/assets/7845b115-2edf-4920-98d0-9d1798b186b3)

**Comment by ANSHIKA-26** [comment]
this is not what our navbar looks like , kindly check again !

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/29d047f0-5a49-4f5b-bb83-061339137d73)
this is what its like and its perfect , thanks
