### ISSUE TITLE
To improve the styling of "Start Writing" and "Contact Us" Page when switched to dark theme.

### ISSUE THREAD

**Issue by ApoorvaSunkad** [ANSHIKA-26/WordWise#1374]
Hi @ANSHIKA-26 ,

I hope you are doing well!

I explored the website, and I liked how it was created, including the color combinations, button format, etc. The website looks good.

I wanted to modify the Start Writing page and Contact Us page in a DARK theme. When you switch to a dark theme there is no box shadow given as it is given for a light theme. Hence I want to provide a slightly lighter box shadow similar to the light theme so that the look of the UI is enhanced.

Also if you see the mic Icon is out of the box "Blog Content" I want to fit it inside the blog content. 

If you see get suggestions option there is no padding, so if we provide a little bit of padding, it looks better.

Also if we see on the Home page in DARK mode the containers are given a pinkish tone box-shadow which matches the overall UI theme and hence I want to provide the same box-shadow to the Contact Us page as well to match the overall look and theme.

See the Attached screenshots for clarity.

I request you to assign me this issue so that I can fix it and contribute to your project and continue my open-source journey.

Please add labels GSSOC'24 and Hacktoberfest.

Thank You!

Screenshots:

![sw1](https://github.com/user-attachments/assets/30107c45-c4ac-4d23-9681-89fc50a37117)

![sw2](https://github.com/user-attachments/assets/f21f36d8-b18e-4fd4-8859-3dacdf2edfee)

![sw3](https://github.com/user-attachments/assets/7e06182c-2379-4ec8-b4a2-4dc89959b344)

Comparing Contact us page box shadow with Home page box-shadow
![sw4](https://github.com/user-attachments/assets/2a3a4399-4ebd-4c6b-9b99-1bb566794988)

**Comment by ANSHIKA-26** [comment]
@ApoorvaSunkad great job with raising a perfect issue , it had explanatory screenshots and what you wish to do in a clear manner , perfect , looking forward to your PR

**Comment by ApoorvaSunkad** [comment]
@ANSHIKA-26 Thank you for assigning the issue to me, I'll resolve it as soon as possible and create a PR for it. 
Thank You!
