### ISSUE TITLE
want to make footer part more attractive

### ISSUE THREAD

**Issue by Kajalmehta29** [ANSHIKA-26/WordWise#138]
**Describe the bug**
I want to make the footer part more attractive. It is soo dull and font is also not nice neither the justification.  I will make it proper, easy to read and attractive.

Please assign this issue to me under gssoc-ex and hacktober.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 56rahul** [comment]
i would like to work on this project. please assign to me
