### ISSUE TITLE
Non-Visibility of the X logo when switched to dark mode

### ISSUE THREAD

**Issue by harjasae2001** [ANSHIKA-26/WordWise#1380]
**Describe the bug**

When switched to dark mode the logo of the X is not visible

**To Reproduce**
1. Go to Footer
2. Click on Dark Mode switch
3. See error

**Expected behavior**

There should be a background of white to show the logo perfectly

**Screenshots**
![{6D08D9B8-7715-4DDC-AC41-0A34C7B560CC}](https://github.com/user-attachments/assets/f6bba9c5-1c29-415a-8cf2-7495547c1917)

![{0EE6E55F-8014-4FF9-92AC-286195A7C200}](https://github.com/user-attachments/assets/efc9ef56-bee5-45c4-b9de-eeb09a87d72d)

**Additional context**

**Comment by harjasae2001** [comment]
Can u pls assign me this issue so that i can start working on the same.

**Comment by harjasae2001** [comment]
@ANSHIKA-26 can u pls assign this issue to me.

**Comment by hiteashgupta1** [comment]
No it's visible
