### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by abhi200446** [ANSHIKA-26/WordWise#1381]
**Is your feature request related to a problem? Please describe.**
the navbar has not properly arranged there is no correct padding  and margin arranged between elements  i will arrange the navbar correctly and improve ui please assign @ANSHIKA-26 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
the navbar is perfect , i dont understand what you wish to do ?
