### ISSUE TITLE
Preloader Missing on Other Pages

### ISSUE THREAD

**Issue by VidhanThakur09** [ANSHIKA-26/WordWise#1390]
**Describe the bug**
The preloader, which displays a loading indicator while pages are loading, is not consistently present across all pages of the website. When navigating to certain pages, the screen becomes blank for a noticeable period before the content appears. This can negatively impact user experience, especially on slower connections.

**To Reproduce**
1. Go to leading blog , start writing , category, contact us , and feedback
2. Reload
3. See blank screen when loading

**Expected behavior**

- The preloader should be visible on all pages of the website
- The preloader should be designed to provide a smooth and informative loading experience.
- The preloader should disappear once the page content is fully loaded.

**Screenshots**
![Screenshot 2024-10-07 135253](https://github.com/user-attachments/assets/b2ba8ca0-cf35-4c52-9beb-a0f5b1c4f90b)

**Additional context**
@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted";

**Comment by ANSHIKA-26** [comment]
not needed !

**Comment by VidhanThakur09** [comment]
Ok mam
