### ISSUE TITLE
Adding sentence feature in "Word of the Day" Section

### ISSUE THREAD

**Issue by shreya2k3** [ANSHIKA-26/WordWise#1394]
**Is your feature request related to a problem? Please describe.**
The current UI for the "Word of the Day" section is simple. I want to make the section more informative and visually appealing by including an example sentence along with the word and its meaning. Currently, users might not get the complete context of how the word is used in a sentence.

**Describe the solution you'd like**
I would like to enhance the "Word of the Day" section to display the word in bold, followed by its meaning and a usage example in a more structured format. The section should follow this pattern:

**Word**
Meaning:
Usage:
Additionally, I would like the design to be more engaging by using a card-like UI.

**Describe alternatives you've considered**
I have considered keeping the current structure but adding a simple sentence below the meaning. However, a more structured approach with better styling will improve readability and engagement for users. 

**Additional context**
![image](https://github.com/user-attachments/assets/ba019cdc-142e-4e7c-848b-badc667ad5d4)

**Comment by shreya2k3** [comment]
@ANSHIKA-26 can you please assign this issue to me?

**Comment by ANSHIKA-26** [comment]
pr #13541 is working on it
