### ISSUE TITLE
[BUG] Navbar is not responsive

### ISSUE THREAD

**Issue by roushan-code** [ANSHIKA-26/WordWise#1395]
**Describe the bug**
Navabar is not responsive for mobile and tablet

**Expected behavior**
Navbar must be responsive for all devices.

**Screenshots**
![2024-10-2513-37-07-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/b1f31d7c-0a49-4e9b-a318-fd3af7cba302)

Could you please assign this to me?

**Comment by ANSHIKA-26** [comment]
pr #1387

**Comment by roushan-code** [comment]
Hey @ANSHIKA-26 , I know someone aleady try to make the navbar responssive. But  I have already done it by spending nearly 2-3 hr. Could you assign me please?  

### Demo video

https://github.com/user-attachments/assets/ff778de6-eff9-497c-8f25-d92ef6b68119
