### ISSUE TITLE
Separate About Page Design

### ISSUE THREAD

**Issue by Sefukamil20R** [ANSHIKA-26/WordWise#1400]
Currently, the Home and About pages contain similar content, which may be redundant for users. Creating a distinct About page would enhance user experience by providing dedicated information about the platform, team, or mission.
Expected Outcome:
                        Improved user experience with unique and organized content on each page
If you’re open to this change, I’d be happy to work on designing and implementing it!

@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
we dont need an about page, we had one , didnt work out !

**Comment by Sefukamil20R** [comment]
Ok, no problem.
