### ISSUE TITLE
Center Align Word of the day section and change font to more appealing

### ISSUE THREAD

**Issue by AbrerAsif07** [ANSHIKA-26/WordWise#1402]
I'd like to center align the word of the day section, along with changing the text font to make it more user appealing
![Screenshot 2024-10-23 153041](https://github.com/user-attachments/assets/d0d6cab6-3192-4394-8292-adc69433511b)

**Comment by AbrerAsif07** [comment]
#1402 @ANSHIKA-26 Kindly assign me the issue, I will make the necessary changes correctly.

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/pull/1319
kindly dont make the mistakes you did in this

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me
