### ISSUE TITLE
Irregular width of footer content

### ISSUE THREAD

**Issue by verma2402** [ANSHIKA-26/WordWise#1404]
**Describe the bug**
The width of the content of footer on the categories page and the contact us page is not same. 

**To Reproduce**
1. Go to categories
2. Scroll down to footer
3. Go to contact Us
4. Scroll down to footer
5. See error , the difference in width of footer content. 

**Expected behavior**
The width of the content of footer must be same on both the pages. 

**Screenshots**
![image](https://github.com/user-attachments/assets/208e69b3-3d71-48fc-921b-4c852391eb38)
![image](https://github.com/user-attachments/assets/26c5a7f9-a98b-440a-98af-f7c1e5f84dac)

I would like to work on this issue. 
Kindly assign this to me with the labels hactoberfest and gssoc-ext

**Comment by KrishChothani** [comment]
hey @ANSHIKA-26 
can i work on this --> i will give you witthin 2 hours as you assign
