### ISSUE TITLE
mismatch of website name's font color and style

### ISSUE THREAD

**Issue by verma2402** [ANSHIKA-26/WordWise#1405]
**Describe the bug**
Website name on the navbar is not the same on the home page and the other pages

**video**

https://github.com/user-attachments/assets/ac07a48f-6deb-4648-80a1-96702484299e

I would like to resolve this issue. 
Please assign this issue to me under the labels gssoc-ext and hactoberfest

**Comment by verma2402** [comment]
Please assign this issue to me @ANSHIKA-26

**Comment by verma2402** [comment]
Please assign the label for level also

**Comment by ANSHIKA-26** [comment]
fixed in latest pr
