### ISSUE TITLE
Add a pop up dialog box for subscribing to newsletter ✨✨ 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1406]
I want to add a pop up dialog box for subscribing to newsletter..

PA please assign me for this task..

![image](https://github.com/user-attachments/assets/b2de5941-32f6-4582-b4c6-7bdc8a397da9)

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
not needed
