### ISSUE TITLE
Improving the Health and wellness page with more data and information + animations and visuals.

### ISSUE THREAD

**Issue by Jay-1409** [ANSHIKA-26/WordWise#1407]
**Is your feature request related to a problem? Please describe.**
The feature focuses on improving the health and wellness page by adding more meaningful data

**Additional context**
- The information would be displayed in cards and the cards.
- The card will contain a preface of the information the a read more opens a pop up in which the following data would be present 

### Physical Health:
- **Daily Movement**: Engage in at least 30 minutes of moderate exercise, such as walking, jogging, or swimming.
- **Balanced Diet**: Focus on nutrient-dense foods like fruits, vegetables, lean proteins, and whole grains.
- **Strength Training**: Incorporate strength exercises, like weightlifting or resistance bands, at least twice a week.
- **Hydration**: Drink 8 cups of water daily to maintain energy and hydration.
- **Quality Sleep**: Aim for 7-9 hours of sleep to support physical recovery and mental clarity.
- **Stretching**: Regular stretching improves flexibility and reduces muscle stiffness.
- **Avoid Harmful Substances**: Limit smoking, alcohol, and drug use to maintain long-term health.

### Mental Health:
- **Mindfulness & Meditation**: Practice mindfulness or meditation for 10-15 minutes daily to reduce stress.
- **Social Connections**: Build and maintain relationships to support emotional well-being.
- **Therapy & Counseling**: Don’t hesitate to seek professional help when feeling overwhelmed.
- **Self-Care Routine**: Engage in activities you enjoy, such as hobbies, journaling, or creative work, to de-stress.
- **Digital Detox**: Reduce screen time and engage in offline activities to boost mental clarity.
- **Positivity & Gratitude**: Practice gratitude daily and use positive affirmations to maintain a healthy mindset.

### Emotional Well-being:
- **Emotional Regulation**: Learn techniques like deep breathing or progressive muscle relaxation to manage emotions.
- **Gratitude Practice**: Keep a gratitude journal to reflect on the positives in your life.
- **Resilience Building**: Develop a growth mindset to view challenges as opportunities for learning.
- **Set Boundaries**: Maintain emotional health by setting personal boundaries and communicating them clearly.
- **Balanced Lifestyle**: Create a healthy balance between work, personal time, and social life to reduce emotional stress.

### Social Wellness:
- **Healthy Communication**: Practice open, honest communication with friends and family.
- **Community Engagement**: Volunteer or participate in community activities to build a sense of belonging.
- **Conflict Resolution**: Develop skills to manage and resolve conflicts in relationships constructively.
- **Social Media Balance**: Limit time on social media and focus on face-to-face interactions to enhance social connections.

### Environmental Wellness:
- **Nature Connection**: Spend time outdoors, whether through hiking, walking in parks, or gardening, to connect with nature.
- **Eco-Friendly Habits**: Adopt sustainable practices like reducing waste, recycling, and conserving energy.
- **Clean Living Spaces**: Keep your home and workspace organized and clean to reduce stress and promote clarity.
- **Air Quality**: Ensure proper ventilation and air filtration to maintain a healthy indoor environment.

Please do suggest any changes :)

I would like to work under hacktober fest and GSSOC EXTD 2024

**Comment by ANSHIKA-26** [comment]
is this even related to our project ? we are focusing on the functionalities and not hardcoding articles !

**Comment by Jay-1409** [comment]
> is this even related to our project ? we are focusing on the functionalities and not hardcoding articles !

Yes it is related to the project since it makes that page robust, currently the page just looks like it is present just for the sake of being present.
