### ISSUE TITLE
Links in the contact with us opens in the same tab.

### ISSUE THREAD

**Issue by Nelcy17** [ANSHIKA-26/WordWise#1408]
The social media links in the contact with us section opens in the same tab affecting the USER EXPERIENCE.

**Expected behavior**
Links should open in the new tab.

**Screenshots**
![Screenshot-contact with us](https://github.com/user-attachments/assets/5bdeff94-3600-4286-9152-3d2d784fe97b)

**Additional context**
Also the twitter logo should changed to X.
![image](https://github.com/user-attachments/assets/d561b245-1e36-45ff-862f-1344b7f65e00)

**Comment by ANSHIKA-26** [comment]
it doesnt really need fixing thanks
