### ISSUE TITLE
Trending post section and footer changes

### ISSUE THREAD

**Issue by saatvika07** [ANSHIKA-26/WordWise#1410]
@ANSHIKA-26 please find the attached.
1. I can make the trending section more appealing to the user.
2. I can make changes in footer to look more neat and structured.

please assign this issue to me with tags gssoc-ext and hackoberfest.
Thank you
<img width="960" alt="Screenshot 2024-10-25 215310" src="https://github.com/user-attachments/assets/76db9cea-9d0e-40b1-958c-aaa8fdf061aa">
<img width="960" alt="Screenshot 2024-10-25 215922" src="https://github.com/user-attachments/assets/959b938a-bae6-4f45-a105-168d3a48dd76">

**Comment by saatvika07** [comment]
The feature post seems to be taken by someone else. I would like to make changes in the other two.

**Comment by ANSHIKA-26** [comment]
refresh the website , trending post section is already removed ! and i have already assigned someone for footer !
