### ISSUE TITLE
Make The Footer Clear And  Attractive 

### ISSUE THREAD

**Issue by sambedan1** [ANSHIKA-26/WordWise#1412]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
![Screenshot 2024-10-25 221928](https://github.com/user-attachments/assets/43eaadd5-6643-4f19-bf73-fd1a7bb2e340)

**Additional context**

**Comment by ANSHIKA-26** [comment]
its clear enough
