### ISSUE TITLE
fix: responsiveness of navbar and different navbar across pages 

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1418]
**Describe the bug**
The header on the home page appears different from the headers on other pages of the website, leading to a lack of consistency in design.

**To Reproduce**
1. Go to the home page (/home or the main landing page).
2. Observe the header section (check for differences in layout, styling, or content).
3. Navigate to another page .
4. Compare the headers on the home page and the other pages.

**Expected behavior**
The header on the home page should match the headers on all other pages in terms of design, layout, and functionality.

**Screenshots**
Home:
![Screenshot 2024-10-25 235118](https://github.com/user-attachments/assets/3202b760-25db-411b-b68c-3ac36bdcab15)
other:
![Screenshot 2024-10-25 235134](https://github.com/user-attachments/assets/0ce8c9c6-e3ed-45e7-9eb8-f67bb0f8b7b1)

**Additional context**
The issue may be related to CSS styling or HTML structure differences between the home page and other pages.

**Comment by ANSHIKA-26** [comment]
@shivam8112005 just find all navbar related issues once and then make a PR , i believe you are working for the 3rd time on navbar ?

**Comment by ANSHIKA-26** [comment]
find more issues if you want to , tbh , you should hv just fixed this in the last PR , i would hv upgraded the level to justify your work , but go ahead and let me know if there are more issues , will give level to issue accordingly

**Comment by shivam8112005** [comment]
i have done first time only but i dont know how it gets changed again and again

**Comment by shivam8112005** [comment]
even my last pr has the normal navbar

**Comment by ANSHIKA-26** [comment]
cool , lmk if there are more issues with navbar that you wish to work on , will assign level then

**Comment by shivam8112005** [comment]
i think responsivness and hamburger menu is not working except home page
![Screenshot 2024-10-26 000810](https://github.com/user-attachments/assets/09fe80e4-c884-4100-88f4-eae2c6a8b6ac)

**Comment by ANSHIKA-26** [comment]
make sure you fix the hamburger menu across all screen sizes

**Comment by shivam8112005** [comment]
yeaa ohk

**Comment by Codersweta7** [comment]
@shivam8112005 
I am working on this .

**Comment by Codersweta7** [comment]
@shivam8112005 
You go along this issue , I am dropping this .

**Comment by DINES-04** [comment]
hover of navigation bar is not interactive :
![image](https://github.com/user-attachments/assets/7c48813a-608a-42f3-8e82-87fdeb543d62)

and mobile responsive not supported and change with interactive bar:
![image](https://github.com/user-attachments/assets/b0f38156-58fa-4f81-ba56-25d2b8193033)

then, i am gssoc contributor to make change to make more interactive navigation bar.

@shivam8112005 ,Could you please assign this navigation  design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!
