### ISSUE TITLE
Improve in Nav bar ( little bit tranparent bg for enhance look)

### ISSUE THREAD

**Issue by justynigam** [ANSHIKA-26/WordWise#142]
![Screenshot 2024-10-03 112542](https://github.com/user-attachments/assets/bacf28c2-efbb-4f95-bb89-9d300a3fdbfe)
it can look good in ur website if we have some bg nav and hover view

**Comment by justynigam** [comment]
![Screenshot 2024-10-04 093129](https://github.com/user-attachments/assets/bc3a08a0-70f0-4ceb-871d-0ab8f9fdda35)
looking not good
can u make level 3 ?
i have to make from start 
there are many issue in code 
double  nav bar code in css

**Comment by Kavish-Paraswar** [comment]
I would like to work on fixing this issue. Please assign it to me.

**Comment by justynigam** [comment]
> I would like to work on fixing this issue. Please assign it to me.
> 

Already assigned
