### ISSUE TITLE
Add Hover Effect to Category Cards

### ISSUE THREAD

**Issue by VidhanThakur09** [ANSHIKA-26/WordWise#1422]
**Is your feature request related to a problem? Please describe.**
Currently, the categories cards on the category section do not have any visual feedback when hovered over. This can make the user experience less engaging and intuitive.

**Describe the solution you'd like**
To improve user interaction, we should implement a hover effect on the category cards. This could involve:

- **Background color change:** A slight change in background color when the card is hovered over. (Like home section).
- **Shadow effect:** Applying a shadow to the card when hovered over.

https://github.com/user-attachments/assets/4609ef66-0a10-421e-b484-6858191dbe24

**Additional context**
@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted";

**Comment by ANSHIKA-26** [comment]
not needed at all @VidhanThakur09 i believe you raised some other issue related to hovers as well ?
im not sure if it was you  , but kindly understand that we are currently focused on increasing the functionality of the website not adding different colors , hovers , different fonts

**Comment by VidhanThakur09** [comment]
I have raised and fixed it , I will keep this in mind and inform you if I come across any suitable or unique features.
