### ISSUE TITLE
Non Visibility of Twitter icon in dark mode on Blog page

### ISSUE THREAD

**Issue by shreya2k3** [ANSHIKA-26/WordWise#1431]
**Describe the bug**
The twitter bird icon is not visible on the dark mode in leading blog page.

**To Reproduce**
1. Go to leading blog page
3. Scroll down to social media icons and footer of the page

**Expected behavior**
A proper color of the twitter icon should be visible in dark mode.

**Screenshots**
Location 1
![image](https://github.com/user-attachments/assets/5a002dff-5f55-4567-9d79-cd06d5c55a20)

Location 2
![image](https://github.com/user-attachments/assets/58a62b74-45ff-485d-bd77-0157da13be22)

**Additional context**
Color of both twitter icons will be changed

**Comment by ANSHIKA-26** [comment]
PR already made by someone else for this
