### ISSUE TITLE
"My Reading List" Tag Missing on Blog Page

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#1442]
**Describe the bug**
I want to add the "My Reading List" tag on the blog page to provide users with easy access to all their bookmarked articles. It was there but now its not.

 
**Screenshots**
![image](https://github.com/user-attachments/assets/1b7dfb20-533d-4655-abd2-df00fd9a9e4f)

**Comment by ANSHIKA-26** [comment]
it is 
![image](https://github.com/user-attachments/assets/85f741d7-5ccf-4f86-be18-4fc756649493)
