### ISSUE TITLE
Adding Favicon to the Website

### ISSUE THREAD

**Issue by AyutheCoder** [ANSHIKA-26/WordWise#1444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AyutheCoder** [comment]
@ANSHIKA-26 ,Kindly assign this task to me.

**Comment by ANSHIKA-26** [comment]
it exists , you just cant see it coz of being hosted on github pages !
