### ISSUE TITLE
Add Chatbot-option to all pages

### ISSUE THREAD

**Issue by KrishChothani** [ANSHIKA-26/WordWise#1448]
**Describe the bug**
Add chatbot-option to all pages so user can ask any dout on any page and not want to open home page every time.

**Screenshots**
![image](https://github.com/user-attachments/assets/c213cf31-c5ad-43a4-92f9-1fcb2d4097fa)

**Comment by KrishChothani** [comment]
please assign me this task and give good level [ level-2 or 3] [ just because i will work on all pages].
i will give you this within two hours as you assign to me

**Comment by ANSHIKA-26** [comment]
not needed
