### ISSUE TITLE
Connect Login with Backend and Mongodb

### ISSUE THREAD

**Issue by KrishChothani** [ANSHIKA-26/WordWise#1449]
**Describe the bug**
Connect Login with Backend [ if backend  is working  otherwise re-write fully backend ] .

and use is login remove login button and add logout button

**Comment by KrishChothani** [comment]
please assign me 
i will give you within 1 day

**Comment by ANSHIKA-26** [comment]
its already connected , i just have not enabled it by adding mongo db uri
