### ISSUE TITLE
Adding new features 

### ISSUE THREAD

**Issue by aditiverma-21** [ANSHIKA-26/WordWise#145]
Commenting System with Reactions: Encourage community interaction by allowing users to comment and react (like, love, insightful, etc.) on blog posts.
Social Sharing Integration: Make it easy for users to share blog content across platforms like Twitter, Facebook, LinkedIn, and Pinterest.

**Comment by aditiverma-21** [comment]
please add level label.

**Comment by hiteashgupta1** [comment]
Start working on it and share relevant screenshots after changes

**Comment by aditiverma-21** [comment]
okay

**Comment by aditiverma-21** [comment]
![image](https://github.com/user-attachments/assets/ed0f56e1-4d30-4dc3-a07d-2c7c38fdd560)
Added the share button and also
![image](https://github.com/user-attachments/assets/5712568f-ab16-4f31-a9cf-c399febf0daa)
when clicked on share these options show.

**Comment by aditiverma-21** [comment]
@hiteashgupta1 please check on this update

**Comment by hiteashgupta1** [comment]
Got it you have added feature #149

**Comment by hiteashgupta1** [comment]
New pr's are merged
Kindly refork entire file and add feature and raise pr

**Comment by aditiverma-21** [comment]
Okay thank you

**Comment by hiteashgupta1** [comment]
Refork fresh from current branch

**Comment by hiteashgupta1** [comment]
And then make pr

**Comment by aditiverma-21** [comment]
yes I am doing that

**Comment by aditiverma-21** [comment]
added the PR
