### ISSUE TITLE
Add File Storage Documentation to README

### ISSUE THREAD

**Issue by banasmita24** [ANSHIKA-26/WordWise#1457]
**Is your feature request related to a problem? Please describe.**
It can be challenging for new contributors to understand the project’s file structure and know where to find specific functionality or assets. This can lead to frustration and confusion when trying to contribute or debug.

**Describe the solution you'd like**
I would like to add a "File Structure" section in the README that outlines the primary folders and files, along with a brief description of each. This will help new contributors and team members understand the organization and purpose of different files in the project.

**Describe alternatives you've considered**
N/A

**Additional context**
Adding this section will make the project easier to navigate, especially for beginners.

Please assign me this under gssoc-ext, hactoberfest-accepted ans respective level

**Comment by ANSHIKA-26** [comment]
hey , nice idea , but honestly our readme is so full right now , we dont need this , thanks !
