### ISSUE TITLE
Missing "Website Views" Option in "About Us" Section on Start Writing Page and Alignment Issue

### ISSUE THREAD

**Issue by khushigupta86** [ANSHIKA-26/WordWise#1459]
Description:

The "About Us" section on the Start Writing page is currently missing the "Website Views" option. Additionally, the text appears congested, making it difficult for users to read.

Steps to Reproduce:

1. Navigate to the Start Writing page.
2. Locate the "About Us" section.
3. Observe the absence of the "Website Views" option and the congested text layout.

Expected Behavior:

1. The "Website Views" option should be present in the "About Us" section.
2. The text should be properly spaced for better readability.

https://github.com/user-attachments/assets/a80d32a8-89a0-4080-baca-d296342a3aed

**Comment by khushigupta86** [comment]
please assignee it to me

**Comment by ANSHIKA-26** [comment]
not needed , thanks
