### ISSUE TITLE
Implementation of  Help center Page

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ANSHIKA-26/WordWise#1462]
**Is your feature request related to a problem? Please describe.**
A Help Center provides visitors with clear, organized guidance on navigating your site, finding content, and using features, making the overall experience smoother and more satisfying.

Visitors can quickly find answers to common questions, reducing frustration. A well-organized Help Center streamlines access to FAQs, tutorials, and troubleshooting information.

A dedicated Help Center signals professionalism and commitment to user satisfaction. Visitors may feel more confident using a blog that offers transparent support and resources.

**Describe the solution you'd like**
simply we can add help center page 

![Screenshot (439)](https://github.com/user-attachments/assets/c4745b5b-5d52-4acb-a065-c88b986e6aaa)

**Comment by ANSHIKA-26** [comment]
not needed ,we already have chatbot
