### ISSUE TITLE
Improve Feedback Form's Interactivity and Aesthetics

### ISSUE THREAD

**Issue by neeru24** [ANSHIKA-26/WordWise#1463]
# Issue: Improve Feedback Form's Interactivity and Aesthetics

### Description
The current feedback form has a static design with minimal interactivity, lacking hover effects and engaging visual elements. Enhancing the form's aesthetics and interactivity will improve the user experience, making it more visually appealing and responsive.

### Suggested Improvements
- **Hover Effects:** Introduce subtle hover effects on input fields and buttons to create a responsive feel.
- **Color Scheme Consistency:** Ensure a consistent color scheme throughout the form, matching the existing theme.
- **Smooth Transitions:** Implement smooth transitions for hover effects and interactions to create a seamless experience.
- **Micro-animations:** Add small animations for form elements on focus and submit to enhance user engagement.

### Expected Outcome
An interactive, attractive, and consistent feedback form that aligns with the project’s theme, improving user experience and satisfaction.

**Would like to work on this to implement these changes!**
#### kindly assign me this issue with level 2 due to the intermediate design and CSS work involved in enhancing the form's interactive elements and maintaining theme consistency. As **level 1** is given to tasks related to documentation. Would be grateful.

Thank you :)

![image](https://github.com/user-attachments/assets/2fc91585-e9b3-4d42-876f-bbb99c381ed1)

**Comment by neeru24** [comment]
@ANSHIKA-26 Kindly assign me this issue.

**Comment by ANSHIKA-26** [comment]
not needed , i dont like hovers everywhere
