### ISSUE TITLE
Enhance "Get in Touch" Form UI and Interactivity

### ISSUE THREAD

**Issue by neeru24** [ANSHIKA-26/WordWise#1464]
# Issue: Enhance "Get in Touch" Form UI and Interactivity

### Description
The current "Get in Touch" form has a basic, static design with limited user interactivity. Enhancing its visual appeal and responsiveness will make the form more engaging, encouraging users to reach out.

### Suggested Improvements
- **Redesign Form Layout:** Update the form layout to create a cleaner, more modern look.
- **Consistent Color Scheme:** Apply a color scheme that aligns with the project’s theme for uniformity across all elements.
- **Hover and Focus Effects:** Add hover effects for buttons and focus effects on input fields to improve interactivity.
- **Smooth Transitions and Animations:** Introduce smooth transitions for all hover and focus states, along with subtle animations for button clicks and form submission.

### Expected Outcome
An enhanced "Get in Touch" form with an updated design, improved interactivity, and a consistent theme that boosts user experience and engagement.

**Note:** Assign me this issue as Level 2, involving moderate CSS and UI design changes to improve interactivity and visual appeal.

**Would like to work on this to implement these changes!**

![image](https://github.com/user-attachments/assets/915ce191-101b-4b44-9083-d88d9a96c6ae)

**Comment by neeru24** [comment]
@ANSHIKA-26 Kindly assign me this issue.

**Comment by ANSHIKA-26** [comment]
not needed , we dont want to add hovers and transitions all over
