### ISSUE TITLE
Enhance UI of Categories Page with Improved Card Design and Interactivity

### ISSUE THREAD

**Issue by neeru24** [ANSHIKA-26/WordWise#1465]
# Issue: Enhance UI of Categories Page with Improved Card Design and Interactivity

### Description
The current design of the Categories page feels static, and the cards lack interactivity. Enhancing the card elements with subtle hover effects, such as shadowing, will create a more engaging and visually appealing experience for users.

### Suggested Improvements
- **Hover Shadow Effect:** Add a soft shadow effect to cards on hover to create a subtle, interactive feel.
- **Card Layout and Spacing:** Refine the card layout and spacing for a more organized, clean appearance.
- **Consistent Color Scheme:** Ensure that colors align with the overall theme for a cohesive look across all cards.
- **Smooth Transition Effects:** Implement smooth transitions for hover effects, ensuring a polished and responsive experience.

### Expected Outcome
A more engaging and visually appealing Categories page with enhanced card interactivity, consistent design elements, and a refined user experience.

**Note:** This issue is designated as Level 2, as it requires CSS modifications and design work to enhance interactivity.

**Would like to work on this to implement these changes!**

![Screenshot 2024-10-27 072301](https://github.com/user-attachments/assets/e9ebfd25-3a19-43e4-9d41-12fa2efabd55)

**Comment by neeru24** [comment]
@ANSHIKA-26 Kindly assign me this issue!!

**Comment by ANSHIKA-26** [comment]
our current design is pretty minimalist and simple , we like it that way , we dont need extra hovers and transitions ,thanks
