### ISSUE TITLE
To add page for 404 Error: Page not found

### ISSUE THREAD

**Issue by shivanjalikarande** [ANSHIKA-26/WordWise#1468]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I will add page showing 404 page not found error with user friendly design & will also add button that will help user to navigate to home page of website easily.

**Describe alternatives you've considered**

**Additional context**

**Comment by shivanjalikarande** [comment]
@ANSHIKA-26  Could you please assign this issue to me?

**Comment by ANSHIKA-26** [comment]
not needed
