### ISSUE TITLE
[BUG]:Non-hovering of sign up here in light and dark-mode both.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#1469]
**Describe the bug**
The sign up here links does not hover in light and dark modes.
 In the dark mode the text of the buttons are not clearly visible.
**To Reproduce**
1. Go to '.Login'
2. Scroll down to 'sign up here.'
3. See error

**Expected behavior**
It should be hovering to and also in the dark mode the text of the buttons are not clearly visible.

**Screenshots**

https://github.com/user-attachments/assets/f5fb7002-b596-4ff7-9a91-9a59327339f4

**Additional context**
Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
its okay , not everything needs hover
