### ISSUE TITLE
Adding New Features

### ISSUE THREAD

**Issue by noobremon** [ANSHIKA-26/WordWise#1472]
1. In categories I want to some new features like Sports, Heritage etc
2. Contact us and Give feedback page both are some I want to change them make to different page for both
3.  In about I want to make the card clickable and on clicking they leave us something about the topic

**Comment by noobremon** [comment]
Please assign this to me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
not needed , we are not hardcoding categories right now
