### ISSUE TITLE
Update Meta Tags for improved SEO and social sharing.

### ISSUE THREAD

**Issue by neeru24** [ANSHIKA-26/WordWise#1475]
#### The meta title and description for the WordWise homepage need to be updated to improve SEO and attract more visitors.

- Revise the meta title to include relevant keywords for UI design.
- Update the meta description to reflect the homepage content and include targeted keywords.

This can be efficiently accomplished by simply adding relevant keywords to the existing meta title and description in the HTML code.

By optimizing these meta tags, we can improve the website’s search engine visibility and attract more visitors.

#### Kindly assign me this issue! @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
not needed
