### ISSUE TITLE
Enable manual transitions between slides

### ISSUE THREAD

**Issue by Niharika2005** [ANSHIKA-26/WordWise#1477]
![Screenshot (183)](https://github.com/user-attachments/assets/be651b8a-f054-4f91-8a73-50989a6aa6a9)
One can not manually transition between the slides

Will add the feature to transition to any slide as required.
Pls assign me this task.

**Comment by Niharika2005** [comment]
@ANSHIKA-26 Kindly assign me the issue, I will make the necessary changes.

**Comment by ANSHIKA-26** [comment]
already added the manual transition feature !
