### ISSUE TITLE
Add a Testimonials Page as well as About Us page

### ISSUE THREAD

**Issue by shivenyadavs** [ANSHIKA-26/WordWise#1479]
**Is your feature request related to a problem? Please describe.**
Currently, WordWise lacks a dedicated space for user testimonials and an "About Us" section, which could enhance the website's credibility and connection with its users. Testimonials provide social proof, helping new visitors trust the platform, while an "About Us" page offers transparency, explaining the mission and values behind WordWise. Without these, the website feels less personal and engaging.

**Describe the solution you'd like**
# Testimonials Page: A section where readers can share their experiences and feedback on how WordWise has helped them improve their vocabulary or discover insightful content. This page will include user ratings, comments, and a submission form for new testimonials.
# About Us Page: A detailed description of the WordWise platform, its vision, team, and the purpose behind its creation. This page will highlight the value WordWise brings to its users and how it aims to make language learning enjoyable.
**Describe alternatives you've considered**
An alternative approach could involve adding these sections as part of the homepage rather than dedicated pages. However, separating them provides better clarity and focus, allowing users to navigate easily between sections.

**Additional context**

**Comment by shivenyadavs** [comment]
I can Start if you assign this to me

**Comment by ANSHIKA-26** [comment]
had this , didnt like it ,not needed right now , thanks
