### ISSUE TITLE
Issues in Footer

### ISSUE THREAD

**Issue by rupeshv2121** [ANSHIKA-26/WordWise#1481]
In Footer Email font color is bad, it is not user friendly.
when hovering on social media icons it's background effect it very poor.

**To Reproduce**
1. Go to Website Footer
2. Hover on Social media icons
3. See error

![Screenshot 2024-10-27 172105](https://github.com/user-attachments/assets/6605fefe-121b-4121-b017-865dcbc9ee44)
![Screenshot 2024-10-27 172255](https://github.com/user-attachments/assets/d25eea9b-9055-40a5-9663-44cb04469de6)

pls assign me under label gssoc-ext and hacktoberfest-accepted.
@ANSHIKA-26

**Comment by HarshKumar1121** [comment]
assign this to me

**Comment by ANSHIKA-26** [comment]
already been fixed in a PR
