### ISSUE TITLE
[BUG]: X icon is either missing or not visible on hovering in dark-mode.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#1484]
**Describe the bug**
X icon is missing in the footer of some pages while in some pages in the dark-mode on hovering it is not visible.

**Expected behavior**

It should be visible on all footers of the pages.

**Screenshots**

https://github.com/user-attachments/assets/5b6d09bb-81ec-45ae-8b0c-513b151eee89

**Additional context**

**Comment by ANSHIKA-26** [comment]
being worked on in a PR
