### ISSUE TITLE
Add a accept cookies popup

### ISSUE THREAD

**Issue by KrishPatel1205** [ANSHIKA-26/WordWise#1490]
**Is your feature request related to a problem? Please describe.**
We dont' ask the user for their permission to use the cookies in the website.

**Describe the solution you'd like**
Designing a new popup that would ask the user permission to use cookies with an option to accept or decline.

**Additional context**
<img width="345" alt="Screenshot 2024-10-27 at 8 42 17 PM" src="https://github.com/user-attachments/assets/ab4f11e6-43d9-4a3e-82ce-b16c972deb07">

**Comment by ANSHIKA-26** [comment]
nope not required , thanks
