### ISSUE TITLE
Footer Optimization Proposal 

### ISSUE THREAD

**Issue by vcerpasalas** [ANSHIKA-26/WordWise#1495]
**Describe the bug**
The footer of Wordwise lacks a clear structure and appears too wide, making it difficult to read. Additionally, the "Feature Posts" are stacked one on top of the other, which could be optimized to enhance visual presentation and user experience. The tags also need better organization.

**To Reproduce**
1. Go to the homepage of Wordwise.
2. Scroll down to the footer.
3. Observe the layout of the "Feature Posts" and tags.

**Expected behavior**
The footer should have a more organized structure. I propose the following improvements:

Divide the footer into clearly defined sections: "About Us," "Feature Posts," "Popular Tags," "Contact Information."
Redesign the "Feature Posts" section in a grid format or a more compact list to display the posts side by side instead of stacked vertically.
Improve the presentation of the tags by using a list or tags that are more compact and easier to read.

**Screenshots**

**Additional context**
A clearer structure in the footer will enhance site navigation and user experience, making it easier for visitors to find the information they seek efficiently.

**Comment by ANSHIKA-26** [comment]
#1494 is same
