### ISSUE TITLE
save user feedback to database

### ISSUE THREAD

**Issue by AyushSharma72** [ANSHIKA-26/WordWise#1498]
i want to add api so that the user feedback can be saved to the database

![image](https://github.com/user-attachments/assets/bb5def05-e1c0-4866-bfc0-f0efcee814b2)

please assign this issue to me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
i think we already have this , mind rechecking once ?

**Comment by AyushSharma72** [comment]
> i think we already have this , mind rechecking once ?

ok i will check and update you @ANSHIKA-26

**Comment by AyushSharma72** [comment]
> i think we already have this , mind rechecking once ?

i have checked it @ANSHIKA-26  it only shows a pop up and no request is sent to the backend
![image](https://github.com/user-attachments/assets/1d9b5d7d-94fa-4a96-96ef-c585bf701481)
you can assign this to me
