### ISSUE TITLE
Add Login/Signup Page, Feedback Form, and Additional Enhancements

### ISSUE THREAD

**Issue by Priyanshi231** [ANSHIKA-26/WordWise#150]
### **Overview:**
I would like to propose the addition of several key features to enhance the user experience on the WordWise website, including a Login/Signup page, a Feedback Form, and other design improvements. These features will make the website more interactive, user-friendly, and aligned with modern web standards.

### **Tasks:**

 **Login/Signup Page:**

- Design & Development of login and signup pages for user authentication.
- Fields for login: Email and Password.
- Fields for signup: Full Name, Email, Password, and Confirm Password.
- Include form validation and error handling (invalid inputs, password mismatch, etc.).
- After successful login, users should be redirected to their profile/dashboard or homepage.
- Implement a Forgot Password link for password recovery.

**Feedback Form:**

-Create a Feedback form to gather user feedback about their experience with the WordWise website.
-  Fields: Name, Email, Rating (star or numerical rating system), and a Message box for detailed feedback.
- The form should include validation (e.g., required fields, valid email format).
- On submission, feedback should be stored or emailed to the website administrator (depending on the project setup).
- Include a thank you message or confirmation after feedback submission.

**Additional Enhancements:**

- UI/UX improvements across the website for better responsiveness and user interaction.
- Enhance the navigation bar with easy access to login/signup and other important sections.
- Add hover effects, button styling, and animations for better user engagement.
- Ensure that all pages are mobile-responsive and follow the design guidelines of the project.

**Timeline:**
I estimate this task will take around 4-5 days to complete, including development, testing, and review.

Please assign me this issue, and I’ll begin working on it right away!

**Thank you!**

**Comment by usha-here** [comment]
hi @ANSHIKA-26  I would like to work on this issue and create a login / sign up and feedback form for the website.
If you could please assign this to me , it would be really great .

**Comment by hiteashgupta1** [comment]
@usha-here can you add functionalities to login/signup
