### ISSUE TITLE
Add a page for top contributors

### ISSUE THREAD

**Issue by KrishPatel1205** [ANSHIKA-26/WordWise#1500]
**Is your feature request related to a problem? Please describe.**
There is no page on the website to show  the top contributors for this project. It would be great to should some love to the top contributors of this project by showing their username, photo and GitHub profile along with the number of commits they have made in order to show appreciation for the top contributors.

**Describe the solution you'd like**
I would like to make a page for the top contributors of the website along with the header and the footer as shown here:
<img width="1799" alt="Screenshot 2024-10-28 at 10 36 52 AM" src="https://github.com/user-attachments/assets/e31fc77d-0d74-4215-84f5-f9f4c081ff65">

**Comment by ANSHIKA-26** [comment]
we had this , it didnt look great , thanks but we dont need it
