### ISSUE TITLE
Feature : Adding Page Titles for All HTML Files

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1503]
**GitHub Issue: Add Page Titles to HTML Files:**

- Adding a appropriate page title for all html files in the website.

@ANSHIKA-26 
Pls assign me this issue, give me labels, and level.

**Comment by ANSHIKA-26** [comment]
hey , this can never be merged , a lot of people are simultaneously working on this project , we would need to change all the links , which might cause more issues than solve hence i do not wish to implement this even though its needed , thanks
