### ISSUE TITLE
Implement Issue Reminder Workflow🚀

### ISSUE THREAD

**Issue by amiya-cyber** [ANSHIKA-26/WordWise#1506]
Description: Create a GitHub Actions workflow that sends reminders on open issues without updates for 7 days. The workflow should post a comment prompting assignees to take action.

Expected Benefits:

Improved responsiveness and prioritization of tasks.
Increased overall productivity.

please @ANSHIKA-26  assign me with level3 label

**Comment by ANSHIKA-26** [comment]
not needed at all , there are just 2 days left for gssoc-ext program to end :)
