### ISSUE TITLE
Alignment Issue: 'All Rights Reserved' Text Misalignment on start writing Page

### ISSUE THREAD

**Issue by kaustubh0601** [ANSHIKA-26/WordWise#1508]
**Describe the bug**

The "All Rights Reserved" text on the page is misaligned, causing a disruption in the overall layout and visual balance of the page. The text should be centered to match the page's alignment standards, ensuring consistency in the website's design and user experience.

**Expected behavior**
The "All Rights Reserved" text should be centered horizontally within its container, aligning consistently with other page elements. This will maintain the overall page symmetry and provide a clean, professional appearance.

**Screenshots**

![Screenshot 2024-10-28 154653](https://github.com/user-attachments/assets/4b39194a-b30f-4019-8972-fedb94a98b4e)

**Comment by Shalinis19137** [comment]
I really like your application  and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by ANSHIKA-26** [comment]
this issue has already been fixed

**Comment by kaustubh0601** [comment]
@ANSHIKA-26  Then could you plz tell me why its not showing on webpage

**Comment by ANSHIKA-26** [comment]
https://anshika-26.github.io/WordWise/ see this link the render one is old , will get it updated asap

**Comment by kaustubh0601** [comment]
Thank you for the confirmation. However, it’s still not updating on the new link provided. I’d like to work on this issue if possible; please assign it to me.

![image](https://github.com/user-attachments/assets/2a3c4c4e-e26b-48c3-a774-2a0874bdce0b)
