### ISSUE TITLE
Improve the navbar section

### ISSUE THREAD

**Issue by mansi066** [ANSHIKA-26/WordWise#1509]
Improve the navbar section by  adding color change hover effect ,change style ,make a logo  and set margin padding.

**Describe the solution you'd like**
 Adding smooth hover effects to navbar links can make the navigation more interactive and visually appealing.
**![Screenshot 2024-10-28 171919](https://github.com/user-attachments/assets/91ff0de8-6f79-41d7-8994-e5807e3c0e6b)** Ensuring your navbar is responsive makes your site accessible and user-friendly on all devices, which is crucial given the increasing 
mobile usage.
**Adding a logo to your website or brand offers several significant benefits:**

Brand Identity: A logo is a visual representation of your brand. It helps establish and reinforce your brand identity, making it easily recognizable.

Professionalism: A well-designed logo conveys professionalism and credibility, which can build trust with your audience.

**Comment by mansi066** [comment]
please add level

**Comment by mansi066** [comment]
@ANSHIKA-26 Please assign me for this work I wants to work on this issue

**Comment by ANSHIKA-26** [comment]
1. our navbar is responsive
2. we do not need a logo 
closing issue since its not needed thanks
