### ISSUE TITLE
Feature : Time-Based Dark Mode and Light Mode Switching

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1511]
### Issue: Time-Based Dark Mode and Light Mode Switching

1. **Automatic Theme Switching:**  
   - Enable dark mode between **7 PM – 7 AM** and light mode between **7 AM – 7 PM** based on system time.

2. **Manual Override (Optional):**  
   - Allow users to manually switch themes, with the preference taking priority over time-based changes.

3. **Smooth Transitions:**  
   - Ensure seamless and visually pleasing transitions between light and dark modes.

4. **Efficient Time Detection:**  
   - Implement lightweight logic for checking time to avoid performance issues.

5. **Future Flexibility:**  
   - Design the feature to easily accommodate custom schedules if needed later.

@ANSHIKA-26 
Pls assign me this issue and give me labels like gssoc-extd, level and hacktoberfest.

**Comment by ANSHIKA-26** [comment]
i would prefer it like it is right now , some people just want dark mode all the time , while some prefer light all the time , its good as it is , thanks
