### ISSUE TITLE
Footer Text Overlap with Language Selector on Start Writing Page

### ISSUE THREAD

**Issue by snehhhcodes** [ANSHIKA-26/WordWise#1515]
**Describe the bug**
The "Right Reserved" line in the footer is not visible due to an overlap with the language selector dropdown on the "Start Writing" page.

**To Reproduce**
1. Open the "Start Writing" page on the live server from index.html.
2. Scroll down to the footer section.
3. Observe the overlap of the language selector on the "Right Reserved" line.

**Expected behavior**
The "Right Reserved" line should be clearly visible in center like other pages without any overlap with the language selector.

**Screenshots**
![Screenshot 2024-10-28 203415](https://github.com/user-attachments/assets/711b8480-378e-4464-a65c-be9c86098ab7)

**Additional context**

**Comment by snehhhcodes** [comment]
@ANSHIKA-26 assign it to me i can solve this easily

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/429f4b24-2c8c-4400-bffa-4c8ee65d3a9e)
this was fixed a long time ago , i dont understand why you are still able to view this ? can you explain how did you open the website ? which browser and which link ?

**Comment by snehhhcodes** [comment]
> ![image](https://private-user-images.githubusercontent.com/114569262/380825679-429f4b24-2c8c-4400-bffa-4c8ee65d3a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzc4NjcsIm5iZiI6MTczMDEzNzU2NywicGF0aCI6Ii8xMTQ1NjkyNjIvMzgwODI1Njc5LTQyOWY0YjI0LTJjOGMtNDQwMC1iZmZhLTRjOGVlNjVkM2E5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNzQ2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDFiODM0ODI3Y2MxZGRhMjJlZWFjZmIzYWYzZjA1MmJkMmNkNmI2MGQ3Y2M5NzljNjk5MDUyNmE4ZDgyODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qLbhSSbtByPe2LpcHYoCkijOIpsqhUNOLTU5EYPHwxI) this was fixed a long time ago , i dont understand why you are still able to view this ? can you explain how did you open the website ? which browser and which link ?

I just opened the deployed link you have given on the repo and its still same there
