### ISSUE TITLE
FEATURE: Add a pop up dialog box for Polls/Survey 🗳️🌟🌟🌟

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1517]
I want to add a pop up dialog box for Polls/Survey 🗳️, It will appear after few seconds of opening the website, It will be very helpful for your website... ✨

🟠Adding Polls/Survey related to your website, content or products can offer several benefits:

⚪Polls/Survey encourage user interaction, making visitors feel more involved with your site.
⚪They provide direct feedback on user preferences, helping you understand your audience better.
⚪Polls/Survey results can guide future content creation or product development based on what your audience cares about.

PA please assign me for this task..

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 @hiteashgupta1

**Comment by ANSHIKA-26** [comment]
not needed , its blogging website , popup for polls would honestly look weird
