### ISSUE TITLE
Add ABOUT US page

### ISSUE THREAD

**Issue by Mrunali01** [ANSHIKA-26/WordWise#1520]
Currently, clicking on About redirects to home page.
I will create another page for it.

Please assign this issue to me @ANSHIKA-26 under label gssoc-extd

**Comment by ANSHIKA-26** [comment]
we dont have an about page in navbar ! kindly visit the updated site , and we do not want an about page !

**Comment by Mrunali01** [comment]
Oh, my bad :)
