### ISSUE TITLE
Badly spaced items in header

### ISSUE THREAD

**Issue by Mrunali01** [ANSHIKA-26/WordWise#1521]
I will space the elements in header properly.
Currently it looks like this:
<img width="500" alt="wordwise2" src="https://github.com/user-attachments/assets/0445e538-af21-4a0d-a2f1-3076069b4ca3">

I will work on this issue.
Please assign this to me @ANSHIKA-26 under label gssoc-extd

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/cbfec321-71d2-4bf1-912f-3b91c8bde1e9)
it looks like this , where are you viewing the website ?

**Comment by ANSHIKA-26** [comment]
oh sorry , here is the new deployment link for the website - https://anshika-26.github.io/WordWise/
it already has the navbar fixed :)
