### ISSUE TITLE
Improve Font Sizes and Font Styles for Better UI/UX

### ISSUE THREAD

**Issue by bavi404** [ANSHIKA-26/WordWise#1522]
Currently, the font sizes and styles across different components of the website are inconsistent. This inconsistency creates a disjointed user experience, especially when navigating between different sections of the site. In some areas, the text is too small or too large, making it harder to read, and in other areas, there isn't enough visual hierarchy between headings and body text.
To improve readability and provide a more cohesive user experience, the font sizes should follow a consistent and scalable pattern. Headings (H1, H2, H3, etc.) should be visually distinct from the body text, and the overall font size should be optimized for accessibility and readability across devices. Consistent and sensible font sizes enhance both usability and aesthetics, making it easier for users to navigate the website. This also improves accessibility, especially for users with visual impairments, by ensuring that text is readable without requiring additional zooming or adjustments. Set the base font size to 16px for body text to ensure readability.
Scale heading sizes using a modular scale:
H1: 2.5em
H2: 2em
H3: 1.75em
H4: 1.5em
H5: 1.25em
H6: 1.125em
Use a readable font family, such as 'Roboto' or 'Arial,' with fallbacks to system fonts.
Maintain consistent line heights (e.g., 1.5 or 1.6) for readability. Improving font sizes and styles will also make the site more visually appealing and professional. Typography best practices can be referenced from resources like the Google Material Design typography guidelines or [W3C's Web Content Accessibility Guidelines](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=143#text-spacing).

Please tag this issue under GSSoC Extended and Hacktoberfest to me.

**Comment by ANSHIKA-26** [comment]
@bavi404 thanks for pointing this out , but we are good with out fonts , closing issue since we dont need this
