### ISSUE TITLE
Testimonial for user trust 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1524]
By adding stronger testimonials, we can build user trust, improve credibility, and significantly enhance the overall experience on our platform

 

![Screenshot 2024-10-18 191732](https://github.com/user-attachments/assets/52a65bb1-cc7d-49ce-81b1-77586772c118)

Something like this i can redesign it according to website theme and make it more beautiful
on clicking on the arrow cards slide with an animation with create great user impact

**Comment by ANSHIKA-26** [comment]
we arent selling anything , we are a blogging website , we do not need testimonials , we have comments which do the needful , so we dont want this , thanks !
