### ISSUE TITLE
Enhance Ui of home page as its our first impression 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1526]
![image](https://github.com/user-attachments/assets/45759f56-de4a-486c-abe5-29440563cc49)

this boxes is not looking good and professional as home page is our first impression it should look the best

i can redesign it more beautiful 
improve user experience

**Comment by ANSHIKA-26** [comment]
we like it this way , you already have an issue assigned , kindly work on that first
