### ISSUE TITLE
Our contribution page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1528]
i can design theme oriented our contributor page where we show hardwork of our developer and invite more good developer to enhance our website !
 
 https://github.com/user-attachments/assets/13586955-3208-410f-84e4-88c20b61f0ae

**Comment by ANSHIKA-26** [comment]
Thank you for the suggestion, but at this time, we won’t be adding a contribution page. We’re keeping the project streamlined and focusing on core functionality, so adding extra pages isn’t a priority. I appreciate your input, though!
