### ISSUE TITLE
Add search bar on home page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1529]
![image](https://github.com/user-attachments/assets/096f1e87-0467-4224-a7ad-7d6f689ca18a)

we can add search bar on home page for better user experience and easy to navigate if user come to find some specific things
Please assign me i want to work on this!

**Comment by InderParmar** [comment]
@ANSHIKA-26 , @Sawan-Kushwah , Hi , I am eager to work on this issue, can you assign this issue to me.
