### ISSUE TITLE
ADDING A SCROLL BACK BUTTON FOR THE HOME PAGE✨

### ISSUE THREAD

**Issue by shriyadindi** [ANSHIKA-26/WordWise#1530]
I would like to add a scroll back button for the home page, kindly assign me the task.

**Comment by ANSHIKA-26** [comment]
https://anshika-26.github.io/WordWise/
 check this , we have it

**Comment by shriyadindi** [comment]
@ANSHIKA-26 ITS NOT THERE ON THE MAIN PAGE
