### ISSUE TITLE
[BUG]-Footer and Logo Misalignment 

### ISSUE THREAD

**Issue by MadhavDhatrak** [ANSHIKA-26/WordWise#1532]
**Describe the bug**
The footer and logo are misaligned and have different styling compared to the rest of the website's elements.

**To Reproduce**
1. Go to start writing page
2. Scroll down to bottom
3. See error

**Expected behavior**
The footer and logo should match the overall design and styling of the website. Additionally, the copyright notice "© 2024 WordWise. All rights reserved" should be centered.

**Screenshots**
![Screenshot 2024-10-29 102311](https://github.com/user-attachments/assets/55f5cd9b-49d7-4f91-83b8-388bef7d00b6)

**Comment by ANSHIKA-26** [comment]
https://anshika-26.github.io/WordWise/
check this , this issue is already fixed
