### ISSUE TITLE
 Real Blog page where user can post there own blog 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1534]
Added full functional blog page
You can create your own blog
you can read all blog

 

by this feature we get the real blog data of human where they share there own thoughts !! 
![image](https://github.com/user-attachments/assets/e45e4ac1-a150-4341-8e73-d59dd0a0badf)
i can redesign it according to website theme

**Comment by ANSHIKA-26** [comment]
already have this feature !
