### ISSUE TITLE
I want to add Question and guideline section

### ISSUE THREAD

**Issue by souvikpramanikgit** [ANSHIKA-26/WordWise#1544]
# ✨ Feature Request

### **Description of the Feature**

# GitHub Issue Creation Guidelines

When creating an issue in this repository, please follow these guidelines to ensure the process runs smoothly and efficiently. We also have additional resources to help guide you depending on the nature of your inquiry.

Before you create a new issue, consider the following options:

### 1. [Questions or Need Suggestions?](https://github.com/vishanurag/Canvas-Editor/discussions/new?category=q-a)
If you're unsure whether to open an issue or if you need clarifications, suggestions, or help with a feature, please use our Q&A discussion section. You can create a new discussion under the **Q&A category**, and the community or maintainers will be able to assist you.

Creating a discussion instead of an issue helps:
- Engage the community for ideas or help.
- Keep the issue tracker focused on bugs and feature requests.
- Provide a space for conversation without needing a formal issue.

### 2. [Guidelines](https://github.com/vishanurag/Canvas-Editor/blob/main/Contributing.md)
Please read our [CONTRIBUTING.md](https://github.com/vishanurag/Canvas-Editor/blob/main/Contributing.md) file for detailed guidelines on how to create a meaningful issue or contribute to the project. Following the guidelines will ensure that:
- Your issue contains all the necessary information.
- It adheres to the project's standards, making it easier to process and address.
- It fits within the workflow of the project, reducing the chance of unnecessary back-and-forth.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ecab3efb-7f50-40c2-9ddc-c3d0356a5e7d)

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

**Comment by ANSHIKA-26** [comment]
already have 3 issues pinned along with same things written in readme , hence this is not needed , thanks

**Comment by souvikpramanikgit** [comment]
I think guidlines will be needed most,because most of the time new open source contributors don't read the whole readme file, so it will redirect to the contribution.md file. @ANSHIKA-26
