### ISSUE TITLE
I want to add login and signup page

### ISSUE THREAD

**Issue by souvikpramanikgit** [ANSHIKA-26/WordWise#1545]
**Is your feature request related to a problem? Please describe.**
I want to add login and signup page

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/1c26a715-3b93-4ce7-9d41-c3c654f291e0)
![image](https://github.com/user-attachments/assets/be38c4fb-5f05-4b6d-b3b3-4082571d79b2)

**Describe alternatives you've considered**

**Additional context**

**Comment by souvikpramanikgit** [comment]
Can you assign me @ANSHIKA-26 in this issue.

**Comment by souvikpramanikgit** [comment]
Can you add the level @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
hey , we dont need a page for login/sign up

**Comment by ANSHIKA-26** [comment]
its perfect the way it is , thanks but im gonna pass on the issue and close it
