### ISSUE TITLE
website need more ui/ux advancement and performance optimization

### ISSUE THREAD

**Issue by ROHAN7051** [ANSHIKA-26/WordWise#155]
I reviewed the WordWise project, and here are some potential areas where issues could arise:

1. UI/UX Improvements
   - Responsiveness could be enhanced for different screen sizes.
   - Better alignment of elements and readability in dark mode.
   
2. Accessibility:
   - Ensure all images have descriptive `alt` text.
   - Test compatibility with screen readers.

3. Performance:
   - Optimize loading times by compressing images or reducing the number of resources loaded.

These can be potential issues and i would really like to work on them

**Comment by hiteashgupta1** [comment]
Kindly refork and resync
