### ISSUE TITLE
blog page with backend

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1554]
Added full functional blog page
You can create your own blog
you can read all blog
the data will be saved on database

https://github.com/user-attachments/assets/08a459f0-78fc-4e85-bd7e-1caa724b85a8

i can redesign it according to website theme !

**Comment by ANSHIKA-26** [comment]
why did you open 2 issues for the same thing ? closing this one

**Comment by Sawan-Kushwah** [comment]
@ANSHIKA-26 by mistake
