### ISSUE TITLE
BETTER LAYOUT OF HEADER

### ISSUE THREAD

**Issue by anushkaa-dubey** [ANSHIKA-26/WordWise#1564]
**Is your feature request related to a problem? Please describe.**
The Headings look very un organized .

**Describe the solution you'd like**
I will shorten the headings and fix the layout of Header

**Describe alternatives you've considered**
Instead of "Give feedback" i will change it to "FEEDBACK" which attracts the user attention
In similar way i will modify the headings of all sections,

PLEASE ASSIGN THIS ISSUE TO ME UNDER GSSOC EXT AND HACKTOBERFEST
**Additional context**
![image](https://github.com/user-attachments/assets/c601f564-913d-423b-8ba6-4cde189250e8)

**Comment by ANSHIKA-26** [comment]
the navbar you have shown comes under responsiveness , its being fixed , thanks
