### ISSUE TITLE
Improve Card Layout for Better Text Fit and Aesthetics

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1569]
**Describe the bug**
Text is not fitting within the card components on the home page, causing overflow issues. This results in text spilling out or being cut off, making it difficult to read.

**To Reproduce**
1. Go to the home page.
2. Observe the text within the cards.
3. Note where text overflows or appears cut of

**Expected behavior**
Text should fit within the boundaries of each card, with proper line breaks or text truncation where necessary, so that all content is fully visible and aligned.

**Screenshots**
![Screenshot 2024-10-30 234407](https://github.com/user-attachments/assets/e3518c24-35f0-44ed-aab6-0719097aaae3)

**Additional context**
The issue might be due to inconsistent font sizes, padding, or lack of text wrapping. Consider adjusting overflow, text-overflow, and white-space properties in CSS or setting a max character count for card content.

**Comment by umarsayed12** [comment]
@ANSHIKA-26 Please assign me this issue!
