### ISSUE TITLE
Improvise WordWise/category.html || Enhace cards

### ISSUE THREAD

**Issue by shubhagarwal1** [ANSHIKA-26/WordWise#1576]
<img width="585" alt="Screenshot 2024-10-31 at 4 03 41 AM" src="https://github.com/user-attachments/assets/c436c06b-c974-4757-89c1-c8af5945cad7">

**Comment by ANSHIKA-26** [comment]
what do you wish to change / improve , except hover effects / change in color/ font etc

**Comment by shubhagarwal1** [comment]
Same for this once also, i will change the and enhace cards

**Comment by ANSHIKA-26** [comment]
any refrence for what you wish to implement ? some example or some previous design of yours ?

**Comment by ANSHIKA-26** [comment]
@shubhagarwal1 ?

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
