### ISSUE TITLE
Improve WordWise/index.html page || Improve page styling and asthetic 

### ISSUE THREAD

**Issue by shubhagarwal1** [ANSHIKA-26/WordWise#1577]
<img width="629" alt="Screenshot 2024-10-31 at 4 08 13 AM" src="https://github.com/user-attachments/assets/f32412aa-4369-42ce-a589-0859f488a0ce">

**Comment by ANSHIKA-26** [comment]
what do you wish to change / improve , except hover effects / change in color/ font etc

**Comment by shubhagarwal1** [comment]
> what do you wish to change / improve , except hover effects / change in color/ font etc

design for the cards displayed, as you you can see, wholsome they are in rectangular div but at 30%they changes shapw which do no look good, i will make a new design for cards and present them neatly

**Comment by ANSHIKA-26** [comment]
not needed as of now , the ui is good as it is
