### ISSUE TITLE
Text Overlap on Hover: Image Overshadows Caption in Gallery View

### ISSUE THREAD

**Issue by Jazz-45** [ANSHIKA-26/WordWise#158]
**Describe the bug**
When hovering over images in the gallery view, the caption text gets overshadowed by the image itself, making the text difficult to read or completely obscured.

**To Reproduce**
Go to the image gallery or section where images and captions are displayed.
Hover over any image with a caption beneath it.
Observe how the image overlaps and overshadows the text when hovering.
See the text being hidden by the image.

**Expected behavior**
The image should not overlap or obscure the caption text on hover. The caption should remain clearly visible, either below or above the image, even during interaction.

**Screenshots**
![Screenshot 2024-10-03 194003](https://github.com/user-attachments/assets/f757c2f1-97f1-4ed6-83cd-8ff710ef9df8)

**Additional context**
 This issue could be related to the CSS z-index or layout rules that determine the positioning of images and text in the gallery. A possible fix could involve adjusting the z-index or hover behavior in the CSS file to prevent overlap.

**Comment by Kavish-Paraswar** [comment]
I would like to work on fixing this issue. Please assign it to me.

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by Kavish-Paraswar** [comment]
is the issue already resolved?
![image](https://github.com/user-attachments/assets/344515ac-66cd-48cc-abb0-6b20167c254c)

**Comment by hiteashgupta1** [comment]
#200 resolved
