### ISSUE TITLE
"back to top" button

### ISSUE THREAD

**Issue by shar2710** [ANSHIKA-26/WordWise#1586]
**Is your feature request related to a problem? Please describe.**
When I have to scroll all the way back to the top of the page after reaching the bottom, especially on longer pages. This disrupts the flow and makes navigation slower, especially when quick access is needed to the main menu or navigation bar.

**Describe the solution you'd like**
I would like a "Back to Top" button that appears at the bottom-right corner when scrolling down. Clicking it would instantly scroll the page back to the top, providing a seamless and user-friendly way to navigate.

**Describe alternatives you've considered**
I've considered using keyboard shortcuts to scroll up, but this isn't as intuitive for all users and may not work well on devices without keyboards, like tablets or mobile phones. Another option could be a persistent navigation bar, but that might reduce screen space on smaller devices.

**Additional context**
A "Back to Top" button could be styled minimally, appearing only after scrolling down a certain distance to avoid clutter. It would improve accessibility and user experience, especially on pages with heavy content.
@ANSHIKA-26 please assign me with this

**Comment by shar2710** [comment]
@ANSHIKA-26 please assign me with this

**Comment by ANSHIKA-26** [comment]
add on all pages

**Comment by shar2710** [comment]
@ANSHIKA-26 i'm getting this error when i run the command "git push origin backtotop
<img width="700" alt="{A3AB3E45-B7CE-4071-9031-57FB1E1D49F7}" src="https://github.com/user-attachments/assets/d58d0707-a832-4767-b807-f2e8778e7035">

**Comment by shar2710** [comment]
@ANSHIKA-26 please help

> @ANSHIKA-26 i'm getting this error when i run the command "git push origin backtotop <img alt="{A3AB3E45-B7CE-4071-9031-57FB1E1D49F7}" width="700" src="https://private-user-images.githubusercontent.com/141775335/382389972-d58d0707-a832-4767-b807-f2e8778e7035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1ODI3MjgsIm5iZiI6MTczMDU4MjQyOCwicGF0aCI6Ii8xNDE3NzUzMzUvMzgyMzg5OTcyLWQ1OGQwNzA3LWE4MzItNDc2Ny1iODA3LWYyZTg3NzhlNzAzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQyMTIwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTJmMDNjNjRiMDI2ZTk1OWViNzg3ZjNiMDdkNWI2MmRhOWI5MGQwMzZiNzhhMzUzYTE5MjdkNDkxN2FjYmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._2BqH1lxd9UCHeTl6O1aROAcyXZ5H3pyZ-u93lvOm0c">
