### ISSUE TITLE
Add Favicon to the Website 

### ISSUE THREAD

**Issue by T-Fathima** [ANSHIKA-26/WordWise#1589]
I would like to add a favicon to our website to enhance its branding and user experience. A favicon is the small icon that appears in the browser tab next to the page title, helping users quickly identify our site among multiple open tabs
![image](https://github.com/user-attachments/assets/f7f5391a-dcb3-4732-8fc7-9401e4dd4393)

@ANSHIKA-26 I would like to work on it.
Please assign it to me under gssoc-ext level1

**Comment by ANSHIKA-26** [comment]
it exists , you cant see it on github pages hosting tho
