### ISSUE TITLE
Misalignment of like buttons in home page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#1591]
These like buttons are not aligned properly, which doesn't look beautiful..

I want to fixed this issue, PA please assign me 

![Screenshot 2024-11-01 010147](https://github.com/user-attachments/assets/bc30dcef-1893-4af6-be6b-bd216eef12f8)
![Screenshot 2024-11-01 010157](https://github.com/user-attachments/assets/13baab67-8512-459f-8a98-031996a0e239)
![Screenshot 2024-11-01 010208](https://github.com/user-attachments/assets/1086a662-3c75-4dfe-a140-726560e0941e)

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
#1583 is same
