### ISSUE TITLE
 Enhancements to NavBar, Social Media Icons, and Category Cards

### ISSUE THREAD

**Issue by VidhanThakur09** [ANSHIKA-26/WordWise#1598]
**Describe the bug**
This issue aims to improve the overall user experience of the website by addressing several key areas:

- **NavBar:** Enhance the navigation bar's design and functionality to provide a more intuitive and visually appealing user experience.
- **Social Media Icons:** Ensure consistency and completeness of social media icons across the pages, including missing icons and fixing hover effects issues.
- **Category Cards:** Improve the design and content presentation of category cards, making them more engaging and informative.

**To Reproduce**
1. Go to category section 
2. Click on cards 
3. see the navbar not sticky and image in contents are sized so large  and social media icons missing with hover effect error

**Expected behavior**
1. sticky Navbar
2. Image in content section on each card must be in perfect size.
3. improve categories cards UI where text is aligned perfectly and visible when hover
4.  improving social media icons ( added missing icon and fixed hover effect).

**Screenshots**

https://github.com/user-attachments/assets/76236b35-ef4b-449b-9734-e2f24ed3d503

**Additional context**
@ANSHIKA-26 can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted";

**Comment by ANSHIKA-26** [comment]
navbar is already sticky , improve the categories page cards

**Comment by VidhanThakur09** [comment]
Ok mam, Thank you for assigning this to me.
