### ISSUE TITLE
Feature : Add Phone Link for Contacting Us

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1607]
### Issue: Add Phone Link for Contacting Us

Implement a clickable phone link for the normal phone text to enhance user experience. This `tel:` link should initiate a call when clicked, making it easier for users to contact us.

**Image for reference:**
- ![image](https://github.com/user-attachments/assets/2343040a-966f-4b0d-b427-4f3337757abf)

@ANSHIKA-26 
Pls assign me this issue, give me labels, level.

**Comment by ANSHIKA-26** [comment]
thanks for pointing this out , but we are currently focusing on core functionality of our project and not issues such as this , sorry but you issue will be closed since its not needed !
