### ISSUE TITLE
Alignment of the images is not perfect .

### ISSUE THREAD

**Issue by Nikhilkumar111** [ANSHIKA-26/WordWise#161]
Hello @ANSHIKA-26 ,
I want to work on this issue to perfectly align the images . To looking website perfect . If you assign to me this issue I'le work on this issue . I promised you that I follow all the contributing guidelines .
plz assign to me this with the label of extd-2024.

![Screenshot 2024-10-03 203439](https://github.com/user-attachments/assets/a425520a-4d3c-436c-9c58-d224a88829e9)

**Comment by Nikhilkumar111** [comment]
hello @ANSHIKA-26 ,
I work on this issue or not .

**Comment by ANSHIKA-26** [comment]
yes

**Comment by usha-here** [comment]
Hello @ANSHIKA-26 
I want to work on this issue to perfectly align the images. I was wondering if it would be possible for you to assign me an issue to work on? I'd love to help out and learn more about the project while contributing to its success.

**Comment by Kavish-Paraswar** [comment]
Hello @ANSHIKA-26
I want to work on this issue to perfectly align the images. I was wondering if it would be possible for you to assign me an issue to work on? I'd love to help out and learn more about the project while contributing to its success.

**Comment by hiteashgupta1** [comment]
Already has been resolved
