### ISSUE TITLE
adding scroll to top button on start writing page

### ISSUE THREAD

**Issue by ak-0283** [ANSHIKA-26/WordWise#1622]
As a contributor to GirlScript Summer of Code 2024, I noticed the absence of a scroll-up button on the Start Writing page, which made navigation challenging, especially on longer posts. To enhance user experience and streamline content creation, I implemented a scroll-up button, allowing users to quickly return to the top of the page. This feature improves accessibility and usability, making the page more intuitive and user-friendly.

**View Bug**

![Screenshot 2024-11-02 191144](https://github.com/user-attachments/assets/1613e56e-a0fb-44a3-b064-13e29ce038f1)

**Comment by ak-0283** [comment]
please assign me this issue @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
add it on all pages please

**Comment by ak-0283** [comment]
first of all thnx for assign me & and you also told that all it all the pages i.e scroll button but after forking i have updated the scroll button in home page & i found that few pages  already scroll button is available. what should i do next

**Comment by ANSHIKA-26** [comment]
no problem , just add it on start writing page and make a PR

**Comment by ak-0283** [comment]
In start writing page I have done many times to update scroll button but I don't find the problem that's scroll button is not showing. So I have added it to main page because In main page scroll button is not available I have updated.
