### ISSUE TITLE
Feature : Prevent Application Crash on Database Connection Failure

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#1623]
# Prevent Application Crash on Database Connection Failure

**Description**:  
Implement error handling to prevent application crashes when database connections fail. Display an alert to inform users of the connection issue, and, if possible, provide a "Retry" option or guidance on next steps.

**Images for reference: **
 - ![image](https://github.com/user-attachments/assets/adb3b6f1-9c8c-471f-8739-605350ca8476)

@ANSHIKA-26 
Pls assign me this issue, give me labels and level.

**Comment by ANSHIKA-26** [comment]
thats okay , let it be , i will add the mongo db uri soon , this wont be an issue then
