### ISSUE TITLE
Subscribe to newletter

### ISSUE THREAD

**Issue by haseebzaki-07** [ANSHIKA-26/WordWise#1630]
**Is your feature request related to a problem? Please describe.**
Users entering their valid mail ids in the input fields should receive a confirmation mail to their mail ids.

**Describe the solution you'd like**
I will write the backend API that will use nodemailer for the purpose.
![Screenshot 2024-11-03 003557](https://github.com/user-attachments/assets/4da007f5-0a0e-4aeb-9bfe-68011bcce8d0)

**Comment by ANSHIKA-26** [comment]
not needed , the newsletter isnt functional
