### ISSUE TITLE
Email for feedback

### ISSUE THREAD

**Issue by haseebzaki-07** [ANSHIKA-26/WordWise#1631]
**Is your feature request related to a problem? Please describe.**
Users feedback should be stored in the database and also they should receive a mail saying thank you and the feedback they shared!

**Describe the solution you'd like**
Will write the backend API and use nodemailer for the purpose,.

![Screenshot 2024-11-03 003850](https://github.com/user-attachments/assets/26d63e3c-9942-44e2-b00f-a9e6e9c247f0)

**Comment by Ranj8521Kumar** [comment]
I want to tackle this issue, please assign to me.
