### ISSUE TITLE
Enhancing footer for appealing look

### ISSUE THREAD

**Issue by saatvika07** [ANSHIKA-26/WordWise#1633]
@ANSHIKA-26 the footer as shown has some areas to improve as increasing the space in between the image and text in feature post and adding  a separator for popular tags.

Please assign it to me with the gssoc and hactoberfest tags.

PFA
Thank you!
<img width="953" alt="Screenshot 2024-11-03 084145" src="https://github.com/user-attachments/assets/fc30ee29-d3ee-4df1-9d6f-035b28dea173">

**Comment by saatvika07** [comment]
Pleasee assign me this issue!

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/44d22f87-cca5-4c39-a079-7ce921ea5a5a)
this is what the footer look like right now and its perfect , we do not wish to change it thanks
