### ISSUE TITLE
Previous and next post changes

### ISSUE THREAD

**Issue by saatvika07** [ANSHIKA-26/WordWise#1634]
@ANSHIKA-26 the image is not rounded in the previous and next post changes as marked in the image attached, with changes it can look much neater.

Please assign it to me with the gssoc and hactoberfest tags.

PFA
Thank you!
<img width="952" alt="Screenshot 2024-11-03 084553" src="https://github.com/user-attachments/assets/f276df09-caeb-49a6-93d2-deab4fe4fb84">

**Comment by saatvika07** [comment]
Pleasee assign me this issue!

**Comment by ANSHIKA-26** [comment]
its okay , we like it this way
