### ISSUE TITLE
Footer is different for different pages

### ISSUE THREAD

**Issue by saatvika07** [ANSHIKA-26/WordWise#1635]
@ANSHIKA-26 the footer is different for different pages and is written multiple times which is not good in few pages like in the travel page. So, a common footer page can be used which will reduce the number of lines and enhance the look. 

Please assign it to me with the gssoc and hacktoberfest tags.

This image is of the home page footer:
<img width="958" alt="Screenshot 2024-11-03 085524" src="https://github.com/user-attachments/assets/1ea7d68a-bab1-4ba5-abef-6e680ca3cba3">

and this one is for the travel page:
<img width="959" alt="Screenshot 2024-11-03 085203" src="https://github.com/user-attachments/assets/8b0bd071-a1a0-42a4-a62e-8d57f5647a6f">

Thank you!

**Comment by saatvika07** [comment]
Pleasee assign me this issue!

**Comment by ANSHIKA-26** [comment]
its not , kindly re- check
