### ISSUE TITLE
header is different for different pages

### ISSUE THREAD

**Issue by saatvika07** [ANSHIKA-26/WordWise#1636]
@ANSHIKA-26 the header is different for different pages and is written multiple times which is not good in few pages like in the travel page. So, a common header file can be used which will reduce the number of lines and enhance the look.

Please assign it to me with the gssoc and hacktoberfest tags.

Below is the home page header:
<img width="958" alt="Screenshot 2024-11-03 085524" src="https://github.com/user-attachments/assets/895e482e-fc2e-41a4-b32c-21d5ec6504bf">

and this is of the travel page header:
<img width="960" alt="Screenshot 2024-11-03 085840" src="https://github.com/user-attachments/assets/625d281b-9b5a-4b99-80b5-3d2aeb9da71b">

Thank you!

**Comment by saatvika07** [comment]
Pleasee assign me this issue!

**Comment by ANSHIKA-26** [comment]
already fixed in a PR
