### ISSUE TITLE
start-writing page is misaligned and contains conflict code.

### ISSUE THREAD

**Issue by rishika105** [ANSHIKA-26/WordWise#1643]
**Describe the bug**
The start writing page is messed up due to some conflicts code added in between.

**To Reproduce**

**Expected behavior**
It should be properly aligned with no over texts.

**Screenshots**
![image](https://github.com/user-attachments/assets/c62852b7-e9df-4763-a342-6dd620dbb092)

**Additional context**

**Comment by ANSHIKA-26** [comment]
fixed already
