### ISSUE TITLE
Add content in Virtual Realms Section

### ISSUE THREAD

**Issue by mansi066** [ANSHIKA-26/WordWise#1645]
When I go through your website on clicking on home page section .I see the virtual realms I was eager to learn about it more but when I am clicking on the Virtual Realms does not redirect to any page as I can't read the content of this topic .So, I want to add the content  related to  this topic like **Abouts ,images , technology ,how does it work etc.**

**Additional context**
![Screenshot 2024-11-03 172122](https://github.com/user-attachments/assets/223da18b-c675-4875-90b2-88b2e7337d17)

**Comment by ANSHIKA-26** [comment]
we arent adding hardcoded articles at the moment , thanks
