### ISSUE TITLE
scroll to top button is inconsisten on pages except home page

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1649]
**Describe the bug**
The "Scroll to Top" button appears on all pages except the Home page, where it is missing or not displayed consistently.

**To Reproduce**
1. Navigate to the Home page.
2. Scroll down to a position where the "Scroll to Top" button should appear.
3. Observe that the button does not appear as expected on the Home page.
4. Navigate to any other page and scroll down. The "Scroll to Top" button appears as expected.

**Expected behavior**
The "Scroll to Top" button should appear on all pages, including the Home page, when the user scrolls down.

**Screenshots**
![Screenshot 2024-11-03 211111](https://github.com/user-attachments/assets/f184fffd-f158-4820-b46d-415613c4d5f7)

**Additional context**
This issue might be related to different CSS/JavaScript settings on the Home page. Check if any conditional display logic is set for the button specifically on the Home page or if there's a conflict with other elements on the page.

**Comment by ANSHIKA-26** [comment]
#1586 is doing it

**Comment by shivam8112005** [comment]
ohk
