### ISSUE TITLE
Adding NavBar on Profile page as well

### ISSUE THREAD

**Issue by Somyajain2004** [ANSHIKA-26/WordWise#1651]
![{853BA005-1536-4318-8CB0-54550B100115}](https://github.com/user-attachments/assets/3492ac34-deaa-4636-ba7e-79f3c3f65e8e)

On switching to profile page, the navbar disappears.
Though there's a home icon to return to HOME page, but i feel it would be better if NavBar is visible on profile page as well, to maintain uniformity throughout the site.

Also, the display mode switches to LIGHT mode automatically, on the profile page, and there's no option to switch to another mode on profile page.

I would like to work on this issue.

**Comment by ANSHIKA-26** [comment]
we do not need a navbar there , thanks
