### ISSUE TITLE
Removing the default info from the profile page and updating it with actual user info.

### ISSUE THREAD

**Issue by Somyajain2004** [ANSHIKA-26/WordWise#1653]
![{39BE29F6-C5D2-4862-B137-F119AA648BC0}](https://github.com/user-attachments/assets/aefb0117-5a87-4231-8a13-16f5ef64538d)

As shown in the screenshot attached, 
The issues I've noticed :
1. The default dummy USER INFO present on the PROFILE page of the user.
2. This information doesn’t update after the user logs in. To address this, the Sign Up/Login page should be shown when the site is opened, and the profile details should only become visible once the user has signed up or logged in.
3. Currently, the sign-up form only asks for email, password, and username. However, the profile page (as shown in the screenshot) 
    displays additional details like phone number, bio, and address. We could add a feature for users to complete their profile with these 
    extra details after signing up, or we could ask for them during the sign-up process. Please let me know which option you prefer.
4. The "Edit" button on the profile page doesn’t function yet. It should allow users to modify their info and then save changes to the 
    backend to update the profile page.

I would like to fix the above mentioned issues on the profile page.

**Comment by Somyajain2004** [comment]
![{42AE65CE-2905-443F-9431-F3583012EBBC}](https://github.com/user-attachments/assets/f711326d-e209-4d6c-81c9-015c9abe5563)

Why am i getting this?

**Comment by ANSHIKA-26** [comment]
doesnt matter , thats a workflow , ignore it
