### ISSUE TITLE
Scroll to top button with animation 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1655]
As we have a blog website so there is need of this button as someone reaches to end after reading blog he has to scroll to top manually which create bad user experience so we can

add this button
something like this

https://github.com/user-attachments/assets/99cbff0d-bf74-411c-8a56-f67f34d7d234

**Comment by ANSHIKA-26** [comment]
#1586 is doing it

**Comment by Sawan-Kushwah** [comment]
@ANSHIKA-26 but she added that back to top button on HTML CSS section which is not preferable (let me correct if i am wrong)
![image](https://github.com/user-attachments/assets/62979dd4-055c-4a0b-8741-c31a08db8a2c)


i will add this button on our main website  !!
