### ISSUE TITLE
want to modify social media icons and add animations on them while hovering .

### ISSUE THREAD

**Issue by ritikm31** [ANSHIKA-26/WordWise#1657]
**Is your feature request related to a problem? Please describe.**
social media icons looks so normal i want to modify them and also add animations on them while hovering.

**Describe the solution you'd like**
adding animations and make them look more appealing.

**Comment by ANSHIKA-26** [comment]
we dont want more hover effects , thank you

**Comment by ritikm31** [comment]
that's totally fine tell me something more if you want in it i''ll love to contribute.
