### ISSUE TITLE
Buttons are colliding with each other

### ISSUE THREAD

**Issue by Ashish-Patnaik** [ANSHIKA-26/WordWise#1671]
**Describe the bug**
In contact Us page the quick navigation button is overlapping with the send button

**To Reproduce**
1. Go to 'Contact Us Page'
2. Scroll down and focus on send button 
3. See error

**Expected behavior**
The quick navigation button should be in the right bottom corner

**Screenshots**

![3](https://github.com/user-attachments/assets/425626c2-55f7-4a8c-94ae-d3c2c3dfa12e)

**Comment by ANSHIKA-26** [comment]
fix this on all pages
