### ISSUE TITLE
Add Hero Section to Homepage of WorldWise

### ISSUE THREAD

**Issue by IkkiOcean** [ANSHIKA-26/WordWise#1673]
**Description:**  
The homepage of the WorldWise blog currently lacks a hero section. A hero section will improve the page’s visual appeal and help draw users' attention to featured content or recent posts. This section should include an engaging background image, a headline, and a short description that highlights the purpose of the blog. Optionally, we could add a "Read More" or "Explore" button that links to the latest posts or categories.

**Requirements:**  
- Add a visually striking hero section at the top of the homepage.
- Include:
  - **Headline**: A catchy tagline summarizing the blog’s focus (e.g., "Explore the World through Stories").
  - **Description**: A short introduction to WorldWise, encouraging users to dive into the content.
  - **Background Image**: Use an image that reflects the blog’s travel or storytelling theme.
  - **Button (optional)**: A button that links to the latest blog posts or featured categories.
- Ensure the hero section is responsive and looks good on both desktop and mobile devices.

**Design Suggestions:**  
- Use a high-quality, full-width background image.
- Apply overlay text for readability.
- Make the section height dynamic or set a standard height for different screen sizes.
- Use typography and colors consistent with the rest of the website's design.

### Demo

<img width="773" alt="Screenshot 2024-11-04 at 8 58 39 PM" src="https://github.com/user-attachments/assets/069702ca-b224-44dd-934a-6b26ef91eee1">

Note: I will implement it considering the context and UI of wordwise

**Comment by ANSHIKA-26** [comment]
thanks but this isnt needed right now
