### ISSUE TITLE
Fix Position of "Scroll to Top" Button on All Pages

### ISSUE THREAD

**Issue by IkkiOcean** [ANSHIKA-26/WordWise#1674]
Description:
The "Scroll to Top" button currently appears inconsistently across different pages, leading to a disjointed user experience. In some cases, the button overlaps with other page elements or appears in different locations depending on screen size. This issue aims to ensure that the "Scroll to Top" button has a fixed position across all pages for a more cohesive and accessible design.

<img width="1280" alt="Screenshot 2024-11-04 at 9 00 54 PM" src="https://github.com/user-attachments/assets/9412b7ca-a8b6-4bd0-aaab-856196607b95">

### Note: I found other issue which doesnt go to the core of the problem only wants to solve the problem at one section but I will solve it everywhere on the website so it doesnt repeat again

**Comment by ANSHIKA-26** [comment]
#1671 is working on this
