### ISSUE TITLE
Profile Page Showing even when not logged in

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#1693]
**Describe the bug**
Profile Page Showing even when not logged in

**To Reproduce**
1. Go to 'main'
2. Click on 'my profile'
3. See error

**Expected behavior**
No profile page when not logged it

**Screenshots**
![image](https://github.com/user-attachments/assets/2f2a0cd6-5122-4754-8351-137598bf55e0)
![image](https://github.com/user-attachments/assets/fb54ff3d-e5ca-4185-8486-30ad325b0b62)

**Additional context**
Make sure to add the labels :)
Thanks :)

**Comment by LatikaAdhikari064** [comment]
I would like to work on this issue .Please assign it to me.
Expected is no profile page when not logged it but it is showing .
