### ISSUE TITLE
add user generated content

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ANSHIKA-26/WordWise#1696]
**Is your feature request related to a problem? Please describe.**
there is no review section from users thus we don't have any idea for what more development must be done in worldwise

**Describe the solution you'd like**
I would like to add a review section that asks users to type their reviews
I can add something similar to this:
![image](https://github.com/user-attachments/assets/b4c8644c-edf8-43e8-9929-24602ad88f1e)
or I can also add textarea along with starts where user can add review at the moment
![image](https://github.com/user-attachments/assets/1e0c8181-2ca1-4e1f-84df-6197add6a415)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ANSHIKA-26** [comment]
we have feedback and we do not need reviews for a blogging website thanks
