### ISSUE TITLE
Merging of buttons

### ISSUE THREAD

**Issue by sachinggsingh** [ANSHIKA-26/WordWise#1699]
**Describe the bug**
The chatbot button and the Go-to-top buttons are merged in the blog page 

**Expected behavior**
Need to be separated

**Screenshots**
![Screenshot 2024-11-05 214226](https://github.com/user-attachments/assets/1f79fcb9-bda4-4ddd-97ca-4ffb8b616b06)

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/pull/1681
this PR will take care of it
