### ISSUE TITLE
To add Go-to-Top button

### ISSUE THREAD

**Issue by sachinggsingh** [ANSHIKA-26/WordWise#1701]
**Describe the solution you'd like**
To add a go to top button in the start writing page
![Screenshot 2024-11-05 214602](https://github.com/user-attachments/assets/bf0e6545-e1f4-4ab8-ade0-b589c84e833c)

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/pull/1681 working on it
