### ISSUE TITLE
can add logo to the website

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ANSHIKA-26/WordWise#1703]
**Is your feature request related to a problem? Please describe.**
no hallmark present in website

**Describe the solution you'd like**
can add a logo
![image](https://github.com/user-attachments/assets/0a805ea7-8a7d-431c-af23-ed444bfc7a93)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ANSHIKA-26** [comment]
not needed thanks
