### ISSUE TITLE
add mark as read option below each blog

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ANSHIKA-26/WordWise#1704]
**Is your feature request related to a problem? Please describe.**
there is no track of what all is read by user

**Describe the solution you'd like**
can add a tick type symbol which turns green after clicking on it (present under every blog post beside like)
![image](https://github.com/user-attachments/assets/a9e45e1f-7267-418f-af13-8793717c3ae3)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ANSHIKA-26** [comment]
this doesnt need to be implemented on the hardcoded frontend , do you wish to add a route for the same in the express part of wordwise? as in work in backend for this ?

**Comment by ANSHIKA-26** [comment]
if you want to then kindly work here - 
https://github.com/ANSHIKA-26/WordWise/tree/main/frontend
(for frontend )
and here for backend -
https://github.com/ANSHIKA-26/WordWise/tree/main/backend

**Comment by ANSHIKA-26** [comment]
@SanikaBhalerao1345

**Comment by SanikaBhalerao1345** [comment]
@ANSHIKA-26 can i work only for frontend

**Comment by ANSHIKA-26** [comment]
@SanikaBhalerao1345 im sorry but we do not want more hardcoded options , we already have lot of static functionality ! thanks but i will be closing this issue since its not needed
