### ISSUE TITLE
Can add a welcoming pop-up

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ANSHIKA-26/WordWise#1705]
**Is your feature request related to a problem? Please describe.**
website looks plain and simple

**Describe the solution you'd like**
cn add a welcoming pop-up with greeting-messages, quotes that promote user to write blogs and to motivate them to read new posts.
can add visually appealing image in pop-up

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ANSHIKA-26** [comment]
not needed , we like what we have right now
