### ISSUE TITLE
Get feedback form data on Mail

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1709]
We can send the data of feedback form on mail with clean and clear ui

**Comment by ANSHIKA-26** [comment]
as in send the data back to user ?

**Comment by Sawan-Kushwah** [comment]
@ANSHIKA-26 we can send this data to admin mail so that admin or if you want we can send this to user too

for user ...
"thanks for your feedback and details of feedback"

for admin ....
"person send a feedback and feedback details...."

**Comment by ANSHIKA-26** [comment]
sending data to admin makes sense , sending feedback back to user seems weird , just implement it for admin
