### ISSUE TITLE
[Feature Request]: Addition of Terms and Conditions Page in Footer and T&C Page Creation.

### ISSUE THREAD

**Issue by Shariq2003** [ANSHIKA-26/WordWise#1712]
I want to craete and add a "Terms and Conditions" (T&C) page link in the footer of the website. Currently, the website lacks easy access to a dedicated page that outlines the terms and conditions. This addition will improve user trust and meet legal requirements for many businesses.

### Demo

![image](https://github.com/user-attachments/assets/dbcb976c-c4fb-4d78-ae78-91f9b04de123)

**NOTE : THE THEME OF THE PAGE VARIES AF PER THE WEBSITE THEME**

**Comment by ANSHIKA-26** [comment]
its a blogging website , we dont need this thanks
