### ISSUE TITLE
Adding a contributors page 

### ISSUE THREAD

**Issue by Son7c** [ANSHIKA-26/WordWise#1721]
**Is your feature request related to a problem? Please describe.**
There is no page for contributors who have contributed to this project

**Describe the solution you'd like**
I would add a contributors page that shows all the contributors in the project and also add cool animation when contributors card is hovered. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Son7c** [comment]
@ANSHIKA-26 Please assign me this issue

**Comment by ANSHIKA-26** [comment]
not needed thanks
