### ISSUE TITLE
Adding back to  top feature to every page!!

### ISSUE THREAD

**Issue by Ashmitha2606** [ANSHIKA-26/WordWise#1724]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2024-11-06 192158](https://github.com/user-attachments/assets/b6e5c874-2fa8-4612-b3d0-6bb3c5f99697)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
already done in a PR
