### ISSUE TITLE
Search bar in Home Page

### ISSUE THREAD

**Issue by pinakviramgama** [ANSHIKA-26/WordWise#1726]
There should be a search bar in home page to redirect user to different pages so that user can go to each and every page or search blogs very easily

This feature can be developed using javascript

**Comment by pinakviramgama** [comment]
Dear @ANSHIKA-26  please assign me this issue

**Comment by pinakviramgama** [comment]
Dear @ANSHIKA-26 , please assign this issue to me so that i can start working upon it.

**Comment by pinakviramgama** [comment]
Mam @ANSHIKA-26 , please assign me this issue.

**Comment by ANSHIKA-26** [comment]
#1706 is doing it , issues are assigned on first come first serve basis
