### ISSUE TITLE
scroll to top button is not consistent

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#1733]
**Describe the bug**
The scroll-to-top button does not consistently appear on all pages, or sometimes fails to function as expected.

**To Reproduce**
1. Navigate to any page where the scroll-to-top button should be visible.
2. Scroll down to trigger the button.
3. Observe whether the button appears and functions as expected.

**Expected behavior**
The scroll-to-top button should be present on all pages, appearing when the user scrolls down and smoothly returning to the top when clicked.

**Screenshots**
![Screenshot 2024-11-07 002921](https://github.com/user-attachments/assets/e3f12335-a24a-4e03-a326-9de683788000)

**Additional context**
This may require checking page layouts or scripts that handle the button’s visibility and functionality.

**Comment by ANSHIKA-26** [comment]
fixed

**Comment by shivam8112005** [comment]
@ANSHIKA-26  but why there are two scroll to top buttons 
![Screenshot 2024-11-07 122842](https://github.com/user-attachments/assets/dac01c4f-52ac-459e-957a-e1f0f8e374fa)
