### ISSUE TITLE
Mismatch of footer in category section

### ISSUE THREAD

**Issue by mansi066** [ANSHIKA-26/WordWise#1737]
**Describe the bug**
On scroll down to the footer which is mismatch to home section

**To Reproduce**
1. Go to Category
2. Click on Food Section
3. Scroll down to Footer

**Expected behavior**

**Screenshots**
Home page:
![Screenshot 2024-11-07 090749](https://github.com/user-attachments/assets/cb1d3eb4-d142-48eb-90ae-b0e5b02fa6fc)

Category page:
![Screenshot 2024-11-07 090721](https://github.com/user-attachments/assets/778128db-22cd-4397-9885-e8ad247b8df6)

@ANSHIKA-26 Please assign me for this work 
**Additional context**

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/7e276d56-b01e-48de-859a-fde4e08d976d)
i dont see any mismatch , can you share a video ?

**Comment by mansi066** [comment]
![Screenshot 2024-11-07 163947](https://github.com/user-attachments/assets/c9373384-aa33-4696-8e9d-da9edfa4f81f)
![Screenshot 2024-11-07 163921](https://github.com/user-attachments/assets/273a938c-e85e-480c-8d5b-49a0584d42e9)
Twitter icon not visible  in category section
Alignment of popular tags different in category section

**Comment by mansi066** [comment]
https://github.com/user-attachments/assets/0c5fc6b9-4107-4701-921d-a931dbe8d7a7

**Comment by mansi066** [comment]
@ANSHIKA-26  I have shared the screen recording

**Comment by ANSHIKA-26** [comment]
can you share the link you are using to open this?

**Comment by ANSHIKA-26** [comment]
https://anshika-26.github.io/WordWise/
this is our hosted link , i do not see any error in this

**Comment by ANSHIKA-26** [comment]
@hiteashgupta1 confirm ?

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26 It's working

**Comment by hiteashgupta1** [comment]
The error in single individual category page when click on it

**Comment by hiteashgupta1** [comment]
@mansi066 Also fix icons not visible in dark mode 
Check on each category page

**Comment by ANSHIKA-26** [comment]
@mansi066 make sure the footer is consistent with the rest of the website

**Comment by mansi066** [comment]
Ok
