### ISSUE TITLE
Add Blog AS per User's choice

### ISSUE THREAD

**Issue by pinakviramgama** [ANSHIKA-26/WordWise#1740]
The user can upload the blog as per his/her choice and it will contain
share button -> which will share the blog on twitter, linkedin and instagram.
delete blog button -> user can delete that blog anytime.
user can upload image, text and username in it's blog,

**Comment by pinakviramgama** [comment]
Dear @ANSHIKA-26 , please assign me this issue

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/blob/main/backend/routes/blogRoutes.js
this feature has already been implemented in our backend made on mern , thanks !
