### ISSUE TITLE
Add animation and hover effect to social icons 

### ISSUE THREAD

**Issue by PATILYASHH** [ANSHIKA-26/WordWise#1744]
**Hover effect of social icon is not good its need some more improvement by adding some more animation when hover it that will make it interesting and attractive**
![image](https://github.com/user-attachments/assets/ed4a45ff-0910-4aff-8371-236bb44b3997)

**Comment by LatikaAdhikari064** [comment]
Hover effect shows some delays effect on  social icon it should be  improvement by adding some more animation .It can be made more attractive and eye catchy .Can you pls assign it to me I will make it more better.

**Comment by PATILYASHH** [comment]
I created the issue please assign me

**Comment by ANSHIKA-26** [comment]
hey , thanks for raising this concern but we are okay with the current hover effects , they are a very minor thing in our functionalities and we are focusing on major features as of now , thanks but i will be closing this issue since i do not wish to change the hover effect
