### ISSUE TITLE
Images used in cagtegories .

### ISSUE THREAD

**Issue by LatikaAdhikari064** [ANSHIKA-26/WordWise#1745]
**Describe the bug**
Images used in categories are not eye catchy . If more interesting and related images are places they attract more attention.
**To Reproduce**
1. Go to categories 
2. Click on images and set some better images

**Expected behavior**
According to their names it should have more height and width and better background image that make a person feel to open it .

**Screenshots**
![Screenshot 2024-11-07 154715](https://github.com/user-attachments/assets/36235343-b09d-4366-8f7b-a8414c9f138e)

**Additional context**
It should also has some heading that make it more formal.

**Comment by LatikaAdhikari064** [comment]
> Thanks @LatikaAdhikari064 for raising this issue! We'll look into it.We hope you have made sure that a similar issue doesnt exist , if it does, kindly ask to be assigned on that issue

yes , thank you

**Comment by ANSHIKA-26** [comment]
@LatikaAdhikari064 this was closed a long time ago !
