### ISSUE TITLE
Feature: Add Search Feature for Categories Card

### ISSUE THREAD

**Issue by PrityanshuSingh** [ANSHIKA-26/WordWise#1750]
**Is your feature request related to a problem? Please describe.**
Users may find it challenging to quickly locate specific categories within a large list. This can make navigation cumbersome and reduce efficiency when searching for a particular category.

**Describe the solution you'd like**
Implement a search functionality for the categories card that allows users to type keywords and filter the displayed categories accordingly. As the user types, only categories matching the search term should appear, making it easy to find the desired category without extensive scrolling.

**Describe alternatives you've considered**
- Adding a sorting option for categories.
- Grouping categories into sections, although this may still require significant scrolling for users to locate specific categories.

**Additional context**
A search bar at the top of the categories card can significantly enhance usability, especially for users navigating through numerous categories. This feature would improve the user experience by offering a quick and efficient way to find relevant content.

![image](https://github.com/user-attachments/assets/b4208b80-3c3c-49eb-9402-110a4e4c3265)

**Comment by ANSHIKA-26** [comment]
#1706 is doing it
