### ISSUE TITLE
Comment Upvotes and Best Answer Feature 

### ISSUE THREAD

**Issue by Ashmitha2606** [ANSHIKA-26/WordWise#1763]
**Is your feature request related to a problem? Please describe.**
Comment Upvotes and Best Answer Feature
Allow users to upvote comments and display the highest-voted comment at the top to encourage quality engagement.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
we  honestly do not need these things for comments , as a blogging website our current focus is to have more blog related functionalities , we arent a social media website ,thanks but since it not needed , i will be closing this issue
