### ISSUE TITLE
Add a change passsword form  in my profile change password Section

### ISSUE THREAD

**Issue by mansi066** [ANSHIKA-26/WordWise#1769]
**Is your feature request related to a problem? Please describe.**
When I clicked on the my profile section go to change password on clicking on it, I couldn't change my password
So, by using change password  form user can change their password
I will include featues in the form i.e. **1.Current password** 
**2.New Password
3.Conform Password**
![Screenshot 2024-11-08 104636](https://github.com/user-attachments/assets/b027329a-1f20-436b-8626-e0e3d4ca5eb2)

**Comment by ANSHIKA-26** [comment]
#1758 is doing this
