### ISSUE TITLE
Want to create aligned blogs thumbnails on homepage

### ISSUE THREAD

**Issue by prashant8578** [ANSHIKA-26/WordWise#177]
**Describe the bug**
Currently all the items on the home page are not aligned with each other, I want to crate a homepage where the items are aligned and it will make it easy to walk through them.

**To Reproduce**
1. Go to 'Home page'
2. Scroll down
3. See error

**Expected behavior**
It will look better with this new grid look, it will be easy to navigate through them.

**Screenshots**
![Screenshot 2024-10-03 232850](https://github.com/user-attachments/assets/40b3ea7a-fcd9-4692-b259-94408eb88845)

**Comment by hiteashgupta1** [comment]
Already done
