### ISSUE TITLE
Want to ADD CONRTIBUTERS PAGE 

### ISSUE THREAD

**Issue by PatelHarsh2006** [ANSHIKA-26/WordWise#1771]
Want to ADD CONRTIBUTERS PAGE Where List of All Contributers of this Repository are Shown with Their GITHUB PROFILE Photos, Name and No of Contributions they Did !

It will Be Fetching DATA Online, So All Contributers Even After this Wepage's Formation will Keep Updating By It Self Only !!!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PatelHarsh2006** [comment]
@ANSHIKA-26 Please ASSIGN me This Task by Adding Labels to it !!!

**Comment by ANSHIKA-26** [comment]
not needed
