### ISSUE TITLE
LOGO OF THIS PLATEFORM

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1772]
**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd like**
THERE SHOULD BE A LOOGO FOR THIS WEBSITE

**Describe alternatives you've considered**
THERE SHOULD BE A LOOGO FOR THIS WEBSITE

**Additional context**
WE CAN PLACE THAT LOGO IN WEBSITE

**Comment by Meetpidev** [comment]
@ANSHIKA-26 Can i make logo for this ?

**Comment by ANSHIKA-26** [comment]
not needed , i like it as it is
