### ISSUE TITLE
NOT SUITABLE COLOR

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1773]
**Describe the bug**
- AS YOU CAN SEE IN THE PICTURE, SOME TEXT ARE NOT VISIBLE PERFECTLY..ITS LIGHT IN COLOR.. 

**Expected behavior**
- WE SHOULD MAKE THAT TEXT BRIGHT.. SO THAT WE CAN SE IT EASILY

**Screenshots**
![image](https://github.com/user-attachments/assets/d6c48266-7114-4812-a9d4-a49f9248bf5d)

**Comment by Meetpidev** [comment]
@ANSHIKA-26 can i work on it ?

**Comment by ANSHIKA-26** [comment]
just make it slightly dark
