### ISSUE TITLE
CATEGORIES NOT DISPLAY

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1774]
**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd like**
IN CATEGORIES PAGE THERE IS NO MENTIONED THAT THAT CARDS ARE FOR WHICH CATEGORISE..  WE CAN ONLY SEE IT WHEN WE HOVER ON CARS.. BUT IN MOBILE VIEW AD TABELET VIEW ITS NOT USER FRIENDLY.. BECUASE IT'S POSSIBLE THAT SOMETIOM HOVER EFFECT NOT WORK IN MOBILE AS HOVER TIME IS LESS..

![image](https://github.com/user-attachments/assets/0531e2cc-e903-4f7f-8850-fb982b0b6ff4)

**Additional context**
WE SHOULD MENTIONED CATEGORIES ALSO BELOW THESE CARDS...

**Comment by ANSHIKA-26** [comment]
out website isnt exactly made for mobile screens yet so we do not need this feature thanks !
