### ISSUE TITLE
DETAILS MISSING IN README.md FILE

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1777]
**Describe the bug**
ITS NOT MENTIONED THAT HOW TO RUN THE CODE IN README.md FILE

**Expected behavior**
MENTION INSTRUCTION FOR HOW TO RUN THE CODE.. ITS NECESSARY  TO INCLUDE..

**Comment by Meetpidev** [comment]
@ANSHIKA-26 can i include this ?

**Comment by ANSHIKA-26** [comment]
not needed , we have a long readme file as it is , we do not wish to make it longer

**Comment by ANSHIKA-26** [comment]
the instructions to setup the mern app are in frontend folder already , as for the setup of index.html file its pretty obvious

**Comment by Meetpidev** [comment]
there is lots of unnecessary information in current readme.md file.. you should include information about how to run the code.. 
no matter its mern app or not.. every project have to this instructions...
