### ISSUE TITLE
SOCIAL LINKS NOT WORKING

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1784]
**Describe the bug**
ALL THE LINKS ARE NOT REDIRECT TO YOUR ACCOUNT

**Expected behavior**
IT SHOULD BE REDIRECT TO YOUR ACCOUNT

**Screenshots**
![image](https://github.com/user-attachments/assets/3b5d06a9-737e-41dc-a0f6-e00514798604)

**Additional context**
YOU SHOULD LINK YOUR ACCOUNT IF WEBISTE ACCOUNT ISNOT AVILABLE..

**Comment by ANSHIKA-26** [comment]
thats because we do not have any fb , twitter or insta account for wordwise , and we dont need one since this is just a project !
