### ISSUE TITLE
Two Different Scrollup buttons

### ISSUE THREAD

**Issue by likitha-kapu** [ANSHIKA-26/WordWise#1789]
**Describe the bug**
There are two different scroll buttons in every page of the website...which is actually not necessary.

**To Reproduce**
1. Go to 'Any page -example:Blog'
3. Scroll down to 'bottom'
4. See two different scrollup buttons

**Screenshots**
![Screenshot 2024-11-08 203459](https://github.com/user-attachments/assets/1e906128-f4b1-4a74-b552-3af2fd9d1017)

**Additional context**

**Comment by ANSHIKA-26** [comment]
keep the pink one , remove the blue one

**Comment by likitha-kapu** [comment]
yeah sure
