### ISSUE TITLE
Make proper profile page

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#1790]
**Is your feature request related to a problem? Please describe.**
Currently the profile page is static and doesn't pull data from the database...

**Describe the solution you'd like**
I will make sure that the profile page is connected to the backend and the database...
Flow of work:
The profile page will make call to the route to fetch the user data stored in the database...
The backend will contain the logic for the GET req to fetch the data...
Database will send the data using the backend and the frontend will show the data after fetching the data from the backend using the JS.

**Additional context**
![Screenshot 2024-11-05 182336](https://github.com/user-attachments/assets/a369ea9f-f943-4556-9902-8e7a5a59eaef)

Make sure to add the labels :)
Personally its a level3 sol. so hope it will be marked as such

**Comment by nikhilritgithub** [comment]
please assign this to me i want to work on this.
