### ISSUE TITLE
There is no scroll to top button in home page

### ISSUE THREAD

**Issue by souvikpramanikgit** [ANSHIKA-26/WordWise#1794]
**Is your feature request related to a problem? Please describe.**

I want to add a scroll to top button in home page

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ANSHIKA-26** [comment]
not needed , we want users to go through the content , why scroll to bottom ?

**Comment by ANSHIKA-26** [comment]
pr #1792 will be fixing it

**Comment by souvikpramanikgit** [comment]
@ANSHIKA-26 , the pr is about to remove the double button on contact us page
