### ISSUE TITLE
Update the card design

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#180]
![image](https://github.com/user-attachments/assets/72b2c5cb-9789-4595-836a-d447754c01fa)
I can make the design for the cards much sleeker and modern...
make sure to add the labels...
thanks:)

**Comment by Akanshaku** [comment]
I can update the design to make it look more enhanced. Pls assign me this.
Thanks.

**Comment by hiteashgupta1** [comment]
Refork and resync
