### ISSUE TITLE
Two Scroll to top Button appears

### ISSUE THREAD

**Issue by AbhijitMotekar99** [ANSHIKA-26/WordWise#1805]
**Describe the bug**
In provide image on right bottom corner you can see two scroll to top button appears only one required.

**To Reproduce**
1. Go to any page 
2. Scroll down little
3. See error

**Expected behavior**
only one button required.

**Screenshots**
![wordwise two top scroll btn](https://github.com/user-attachments/assets/159be5d9-1ce6-4ce5-9bfc-b533cc18252f)

**Comment by ANSHIKA-26** [comment]
already being fixed in a PR
