### ISSUE TITLE
There is no contributer page 

### ISSUE THREAD

**Issue by Rohan1786** [ANSHIKA-26/WordWise#1811]
**Is your feature request related to a problem? Please describe.**
In many Google Summer of Code (GSoC) projects, contribution details can be scattered or unclear. This lack of clarity makes it challenging for users and potential contributors to understand the impact of their contributions and to recognize the extent of involvement from the community.

**Describe the solution you'd like**
I would like to propose a dedicated "Contributors" section or page that highlights all contributors to the project. This would display a clear, comprehensive list of contributors, including their contributions, to provide visibility and recognition. This feature would positively impact both current and prospective contributors by acknowledging their work and encouraging future contributions.

**Describe alternatives you've considered**
An alternative solution could be integrating a contribution counter on each project page that shows the number of contributors and their contribution types. This would still provide insight but with less individual recognition.
**Additional context**

This feature could also include visual elements, such as avatars or brief bios, to make the contributor list more engaging and informative. See the attached screenshots for examples of how other projects structure their contributor recognition.  please assign me this issue i can resolve it

**Comment by Rohan1786** [comment]
please assign it to me

**Comment by ANSHIKA-26** [comment]
hey , we currently dont need one thanks
