### ISSUE TITLE
Word of the day is not responsive

### ISSUE THREAD

**Issue by Hemraj-7** [ANSHIKA-26/WordWise#1820]
**Describe the bug**
Word of the day is not responsive in the mobile version. it is not looking good.

**Screenshots**
![Screenshot 2024-11-09 200432](https://github.com/user-attachments/assets/b5b97411-473c-4590-adca-ee3ddb63c224)

Assign me this issue

**Comment by ANSHIKA-26** [comment]
its okay , making it more responsive wasn't possible ! thanks for the issue but we dont need it
