### ISSUE TITLE
Proposal : Adding Dynamic moving animation to Scroll Top button

### ISSUE THREAD

**Issue by AbhijitMotekar99** [ANSHIKA-26/WordWise#1826]
**Is your feature request related to a problem? Please describe.**
It can be challenging to locate the "Scroll to Top" button on long pages. Adding dynamic movement will make it more noticeable and engaging, enhancing user experience.

**Describe the solution you'd like**
I’d like to implement a smooth, floating animation for the "Scroll to Top" button when a user scrolls down the page. The button could gently bob up and down or move side-to-side to catch the user’s attention. Additionally, we could have it fade in or out based on scroll position to create a smoother visual transition.

**Describe alternatives you've considered**
Hover Animation: The button could grow in size or change color when hovered over, but this wouldn’t solve visibility when users are scrolling.
Pulse Animation: Instead of moving, the button could have a subtle pulse effect to make it noticeable without much movement.

**Comment by ANSHIKA-26** [comment]
not needed , we like the simple button
