### ISSUE TITLE
Improve Input Field Headings Color on Login and Sign-Up Pages

### ISSUE THREAD

**Issue by sanchitc05** [ANSHIKA-26/WordWise#1832]
**Describe the bug**
The input field headings on the login and sign-up pages have a dull color, making them difficult to read due to low contrast with the background. This affects readability and impacts the user experience.

**To Reproduce**
1. Go to the 'Login' or 'Sign-Up' page on the website.
2. Locate the input fields (e.g., Username, Password).
3. Observe the color of the headings above each input field.

**Expected behavior**
The input field headings should have a color that provides better contrast, aligning with the website’s color palette, to ensure clear readability and an improved visual experience for users.

**Screenshots**
![Screenshot (280)](https://github.com/user-attachments/assets/1c46b719-2081-4b3e-bb8f-8de0e69d5a28)
![Screenshot (281)](https://github.com/user-attachments/assets/cec985ae-cc3b-4431-b88d-63f41c31f66b)

**Additional context**
Updating the color of these headings to match the website’s existing color palette can significantly enhance readability and maintain a cohesive design. Please assign this issue to me.

**Comment by sanchitc05** [comment]
@ANSHIKA-26 please assign this issue to me so that I can start working on it

**Comment by ANSHIKA-26** [comment]
not needed , we like the UI of login and singup including its colors !

**Comment by sanchitc05** [comment]
Alright, @ANSHIKA-26 I there anything you would like me to do to enhance WordWise specific to my domain?
