### ISSUE TITLE
Add Scroll Up and Down Buttons for Improved User Experience

### ISSUE THREAD

**Issue by Charul00** [ANSHIKA-26/WordWise#186]
**Describe the bug**
Currently, the website lacks navigation buttons that allow users to quickly scroll up and down the page, which can affect usability, especially on longer pages.

**To Reproduce**

1. Go to the website.
2. Scroll down to the bottom of the page.
3. Notice the absence of scroll up/down buttons.
4. Attempt to scroll back up manually.
5. Expected behavior
6. I expected to see visible scroll up and down buttons that would allow easy navigation to different sections of the website.

**Screenshots** 

![Screenshot 2024-10-04 013902](https://github.com/user-attachments/assets/b7ec2e11-2915-4677-8a92-8168f086ef1d)

**Additional cozntext**
Adding scroll buttons will enhance user experience by providing a quick and accessible way to navigate through long content, especially for users on mobile devices or those who prefer not to scroll manually.

**Comment by Charul00** [comment]
can you please add the level 2 label to it

**Comment by hiteashgupta1** [comment]
Refork and resync
