### ISSUE TITLE
Add  title logo

### ISSUE THREAD

**Issue by vijaychandra1910** [ANSHIKA-26/WordWise#188]
![Screenshot 2024-10-04 020917](https://github.com/user-attachments/assets/769e288c-da20-4964-a9de-5c14f869a07b)
Add logo on the title while looking good for user.

**Comment by vijaychandra1910** [comment]
Oki

**Comment by vijaychandra1910** [comment]
#188 assign to me I don't want to work on #187

**Comment by ANSHIKA-26** [comment]
what you are trying to add is a favicon , we already have an issue for it , so kindly find some other issue to work on
