### ISSUE TITLE
Want to Make Font Consistent Across Navbar and Body

### ISSUE THREAD

**Issue by Sitambhra02** [ANSHIKA-26/WordWise#201]
Issue:
The navbar and body currently use different fonts, affecting the website's visual consistency and readability.
 
Solution:
If this enhancement sounds good, I’d love to work on implementing it. Could you please assign this issue to me?

Request:
Please assign this issue to me and add labels: 
**GSSoC-extd, Hacktoberfest-accepted, level label.**

 
![image](https://github.com/user-attachments/assets/82edc070-e4d2-4fe8-81d3-06813c6f8410)

**Comment by Kavish-Paraswar** [comment]
Issue:
The navbar and body currently use different fonts, affecting the website's visual consistency and readability.

Solution:
If this enhancement sounds good, I’d love to work on implementing it. Could you please assign this issue to me?

Request:
Please assign this issue to me and add labels:
GSSoC-extd, Hacktoberfest-accepted, level label.

**Comment by Sitambhra02** [comment]
@Kavish-Paraswar Thank you for your comment. It seems you've copied the same content as my original issue. I'm currently assigned and working on this. Feel free to share any specific suggestions or insights

**Comment by Sitambhra02** [comment]
@ANSHIKA-26 I noticed that the issue I am working on (#201) hasn't been assigned a level 1/2/3. Could you please assign the appropriate level so I can ensure I'm meeting the project's expectations?

**Comment by Raj-Aditya-27** [comment]
Hi @ANSHIKA-26 

I want to work on this issue.
You can refer to my previous project.
https://raj-aditya-27.github.io/SarvottamSamachar/

**Comment by Raj-Aditya-27** [comment]
Is this issue still open?
