### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [ANSHIKA-26/WordWise#202]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible.

Hey @ANSHIKA-26 I can work on this.

**Comment by ANSHIKA-26** [comment]
hey @harish08102004 , we already have a workflow which does the same thing , so we really dont need this , thanks !
