### ISSUE TITLE
Tag fonts not visible in Footer

### ISSUE THREAD

**Issue by Jazz-45** [ANSHIKA-26/WordWise#209]
**Describe the bug**
The Text in the tags at the footer looks trimmed.

**To Reproduce**
1. Go to 'Landing Page'
2. Scroll down to 'Footer'
3. See error

**Expected behavior**
Full text should be visible on the tags.

**Screenshots**
![image](https://github.com/user-attachments/assets/7c71a79f-31d7-41a3-9733-0064b33b128a)

**Comment by DarakshanSaara** [comment]
Could you please assign this issue to me?
