### ISSUE TITLE
Add "scroll top button" to the website

### ISSUE THREAD

**Issue by ruchikakengal** [ANSHIKA-26/WordWise#213]
This will go to top of the website @ANSHIKA-26 assign me i like to work on it

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by MaNaN1803** [comment]
"Please assign me to this repository. I would like to work on this."

**Comment by ANSHIKA-26** [comment]
@ruchikakengal are u working on this , or should i assign @shubhagarwal1 ?

**Comment by ruchikakengal** [comment]
No

**Comment by MaNaN1803** [comment]
Yes I have started working on it

**Comment by Arghya-Chakraborty0812** [comment]
@ANSHIKA-26 Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
feature already added
