### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by rutikakengal** [ANSHIKA-26/WordWise#215]
This chatbot gives fast response to the users and answers every question of the users
Add gssoc-ext , hactoberfast-accepted and level 3 to the issue 
assign me I like to work on it

**Comment by govindumeesala** [comment]
@ANSHIKA-26  can I work on it

**Comment by Deepikajyothi007** [comment]
the chatbot is really helpful for clearing the queries and providing explanations on a wide range of topics, I would like to work on this, please assign me this @ANSHIKA-26

**Comment by shalini-bhandari** [comment]
@ANSHIKA-26 assign me this issue

**Comment by ANSHIKA-26** [comment]
guys .. ask @rutikakengal if she needs help, only if she does then only i can assign this issue to you :)
