### ISSUE TITLE
Fix responsivenes of the site 

### ISSUE THREAD

**Issue by iamparas0** [ANSHIKA-26/WordWise#216]
![Uploading Screenshot_2024-10-04-22-13-36-334_com.android.chrome.jpg…]()
Look athe screenshot and fix the responsivenes of the site for mobile as well as , add some responsive features to container so they can sustain container

**Note. : please add before and after ss

**Comment by hiteashgupta1** [comment]
Anyone can work on this

**Comment by Raj-Aditya-27** [comment]
Hi @ANSHIKA-26 
I want to work on this issue.

You can refer to my previous project where I implemented a responsiveness.
https://raj-aditya-27.github.io/SarvottamSamachar/

**Comment by Raj-Aditya-27** [comment]
> Anyone can work on this

Yes, I can.
