### ISSUE TITLE
I want to Enhance 'Start Writing' Page and about us section.

### ISSUE THREAD

**Issue by Deepika14145** [ANSHIKA-26/WordWise#218]
Issue:
The Start Writing and About Us sections are not interactive and readable. 
![Screenshot 2024-10-04 204339](https://github.com/user-attachments/assets/31e6f5fc-6292-4ca5-8bab-c18ca6039eda)
![Screenshot 2024-10-04 204350](https://github.com/user-attachments/assets/926f9a10-34d3-4718-984c-5371356f2ee1)
![Screenshot 2024-10-04 204404](https://github.com/user-attachments/assets/8c234918-eaf7-43ca-acf3-f0d4410cf4b3)

Solution:
If this enhancement sounds good, I’d love to work on implementing it and make your project more interactive. Could you please assign this issue to me @iamparas0?

Benefits:
1) The user will be able to write their blogs and the UI of this website will be enhanced.

Request:
Please assign this issue to me and add labels:
GSSoC-extend, Hacktoberfest-accepted, level label.

**Comment by Deepika14145** [comment]
Thank you for assigning me this task. I will work on it and give you updates as soon as possible.

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by hiteashgupta1** [comment]
#271
