### ISSUE TITLE
[BUG] Bad hover effect on nav bar

### ISSUE THREAD

**Issue by 4F24L** [ANSHIKA-26/WordWise#220]
**Describe the bug**
BAd hover effect on nav bar

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
light and standard effect should be there.

**Screenshots**
![image](https://github.com/user-attachments/assets/ae3dbbbf-2bc4-44f4-aadd-8967827bf3db)

**Additional context**

**Comment by 4F24L** [comment]
Hello, why is the issue closed ?

**Comment by hiteashgupta1** [comment]
You have to refork and resync as recently merged can get removed so make new pr from refork

**Comment by hiteashgupta1** [comment]
Are you working on this

**Comment by Adityakashyap1011** [comment]
can i work on this issue

**Comment by 4F24L** [comment]
Yes, I am working on this.

My 1 PR was pending to merge. So, I didn't commit this in case of any conflicts.

**Comment by hiteashgupta1** [comment]
Okay now refork and resync from the latest repo

**Comment by hiteashgupta1** [comment]
Then make changes you want
And raise pr and add screenshots

**Comment by 4F24L** [comment]
Okay
