### ISSUE TITLE
Scrollbar Styling Could Use Some Improvement

### ISSUE THREAD

**Issue by richa-k23** [ANSHIKA-26/WordWise#223]
**Describe the bug**
The scrollbar appears as a basic style, which doesn't integrate well with the overall design of the page.

**To Reproduce**

1. Navigate to the main page of the application.
2. Scroll down through the content.
3. Observe the default scrollbar styling.

**Expected behavior**
I expected the scrollbar to be styled in a way that complements the page’s design, making it more visible and engaging.

<img width="49" alt="image" src="https://github.com/user-attachments/assets/9041db55-bb41-4dba-988b-942351112b40">

**Additional context**
Customizing the scrollbar to align with the page's aesthetics could greatly enhance the user experience.
Also, the bottom horizontal scrollbar is not needed.

**Comment by richa-k23** [comment]
Thank you for assigning me this issue! 
Could you please add the 'level' label so that I can get started? I would appreciate it!

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by richa-k23** [comment]
Should I remove the horizontal scroll or not?

**Comment by ANSHIKA-26** [comment]
you should
