### ISSUE TITLE
fixing the dark mode

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ANSHIKA-26/WordWise#228]
**Describe the bug**
The dark mode isnt working, can u assign it so i can work on it, ill pull a PR in 5 mins.

**Comment by T-Rahul-prabhu-38** [comment]
@ANSHIKA-26 there seems to be a problem with the code
<img width="1461" alt="Screenshot 2024-10-05 at 2 57 00 AM" src="https://github.com/user-attachments/assets/97e8289a-b121-46d8-9875-f6ef5af88da5">

the CSS needs to be fixed .

**Comment by hiteashgupta1** [comment]
But do refork from latest repo

**Comment by hiteashgupta1** [comment]
Also navbar clicking not working

**Comment by T-Rahul-prabhu-38** [comment]
sure , just a request to fix the whole navbar and darkmode , can i get level3 pls :)😅

**Comment by hiteashgupta1** [comment]
Okay but do make sure latest additions not be removed

**Comment by hiteashgupta1** [comment]
And navbar clicking should properly working

**Comment by T-Rahul-prabhu-38** [comment]
sure that will be done asap! Thank you

**Comment by Raj-Aditya-27** [comment]
Hi @hiteashgupta1 

Can you assign me this issue?
I will also make it responsive.

**Comment by hiteashgupta1** [comment]
@Raj-Aditya-27 you can work on some other issue

**Comment by Raj-Aditya-27** [comment]
Hi @hiteashgupta1 
I have already tagged you on other issue.

**Comment by T-Rahul-prabhu-38** [comment]
@hiteashgupta1 i have called for a PR, this was for navbar and dark mode.
I will create a new issue as the categories , about and contact pages are messed up . ill fix them aswell.
