### ISSUE TITLE
Improve the footer UI

### ISSUE THREAD

**Issue by jayanththalla** [ANSHIKA-26/WordWise#235]
The UI footer needs to be improve in a better manner
please sign me @pa under the gssoc-etd and hacktoberfest-accepted
![image](https://github.com/user-attachments/assets/3cb64c6a-0d0e-473e-8fc5-a16cb0fbbc27)

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by ANSHIKA-26** [comment]
PR made by someone else , issue solved
