### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by sakshamsaraf23** [ANSHIKA-26/WordWise#240]
mam do update the readme file of the project because the screen shot of the website in the readme file does not match the deployed website.
@ANSHIKA-26 can u assign me this issue

**Comment by sakshamsaraf23** [comment]
mam do add the label of level so my contributuin can count

**Comment by hiteashgupta1** [comment]
you don't have to add screenshot in the readme file instead make it in this way that readme fetch from contributor section

**Comment by sakshamsaraf23** [comment]
@hiteashgupta1 i m sorry sir but i don't know how to do that cause i m new here

**Comment by hiteashgupta1** [comment]
So are you adding screenshot in the readme file

**Comment by hiteashgupta1** [comment]
As new contributors may come and then their name is not in the list

**Comment by hiteashgupta1** [comment]
So what can you do to fix this

**Comment by sakshamsaraf23** [comment]
@hiteashgupta1 sir the issue is not fixed yet as the image is not updated
