### ISSUE TITLE
Navbar Ui needs an update 

### ISSUE THREAD

**Issue by aditya07389** [ANSHIKA-26/WordWise#242]
# Hey @ANSHIKA-26 ,

i was just looking at your website and i must say the idea behind it is pretty impressive , although i noticed that the U.I. of navbar is pretty basic , i would like to work on it and make it look more aesthetic by improving the hover effect , also making it more responsive.The boxes are currently resizing on hovering .

It looks like this , on my phone screen. 
Please assign this issue to me .
P.S. : please add the gssoc extd and hacktoberfest labels .

![image](https://github.com/user-attachments/assets/7c570375-7eb1-4463-baa7-1e623817605d)

**Comment by Dipanita45** [comment]
I  want to make changes in the navbar . Please assigned  me in that issue

**Comment by hiteashgupta1** [comment]
@aditya07389 are you working on this issue

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by hiteashgupta1** [comment]
@Dipanita45 otherwise it will be assigned to you

**Comment by aditya07389** [comment]
hey @hiteashgupta i am working on this issue

**Comment by aditya07389** [comment]
@ANSHIKA-26 it will be helpful to know by when do you want me to be done with this work

**Comment by hiteashgupta1** [comment]
Issue is open and you are already assigned 
Kindly refork and resync

**Comment by aditya07389** [comment]
@hiteashgupta1 okay buddy

**Comment by aditya07389** [comment]
hey @hiteashgupta1 i am suppossed to close the request right ? once the pull request is  approved .

**Comment by aditya07389** [comment]
thankyou guys
