### ISSUE TITLE
Feature Request: Login and Signup Pages with JavaScript Validation

### ISSUE THREAD

**Issue by MasirJafri1** [ANSHIKA-26/WordWise#243]
### Login Page
- **Form Fields**: 
  - Email
  - Password
- **Validation**:
  - Ensures the email is in the correct format.
  - Ensures both fields are filled.
- **Guidance Message**: 
  - Users are prompted to sign up if they don’t have an account.

### Signup Page
- **Form Fields**:
  - Full Name
  - Email
  - Password
  - Confirm Password
- **Validation**:
  - Checks email format.
  - Ensures all fields are completed.
  - Validates that Password and Confirm Password fields match.
  - **Password Strength Validation** (Stretch Goal): Additional checks can be added to ensure password strength.
- **Guidance Message**: 
  - Users are prompted to log in if they already have an account.

### Form Submission Feedback
- Displays alerts or on-screen messages if any form validation fails.
- Provides a success message upon completing the login/signup process.

**Comment by MasirJafri1** [comment]
@ANSHIKA-26  Can i  get assigned for this issue?

**Comment by hiteashgupta1** [comment]
#239 is already there

**Comment by hiteashgupta1** [comment]
You can work on validation after this feature is added and make new pr after refork

**Comment by MasirJafri1** [comment]
@hiteashgupta1 Ohk I will work on the Validation part once the feature is added.

**Comment by hiteashgupta1** [comment]
@MasirJafri1 you can work on validation

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by MasirJafri1** [comment]
@hiteashgupta1 sure can you pls assign the labels too so that i can start working..

**Comment by ANSHIKA-26** [comment]
go ahead
