### ISSUE TITLE
Header Font not visible clearly

### ISSUE THREAD

**Issue by harshit1arora** [ANSHIKA-26/WordWise#248]
The header font on the webpage appears to have a couple of issues:
1. Visibility: The font size may be too small for easy readability, especially on smaller screens.
2. Contrast: Depending on the background color, the header font might lack sufficient contrast, making it harder to read for some users.

![wordwise issue](https://github.com/user-attachments/assets/763d21c1-b2d7-4871-ae0f-14c00636db91)

**Comment by harshit1arora** [comment]
I would like to work on it, please assign it to me

**Comment by ANSHIKA-26** [comment]
this issue comes under navbar Ui enhancement , there are already a lot of issues present related to the navbar , kindly ask to get assigned in one of those !
