### ISSUE TITLE
Add Sign-Up Page and link with home section

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#249]
**Describe the bug**
The sign-up page link is missing or not properly added to the website’s home section. Users are unable to access the sign-up page from the homepage.

**To Reproduce**

1. Go to the website’s homepage.
2. Look for the "Sign Up" link/button in the header or navigation bar.
3. Click on the "Sign Up" link.
4. Either the link is missing, or clicking on the link does not redirect to the sign-up page.

**Expected behavior**
The "Sign Up" link should be visible and easily accessible from the homepage, and clicking on it should take the user to the sign-up form.

**Additional context**

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by Vishwajeet594** [comment]
Why

**Comment by hiteashgupta1** [comment]
As the latest repo are merged 
So there will be no merged pr issue if you have resolved

**Comment by Vishwajeet594** [comment]
Ok

**Comment by hiteashgupta1** [comment]
Have you done

**Comment by Vishwajeet594** [comment]
Yes
Please add level 3 sir as I have to create new two pages for the same

**Comment by hiteashgupta1** [comment]
You are only adding but it's validation and integration through backend will be level3

**Comment by ANSHIKA-26** [comment]
PR already made for same issue by someone else
