### ISSUE TITLE
[Change] I would like fix the nav Bar 

### ISSUE THREAD

**Issue by Vatsal-Verma** [ANSHIKA-26/WordWise#25]
![image](https://github.com/user-attachments/assets/ed6bd531-d638-4afb-90d8-1ca79b5f1000)

I would like to work to improve the nav-bar I can see that the side nav bar functionality doesn't work , so i can fix that . More over there is problem in the media query in the nav-bar i can fix that too.
You can assign this work to me , i can fix this problem :)

**Comment by sehajsomal5** [comment]
@ANSHIKA-26  please assign me the issue .

**Comment by Vatsal-Verma** [comment]
can you please assign this work to me again I mistakenly remove assigned work   :(

**Comment by Kavish-Paraswar** [comment]
I would like to work on fixing this issue. Please assign it to me.
