### ISSUE TITLE
ADD Login Page and link with homepage

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#250]
**Describe the bug**
The login page link is not correctly added or is broken. Users cannot access the login page from the homepage.

**To Reproduce**

1. Go to the website’s homepage.
2. Look for the "Login" link/button in the header or navigation bar.
3. Click on the "Login" link.
4. Either the link is missing, or it does not redirect to the login page.

**Expected behavior**
The "Login" link should be clearly visible on the homepage, and clicking on it should take the user to the login page where they can enter their credentials.

**Comment by ANSHIKA-26** [comment]
please combine it with your issue #249 , add both login and signup functionality , raising two separate issues then 2 PR's might cause merge conflicts in future , you will be given enough points to compensate for your work !

**Comment by Vishwajeet594** [comment]
ok thanks for assigning
