### ISSUE TITLE
 adding an FAQ section to a website

### ISSUE THREAD

**Issue by Vishwajeet594** [ANSHIKA-26/WordWise#251]
**Describe the bug**
The FAQ section is missing or not properly added to the website’s homepage. Users cannot find or access the FAQ section from the homepage.

**To Reproduce**

Go to the website’s homepage.
Look for the "FAQ" section or link in the main navigation or footer.
Scroll down or click on the link.
Either the FAQ section is missing, or clicking on the link does not navigate to the FAQ section

**Expected behavior**
The FAQ section or a link to it should be visible and easily accessible from the homepage. Clicking on the link should display a list of frequently asked questions and their answers.
.

**Comment by SHUBHAG100520** [comment]
Can i work on this issue.
