### ISSUE TITLE
Remove Give Feedback Feature and Improvements in "Get in Touch" section of Contact Us.

### ISSUE THREAD

**Issue by harshit1arora** [ANSHIKA-26/WordWise#255]
I believe that removing the "Give Feedback" feature could streamline the navigation experience for our users. 
This will give Clarity and Focus, Redundancy. Since users can still reach out through the "Contact Us" section, the "Give Feedback" feature might be redundant and could create confusion.
Aesthetics: Removing the feature may enhance the overall aesthetics of the header, contributing to a cleaner and more professional look.

Also, I would like to improve the Get in Touch section of Contact Us.
Please assign this task to me, I want to work on it.

![wordwie2](https://github.com/user-attachments/assets/737fd73b-3da6-4305-a6f2-0570da849b50)

**Comment by ananyakaligal** [comment]
can you assign me this?
