### ISSUE TITLE
Make the Website Responsive!

### ISSUE THREAD

**Issue by SAMluci666** [ANSHIKA-26/WordWise#257]
### Proposed Changes
- Make website responsive for mobile and tablet devices.

Please assign this to me with gssoc-ext, hactoberfest and level tags

**Comment by keerthana2-005** [comment]
I'd like to work on this

**Comment by Hemraj-7** [comment]
@SAMluci666 bro are you doing work on cards, They are not responsive in small devices 
If you don't work on cards then assign me

**Comment by SAMluci666** [comment]
@Hemraj-7 It's just about completed. I'll be sending a PR soon.

**Comment by SAMluci666** [comment]
@ANSHIKA-26 
### Changes I have Made.
- Fixed the issue with the cards
- Fixed the issue of the loading more posts button overlapping with the cards

### Working on Issues
- Working to make the navigation bar responsive.
- Making the other pages responsive.

### Questions:
- The whole file structure has become very messy and complicated, so I'll need to edit a lot of lines of code that can generate conflicts if other people make changes during that time. Should I do that?

### Redundant and Complicated Code: -
- People have written same code without following the necessary structure.
- Duplicate Code as well as redundant code in many places in the whole file. Could you please implement a stricter code-review phase.

I'll try my best to make the webpages responsive. If any further change required feel free to contact me. I'll send the PR within an hour.
