### ISSUE TITLE
Improvements and "Changes in Logo" of Tags and Social Section 

### ISSUE THREAD

**Issue by harshit1arora** [ANSHIKA-26/WordWise#258]
Improvements in the Font Style and Font Size to be done in the "Tags" and "Social" section.
Also changing the "Logo's" of social handles and improving/adding more tags in order to attract user's attention and make the webpage aesthetic.

![improvement](https://github.com/user-attachments/assets/fb2d67cf-2c4e-4866-9b97-e63458a47e6d)

**Comment by harshit1arora** [comment]
Please assign the task to me as I want to work on it.

**Comment by ANSHIKA-26** [comment]
done with footer PR
