### ISSUE TITLE
Missing username and password validation

### ISSUE THREAD

**Issue by kashikaga** [ANSHIKA-26/WordWise#262]
Validation
   - Input validation for username and password fields.
   - Display error messages for incorrect logins.
   
 @ANSHIKA-26 kindly assign me this issue along with the labels gssoc-extended, level and hacktoberfest accepted

**Comment by kashikaga** [comment]
@ANSHIKA-26 kindly assign the level lavel also

**Comment by hiteashgupta1** [comment]
#243 already there
