### ISSUE TITLE
Navbar hover

### ISSUE THREAD

**Issue by Adityakashyap1011** [ANSHIKA-26/WordWise#264]
The hover effect in Navbar shows immediate change. It would be better if it has smooth transition with better hover styling

**Comment by Adityakashyap1011** [comment]
Earlier this issue was dismissed as a similar issue was being worked upon. Now that issue is completed but still this problem persists with the navbar.

**Comment by ANSHIKA-26** [comment]
#242 , this issue still comes under navbar Ui
