### ISSUE TITLE
Add a feedback page

### ISSUE THREAD

**Issue by ANANDISHARMA0109** [ANSHIKA-26/WordWise#266]
there is no page linked to feedback option given on the navbar. I would like to take up this issue under ggsoc-extd'24 and hacktoberfest under level 2.

**Comment by SHUBHAG100520** [comment]
Can i work on it.

**Comment by Supraja-Gao** [comment]
Please assign this issue to me also.. I would like to work on it

**Comment by Supraja-Gao** [comment]
@ANANDISHARMA0109 I am working on feedback page issue.

**Comment by ANANDISHARMA0109** [comment]
but wasn't i already been assigned this issue?

**Comment by hiteashgupta1** [comment]
All 3 are already assigned

**Comment by hiteashgupta1** [comment]
You can add page if you have created

**Comment by hiteashgupta1** [comment]
@Supraja-Gao @ANANDISHARMA0109 @SHUBHAG100520 If no one has created feedback page then this issue will be closed
And #438 will be merged

**Comment by hiteashgupta1** [comment]
Anyone working on this

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
