### ISSUE TITLE
Inconsistent Navbar Across Pages and Missing 'Start Writing' Section on Other Pages

### ISSUE THREAD

**Issue by Raj-Aditya-27** [ANSHIKA-26/WordWise#271]
**Describe the bug**

The navbar is not consistent across all pages, and the hover effect is also missing. Additionally, the 'Start Writing' section is present only on the home page and not on the other pages.

**Expected behavior**
Ensure the navbar is consistent across all pages and add the missing 'Start Writing' button.

**Screenshots**
In Home page:
![image](https://github.com/user-attachments/assets/a129f8f6-1443-4837-ad8b-6c348f54cbde)

In contact page:
![image](https://github.com/user-attachments/assets/8b4d99ef-d895-458d-8abf-1e5a1beb0f93)

**Comment by Raj-Aditya-27** [comment]
Thanks for giving me this opportunity.
I will do it shortly.

**Comment by hiteashgupta1** [comment]
#218 already there

**Comment by Raj-Aditya-27** [comment]
Hi @hiteashgupta1 

I have started working on it.
As this issue isn't solve yet as i can see in website.

So can you please assign this issue #218  to me.

**Comment by hiteashgupta1** [comment]
@Raj-Aditya-27 Okay but kindly refork and resync

**Comment by hiteashgupta1** [comment]
And do changes properly and then make pr

**Comment by Deepika14145** [comment]
How could you assign @hiteashgupta1,my generated issue #218 to others as I had already started working on it and just wanted to contribute? Please assign me another issue now.

**Comment by hiteashgupta1** [comment]
@Deepika14145 you have not responded on this issue so it is assigned 
As new pr merged and recent changes should be updated timely

**Comment by hiteashgupta1** [comment]
@Deepika14145 It's very clear if you raise issue then you should work on it timely
Kindly keep these things for next time

**Comment by Deepika14145** [comment]
Okay

**Comment by Deepika14145** [comment]
Do you have any other issues to assign me @hiteashgupta1? If yes please assign me.

**Comment by hiteashgupta1** [comment]
@Deepika14145 That's up to you have to raise relevant issue you find and make pr

**Comment by Deepika14145** [comment]
okay I will check.

**Comment by Raj-Aditya-27** [comment]
Okay 
I will do it shortly.

**Comment by Raj-Aditya-27** [comment]
I have generated a PR
