### ISSUE TITLE
Improve Repository Structure and Organization

### ISSUE THREAD

**Issue by jaidh01** [ANSHIKA-26/WordWise#272]
I propose restructuring the `WordWise` repository to improve code organization, maintainability, and developer onboarding. Below are the key enhancements:

1. Restructure Folder Hierarchy:

  * Create dedicated folders for `src` (source code), `tests` (unit tests), `docs` (documentation), and `data` (example datasets).
2. Improve Documentation:

  * Include `architecture.md` in the `docs/` folder for better understanding of the project.
    Code Organization:

These changes will make the repository more professional, readable, and contributor-friendly. Let me know your thoughts!

**Comment by jaidh01** [comment]
Hi @ANSHIKA-26,
I request you to please add the `level 1` label to this issue.

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26
