### ISSUE TITLE
Update login ui

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#274]
![image](https://github.com/user-attachments/assets/4e4d108e-b639-4e6e-bc15-500e34945b8f)
I can update the login ui and make it modern and better...
![image](https://github.com/user-attachments/assets/64baba67-5cba-4adc-9139-4bc4b8827577)
somewhat like this...
make sure to add the labels....
thanks...

**Comment by ANSHIKA-26** [comment]
hey @NK-Works any update ?

**Comment by NK-Works** [comment]
@ANSHIKA-26 working on it... will ask for a pull req it within 30 min to an hour max...
