### ISSUE TITLE
Feature Post section is not proper

### ISSUE THREAD

**Issue by DarakshanSaara** [ANSHIKA-26/WordWise#277]
Issue description:
The feature post section is quite imbalanced. It is needed to be create properly.

**Expected behavior**
![Screenshot 2024-10-05 165933](https://github.com/user-attachments/assets/db2a9976-4cb7-486f-8192-57f95f581668)

As of now it is showing like this
![Screenshot 2024-10-05 170127](https://github.com/user-attachments/assets/2f7f60ec-f84b-4fa9-b0f0-1e525fde87d3)

Could you please assign this issue to me?

**Comment by hiteashgupta1** [comment]
#258 is already there

**Comment by DarakshanSaara** [comment]
#258 is about tags and social section. I'm talking about the modification of "Feature Post"

**Comment by hiteashgupta1** [comment]
@DarakshanSaara You are having old commited repo
If you want to contribute then refork and raise issue if not seems correct
