### ISSUE TITLE
Wanted to Work on About Part

### ISSUE THREAD

**Issue by bm9240** [ANSHIKA-26/WordWise#278]
On clicking the about button in navbar the page refreshes to Home again
Wanted to work on about such that on clicking about the screen scrolls down to about section in the page
Also the image in the about section overlaps the text written.
Wanted to fix this can I, @ANSHIKA-26 ?

**Comment by Shariq2003** [comment]
@bm9240 if you are working on this issue, please let me know, else I want to and I can work on this issue.
Thanks

**Comment by bm9240** [comment]
Hi @Shariq2003 ,
My PR for this issue was accepted yesterday #281 
Please let me know if some other changes are required 
sorry I did not tag the issue in my PR.

**Comment by Shariq2003** [comment]
> Hi @Shariq2003 , My PR for this issue was accepted yesterday #281

But the page is still messing up
