### ISSUE TITLE
THERE IS A BUG IN SWITCHING BETWEEN LOGIN AND SIGN UP

### ISSUE THREAD

**Issue by HS202022** [ANSHIKA-26/WordWise#285]
Describe the bug
there is no simultaneous switch between login and sign up once signup is pressed we cant go back to login

To Reproduce
1.Click Login
2. then click on sign up
3.try to click login again it wont work

Expected behavior
we can simultaneously switch between login and sign up page

https://github.com/user-attachments/assets/356b3ca3-f9d6-41c5-b9c3-8151e36170aa

**Comment by ANSHIKA-26** [comment]
already done in pr #299
