### ISSUE TITLE
issue in about section and issue in not a static webpage 

### ISSUE THREAD

**Issue by srivishnu2805** [ANSHIKA-26/WordWise#288]
I've noticed a few issues with spacing and social icon alignment. Additionally, when scrolling left, a black page appears beneath the scroll bar, which negatively affects the website's appearance. To improve this, a column arrangement for the images could be implemented to eliminate the scrolling effect. I kindly request you to address these issues for a better user experience. Also, ensuring the website is cross-platform and mobile-friendly would make it even more appealing
![image](https://github.com/user-attachments/assets/adec7f04-66ce-4bdd-b7f2-cd957478b364)
![20](https://github.com/user-attachments/assets/1cb92191-09c0-47ff-bfa9-ccf4541a27f0)
![image](https://github.com/user-attachments/assets/70293240-1e91-445a-b80d-412154bffa74)
if I get assigned to this project I will try my best to fix these issues and improvise the UI of the navbar

**Comment by ANSHIKA-26** [comment]
issue #278 is there
