### ISSUE TITLE
Missing Email Validation in Subscibe Newsletter, and no popup for success/failure and Enhancement of Navbar UI

### ISSUE THREAD

**Issue by Shariq2003** [ANSHIKA-26/WordWise#289]
Email Validation is missing in Newsletter subscription, no popup or alert for success and failure, and Also the Navbar UI is not interactive and attractive.

https://github.com/user-attachments/assets/497410c9-d957-46cf-8943-6a821b788e19

Please assign this to me.

**Comment by keerthana2-005** [comment]
@ANSHIKA-26  iw ould like to work on this

**Comment by Shariq2003** [comment]
@ANSHIKA-26 please close this issue as completed in #407
