### ISSUE TITLE
Contact Us Page Improvement With Validation of Email and Phone Number (Accepting Alphabets)

### ISSUE THREAD

**Issue by Shariq2003** [ANSHIKA-26/WordWise#290]
There is not validation for Email and Phone number in contact us page.
Phone number field is accepting alphabets.
UI is not good. 

https://github.com/user-attachments/assets/8c3e1339-77c1-479f-9bf4-33ae390b9658

@hiteashgupta1 Please assign this to me.

**Comment by hiteashgupta1** [comment]
#292 already done
