### ISSUE TITLE
IMPROVING UI OF THE ABOUT US 

### ISSUE THREAD

**Issue by Kavish-Paraswar** [ANSHIKA-26/WordWise#296]
Subject: UI and Alignment Issues on About Us Page

Hello,

I would like to report the following issues found on the About Us page:

Alignment Problems: The overall alignment on the page appears inconsistent, negatively impacting the user experience.
Social Media Tags: The tags could benefit from a more interactive UI and color effects on hover to enhance user engagement.
Footer Section: There is an extra line after the copyright text, making the layout feel incomplete.
Newsletter Box: The positioning of the newsletter input box is misaligned and should be shifted left for better presentation.
Please find the attached screenshot for reference.

Thank you,
Kavish Paraswar

**Comment by Kavish-Paraswar** [comment]
Please assign me under GSSOC'24 extended and level 2 or level 3 atleast .

**Comment by hiteashgupta1** [comment]
#235 already there
