### ISSUE TITLE
Cluttered Tags and Social media Section

### ISSUE THREAD

**Issue by Jazz-45** [ANSHIKA-26/WordWise#298]
**Describe the bug**
The tags section is very cluttered which overall decreases the user experience.

**To Reproduce**
1. Go to 'Word Wise'
2. Scroll down to 'Footer'
3. See error

**Expected behavior**
The sections should have a clear look , I will provide proper spacing between elements so that it looks clean.

**Screenshots**

![Screenshot 2024-10-05 194721](https://github.com/user-attachments/assets/70861640-ffb5-4e40-baa2-104b19642096)

**Comment by hiteashgupta1** [comment]
#258 already there
