### ISSUE TITLE
Change footer background and text color for better visibility

### ISSUE THREAD

**Issue by BaraniVA** [ANSHIKA-26/WordWise#3]
**Issue:**
- The current footer background color is not appropriate and needs to be changed.
- The text color in the footer is not very visible and needs to be adjusted.

**Steps to reproduce:**
1. Visit the website.
2. Scroll down to the footer section.
3. Observe that the footer color and text color are not optimal.

**Expected behavior:**
- The footer should have a background color that complements the overall design of the website.
- The text color in the footer should be more visible.

**Additional context:**
![image](https://github.com/user-attachments/assets/6f7f059e-3076-465a-9d0a-eaf5a5d5b0f5)

**Comment by miteshanshu** [comment]
Hi! I would like to work on the issue of enhancing the category.html for better UI/UX. My plan is to improve the layout, make it more visually appealing, and ensure it is user-friendly across different devices. I will keep the team updated on my progress. Looking forward to collaborating!

**Comment by itsshreyanigam** [comment]
Please assign this me this issue, I would like to work on resolving this.
