### ISSUE TITLE
Inconsistent Image Sizes Causing Visual Imbalance on the Website

### ISSUE THREAD

**Issue by sehajsomal5** [ANSHIKA-26/WordWise#30]
The images displayed on the website are of varying sizes, causing a lack of consistency and making the design look unbalanced. This inconsistency negatively affects the user experience as it disrupts the visual flow of the page.

SCREENSHOT: [
![Screenshot 2024-10-02 131347](https://github.com/user-attachments/assets/04aa3ed0-0a92-463c-823d-b1acd517f90b)
](url)

The below screenshot shows overlapping of img on text when hover is used.
![Screenshot 2024-10-02 131806](https://github.com/user-attachments/assets/4e1a6faa-b665-4ab2-a247-d359522be6da)

PROPOSED FIX : 
Using CSS grid.
Using CSS object-fit or aspect-ratio CSS properties.

**Comment by ANSHIKA-26** [comment]
go ahead !
