### ISSUE TITLE
Navbar list items collapsing on hovering

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#304]
**Describe the bug**
The navigation bar list items collapse when hovering over them. Instead of remaining visible and clickable, the items shrink or disappear, making it difficult to navigate the menu.

**To Reproduce**
1. Go to the website/project page.
2. Hover over the navbar items (e.g., Home, Projects, Skills, Contact).
3. Notice that the list items collapse or disappear upon hover.

**Expected behavior**
The navbar list items should remain visible and clickable when hovered over. The hover effect should highlight the item but not cause it to collapse or disappear.

**Screenshots**
![image](https://github.com/user-attachments/assets/70869a80-ec8a-463a-b561-4f8f1329acd5)

**Additional context**
This issue might be related to CSS or JavaScript used for the hover effect or the navbar’s responsive design. The bug occurs on desktop

**Comment by hiteashgupta1** [comment]
@shivam8112005 try to make some better hover

**Comment by shivam8112005** [comment]
ohk i am creating one more issue

**Comment by shivam8112005** [comment]
Can you please close this issue because this issue has been solved and pr was successfully merged
