### ISSUE TITLE
Expand Theme Customization Options and Enhancing the Word Wise Landing Page for a More Engaging and Impactful User Experience

### ISSUE THREAD

**Issue by devki412** [ANSHIKA-26/WordWise#305]
Allow users to customize fonts, colors, and layouts for a personalized experience. and Upgrade the landing page with modern visuals and interactivity to boost user engagement.  @ANSHIKA-26 plz asign this project .

**Comment by ANSHIKA-26** [comment]
what exactly do you wish to implement and how ?

**Comment by devki412** [comment]
I want to redesigning the navbar to improve its aesthetics and functionality, while also adding more post frames to showcase additional content, making it easier for users to explore and engage with blogs.

**Comment by ANSHIKA-26** [comment]
issue #304 covers that

**Comment by devki412** [comment]
i want to improve it more
