### ISSUE TITLE
website is not responsive in all devices 

### ISSUE THREAD

**Issue by keerthana2-005** [ANSHIKA-26/WordWise#315]
when the website is opnened in mobiles or tabs other than laptops it looks weird with no proper allignment i can make it responsive plz assign hacktoberfest and gssoc extended labels and also add level 3

**Comment by keerthana2-005** [comment]
Plz assign level

**Comment by hiteashgupta1** [comment]
Share a video of resizing how it is not responsive

**Comment by keerthana2-005** [comment]
@hiteashgupta1 
![WhatsApp Image 2024-10-05 at 22 02 29_b2c95bcc](https://github.com/user-attachments/assets/34b2f7c3-6732-4e74-86bc-b839b7969ccc)
this is how it looks like in mobile

**Comment by hiteashgupta1** [comment]
Firstly you have to add slider feature to these photos
And then work on responsiveness 
But make sure it doesn't affect alignment of images

**Comment by ANSHIKA-26** [comment]
issue #257 exists , ask to be assigned on that
