### ISSUE TITLE
adding favicon icon

### ISSUE THREAD

**Issue by solanki505** [ANSHIKA-26/WordWise#316]
**Describe the bug**
![Screenshot 2024-10-05 214533](https://github.com/user-attachments/assets/cbfbb829-c7f2-4622-a925-fefa66dd992b)

**To Reproduce**

**Expected behavior**
showing a favicon gives more user friendly experience.

**Additional context**

**Comment by hiteashgupta1** [comment]
#311 already there

**Comment by solanki505** [comment]
but still the favicon is not visible when site is opened

**Comment by ANSHIKA-26** [comment]
it is
