### ISSUE TITLE
improving the navbar

### ISSUE THREAD

**Issue by solanki505** [ANSHIKA-26/WordWise#317]
**Describe the bug**
the navbar not responding properly in darkmode abd ui needs improvement 
**To Reproduce**

**Screenshots**
![Screenshot 2024-10-05 214731](https://github.com/user-attachments/assets/68f7a34f-2b9f-4c0c-8932-4f2feaaf72ef)

**Additional context**

**Comment by ANSHIKA-26** [comment]
kindly work with #304 , in order to avoid future merge conflicts
