### ISSUE TITLE
Enhance cards background

### ISSUE THREAD

**Issue by SurajSG23** [ANSHIKA-26/WordWise#319]
Hey, i noticed that your cards didn't had any background shadow effect.

![image](https://github.com/user-attachments/assets/06980d4d-76bf-46f5-88b0-70e39e2caadf)

I would like to fix it by adding some cool shadow effects to it, So the user can easily make out the cards.
This would really enhance the UI of your website.
Please assign me this under gssoc and hacktober fest.Thank you.

**Comment by PulkitShubham** [comment]
Hi @ANSHIKA-26,

I noticed that the box shadow and hover effects could be further optimized to improve the overall user experience. I would love the opportunity to contribute to enhancing these elements and refining their design. Please assign me this task, and I'll ensure the visual aspects are elevated for a more polished result.
