### ISSUE TITLE
FEATURE : Scroll to Top Button component

### ISSUE THREAD

**Issue by archanasingh11** [ANSHIKA-26/WordWise#324]
**Description:**

The WordWise website currently lacks a **"Scroll to Top"** button, which is a key feature for enhancing user experience, especially on pages with extensive content. Without this button, users have to manually scroll back to the top of the page, which can be inconvenient and time-consuming.

Implementing a **"Scroll to Top"** button would:
- Improve the website's accessibility and usability.
- Provide a smoother navigation experience, particularly on long articles or blog posts.
- Align the user interface with modern design practices.

I recommend adding a floating "Scroll to Top" button that becomes visible as users scroll down the page.

Please @ANSHIKA-26  assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by ANSHIKA-26** [comment]
#213 already exists
