### ISSUE TITLE
Need to fix Page Aliment 

### ISSUE THREAD

**Issue by kaustubh0601** [ANSHIKA-26/WordWise#325]
**Describe the bug**
The page layout is not well-aligned. This affects the overall user experience, making the page look disorganized. It would be helpful to adjust the alignment of the elements to improve the page's aesthetics and readability.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/a11f063c-4989-46d5-8e06-9a5b9098e164)

**Additional context**

**Comment by Akanshaku** [comment]
I would like to work on this issue @ANSHIKA-26

**Comment by Nikhilkumar111** [comment]
I would like to work on this issue @ANSHIKA-26 .
