### ISSUE TITLE
Login and Sign Up Forms Only Pop Up on Index Page

### ISSUE THREAD

**Issue by JomanaMahmoud** [ANSHIKA-26/WordWise#327]
https://github.com/user-attachments/assets/9d1a162f-3029-4df4-b214-8f5f6d08fd3c

### Description: 
Currently, the login and sign-up forms are only functional on the index (home) page. These forms should be available on all pages of the website, but they fail to pop up on any other page, making it difficult for users to access them.

### Steps to Reproduce:
1. Navigate to any page other than the index (home) page.
2. Attempt to open the login or sign-up forms.
3. Notice that the forms do not appear.

### Expected Behavior:
The login and sign-up forms should be available and functional across all pages of the website, not just the home page.

Assign it to me I can work on it, under these Labels. @ANSHIKA-26 
**Labels:** Hacktoberfest, gssoc-extd

**Comment by hiteashgupta1** [comment]
Fixed it
