### ISSUE TITLE
Carousel synchronization 

### ISSUE THREAD

**Issue by irfanbroo** [ANSHIKA-26/WordWise#331]
![Screenshot (103)](https://github.com/user-attachments/assets/39ef4820-f432-4369-9846-0c956bc23d93)
The carousel is looking good, but the 6 mini dots in the bottom section and the carousel is no synchronized properly and an arrow option can be added to toggle back and forth between the carousels.
I  will be very Glad to work upon it

**Comment by ANSHIKA-26** [comment]
#318 is there
