### ISSUE TITLE
Problem with login and SignUp page !!!!

### ISSUE THREAD

**Issue by Abhi9shinde** [ANSHIKA-26/WordWise#338]
Need to blur the background when the login page pop's up or can create a new page for login and signup.
Because the UI for the Login and SignUp is not quite appealing.
![image](https://github.com/user-attachments/assets/8701eee9-ad71-4083-bc73-34d802186e28)

**Comment by ANSHIKA-26** [comment]
issue #274 is there

**Comment by Abhi9shinde** [comment]
No,no, I was saying that the login page after popping up should look like this rather than just popping up

![image](https://github.com/user-attachments/assets/844f6e16-7a2b-4092-b4c1-f3046e3dc242)
