### ISSUE TITLE
Upper and lower part of card and text are cutting at the time of hovering.

### ISSUE THREAD

**Issue by Mr-DK07** [ANSHIKA-26/WordWise#339]
Hey @ANSHIKA-26 There is a issue on the home page. When we hover on the card, it's upper lower section cuts and the bottom texts of the image get hide.
I want to improve design of the card, so that UI/UX of the website can improve and issue get resolved.

![Screenshot 2024-10-06 004404](https://github.com/user-attachments/assets/edf597de-6925-4a45-ba5b-3f6ae5cb81f0)

Please assign this task to me, So that I can start working on it.
Kindly add the Labels (gssoc-ext, hactoberfest and Level1, Level2, Level3).

**Comment by Mr-DK07** [comment]
Add any level (Level1, Level2, Level3) also.

**Comment by ANSHIKA-26** [comment]
#319 exsits
