### ISSUE TITLE
Restructuring the following element as footer.

### ISSUE THREAD

**Issue by CodeMosaic7** [ANSHIKA-26/WordWise#344]
**Describe the bug**
The footer section has alignment and spacing issues, inconsistent fonts, a misspelled tag, and unclear date formats. Social media icons are misaligned, and contrast issues affect readability.

**To Reproduce**

Go to the footer section.
Observe the alignment of the "Connect with us" icons.
Check the "Popular Tags" for the misspelled word "Techonogy."
Review the inconsistent date formats under "Feature Post."

**Expected behavior**
Social media icons should be properly aligned.
Correct spelling of "Technology" in "Popular Tags."
Consistent date formats like "02 Feb, 2022."
Improved spacing and contrast for better readability.
Common background for better layout and color coordination of the website.

**Screenshots**
![image](https://github.com/user-attachments/assets/de2c139a-f586-44ab-9e3c-e8f050458c13)
Screenshot provided (as attached above) showing the misalignment of icons, inconsistent date format, and typo.

**Comment by ANSHIKA-26** [comment]
already done
