### ISSUE TITLE
Redesign the footer section

### ISSUE THREAD

**Issue by bhai-hub** [ANSHIKA-26/WordWise#348]
Problem:
![Screenshot 2024-10-06 030232](https://github.com/user-attachments/assets/9377ef90-a59a-4f26-a3ff-e4105cba4a41)
![Screenshot 2024-10-06 025948](https://github.com/user-attachments/assets/7c798900-b18d-4097-b6cf-1a14b3212fdd)

solution:

I will redesign this part of section to make it look appealing for the users and responsive with proper styling. 
I will make the image carousel better and working as its misaligning the page.

Please assign it to me under gssoc-ext.

**Comment by 4F24L** [comment]
Can I work on this ?

**Comment by ArthKulkarni93** [comment]
@ANSHIKA-26 I'd love to finish it up till end of today

**Comment by ANSHIKA-26** [comment]
issue #309 is already present
