### ISSUE TITLE
The current "About" section closely resembles the homepage and lacks a distinct identity

### ISSUE THREAD

**Issue by satyasootar** [ANSHIKA-26/WordWise#351]
**Proposal**
I will completely redesign the "About" section to differentiate it from the homepage. This will include:
-Unique layout and content structure
-Enhanced visuals and design elements that better represent the section's purpose
-A more informative and engaging narrative that tells the story or mission of the brand

**Expected Behavior**
The new "About" section will have a unique, visually appealing design that is distinct from the homepage, providing a clear and compelling introduction to the brand, its mission, and values.

**Screenshots & Screen-recording**
![image](https://github.com/user-attachments/assets/1d12a27a-75a1-4471-96a5-5307e44d0b9e)

https://github.com/user-attachments/assets/c8dacae0-9615-4044-be55-6d9a63ee4ed0

**Comment by ANSHIKA-26** [comment]
issue #278
