### ISSUE TITLE
share button in about section

### ISSUE THREAD

**Issue by Adityakashyap1011** [ANSHIKA-26/WordWise#353]
![Screenshot 2024-10-06 083142](https://github.com/user-attachments/assets/2232c6f8-49a6-490a-ae80-7bddc0adf913)

Current design of share button.

I suggest to change the design of share button in about section to the below design
![Screenshot 2024-10-06 083124](https://github.com/user-attachments/assets/f4b232ce-e60f-4f9c-810d-79461d041601)

**Comment by ANSHIKA-26** [comment]
and what is the difference in both ?

**Comment by ANSHIKA-26** [comment]
since issue #351 is already open , please ask to be assigned in that
