### ISSUE TITLE
Correction in alignment of feature post

### ISSUE THREAD

**Issue by Adityakashyap1011** [ANSHIKA-26/WordWise#354]
This is the current situation , where the misalignment is clearly visible
![Screenshot 2024-10-06 083900](https://github.com/user-attachments/assets/ebf7e619-ce70-4cf2-b194-6847bc49eb32)

I suggest a better alignment for the feature post section in leading blog page
An alignment like the one below would be more suitable
![Screenshot 2024-10-06 083842](https://github.com/user-attachments/assets/e9db81a0-25ef-4625-b161-32bad7b99939)

**Comment by ANSHIKA-26** [comment]
current one works too

**Comment by Adityakashyap1011** [comment]
The current one does work but a proper alignment looks better
