### ISSUE TITLE
FIXING THE LANDING PAGE

### ISSUE THREAD

**Issue by RAJIV81205** [ANSHIKA-26/WordWise#355]
THE FRONT PAGE HAVE MANY CARD LIKE STRUCTURES WHICH CAN BE FIXED TO MAKE IT ATTRACTIVE , ASSIGN ME TO FIX IT 
![image](https://github.com/user-attachments/assets/32d4650d-2c85-461b-8a78-68a9e266aea4)

**Comment by ANSHIKA-26** [comment]
this issue already exists
