### ISSUE TITLE
The Categories page topics needs an Update!!

### ISSUE THREAD

**Issue by Kishore007raj** [ANSHIKA-26/WordWise#356]
Hello there! I’ve noticed a bug in the Categories section. When I click on topics like 'Food' or 'Travel,' it doesn’t take me to the correct page. I want to work on this issue and ensure that all category topics lead to their respective pages. I’m also open to making any other necessary improvements to the website!

**Comment by Nikhilkumar111** [comment]
Hello, 
 I  want to work on this issue plz assign to me .

**Comment by Arshadkh123** [comment]
Hello, @ANSHIKA-26 I would like to work on these issues and also want to add a few more blogs on the page of that particular topic or to add more details. and I think the image is bigger, I mean I can make more appealing.
![Screenshot 2024-10-15 193110](https://github.com/user-attachments/assets/a176741d-5d59-4535-a2c6-49332b141917)

**Comment by ANSHIKA-26** [comment]
all bugs fixed
