### ISSUE TITLE
Enhance Blog Page !!!

### ISSUE THREAD

**Issue by Abhi9shinde** [ANSHIKA-26/WordWise#358]
As seen in the images the blog page can be made more appealing !!!
Points to change:
1. Heading - Travel can be made more attractive by using a different style
2. Logos below the header can also be changed. 
3. The white colored text in the second screenshot is not readable due to the background color
4. Social Media logos are small and can also add a better hover effect.
5. The Submit button is not looking good it should be changed
6. Also the footer section needs arrangement.
![Screenshot 2024-10-06 102404](https://github.com/user-attachments/assets/6a69a437-0b82-4520-85ab-7ebe1010971c)

![Screenshot 2024-10-06 102411](https://github.com/user-attachments/assets/48856ace-298e-483b-a1c7-0f2083bef3d9)
![image](https://github.com/user-attachments/assets/cbe2e2e9-4536-4ccf-a843-85daef72b23f)

**Comment by ANSHIKA-26** [comment]
issue #302 exists , do not raise duplicate issues
