### ISSUE TITLE
BUG: Load more posts button hover effect is not proper

### ISSUE THREAD

**Issue by sriraghavi22** [ANSHIKA-26/WordWise#360]
**Describe the bug**
When hovering over Load more posts button, the text inside it is not visible

**To Reproduce**
1. Go to home
2. Scroll down to Load more posts button
3. Hover on that button

**Expected behavior**
The text needs to be visible

**Screenshots**

https://github.com/user-attachments/assets/615e6dbe-f4e2-415b-8004-ede950220a3b

**Additional context**
I would like to solve this issue

**Comment by ANSHIKA-26** [comment]
already covered in another issue
