### ISSUE TITLE
Minute issues 

### ISSUE THREAD

**Issue by Codersweta7** [ANSHIKA-26/WordWise#361]
1. At home page (load more posts ) cursor should change in pointer .
2. Redirection of social media to their login pages 
3. At start page - > 
-> frontend part of start writing page
-> the user can also submit their written work
Making start.html interactive 
And somethings you can also suggest 🙂

Please assign this to me under gssoc extd' 2024

**Comment by Codersweta7** [comment]
Thankyou anshika , I am grateful that you responded at least I will have something to work as of now 🙂

**Comment by ANSHIKA-26** [comment]
all of these issues already exist , kindly check OLD ISSUES BEFORE RAISING NEW ONES
