### ISSUE TITLE
Enhancement: UI of toggle button can be improved

### ISSUE THREAD

**Issue by sriraghavi22** [ANSHIKA-26/WordWise#362]
The toggle button for dark mode and light mode looks basic. It can be improved.

![Screenshot 2024-10-06 105249](https://github.com/user-attachments/assets/eb897b42-80ff-4087-bf09-5d2a01058f0a)

I would like to work on this

**Comment by ANSHIKA-26** [comment]
kindly suggest what u wish to do

**Comment by sriraghavi22** [comment]
icons like a sun for light mode and a moon for dark mode or background could change color with a gradient effect.
