### ISSUE TITLE
Redesign Complete Navbar Design (Enhancement).

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#366]
**Describe the bug**
The current navbar design lacks innovation and does not have a well-arranged layout. The hover effects on the links are not visually appealing and do not effectively enhance user interaction.

**To Reproduce**
1. Go to the homepage of the website.
2. Hover over any of the navbar links (e.g., Home, About, Contact Us).
3. Observe the hover effect and overall arrangement of items.

**Expected behavior**
1. A more visually appealing hover effect that changes the link color to a darker shade when hovered.
2. A smooth underline effect that animates when users hover over the links, enhancing the overall interaction.
3. A well-arranged layout that improves aesthetics and user experience.

**Screenshots**
Current Navbar
![Screenshot 2024-10-06 113706](https://github.com/user-attachments/assets/137812fd-8c63-4254-ab09-64e44456f659)

**Additional context**
Improving the navbar design will enhance user experience by providing better visual feedback and a more organized layout. This change should align with the overall design theme of the website.

**Comment by shivam8112005** [comment]
can you please add level label

**Comment by ANSHIKA-26** [comment]
#304 exists

**Comment by shivam8112005** [comment]
I have new design, assign this issue to me.

**Comment by shivam8112005** [comment]
But #304 pr was successfully merged but issue is still open
