### ISSUE TITLE
Enhance the alignment of the gallery section under load more posts!

### ISSUE THREAD

**Issue by maniacedoc** [ANSHIKA-26/WordWise#367]
What is the issue?
Under the load more post option, the posts seems very unaligned, want to work on this to make the alignment of the page proper so that it doesn't look unaligned. 

Steps to reproduce the behaviour:
1. Go to the photos under the load more post button
2. Click on next icon to see more photos

**Expected behavior**
I basically want to add all the pictures in a single post where. we can move to the next one simply by clicking on the next button

Screenshots
![Screenshot 2024-10-06 114138](https://github.com/user-attachments/assets/021fdd16-eab6-4697-8f0b-21811f9359d7)

**Comment by maniacedoc** [comment]
No the issue hasn't been raised by anyone earlier.

**Comment by ANSHIKA-26** [comment]
#318 covers this
