### ISSUE TITLE
Update UI of Contact Us page

### ISSUE THREAD

**Issue by IshaRawat7** [ANSHIKA-26/WordWise#368]
Hii @ANSHIKA-26 , The current design of the "Contact Us" page can be enhanced to improve its usability and visual appeal.
Currently, it is not visually appealing. We can use this:

![Screenshot 2024-10-06 113543](https://github.com/user-attachments/assets/6d231a61-e80e-433e-88df-94b104ee7de7)

Instead of this
 
![Screenshot 2024-10-06 113719](https://github.com/user-attachments/assets/9902666f-f582-4015-b136-c619778592f2)

The new design will be more appealing. I am wiling to contribute to this project.

**Comment by IshaRawat7** [comment]
Thanks for the response! Could you please assign me this issue @ANSHIKA-26 ? I'm looking forward to working on improving the UI of 'CONTACT US' page

**Comment by ANSHIKA-26** [comment]
#255 already there
