### ISSUE TITLE
Feat Update: To add a Website Views Counter

### ISSUE THREAD

**Issue by rohitinu6** [ANSHIKA-26/WordWise#376]
Hi @ANSHIKA-26 , I would like to add a widget in the footer of the page that can show the no of view, the website has got.

A prototype is attached for your reference:
![image](https://github.com/user-attachments/assets/def41449-4c09-4b0a-a7d9-fccc66d5e138)

Please assign the issue to me and add the gssoc and hactoberfest labels.

**Comment by AnushkaS77** [comment]
hey @rohitinu6 could you also assign me ?? 
the feature you suggested seems quite interesting

**Comment by hiteashgupta1** [comment]
@AnushkaS77 already added
