### ISSUE TITLE
The home page is not responsive and is not displaying correctly on various screen sizes.

### ISSUE THREAD

**Issue by SurajSakhare100** [ANSHIKA-26/WordWise#380]
Describe the bug
The home page is not displaying correctly on certain screen sizes. On small screens, some elements are misaligned, overflowing, or not scaling properly, leading to a broken layout.

Expected behavior
The home page should adjust fluidly to different screen sizes, ensuring that all elements are aligned, properly scaled, and contained within the viewport. The layout should adapt responsively across all screen sizes from mobile to desktop without visual breaks.

Screenshots
![s](https://github.com/user-attachments/assets/63017cb2-9063-4cad-839a-f61c9a67b0ad)

**Comment by SurajSakhare100** [comment]
would like to work on this issue under GSSoC Extension and Hactoberfest.

@ANSHIKA-26  Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
issue #257 is already there , please do not make duplicate issues
