### ISSUE TITLE
[Feature]: Design a Home Page for the Website 

### ISSUE THREAD

**Issue by Devaki01** [ANSHIKA-26/WordWise#383]
I would like to contribute by adding a home page for WordWise website that is user-friendly, visually appealing, and aligns with the brand's identity. This page will serve as the main entry point for visitors and should clearly convey the site's purpose, provide easy navigation, and highlight key features.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/1c1d40d3-5ed4-4be4-ad92-a379fc2f7ae8">

Please assign me this issue under gssoc'24 extd.

**Comment by Devaki01** [comment]
Thank you for assigning it to me. Will complete it by end of the day.

**Comment by ANSHIKA-26** [comment]
the page right now is good , also i didnt assign it to you
