### ISSUE TITLE
Improve the UI of the Navbar

### ISSUE THREAD

**Issue by Devaki01** [ANSHIKA-26/WordWise#387]
The current navbar has functionality but some more UI improvements would enhance its usability and visual appeal. I would like to contribute by improving the layout and spacing between elements and adding icons to make it more user friendly. 

Please assign me this issue under gssoc'24 extd.

**Comment by Devaki01** [comment]
Thank you for assigning it to me. Will complete it by end of the day.

**Comment by ANSHIKA-26** [comment]
#304 is already working on navbar
