### ISSUE TITLE
Footer can be updated

### ISSUE THREAD

**Issue by monishkumardvs** [ANSHIKA-26/WordWise#390]
**Describe the bug**
The footer in ur website is very clumsy and very near to each other

**To Reproduce**
1. Go to 'home'
3. Scroll down to 'About us'

**Expected behavior**
The footer can be more neat and have gaps between them

**Screenshots**
![image](https://github.com/user-attachments/assets/0b84b344-cd48-40eb-b7b8-27e5b8445032)

can u assign me
**Additional context**

**Comment by monishkumardvs** [comment]
Can u assign me i want to work on this

**Comment by Hemraj-7** [comment]
Footer already updated
