### ISSUE TITLE
UI is not responsive

### ISSUE THREAD

**Issue by simmi-verma** [ANSHIKA-26/WordWise#391]
![WhatsApp Image 2024-10-06 at 3 15 23 PM](https://github.com/user-attachments/assets/ef654dcc-9570-40f9-a882-ab654461a523)

The website does not adjust properly on mobile devices, causing layout issues and making it difficult for users to access or fill out the contact form.
 I can solve this issue so please assign to me.

**Comment by simmi-verma** [comment]
please add gssoc level and please assign to me

**Comment by ANSHIKA-26** [comment]
#257 is there , kindly do not make duplicate issues
