### ISSUE TITLE
Text color blending with background in blog post section

### ISSUE THREAD

**Issue by PATILYASHH** [ANSHIKA-26/WordWise#4]
There is an issue with the text color blending into the background on the blog post section of the website. The pink text used for the date and comment icons is difficult to read against the light pink background.

### Steps to reproduce:
1. Navigate to the blog post section on the home page.
2. Notice that the text displaying the date and comment count blends with the background, making it hard to read.

### Expected behavior:
The text should have better contrast with the background to improve readability.

### Suggested solution:
- Change the text color to a darker shade or modify the background color.
- Also, could you consider adding a text-shadow for better visibility?

### Screenshot:
![project before](https://github.com/user-attachments/assets/a974cca9-48fe-4e20-b8a8-0a4fd7e3ee80)

**Comment by PATILYASHH** [comment]
Hi, I’d like to take this issue and work on a fix!

**Comment by ragineedarade** [comment]
i want to give proper sizes of all thi simages

**Comment by PATILYASHH** [comment]
> i want to give proper sizes of all thi simages

The website isn't responsive, but with a few adjustments like media queries and flexible layouts you can make it adapt to any device.
