### ISSUE TITLE
Photo Slider Indicators Not Updating on Slide Change

### ISSUE THREAD

**Issue by 1101surabhi** [ANSHIKA-26/WordWise#408]
![image](https://github.com/user-attachments/assets/bee25847-bc58-4f62-8137-9ed6d9de333b)

Description:
The photo slider's pagination dots (indicators) are not updating as expected. All the dots appear blank and do not visually reflect the current slide. The indicator corresponding to the active photo should be filled or highlighted to show the current position in the slider.

Expected Behavior:
When the slider transitions to the next photo, the corresponding dot should fill or change color to indicate the current photo.

Current Behavior:
All the dots remain blank across all slides, regardless of which photo is currently displayed.

This issue affects user navigation, as it’s difficult to tell which photo is currently being shown. I want to solve this issue. Please assign this issue to me @ANSHIKA-26 .

**Comment by ANSHIKA-26** [comment]
#318
