### ISSUE TITLE
[BUG] : FAQ Readability Issues Due to Color Palette

### ISSUE THREAD

**Issue by Someshog** [ANSHIKA-26/WordWise#416]
**Describe the bug**

The FAQ section of the website exhibits poor readability due to the current color palette. The text color does not contrast sufficiently with the background, making it difficult for users to read the content clearly.

**To Reproduce**
1. Navigate to the website.
2. Scroll down to the FAQ section.
3. Observe the text color against the background.

**Expected behavior**
Text in the FAQ section should have a high contrast with the background to ensure readability for all users, including those with visual impairments.

**Screenshots**

![image](https://github.com/user-attachments/assets/75006280-d75a-423e-bbae-449757bd4648)

**Additional context**
This issue could negatively impact user experience and accessibility. A minimal design approach would enhance readability and compliance with accessibility standards.

**Comment by ANSHIKA-26** [comment]
#364 covers it
