### ISSUE TITLE
Categories and Contact Us Modules Not Attractive and Missing Information

### ISSUE THREAD

**Issue by sadafhukkeri** [ANSHIKA-26/WordWise#422]
**Describe the bug**
The Categories module lacks visual appeal, and when clicking on "Learn More," it does not display any additional information. Additionally, the Contact Us module is visually unappealing, leading to a suboptimal user experience.

**To Reproduce**
1. Go to the "Categories" section.
2. Click on "Learn More" for any category.
3. Observe that no additional information is displayed, and the layout lacks attractiveness.
4. Go to the "Contact Us" section.
5. Notice that the design of this section is plain and not engaging.

**Expected behavior**
The Categories module should display visually appealing content with appropriate design elements.
Upon clicking "Learn More" in the Categories module, additional information related to the selected category should be displayed.
The Contact Us section should be visually attractive with better design elements such as interactive forms, better typography, and layout.
**Screenshots**
![Screenshot (162)](https://github.com/user-attachments/assets/5030a266-9843-455e-8f0b-ed9d4fca26fb)
![Screenshot (163)](https://github.com/user-attachments/assets/4124b291-e389-45cd-945b-93be0658f8c3)

**Additional context**
This issue impacts the overall user experience on the ML Fusion Labs website. Enhancing the visual appeal and functionality of both modules will improve user interaction and engagement.

**Comment by ANSHIKA-26** [comment]
issue #372

**Comment by sadafhukkeri** [comment]
i have checked the project it is still not done. Can you assign me this project?
