### ISSUE TITLE
the slide feature is not working and also its not showing the banner when pressing the corresponding point 

### ISSUE THREAD

**Issue by HS202022** [ANSHIKA-26/WordWise#424]
**Describe the bug**
the slide feature is not working and also its not showing the banner when pressing the corresponding point 

**To Reproduce**
https://github.com/user-attachments/assets/b7fffc0c-4d17-4e39-8cc6-3226cf76f5b2

**Expected behavior**
it should respond and slide when i try to slide it

**Comment by HS202022** [comment]
Hey can you assign me this issue ![Screenshot_20241006_203037.jpg](https://github.com/user-attachments/assets/b485ed90-b697-4945-b929-c82566b1f109)

I'm getting this warning

**Comment by ANSHIKA-26** [comment]
#318 is similar to your issue , ask to be assigned on that
