### ISSUE TITLE
Like/Dislike System

### ISSUE THREAD

**Issue by aditiverma-21** [ANSHIKA-26/WordWise#430]
Enable readers to rate posts or comments.

**Comment by shalini-bhandari** [comment]
Is this issue open? if it is kindly assign me

**Comment by NirajD04** [comment]
could you assign this to me

**Comment by ANSHIKA-26** [comment]
@aditiverma-21 ?

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 YES I AM WORKING ON IT. SORRY FOR LATE RESPONSE.I HAVE BEEN LITTLE BUSY. I WILL SEND YOU SAMPLES AT NIGHT.

**Comment by ANSHIKA-26** [comment]
its okayy , relax 
@NirajD04 , @aditiverma-21 is working so i cant assign it to you
