### ISSUE TITLE
Enhancing the design of the login/signup page to make them look more professional and user friendly with proper animations and all

### ISSUE THREAD

**Issue by tarunkumar2005** [ANSHIKA-26/WordWise#432]
**Describe the bug**
Enhancing the design of the login/signup page to make them look more awersome as right now they are good but not that much professional i want to do that with proper animations and all.

**To Reproduce**
Go to home page then click on login or signup and see the issue.

**Expected behavior**
It should be more dynamic and professional with proper animations.

@ANSHIKA-26 Assign this to me under gssoc ext 2024 and hacktoberfest

**Comment by ANSHIKA-26** [comment]
#274 already there
