### ISSUE TITLE
Website Horizontal Scrolling Issue

### ISSUE THREAD

**Issue by snehhhcodes** [ANSHIKA-26/WordWise#437]
# Describe the bug
The website is currently scrollable horizontally, allowing users to scroll left and right. This issue negatively impacts the user experience, as it causes unnecessary horizontal movement, making it difficult to navigate the page content properly. The horizontal scrolling appears to be due to certain elements exceeding the viewport width, leading to content overflow.

# To Reproduce
1. Open the website on any desktop or mobile browser.
2. Scroll to the right side of the page.
3. Observe that the page content overflows, allowing for horizontal scrolling.

# Expected behavior
The website should not have horizontal scrolling. All content should be contained within the viewport, and the page should only scroll vertically.

# Screenshots

[screen-capture (2).webm](https://github.com/user-attachments/assets/d83a366f-fbdb-44ed-9c66-e94d08682c6c)

# Additional context
If suitable Please assign it to me I can fix it

**Comment by snehhhcodes** [comment]
@ANSHIKA-26 it got closed why?

**Comment by ANSHIKA-26** [comment]
someone is already working on this , thats why
