### ISSUE TITLE
Add login and signup form

### ISSUE THREAD

**Issue by Mahima-2404** [ANSHIKA-26/WordWise#442]
Add a login and sign up form.
Also Add a dropdown section under a profile icon in the navbar containing links to the login and signup form

**Comment by Mahima-2404** [comment]
@ANSHIKA-26 Please assign me. I am well capable

**Comment by hiteashgupta1** [comment]
But login and signup are already there
What are you trying to doing

**Comment by Antima2004** [comment]
@hiteashgupta1 In the login and signup page there is no cancel button that the user can go back to the homepage.they have to refresh the website.
Please assign this to me.
Here's the screenshot:
![Screenshot 2024-10-07 9 17 57 AM](https://github.com/user-attachments/assets/ecd9748a-dee0-4b33-bdb5-623ae4c361b7)

**Comment by lavanyabandari** [comment]
can you assign it to me

**Comment by ANSHIKA-26** [comment]
the form is already added , what do you wish to implement ?

**Comment by hiteashgupta1** [comment]
Share video after changes on the website

**Comment by lavanyabandari** [comment]
their is no search bar in the header section and color combination ,proper borders  is not nice so, i will with go that ..can you please  assign it to me.

**Comment by hiteashgupta1** [comment]
@lavanyabandari raise issue
