### ISSUE TITLE
Navbar Position is Not Fixed

### ISSUE THREAD

**Issue by shashankgoud18** [ANSHIKA-26/WordWise#449]
Steps to Reproduce:

1.Visit any page with a navbar (e.g., homepage or about page).
2..Scroll down the page.
3.Observe that the navbar scrolls with the content instead of remaining fixed at the top.

Expected Behavior: The navbar should remain fixed at the top of the viewport when scrolling, making navigation easier.
Actual Behavior: The navbar scrolls along with the page content, leaving the top of the viewport.

**Comment by shashankgoud18** [comment]
Hey @ANSHIKA-26 
I have reviewed all the open issues in the repository but did not find any related to the navbar position not being fixed. Hence, I am raising this issue to address the problem.

**Comment by ANSHIKA-26** [comment]
issue #431 
i believe making navbar sticky comes under navbar Ui only , you are requested to go through contribution guidelines before raising duplicate issue ,
https://github.com/ANSHIKA-26/WordWise/issues/435
I have very specifically mentioned that once 1 person is working on UI , you can either collaborate with them / give them suggestions / ask to be assigned on their issue , or raise another issue , one person working on navbar UI while other person just making it sticky doesnt make sense !
