### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [ANSHIKA-26/WordWise#452]
@ANSHIKA-26 
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by ANSHIKA-26** [comment]
im sorry , but we dont need these
