### ISSUE TITLE
update the responsiveness of footer and main content in about us page 

### ISSUE THREAD

**Issue by harshgupta2125** [ANSHIKA-26/WordWise#453]
In about us page the navbar and main content does not contain any space and all the content is of index.html file and at footer their an extra margin from the bottom and theirs a Load more button which do nothing so have to remove it . I would like to work with it.
@ANSHIKA-26 

![image](https://github.com/user-attachments/assets/2ee60899-14fc-46a8-abb1-e893659e4031)
![image](https://github.com/user-attachments/assets/752d6841-bc59-45cf-89c3-fa216b52b51c)

**Comment by ANSHIKA-26** [comment]
issue #257 is there
