### ISSUE TITLE
🌕 NO seperate feedback page

### ISSUE THREAD

**Issue by 1ShahidBashir** [ANSHIKA-26/WordWise#457]
@ANSHIKA-26 when clicked on Give Feedback it redirect to contact us
![image](https://github.com/user-attachments/assets/36421482-eb79-4969-bc2e-759f876b6cd7)

![image](https://github.com/user-attachments/assets/a5b943d4-1220-4ec3-981f-1fc78a683cd3)
WE should have a separate page for feedback and improvements.

**Comment by 1ShahidBashir** [comment]
@ANSHIKA-26 check out the screenshots to verify.
Assign this issue to me. I can create a great feedback page for the project

**Comment by ANSHIKA-26** [comment]
#266
