### ISSUE TITLE
proper landing page

### ISSUE THREAD

**Issue by lavanyabandari** [ANSHIKA-26/WordWise#464]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lavanyabandari** [comment]
can you assign these issue to me .

**Comment by ANSHIKA-26** [comment]
follow the issue template while raising the issue ! , there is no description of what you wish to implement

**Comment by shruti4083** [comment]
i would like to work in this project , please assign it to me.

**Comment by hiteashgupta1** [comment]
@lavanyabandari what you want to implement

**Comment by yashasvi045** [comment]
hey, i can help in this by adding a colour gradient to the landing page background. please assign it to me.

**Comment by ANSHIKA-26** [comment]
> hey, i can help in this by adding a colour gradient to the landing page background. please assign it to me.

not needed
