### ISSUE TITLE
add about page where your info and about this page

### ISSUE THREAD

**Issue by nishant4500** [ANSHIKA-26/WordWise#474]
Bug Report for Missing "About" Page
Describe the bug
The "About" page link is visible in the navigation bar, but when clicked, it does not display the intended content or may not load the page correctly.

To Reproduce

Go to the website (e.g., "https://anshika-26.github.io/WordWise/about.html").
Click on the 'About' link in the navigation menu.
Observe the behavior (whether it leads to a missing page, error, or no content is displayed).
Expected behavior
The "About" page should load, displaying content that explains the purpose of the website or provides information about the platform, its mission, and team.

Screenshots
![Screenshot 2024-10-07 135220](https://github.com/user-attachments/assets/991eb140-1eb4-416d-b4d1-10d9e21d3f60)

Additional context
Ensure that the "about.html" file is present in your repository and correctly linked in the navigation bar. Double-check the folder paths and file names for any discrepancies.

**Comment by hiteashgupta1** [comment]
@nishant4500 the page is already there but needs some changes if you want to add changes kindly share what you want to implement

**Comment by nishant4500** [comment]
i want to add a comment section where any issue if user faced then they mailed it . and make the about page more sysmatic way

**Comment by ANSHIKA-26** [comment]
we already have a feedback page for this

**Comment by ANSHIKA-26** [comment]
about us page doesnt make sense for a small website like this , we already have an about us section , kindly research about what you wish to do before opening an issue and then describe the changes properly
