### ISSUE TITLE
Adding a favicon icon

### ISSUE THREAD

**Issue by RiddhiM170904** [ANSHIKA-26/WordWise#475]
**Describe the bug**
A favicon icon to be added to the website making it more attractive.

**To Reproduce**

**Expected behavior**
Favicon icon of the website will be presented at the opening tab.

**Screenshots**
Before the changes -
![image](https://github.com/user-attachments/assets/3dee9db6-ec8f-40dc-8607-f1d0e4470f8c)
After the changes - 
![image](https://github.com/user-attachments/assets/e1083475-4e80-4248-b0b5-f6a5600f8ef5)
(example)

Please assign me under GSSoC'24 EXTD and Hacktoberfest.

**Additional context**

**Comment by RiddhiM170904** [comment]
@ANSHIKA-26 why issue is closed ??

**Comment by ANSHIKA-26** [comment]
https://wordwise-k9ho.onrender.com/index.html

because we already have a favicon , which can be clearly seen here
