### ISSUE TITLE
the about button should not be displayed in about page ,meanwhile the buttons to open a relevant page should not be displayed on the same page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [ANSHIKA-26/WordWise#480]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Uploading im.png…]()

**Additional context**

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
solved this issue by removing the contact us button from contact us page and feed back button from feed back page ,about us button from about us page ,start writing button from start writing page

https://github.com/user-attachments/assets/3ba5fd3f-c0e8-4d29-8c40-e2eb74a0c4fa

**Comment by ANSHIKA-26** [comment]
@KapuluruBhuvaneswariVspdbct a lot of people are already assigned navbar UI , its their issue , kindly do not work on an issue unless it has been assigned to you , which in this case , was not , instead we closed your issue and did inform you that a similar issue exists ,hence your PR will not be merged .
