### ISSUE TITLE
Duplicate Submit Button and Lack of Form Validation in Blog Page

### ISSUE THREAD

**Issue by MasirJafri1** [ANSHIKA-26/WordWise#489]
### 2)Will Validate the form as follows:
          Name (required)
          Email (should follow a valid email format)
          Website (optional but should follow a valid URL format if provided)
          Message (required) 

## Screenshot of the bug

![Screenshot 2024-10-07 171038](https://github.com/user-attachments/assets/1b9016fa-810b-4f60-b9be-daea1d015f7e)

**Comment by MasirJafri1** [comment]
Hi @ANSHIKA-26 , I noticed there are two submit buttons and no form validation, but I couldn't find an existing issue on this. Could you guide me to one if it exists?

**Comment by ANSHIKA-26** [comment]
form validation done in a PR , just fix the submit issue button
