### ISSUE TITLE
Improve the "Leave Comment" Section in Leading blog page

### ISSUE THREAD

**Issue by master-ginger** [ANSHIKA-26/WordWise#496]
As clearly seen the comment section is not visually appealing in this page. I can create a better one while adding responsiveness to it for all the screens. Also the title "Leave comments" is very similar to the background color which might make it unnoticed.
![image](https://github.com/user-attachments/assets/0ddb5706-4640-42aa-8f33-0b91040ae25f)

**Comment by ANSHIKA-26** [comment]
#302 is doing this alreadt
