### ISSUE TITLE
Add a forgot password feature 

### ISSUE THREAD

**Issue by 17arindam** [ANSHIKA-26/WordWise#501]
if a user forgot his password he should get a mail to reset their password 
![image](https://github.com/user-attachments/assets/3a176575-9a02-47d9-b9a3-8cdafaac6521)

**Comment by 17arindam** [comment]
hey @ANSHIKA-26 i didnt find forgot password in issues if its not present can you assign me that issue

**Comment by SaanyaGarg5** [comment]
you can assign that task to me
