### ISSUE TITLE
Issue in NavBar !!!

### ISSUE THREAD

**Issue by AnujShrivastava01** [ANSHIKA-26/WordWise#511]
![image](https://github.com/user-attachments/assets/f022d46f-87bd-482f-93b8-ac98c2a59bbc)

-> The Logo Name (Worldwise) is appearing twice and also Home button is displaying at top right corner.
Assign this to me with !

**Comment by ANSHIKA-26** [comment]
@AnujShrivastava01 it isnt correct to raise an issue on someone elses PR , you could have just commented here and i would have seen it

**Comment by Saurabhchaudhary9799** [comment]
hey @ANSHIKA-26 ,could  you please assign this to me ?

**Comment by ANSHIKA-26** [comment]
@AnujShrivastava01 raised it first , then someone else already made a PR , so i cant assign it to you now @Saurabhchaudhary9799
