### ISSUE TITLE
Improve Navbar UI for better user experience

### ISSUE THREAD

**Issue by Deepak0yadav** [ANSHIKA-26/WordWise#517]
**Navbar have some issues**

1. **The Home ,categories, about us are appearing twice and the world wise logo also**
 
![Screenshot 2024-10-07 233545](https://github.com/user-attachments/assets/48fb1cc7-cf08-4c78-97b5-f464a43a090f)

2. **Login and sign-up buttons are having bad color combination and border ,creates a poor visual experience for users**

We should resolve them to improve better user experience.

**Comment by srivishnu2805** [comment]
Can i work on this to enhance the navbar and to be more attractive

**Comment by TornovDutta** [comment]
please assign it to me.
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
PR already made , ask @Deepak0yadav if he needs help , there still a lot he has to finish

**Comment by sayiamarora** [comment]
Hi @ANSHIKA-26, I would like to enhance the "Navbar UI" to improve overall user experience. This update will include better visual styling, improved responsiveness for different screen sizes, and streamlined navigation links to make it easier for users to access key sections of the website. Please let me know if this aligns with our project goals.

**Comment by Saurabhchaudhary9799** [comment]
@ANSHIKA-26 , could you please assign to me ?

**Comment by ANSHIKA-26** [comment]
PR already made
