### ISSUE TITLE
Add GitHub Workflow for Auto-Closing Similar Issue Requests

### ISSUE THREAD

**Issue by shubhagarwal1** [ANSHIKA-26/WordWise#529]
Implement a GitHub workflow that automatically detects and closes duplicate or similar issue requests. The workflow should:

Utilize a bot or script to compare new issues against existing ones.
Automatically flag or close issues with matching titles, descriptions, or keywords.
Provide a comment linking the user to the original issue for reference.
Ensure the workflow runs on issue creation to streamline project management.

Hey @ANSHIKA-26 please assign me this task.

**Comment by ANSHIKA-26** [comment]
this workflow exists , what changes do you wish to do ?

**Comment by shubhagarwal1** [comment]
> this workflow exists , what changes do you wish to do ?
<img width="1364" alt="Screenshot 2024-10-08 at 4 29 38 PM" src="https://github.com/user-attachments/assets/1d2539b4-20a4-4d68-b3f3-b8d39ed81f32">

okay can i a search bar to the page

**Comment by ANSHIKA-26** [comment]
sure , wait for the navbar issue to get fixed though , someone is working on it
