### ISSUE TITLE
Fixes some U.I. Issues 

### ISSUE THREAD

**Issue by aditya07389** [ANSHIKA-26/WordWise#539]
# @ANSHIKA-26 , i would like to work on the following things 

## 1) SIgnup page:

it looks like this ,
![image](https://github.com/user-attachments/assets/2ad7805c-da46-4925-a583-c78173727f99)
## 2) Rollover animation for home page :
i think it will look good if i can add rollover animations to the home page .

### kindly assign this under 'gssoc extended'

**Comment by aditya07389** [comment]
give me the issue number of similar issue

**Comment by aditya07389** [comment]
thers no issue which fixes signup alignment

**Comment by NirajD04** [comment]
could you also assigned similar issue as this
