### ISSUE TITLE
Proposal  : Adding separate contact us form.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [ANSHIKA-26/WordWise#54]
- Objective:
Implement a dedicated "Contact Us" form for user inquiries.

- Features:
Name: Identify the sender.
Email: Enable replies.
Questions/Comments: Collect user feedback.

- Benefits:
Simplifies communication for users.
Gathers valuable inquiries directly.
Enhances user experience.

**Comment by AbhijitMotekar99** [comment]
Hey @ANSHIKA-26 
Please Assign this issue to me.

**Comment by iamparas0** [comment]
> * Objective:
>   Implement a dedicated "Contact Us" form for user inquiries.
> * Features:
>   Name: Identify the sender.
>   Email: Enable replies.
>   Questions/Comments: Collect user feedback.
> * Benefits:
>   Simplifies communication for users.
>   Gathers valuable inquiries directly.
>   Enhances user experience.

Go for please attach before and after ss or video while pr
