### ISSUE TITLE
No Option to View Password While Typing

### ISSUE THREAD

**Issue by PATILYASHH** [ANSHIKA-26/WordWise#541]
#### Description
Currently, there is no option to view the password while typing in the password field, making it difficult for users to verify what they have entered. Adding a "Show Password" toggle will allow users to view their password as they type, improving usability.

#### Steps to Reproduce
1. Navigate to the password input field.
2. Start typing a password.
3. Notice there is no option to reveal the password while typing.

#### Expected Behavior
- A "Show Password" toggle (e.g., an eye icon) should be added next to the password field. When clicked, it should allow the user to see the password in plain text.
- Clicking the toggle again should revert the password back to hidden.

#### Possible Solution
- Implement a toggle button or icon (such as an eye icon) next to the password field that toggles between showing and hiding the password by changing the input field type from `password` to `text`.

#### Screenshot
![image](https://github.com/user-attachments/assets/93c25c31-4c85-44bf-94c9-dc1b5c4b34ac)

#### Additional Context
By adding this feature, users will have the option to verify their passwords easily, reducing the chance of mistakes and improving the overall user experience.

**Comment by aryangaur380** [comment]
Dear @ANSHIKA-26  ,

I hope you're doing well. I would like to request this project assignment to contribute to. I'm eager to get involved and apply my skills to make a meaningful impact.

Looking forward to your response.

Best regards,  
Aryan Gaur

**Comment by ANSHIKA-26** [comment]
issue resolved already @aryangaur380
