### ISSUE TITLE
Integrating Google Login: Adding Google Authentication to Your Website

### ISSUE THREAD

**Issue by amanver45** [ANSHIKA-26/WordWise#543]
### 🔴 **Title**:
**Integrating Google Login: Adding Google Authentication to Your Website**
 🔴 Tech stack:
- **HTML**: Structure the login page and buttons
- **CSS**: Style the Google login button and overall UI
- **JavaScript**: Handle Google Sign-In integration and manage authentication
- **Google OAuth API**: Enable and configure Google authentication services

 🔴 Objective:
The objective of this project is to integrate Google Sign-In functionality into a website, allowing users to log in using their Google accounts. This simplifies the login process by leveraging Google’s OAuth 2.0 authentication system and enhances user experience by eliminating the need to remember separate usernames and passwords.

🔴 Summary:
In this project, we will implement a Google login button on a web page using Google’s OAuth 2.0 API. The Google Sign-In integration allows users to authenticate securely using their Google credentials, which improves convenience, security, and user retention.

The key steps in this project are:
1. **Setting up Google API**: Create a project in Google Developer Console, enable the OAuth API, and obtain client credentials.
2. **HTML Structure**: Design a login page with a “Sign in with Google” button.
3. **JavaScript Integration**: Use Google’s JavaScript API to manage the authentication process. When a user clicks the login button, they will be prompted to log in via their Google account.
4. **Handling Authentication**: Once the user logs in, retrieve their profile information (name, email, etc.), and handle session management.

**Comment by amanver45** [comment]
@ANSHIKA-26 there is no open issue related to my issue pls check and asssign me

**Comment by ANSHIKA-26** [comment]
issue #375
