### ISSUE TITLE
[Bug] Same form display at contact us and feedback form

### ISSUE THREAD

**Issue by ananyag309** [ANSHIKA-26/WordWise#544]
I am willing to fix it and design a new feedback form respectively

currently contact us
![image](https://github.com/user-attachments/assets/19b23fc7-a681-412c-9bdf-9a62831e77b9)
and feeback 
![image](https://github.com/user-attachments/assets/d707bc7a-ce02-4458-baca-515ab9801160)
both have same form or feedback 

that needs to be fix

**Comment by hiteashgupta1** [comment]
#266 already there
