### ISSUE TITLE
create backend Api for the blog submission

### ISSUE THREAD

**Issue by AyushSharma72** [ANSHIKA-26/WordWise#546]
i want to create a backend api which enables user to submit the blog 

![image](https://github.com/user-attachments/assets/15cd9219-29f6-433a-b8e6-4099dcbbc4ec)

please assign this issue  to me @ANSHIKA-26

**Comment by AyushSharma72** [comment]
> i want to create a backend api which enables user to submit the blog
the website already have a backend folder i will add an api which lets save the user blogs with photo
> 
> ![image](https://private-user-images.githubusercontent.com/133676532/374430452-15cd9219-29f6-433a-b8e6-4099dcbbc4ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjgzNzAsIm5iZiI6MTcyODM2ODA3MCwicGF0aCI6Ii8xMzM2NzY1MzIvMzc0NDMwNDUyLTE1Y2Q5MjE5LTI5ZjYtNDMzYS1iOGU2LTQwOTlkY2JiYzRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwNjE0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWIwYjhlNmYzNzc0NTQzMmQ3NDU4Yzk0ZjI5YWQ1OWQ3OWQ3YzY0MzdmZTZkZTFhYzViMWRmNmM0MjcwM2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FsJZ_Z2oyhyEtA8_n-DR0COL8wyV7EKa6n0uSrlp-1I)
> 
> please assign this issue to me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
where will you be storing the blog  ? local storage ?

**Comment by AyushSharma72** [comment]
> where will you be storing the blog ? local storage ?

not locastorage i will connect mongodb database for that since your backend api is in nodejs mongodb is the right option for that
