### ISSUE TITLE
 Design and Usability Issues in Sidebar Layout

### ISSUE THREAD

**Issue by TornovDutta** [ANSHIKA-26/WordWise#551]
# Description: 
The sidebar design presented has several usability and aesthetic issues that reduce its overall effectiveness. The primary concerns are related to typography, alignment, spacing, icon size, and color contrast.

# screenshot:
![Screenshot 2024-10-08 124918](https://github.com/user-attachments/assets/128dbac7-b32e-448a-bca5-4add5a1dc5ce)

**Comment by TornovDutta** [comment]
@ANSHIKA-26 please label the issuse

**Comment by TornovDutta** [comment]
@ANSHIKA-26 please assign it to me

**Comment by TornovDutta** [comment]
@ANSHIKA-26 please label the lavel of the issuse

**Comment by ANSHIKA-26** [comment]
what changes do you wish to do ?

**Comment by TornovDutta** [comment]
# To improve the sidebar design:

1.Typography: Make headings (e.g., "Popular Tags") larger and bold. Fix "Techonogy" to "Technology" and add more space between tags for better readability.

2.Alignment: Align social icons evenly and ensure headings are properly aligned with their sections.

3.Spacing: Increase space between sections and add more space between social media icons.

4.Icon Size: Make social media icons slightly larger for better visibility.

5. Contrast: Increase the contrast between text/icons and the background for easier readability.

These changes will improve both usability and visual appeal.

**Comment by Sravanthi1664** [comment]
@ANSHIKA-26 assign me here
