### ISSUE TITLE
Cards is creating issue in small devices (mobile phone)

### ISSUE THREAD

**Issue by Hemraj-7** [ANSHIKA-26/WordWise#552]
## Home page cards is not responsive in small devices. they are take extra width

![Screenshot 2024-10-08 125353](https://github.com/user-attachments/assets/694657fb-e780-43db-a049-1a7be82c7298)

I want to fix this issue 
assigned me

**Comment by Hemraj-7** [comment]
> Thanks for raising this issue! However, we believe a similar issue already exists. Kindly go through all the open issues and ask to be assigned to that issue.

similar issue number

**Comment by ANSHIKA-26** [comment]
issue #257 , it means the same

**Comment by Hemraj-7** [comment]
> issue #257 , it means the same
ok thanks

**Comment by ANSHIKA-26** [comment]
ask on that issue
