### ISSUE TITLE
 i want to add card like style  for scrolling images  left and right

### ISSUE THREAD

**Issue by ragineedarade** [ANSHIKA-26/WordWise#56]
![{8521D789-CD07-43FC-97F8-BE76074ECE18}](https://github.com/user-attachments/assets/0c6ec85e-24f3-49a1-a379-3d58519adefa)
  i want to add this type of scrolling

**Comment by lakshya-pratap-singh-chauhan** [comment]
I would like to start my contribution from your issue , i'm looking forward to solve this issue ...
