### ISSUE TITLE
 bug in  header UI  after clicking header links

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [ANSHIKA-26/WordWise#562]
**Describe the bug**
whenever i click on header links of header , the UI of header changes every time .

**To Reproduce**
1. Go to 'Homepage'
2. Click on  any 'nav links'
3. See error

**Expected behavior**
whenever i click on header links , the UI should be remain same for every time.

**Screenshots**
[Screencast from 2024-10-08 15-35-50.webm](https://github.com/user-attachments/assets/bfd105f5-f38c-4440-8cf9-924a230e5606)

**Comment by Saurabhchaudhary9799** [comment]
@ANSHIKA-26 , could you please assign this to me ?

**Comment by ANSHIKA-26** [comment]
ask #517 here
