### ISSUE TITLE
[BUG] : Duplicate navbar in Contact-Us page 

### ISSUE THREAD

**Issue by MasirJafri1** [ANSHIKA-26/WordWise#563]
## There is a duplicate repeated Navbar in Contact-us page.
![Screenshot 2024-10-08 155010](https://github.com/user-attachments/assets/d83c85a2-2bdc-4857-a8bb-498a86d47cd4)

**Comment by MasirJafri1** [comment]
@ANSHIKA-26 can I get assigned to fix this?

**Comment by ANSHIKA-26** [comment]
someone is already working on this in a PR
