### ISSUE TITLE
Create a FAQ section

### ISSUE THREAD

**Issue by ananyag309** [ANSHIKA-26/WordWise#574]
It will be great if we add a faq section 
A FAQ (Frequently Asked Questions) section is essential because it provides quick and concise answers to common questions, improving user experience by addressing concerns and clarifying information efficiently. It also reduces repetitive inquiries, saving time for both users and support teams.

**Comment by sayiamarora** [comment]
Hi @ANSHIKA-26, I would like to create a FAQ (Frequently Asked Questions) Section for our website. This section will address common queries, providing users with quick access to helpful information and reducing support requests. It will enhance user experience by making the website more informative and user-friendly. Please let me know if I can proceed with this addition.

**Comment by ANSHIKA-26** [comment]
its already made ? what do you wish to do ?

**Comment by sayiamarora** [comment]
Actually the FAQ Section was not well aligned when seen from the smaller screen.

**Comment by ANSHIKA-26** [comment]
work together or decide who wants to work on what portion as  both of you wanted to get assigned
