### ISSUE TITLE
Changing Navbar Design

### ISSUE THREAD

**Issue by shivam8112005** [ANSHIKA-26/WordWise#580]
**Describe the bug**
The Navbar design uses an outdated hover effect, and the spacing and alignment of items are inconsistent. The links look cluttered, and the overall visual appeal is diminished due to these issues.

**To Reproduce**
1. Go to the website.
2. Hover over the Navbar links and observe the outdated hover effect.
3. Observe the improper spacing and misalignment of Navbar items.

**Expected behavior**
The Navbar should have a modern, sleek hover effect, such as smooth transitions or subtle highlights. The items should be properly spaced and aligned for a clean, visually appealing design. The Navbar should maintain a balanced layout without any overlapping or uneven spacing.

**Screenshots**

![Screenshot 2024-10-06 212825](https://github.com/user-attachments/assets/bc26ee10-c51f-4c2e-8d70-ef628ece9747)

**Additional context**
The issue may stem from outdated CSS styles or incorrect use of layout classes. Revisiting the CSS for hover effects and item alignment could help modernize the design..

**Comment by ANSHIKA-26** [comment]
heyy , 
![image](https://github.com/user-attachments/assets/026b4bc5-8cbc-47f0-8f76-301a666c9f09)
i really like this effect , just make sure its added across all pages ! and that sign in and login buttons drop down when one clicks on the profile icon

**Comment by shivam8112005** [comment]
ohk you mean i have to remove signin and login button from navbar and add profile icon on place of that

**Comment by ANSHIKA-26** [comment]
yep , and when one clicks on profile the login sign up drop down opens

**Comment by ANSHIKA-26** [comment]
just start with hover and lets see how it goes from there , keep us updated , make sure the navbar is consistent on all pages

**Comment by ANSHIKA-26** [comment]
pr https://github.com/ANSHIKA-26/WordWise/pull/507
something like this

**Comment by shivam8112005** [comment]
Okk got it

**Comment by shivam8112005** [comment]
hey @ANSHIKA-26  can i complete this task till tomorrow evening? coz tody i am traveling.

**Comment by ANSHIKA-26** [comment]
sure

**Comment by ANSHIKA-26** [comment]
take your time , just do it properly once you do it

**Comment by shivam8112005** [comment]
okk sure

**Comment by PulkitShubham** [comment]
I want to enhance the overall design .......it would be great if you assign it to me maam
