### ISSUE TITLE
[BUG]: Misalignment in sign up page

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#589]
**Describe the bug**
The input boxes in the signup page are not aligned properly.

**To Reproduce**
1. Go to Signup
3. See error

**Expected behavior**
All input boxes should be aligned to make it look better
**Screenshots**
<img width="888" alt="Screenshot 2024-10-08 at 7 19 11 PM" src="https://github.com/user-attachments/assets/5d2f396c-dadd-4e9b-a702-c284f29ad0b8">

Please assign me this issue.

**Comment by ANSHIKA-26** [comment]
PR made already for this issue
