### ISSUE TITLE
[Enhance]: Login and signup pages can open in different page without overlapping the content.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#591]
**Describe the bug**
Login and signup pages can open in different page without overlapping the content.

**To Reproduce**
1. Go to 'Login/Signup.'
2. See error

**Screenshots**

<img width="1409" alt="Screenshot 2024-10-08 at 7 32 09 PM" src="https://github.com/user-attachments/assets/df078656-2123-43bb-b9b4-6d42ef870f1e">

**Additional context**
Please assign this issue to me.

**Comment by Arghya-Chakraborty0812** [comment]
"Check for Duplicate Issues" workflow failed, @ANSHIKA-26 can you please review and it and assign it to me if appropriate.

**Comment by ANSHIKA-26** [comment]
what do you wish to add to the workflow ? @Arghya-Chakraborty0812 ?

**Comment by ANSHIKA-26** [comment]
and login and signup are already being worked on in a PR , so cant assign this issue to you sorry

**Comment by ANSHIKA-26** [comment]
> "Check for Duplicate Issues" workflow failed, @ANSHIKA-26 can you please review it, and assign it to me if appropriate.

im open to suggestions , open a discussion regarding it and let me know what you wish to do , if its implementable we can make it an issue
