### ISSUE TITLE
Adding a 'Scroll to top Button' 

### ISSUE THREAD

**Issue by NirajD04** [ANSHIKA-26/WordWise#593]
Adding a 'Scroll to Top' button will improve navigation by allowing users to quickly return to the top of long pages. This will enhance the overall user experience by making it more convenient and efficient to browse the content

**Comment by NirajD04** [comment]
please assign this issue to me for resolution or Similar one

**Comment by sayiamarora** [comment]
Hi @ANSHIKA-26 I would like to add a "Scroll to Top Button" to our website. This button will appear when users scroll down and allow them to quickly return to the top of the page, enhancing navigation and user experience. Please let me know if this feature aligns with our goals.

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/pull/594
done already
