### ISSUE TITLE
Want to fix the UI in dark mode

### ISSUE THREAD

**Issue by ananyakaligal** [ANSHIKA-26/WordWise#601]
White box doesnt look good.
![image](https://github.com/user-attachments/assets/7f4646f5-0e63-44ad-b0d3-7bf90ea2a253)

**Comment by ANSHIKA-26** [comment]
fix Ui of dark mode across all the pages

**Comment by ANSHIKA-26** [comment]
@ananyakaligal ?

**Comment by ANSHIKA-26** [comment]
closing issue due to lack of response
