### ISSUE TITLE
Fixing the alignment of Trending post in Trending Blogs page

### ISSUE THREAD

**Issue by Kiran-F** [ANSHIKA-26/WordWise#605]
Hi there!
It's me kiran. I found a problem in Leading Blog page under trading posts section. Here's the screenshot.
![Screenshot (620)](https://github.com/user-attachments/assets/376fb90b-83bc-4cb4-8ce8-22c2350e21b3)

It can be aligned in a single line in blocks form.
Kindly assign me this issue to fix. Looking forward to contribute. 
Also add the labels of hacktoberfest, hacktoberfest-accepted, level2 and gssoc-ext.

**Comment by Kiran-F** [comment]
@ANSHIKA-26 isn't this issue possible?

**Comment by ANSHIKA-26** [comment]
go ahead

**Comment by ANSHIKA-26** [comment]
update : removing this section , issue not needed
