### ISSUE TITLE
Consolidate 'Contact Us' and 'Give Feedback' Sections

### ISSUE THREAD

**Issue by ananyakaligal** [ANSHIKA-26/WordWise#606]
## Issue: Consolidate 'Contact Us' and 'Give Feedback' Sections

**Description**:
It has been observed that the "Contact Us" and "Give Feedback" sections of our application serve similar purposes and can lead to confusion among users. To enhance user experience and clarity, we propose merging these two sections into a single, streamlined feedback form.

**Proposed Changes**:
1. Rename the current "Contact Us" section to "Feedback".
2. Combine the functionalities of both sections to allow users to contact us while also providing feedback.
3. Ensure that the new section clearly states that users can reach out for inquiries or provide feedback on their experience.

**Benefits**:
- Simplifies the user interface.
- Reduces confusion regarding the purpose of each section.
- Enhances user engagement by providing a single point of contact.

**Next Steps**:
- Review the current implementations of both sections in the codebase.
- Implement the proposed changes and test for functionality.
- Update any relevant documentation to reflect this change.

**Comment by gaurkrutika** [comment]
I would like to contribute to this issue.

**Comment by Kajalmehta29** [comment]
@ANSHIKA-26  Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
@ananyakaligal update
