### ISSUE TITLE
Feature Implementation: Adding Search functionality to Filter Blog posts in Home page and Leading blog post page

### ISSUE THREAD

**Issue by Varsha-1605** [ANSHIKA-26/WordWise#622]
# ExpectedUpdates

- [ ]  Add a search input field to the dashboard allowing users to filter chatbots based on their name or description.

- [ ]  The search functionality should dynamically filter both System Chatbots and User Chatbots in real-time as the user types in the search bar.

- [ ]  Update readme.md file

@ANSHIKA-26 Could you please assign this task to me, I would love to work on  it!

**Comment by Varsha-1605** [comment]
@ANSHIKA-26 
I have already checked there isn't an issue similar to what I have raised. So I kindly request you to allow me to work on it.

**Comment by pavitraag** [comment]
Can u please assign this to me

**Comment by Varsha-1605** [comment]
@pavitraag I have already started working on it and am about to complete it.

**Comment by ANSHIKA-26** [comment]
@Varsha-1605 ?
