### ISSUE TITLE
UI/UX Enhancement for Login and Sign-Up Pages

### ISSUE THREAD

**Issue by ritiksingh-01** [ANSHIKA-26/WordWise#641]
**Describe the bug**
I have made significant improvements to the UI/UX of both the login and sign-up pages. The design is now more polished, with better button alignment, improved styling, and enhanced usability. These changes create a more user-friendly and visually appealing experience, ensuring smoother interactions and a more professional appearance.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

**Screenshots**
![login page](https://github.com/user-attachments/assets/7e6a4d3c-616e-44db-82ae-a774253fc71e)

**Comment by ritiksingh-01** [comment]
Hi, @ANSHIKA-26 

Could you please clarify why this issue was closed without being assigned? 
I would appreciate understanding the reason for this action.

**Comment by ANSHIKA-26** [comment]
check #601  , they are already working on UI for this

**Comment by ANSHIKA-26** [comment]
someone already raised a PR for this , but it seems like they arent pursuing this , so go ahead

**Comment by ritiksingh-01** [comment]
Hi, @ANSHIKA-26 
Please respond quickly so I can start working right away.

**Comment by ANSHIKA-26** [comment]
> Hi, @ANSHIKA-26
> 
> Could you kindly provide your input on whether you'd prefer separate pages for login and sign-up, or if you would like to keep them as they are currently? Your feedback will help guide the next steps in improving the user experience.

same as current

**Comment by ritiksingh-01** [comment]
Hi, @ANSHIKA-26 
If I deliver the PR by tonight, will there be any issues?
