### ISSUE TITLE
Mouse Cursor Trail Effect

### ISSUE THREAD

**Issue by Priyanshi0112** [ANSHIKA-26/WordWise#642]
A mouse cursor trail effect is a visual enhancement used in websites or applications where an animated element follows the movement of the mouse cursor on the screen. This effect adds a dynamic and engaging layer to the user interface, making the interaction feel more immersive.

This will bring :
1.Increased Interactivity: The trail effect responds to user actions, creating a more immersive and interactive experience. It encourages users to explore the site.

2.Aesthetic Enhancement: A well-designed trail can make the interface visually more appealing. It can add a sense of modernity, elegance, or playfulness.

3.Unique Branding: The mouse trail can match your website’s theme or brand colors can give your site a unique identity, making it more memorable to users.

Please assign this issue to me under GSSoC - ext and Hacktoberfest

Thank You

**Comment by ANSHIKA-26** [comment]
not needed
