### ISSUE TITLE
cursor modification

### ISSUE THREAD

**Issue by abhi200446** [ANSHIKA-26/WordWise#647]
i want to change the cursor style in website there we are using a normal cursor I added screenshots.if you don't like the cursor style which I chosen I will modify according to your wish please give label hacktoberfest and gssoc ext
from
https://github.com/user-attachments/assets/bafb93a0-f2e7-42e7-ae12-9dc073f712df
to
![image](https://github.com/user-attachments/assets/29f60a72-9c0d-44a5-a1b3-4bc7b66ab8fd)

**Comment by abhi200446** [comment]
should i proceed with the work @ https://github.com/ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
no , this seems a little off , any other styles ?

**Comment by abhi200446** [comment]
this cursor visibles if not used should I proceed with this @ANSHIKA-26
https://github.com/user-attachments/assets/bc6d841a-b46a-458a-90e7-3be78a21081a

**Comment by ANSHIKA-26** [comment]
honestly , i dont like it , i prefer a plain cursor instead , sorry , kindly open some other issue !

**Comment by abhi200446** [comment]
If you have any other project-related ideas, please assign them to me  @ANSHIKA-26.
