### ISSUE TITLE
BUG: Fixing Footer

### ISSUE THREAD

**Issue by Abhi9shinde** [ANSHIKA-26/WordWise#649]
**Describe the bug**
At the end of the page, there is one text stating "this script is to display year...."
I can fix it

![image](https://github.com/user-attachments/assets/08c3002e-b20c-40c6-8831-2546e722853d)

**Expected behavior**
Year and copyright symbol should be added

**Comment by ANSHIKA-26** [comment]
while you are doing this , also remove  the text "designed by anshika" , thanks !

**Comment by Abhi9shinde** [comment]
Ok maam

**Comment by Abhi9shinde** [comment]
Should I add the same footer to the Contact Us page, cause it doesn't have one?

**Comment by Abhi9shinde** [comment]
@ANSHIKA-26  Can you please tell whether I should add the footer or else make PR, I have completed my assigned task
