### ISSUE TITLE
Better UIUX for Blog Card on Landing Page

### ISSUE THREAD

**Issue by RushikeshGhodke** [ANSHIKA-26/WordWise#660]
**Is your feature request related to a problem? Please describe.**
My feature is related to the Experience.
Ex. When we land on WordWise the blog post is not effective. (the picture and the image are away from each other).

**Describe the solution you'd like**
The BlogCard should look like a Card, it should developed as per the UIUX Standards and reader psychology.

**Describe alternatives you've considered**
I am going to redesign card as it will be more appealing and effective.
(I will group the image and title together and make it look proffesional.)

**Additional context**
Current Design:
![image](https://github.com/user-attachments/assets/6c24fc6d-1d63-42c4-9a2f-a641e15ebd6c)

**Comment by RushikeshGhodke** [comment]
@ANSHIKA-26 I checked all Open Issues and dont find anyone who working on this.
If no one is working on this issue please assign to me.

**Comment by ANSHIKA-26** [comment]
what changes do you wish to do

**Comment by RushikeshGhodke** [comment]
![image](https://github.com/user-attachments/assets/e0f1bb8e-36e7-4090-a954-de8d0cef2805)

I want to change the Card Design, something I the photo. If you have any suggestion I can add/modify it.

**Comment by ANSHIKA-26** [comment]
its pretty same to what we have right now , any other design you have in mind ?

**Comment by ANSHIKA-26** [comment]
i am honestly okay with the current card design and hence dont have any suggestions , if you have something creative in mind then kindly explain

**Comment by RushikeshGhodke** [comment]
Previously I designed irablogging.com where I used the design. We can use something like that.
![image](https://github.com/user-attachments/assets/ea125d75-24c8-46ab-812f-5619ee375e3f)
If you have any suggestion or okay with the current card design I will work on some different issue.

**Comment by ANSHIKA-26** [comment]
this is nice , go ahead with it
