### ISSUE TITLE
In the phone number box digits are exceeds from 12 digits

### ISSUE THREAD

**Issue by Mayanksaininh** [ANSHIKA-26/WordWise#661]
**Describe the bug**
A clear and concise description of what the bug is. In the phone number box the digits are exceeds from 12 digits it should not be exceeds from 12 digits including country code. 

**To Reproduce**
1. Go to '.The website..' 
2. Click on '.Contact us ...'
3. Scroll down to 'Phone number box....'

**Expected behavior**
A clear and concise description of what you expected to happen. In the phone number box there should be limitation up to 12 digits, after including the country code, after solving this maintainer have the proper report of registered blogger on the website. 

**Screenshots**

![Screenshot (8)](https://github.com/user-attachments/assets/dceb7158-857b-40f2-b22b-708f5b7dbdfb)

**Additional context**

**Comment by hiteashgupta1** [comment]
#721 pr already made

**Comment by AshishVerma10** [comment]
Please assign this issue to me.

**Comment by Mayanksaininh** [comment]
@ANSHIKA-26 
I generate PR #1061 regarding this issue please review it.
This issue was assign to me.

**Comment by Mayanksaininh** [comment]
@hiteashgupta1 
I generate PR https://github.com/ANSHIKA-26/WordWise/pull/1061 regarding this issue please review it.
This issue was assign to me.
