### ISSUE TITLE
Website is not responsive for all screen

### ISSUE THREAD

**Issue by Mayanksaininh** [ANSHIKA-26/WordWise#663]
**Describe the bug**
A clear and concise description of what the bug is. Website is not responsive for all type of screens.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. Website should be responsive for screen phone, tab, pc etc.

**Screenshots**
![Screenshot (9)](https://github.com/user-attachments/assets/7d7a1b49-b54b-4d06-97aa-4a6c9ed9a5fe)

**Additional context**

**Comment by Mayanksaininh** [comment]
Please assign this issue to me.

**Comment by ANSHIKA-26** [comment]
it is responsive !
