### ISSUE TITLE
making about page

### ISSUE THREAD

**Issue by 1ShahidBashir** [ANSHIKA-26/WordWise#674]
@ANSHIKA-26 can you please check this out. The index and about page are the same, so this project basically lacks an about page
here is index page
![image](https://github.com/user-attachments/assets/2a1f678d-3695-4c3b-84ef-8de4e51f3feb)
and here is about page
![image](https://github.com/user-attachments/assets/0d03823e-e6b2-405f-8316-6ca6bd791479)

**Comment by Aditi2k5** [comment]
@ANSHIKA-26 Hi could i be assigned to this issue as well

**Comment by ANSHIKA-26** [comment]
@1ShahidBashir u need help ? @Aditi2k5 wants to

**Comment by NK-Works** [comment]
Been 2 days if u wanna assign someone else...
U can sign me

**Comment by Aditi2k5** [comment]
Hey hi, it's been some time but it's not been solved yet so could I be
assigned to it if possible?

**Comment by ANSHIKA-26** [comment]
@1ShahidBashir ?

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..

**Comment by Aditi2k5** [comment]
Hey hi, if possible could you assign this issue if there's no response as
others are coming and asking about this now

**Comment by ANSHIKA-26** [comment]
due to lack of response from @1ShahidBashir  and first come first serve policy  @Aditi2k5 is being assigned this issue
