### ISSUE TITLE
Improve the navbar according to theme

### ISSUE THREAD

**Issue by harshitjain476493** [ANSHIKA-26/WordWise#677]
**Title:** Improve Navbar Design to Align with website Theme

**Description:**

The current navbar on the WordWise website serves its purpose but could be better aligned with the overall theme of the website. We're looking for improvements that make the navbar more visually appealing, functional, and consistent with WordWise’s mission of enhancing vocabulary and language skills.

**Timeline:**
I would complete it in 2 days.

Please assign this task to me.

**Thankyou!!**

**Comment by harshitjain476493** [comment]
Open this issue as i want makes changes and make better improvements

**Comment by ANSHIKA-26** [comment]
#580 already there
