### ISSUE TITLE
Missing Hover effect and Improper alignment of paragraph of Image

### ISSUE THREAD

**Issue by Deepak0yadav** [ANSHIKA-26/WordWise#679]
1.Paragraph and image is not having in spacing looking in Improper format

![Screenshot 2024-10-10 033159](https://github.com/user-attachments/assets/e38c0f57-f707-4aaa-8759-eb3f6d623aa4)

2.Hover effect is missing in send button on get in touch

https://github.com/user-attachments/assets/1f175ab1-5074-4134-bf4e-77780ce8d679

**Comment by Deepak0yadav** [comment]
Why closed this issue

**Comment by ANSHIKA-26** [comment]
just remove hover effect from image , align the page neatly , thats all , do not implement any extra features , its okay if it looks simple !

**Comment by Deepak0yadav** [comment]
@ANSHIKA-26 ok

**Comment by Deepak0yadav** [comment]
> @ANSHIKA-26 ok
