### ISSUE TITLE
Some issues in Blog Page!

### ISSUE THREAD

**Issue by isnehamondal** [ANSHIKA-26/WordWise#682]
Hello @ANSHIKA-26,

This is Sneha, a contributor in GSSoC and also a  part of hacktoberfest.

**feature request**
1) In the blog page, neither the navbar is fixed nor there is any scroll back to top button, so there there is no way going back to other pages quickly. 
2) The comment section can be made better by adding more css features.
![2](https://github.com/user-attachments/assets/25d907f8-5e1c-4492-b3f2-7c2ad47b2ae1)

**The solution**
1) I would like to add a scroll back to top button to quickly move to top from the end of the page.
2) Set the navbar fixed to move to other pages.
3) Enhance the comment section to make it more readable and beautiful.

I would like to work on this. Please assign this task to me and add the labels(gssoc-ext, hacktoberfest-accepted, level1/2/3).

Thank you!

**Comment by ANSHIKA-26** [comment]
all the 3 features you have listed are raised as individual issues
