### ISSUE TITLE
ADD Singup/Signin with Google

### ISSUE THREAD

**Issue by haseebzaki-07** [ANSHIKA-26/WordWise#690]
I want to implement signup/signin functionality with google.

**Comment by haseebzaki-07** [comment]
hey @ANSHIKA-26 I searched the issues and didn't find any similar one.Please open this issue as I want to work on it

**Comment by ANSHIKA-26** [comment]
its already present in website

**Comment by haseebzaki-07** [comment]
@ANSHIKA-26 But it is not working as expected.

Clicking on the google signup/signin button does nothing . Ideally it should redirect to google auth provider and the user should see his accounts to login
