### ISSUE TITLE
IMPROVEMENT IN THE UI OF THE CONTACT US SECTION AND THE NEWSLETTER SECTION

### ISSUE THREAD

**Issue by eshitatalukdar08** [ANSHIKA-26/WordWise#698]
Hello @ANSHIKA-26,

I noticed that the UI of the Contact Us section can be improved significantly. Some of the adjustments include:
(i) Improving the spacing and border of the boxes.
(ii) Making adjustments to the border radius.
(iii) Trying out more contrasting colors as a background to give a bold look.
(iv) Improving the look of the send button.
(v) Decreasing the width of the button.
(vi) Aligning the text within the Contact Us form.
![Screenshot 2024-10-10 053640](https://github.com/user-attachments/assets/7d9a4284-ddde-403c-b5c7-fe2595aa37c0)

Additionally, the UI in the newsletter section can be improved. Some ways to achieve this include:
(i) Decreasing the width of the newsletter card.
(ii) Enhancing the submit button with better border radius, color, etc.
(iii) Proper spacing between the elements is required.
(iv) Also, altering the border radius and border of the email box will enhance the overall look.
Also aligning the logo is required.
Please assign me to this task. Thank you and have a nice day.!
[Screenshot 2024-10-10 045502](https://github.com/user-attachments/assets/fcda3a70-52b0-43f3-ae9e-73eff36a3a82)

**Comment by eshitatalukdar08** [comment]
Hello @ANSHIKA-26 please assign me to this task.

**Comment by eshitatalukdar08** [comment]
Sure, Thank you!

**Comment by anshguptasince2004** [comment]
Hey there,
As I can see, there seems to be a room of improvement in the header section, the scaling and box shadow design is good but I would like to make it better with my designing skills. 
The box shadow colors can be adjusted, with better scaling animation. The nav bar needs to be optimised and should also change colors with dark mode. Issue should be reopened for an update.
Also, there are some minor things on the homepage that can be improved. I would love to be assigned for this issue as a part of Gssoc-24 and Hacktober Fest.

**Comment by eshitatalukdar08** [comment]
Hello @ANSHIKA-26 will it be a problem if I take 2 days to complete the task due to my health reasons?

**Comment by ANSHIKA-26** [comment]
nope , take care , just make sure to check that someone isnt working on this issue

**Comment by eshitatalukdar08** [comment]
Thank you

**Comment by eshitatalukdar08** [comment]
@ANSHIKA-26, please let me complete this task. As I had told you, due to my health conditions, I might need sometime. My work is done; please let me complete this task.

**Comment by eshitatalukdar08** [comment]
@ANSHIKA-26  and @hiteashgupta1 As already most of the work is done please do not close this now. I request you to please reopen it. I will definitely try to complete it by tomorrow.

**Comment by eshitatalukdar08** [comment]
@ANSHIKA-26 I have made the changes and created a pull request. Please merge it. Also, I cannot see the level 2 label you assigned me earlier. Please look into this matter. Thank you and have a nice day!

**Comment by ANSHIKA-26** [comment]
sure
