### ISSUE TITLE
Misalignment of Buttons in Navbar

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#704]
![Screenshot 2024-10-10 190936](https://github.com/user-attachments/assets/05cba19d-2b0a-44be-a3e6-1fbf53ec9d03)

The "Home", "Leading Blog", "Start Writing", "Categories", "About", "Contact Us" & "Give Feedback" buttons in the navbar of the repository's UI is not aligned properly, which doesn't looking good. The buttons should maintain the same alignment like  "WordWise" website logo alignment . 

I want to align the buttons properly in the center.   @ANSHIKA-26  please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 what happen ??

**Comment by ANSHIKA-26** [comment]
pr #692 covers this

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 is it merged ?? Because the alignment problem is still not solved on the website.. please check

![Screenshot 2024-10-10 202803](https://github.com/user-attachments/assets/10f9da19-a8b9-45cc-adf0-38002d2a950a)
