### ISSUE TITLE
Enhance Login and Signup Form Overlay with Cross Button for Closure and Center Alignment

### ISSUE THREAD

**Issue by rishika105** [ANSHIKA-26/WordWise#711]
Description: The current login and signup form overlays lack essential features for usability and aesthetics. They need the following adjustments:

To Reproduce
1. Navigate to the login or signup section.
2. Click on the login or signup button to open the respective form.
3. Note that there is no cross button to close the form.
4. Ensure that the form is not centered on the page.

Expected behavior
- Each form (login and signup) should include a cross button to close it.
- The forms should be centered on the page for improved accessibility and aesthetic appeal.

Screenshots
![Login Form](https://github.com/user-attachments/assets/fb042f8b-e004-4f7e-969d-b25c1aa8001b)

Additional Context
Both the login and signup form overlays need enhancements. Adding a cross button for closure and centering the forms on the page will enhance user experience and visual consistency.

Please assign me this issue.

**Comment by rishika105** [comment]
There is no existing issue specifically addressing the addition of a cross button for closure on the login and signup forms. The current issues listed focus on different aspects like UI/UX enhancements and login signup designs and their alignment also. But this issue also pertains specifically to improving  user experience with a cross button and centered alignment for the login and signup forms.

**Comment by rishika105** [comment]
Kindly assign me this.

**Comment by ANSHIKA-26** [comment]
hey , we already have cross button on the homepage sign in , since people are already working on Ui , this is a part of UI and hence will be fixed by them , kindly ask if they need any help !

**Comment by ANSHIKA-26** [comment]
i cannot assign this issue to you , it will cause a lot of conflicts in future
