### ISSUE TITLE
ADD SEARCH NAV BAR AND MAKE MARGIN UNDER THE HOME NAV BAR

### ISSUE THREAD

**Issue by Shivasingh15** [ANSHIKA-26/WordWise#727]
HELLO,
  According to me we have to ADD SEARCH NAV BAR AND  MARGIN LINE UNDER THE HOME NAV BAR .
so, please assign me .

**Comment by Shivasingh15** [comment]
please reopend  my issue it is different from another one and my idea is unique

**Comment by ANSHIKA-26** [comment]
navbar fixed
