### ISSUE TITLE
Logo Does Not Redirect to Home Page

### ISSUE THREAD

**Issue by JomanaMahmoud** [ANSHIKA-26/WordWise#728]
**Describe the bug**
The logo on the website does not redirect to the home page when clicked. Typically, clicking on a website’s logo should lead the user back to the homepage, but this feature is missing or not functioning properly on this site.

**To Reproduce**
1. Go to any page other than the home page.
2. Click on the logo in the header.
3. Observe that the logo does not redirect to the homepage as expected.

**Expected behavior**
Clicking the logo should redirect the user to the homepage from any other page on the website.

**Screenshots**

https://github.com/user-attachments/assets/33ad2207-c169-4e0b-98bc-7914d857e61c

**Additional context**
I would like to fix this issue to improve the user experience. Please assign this issue to me, and add the labels: `hacktoberfest-accepted`, `gssoc-ext`. Thank you!

**Comment by JomanaMahmoud** [comment]
there is only an issue for the changing the logo it doesn't mention that it will fix this bug.

**Comment by jvkousthub** [comment]
@ANSHIKA-26 I can do that logo-->home page, please assign me
