### ISSUE TITLE
Add Logo to Navigation Bar

### ISSUE THREAD

**Issue by aparna-44** [ANSHIKA-26/WordWise#743]
I propose adding a logo to the navigation bar of the WordWise website. This enhancement can improve brand recognition and create a more professional appearance.
The logo could be placed on the left side of the navbar to ensure it is visible and does not disrupt the navigation links.
Looking forward to your feedback!
@ANSHIKA-26 plz assign me this issue, i really want to work on it

**Comment by ANSHIKA-26** [comment]
Thank you for offering to contribute by designing a logo for the project! We really appreciate your willingness to help. At the moment, we already have a design direction in place and do not have plans to change or introduce a new logo. However, we welcome any other suggestions or contributions that align with our current needs and vision for the project
