### ISSUE TITLE
The login/signup popup is not the same across all tabs

### ISSUE THREAD

**Issue by Iampratyush004** [ANSHIKA-26/WordWise#746]
**Is your feature request related to a problem? Please describe.**
It becomes very bad for the site , of the features of home tab does not get reflected across all tabs. Especially when the user is on some other tab apart from home and would like to use login/signup page.

**Describe the solution you'd like**
I have added the same type of feature for login/signup across all the tabs

pls add expected tags : gssoc-extd, hactoberfest accepted and level 2

![Screenshot 2024-10-11 015801](https://github.com/user-attachments/assets/b4d4707d-1ed7-4216-bc97-15c9847698d1)
![Screenshot 2024-10-11 015828](https://github.com/user-attachments/assets/7b91640d-a06c-4ce0-9562-064dce6666af)
![Screenshot 2024-10-11 015909](https://github.com/user-attachments/assets/6dcd8975-b6a2-4329-a624-66d8d921bf45)

**Comment by Iampratyush004** [comment]
@ANSHIKA-26 ma'am this issue is unique , the bot is mistaken . please consider my request and kindly reopen the issue and assign me to work upon it

**Comment by Iampratyush004** [comment]
hello @ANSHIKA-26 

I would appreciate understanding the reason for this action.
Kindly acknowledge

**Comment by ANSHIKA-26** [comment]
#750
