### ISSUE TITLE
🐞 Bug: Misaligned Login and Sign Up Popups on Pages Other than Homepage

### ISSUE THREAD

**Issue by Rahul-AkaVector** [ANSHIKA-26/WordWise#750]
### Description:
The login and sign-up popup windows are misaligned on all pages except the homepage. On other screens, the popups appear at the very top, cutting off the cancel button, which makes it difficult to close. However, on the homepage, the popups are properly centered. I would like to fix this issue by ensuring the popups are consistently centered across all pages, making the cancel button fully visible.

### Screenshot/ Video:

https://github.com/user-attachments/assets/ccaabbd8-1a65-4d1b-8b3c-bac705add330

### Steps to Reproduce:
1. Navigate to any page except the homepage.
2. Open the login or sign-up popup.
3. Observe the alignment issue at the top of the screen.
4. Compare the popup alignment on the homepage to see the correct position.

### Expected Behavior:
The login and sign-up popups should be consistently centered across all pages, with the cancel button fully visible.

### Actual Behavior:
The popups are misaligned at the top of the screen, cropping the cancel button on all pages except the homepage.

### Proposed Solution:
Adjust the positioning of the login and sign-up popups to be centered on all pages.

@ANSHIKA-26 

### Labels:
- Gssoc
- Hacktoberfest
- Contributor
- Level 2

**Comment by Iampratyush004** [comment]
@ANSHIKA-26  kindly assign me to this task too. we could work together
thanks
