### ISSUE TITLE
Lag in the photo slider

### ISSUE THREAD

**Issue by Arveti-likhitha** [ANSHIKA-26/WordWise#756]
**Is your feature request related to a problem? Please describe.**
The photos slide very slowly and there are no arrow buttons for navigating to the next or previous photos. 

**Describe the solution you'd like**
I would like to make changes by adding the arrow buttons for easy navigation and increase the speed of the phot sliders.

![Screenshot 2024-10-11 105350](https://github.com/user-attachments/assets/8f0ddc8b-c777-4f17-a627-11b5724ad70a)

@ANSHIKA-26 please assign this to me and include the labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext

**Comment by Arveti-likhitha** [comment]
I have checked through all the issues and I did not find any similar issue opened. Somebody did make changes to the same section but they are different from the issue I have opened.

Could you assign it to me?

**Comment by ANSHIKA-26** [comment]
its not a lag , its timed , and its good , we do not wish to change it
