### ISSUE TITLE
[bug]: Password Visibility Toggle Not Functioning Correctly for SignIn and SignUp pages

### ISSUE THREAD

**Issue by faiz66388** [ANSHIKA-26/WordWise#758]
Description:
The password visibility feature on the SignIn and SignUp pages is not functioning as expected. When the eye icon is open, it should display the password, and when the eye icon is closed, it should hide the password. Currently, the behavior is reversed, causing confusion for users.

Steps to Reproduce:
Navigate to the SignIn or SignUp page.
Enter a password into the password input field.
Click on the eye icon to toggle password visibility.
Expected Behavior:
When the eye icon is open, the password should be visible in plain text. When the eye icon is closed, the password should be hidden and displayed as dots or asterisks.

Actual Behavior:
Currently, the eye icon being open hides the password, while the eye icon being closed shows the password in plain text.

Screenshots/Logs:
![Screenshot 2024-10-11 123221](https://github.com/user-attachments/assets/5128ad3c-96de-4d06-9109-688e46e7f2c7)

**Comment by faiz66388** [comment]
Could you please assign the level label?

**Comment by BhavikaPachauri** [comment]
could you assign me
