### ISSUE TITLE
Enhance the UI of the footer section

### ISSUE THREAD

**Issue by T-Fathima** [ANSHIKA-26/WordWise#765]
**What documentation needs to be updated?**  
The design and functionality of the footer section of the website.

**Describe the changes needed**  
- Revamp the layout for a more modern and visually appealing design.  
- Ensure accessibility with proper contrast and font sizes for readability.  
- Visually enhance the styling of footer by making it more visually interactive. 
- Ensure the footer is fully responsive for all screen sizes.

I would like to work on this issue.
@ANSHIKA-26 Please assign it to me under gssoc-ext and hacktoberfest along with levels.
**Additional context**  
Enhancing the footer will improve user navigation, aesthetic appeal, and accessibility of important information.
![image](https://github.com/user-attachments/assets/eb5af833-1c58-408e-add5-de72808921cb)

**Comment by T-Fathima** [comment]
@ANSHIKA-26 Can u please assign it to me and add levels so that i will start working on it.

**Comment by Suvadip-sana** [comment]
@ANSHIKA-26 
Could you please assign me this ISSUE?
I am able to make this footer like this ->
![image](https://github.com/user-attachments/assets/61affc16-0d91-488d-8c1f-86ba1c4ccc41)

Which is more visually appealing, more stylish, more modern.   Which has also cool hover effect.

**Comment by satyamra1** [comment]
Hi , I came across this issue  and found it aligns with my skills and interest. I have experience In UI development. I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.
This is how footer will look like , this i my own personal design.
![footer](https://github.com/user-attachments/assets/babd31d3-3409-4e99-b412-29fb12a9c3d2)

**Comment by PulkitShubham** [comment]
@ANSHIKA-26 Please Assign this issue to me .......i would like to work on it

**Comment by hiteashgupta1** [comment]
Anyone working on this

**Comment by ANSHIKA-26** [comment]
closing issue due to lack of response
