### ISSUE TITLE
Enhancing FAQ styling

### ISSUE THREAD

**Issue by jvkousthub** [ANSHIKA-26/WordWise#766]
**Is your feature request related to a problem? Please describe.**
It is just an enhancement issue

**Describe the solution you'd like**
on hover of particular question the answer will appear with smooth transition which prevents from clicking 

**Describe alternatives you've considered**

**Additional context**

**Comment by jvkousthub** [comment]
@ANSHIKA-26 I would like to work on this issue 
I am a GSSSoC and Hacktoberfest contributor

**Comment by jvkousthub** [comment]
@ANSHIKA-26 reopen the issue

**Comment by ANSHIKA-26** [comment]
Thank you for your suggestion regarding the hover effect on the FAQ section. After careful consideration, we've decided not to implement this feature. The hover effect seems to introduce unnecessary complexity and interferes with the intended clean and simple design of the FAQ. We aim to keep the user interface straightforward, and this change doesn't align with our vision for the user experience.

We appreciate your input and encourage you to submit any other ideas you think could enhance the project!
