### ISSUE TITLE
I want to add a "Rate Us" Functionality for this web app (star rating)

### ISSUE THREAD

**Issue by Suvadip-sana** [ANSHIKA-26/WordWise#768]
**Is your feature request related to a problem? Please describe.**
The modern website have a "Rate Us" feature. Which is bassically a 1 to 5 star and a comment input based rating system. Thow it has now backend, so for now i built the functionalty of frontend. It only display the grettings after submit the rating.  

**Describe the solution you'd like**
This functionality should be there because it help to developer to improve the UI, UX accordingly.
I attached it in Footer.

**Additional context**
I f you assign me this task i made it like this ---> 

https://github.com/user-attachments/assets/58b3f811-600e-4520-a545-4512ae934668

Please assign me this issue I want to work on it

**NOTE**
If you assgn me this task pleasse add the all necessary tags along with *hacktoberfest-accepted*

**Comment by hiteashgupta1** [comment]
#771
