### ISSUE TITLE
A Chatbot 

### ISSUE THREAD

**Issue by aditya07389** [ANSHIKA-26/WordWise#769]
Hey @ANSHIKA-26  I would like to add to add a chatbot to your website 

A chatbot could enhance user experience by providing instant assistance with site navigation, answering FAQs, helping users with login or signup processes, and guiding them on how to write and publish blog posts. It could also recommend relevant blog content based on user preferences, improving engagement and interaction with the platform.

I will try my best to implement this 

you can assign this to me under gssoc extd and hacktoberfest , Thankyou !

**Comment by aditya07389** [comment]
I did not see a similar issue @ANSHIKA-26  ,Can you pls confirm

**Comment by ANSHIKA-26** [comment]
PR already made
