### ISSUE TITLE
There should be star based Rate Us Functionality

### ISSUE THREAD

**Issue by Suvadip-sana** [ANSHIKA-26/WordWise#771]
1) The modern website have a Rate Us feature. Which is bassically a 1 to 5 star and a comment input based rating system. Though it has now backend, so for now i built the functionalty of frontend. It only display the grettings after submit the rating at the center of the screen.

2) This functionality should be there because it help to developer to improve the UI, UX accordingly.
I attached it in Footer.

3) Additional context
I f you assign me this task i made it like this --->

https://github.com/user-attachments/assets/bc93b1dc-4410-4bb3-9b37-8222277384cd

**Comment by PulkitShubham** [comment]
@ANSHIKA-26 Please assign this task to me.......as i see the task is still not completed

**Comment by Suvadip-sana** [comment]
@PulkitShubham 
It's on going

**Comment by PulkitShubham** [comment]
Okay no issues

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/0b72165b-b356-46d8-b439-2da7da7d71f0

@ANSHIKA-26 
@hiteashgupta1 

It's ready. Give me atleast `label-2`.  It's take lot more time and effort. Because I built it using vanila HTML, CSS, JS.
Please considerd this. I made a PR.
