### ISSUE TITLE
Feat : I want to add google signup in this project

### ISSUE THREAD

**Issue by Mohitbagul** [ANSHIKA-26/WordWise#776]
Google signup/signin
You want to implement Google Sign-In for both sign-up and login functionality, allowing users to authenticate with their Google accounts.

The output will have Google button from which he/she can sign in using the already logged in Google account.

The picture will look like
![Screenshot 2024-10-11 164222](https://github.com/user-attachments/assets/d26b08ee-3178-442a-9fac-f9b20d72a38a)

**Comment by supreetkaursareen** [comment]
@ANSHIKA-26 can you please assign this task to me?

**Comment by ANSHIKA-26** [comment]
closing due to lack of response
