### ISSUE TITLE
Add chatbot to website

### ISSUE THREAD

**Issue by jvkousthub** [ANSHIKA-26/WordWise#781]
**Is your feature request related to a problem? Please describe.**
It would be better if a chatbot is added to the site

**Describe the solution you'd like**
create a chatbot and add it to the site

**Describe alternatives you've considered**

**Additional context**

**Comment by jvkousthub** [comment]
@ANSHIKA-26 i would like to work on this issue
reopen it

**Comment by ANSHIKA-26** [comment]
pr #596 is there
