### ISSUE TITLE
[BUG]:The Send Button in both of the forms (Contact us and Feedback)is not hovering

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#783]
**Describe the bug**
The Send Button in the Contact Us and Feedback forms are not hovering.

**To Reproduce**
1. Go to '.Contact Us/Feedback'
2. See that the send button in both are not hovering.

**Expected behavior**
The Send button in both forms must be hovering for better UI experience for users.

**Screenshots**

https://github.com/user-attachments/assets/b125c516-66e9-4cb3-84ee-8875eaf90840

**Additional context**
Please assign this issue to me under level1, I'm eager to work on it to resolve it as soon as possible.

**Comment by satyamra1** [comment]
Hi , I came across this issue  and found it aligns with my skills and interest.  Please assign it to me so I can start working on it? Looking forward to contributing and adding value to the project.
