### ISSUE TITLE
Enhance About Us section in Start Writing page so that font and icons will be properly visible in Dark mode.

### ISSUE THREAD

**Issue by Deepika14145** [ANSHIKA-26/WordWise#787]
**Describe the bug**
The font color in the About Us section does not match Dark mode.
Along with social media, icons are not properly visible in Dark mode.

**To Reproduce**
I will modify the font color to ensure the text is readable in dark mode and also adjust the color of icons accordingly.

**Benefits**
The page will look interactive in Dark mode.

**Screenshots**
![Screenshot 2024-10-11 183133](https://github.com/user-attachments/assets/68013b13-7137-407a-893e-955cf282be7d)

**Additional context**
Add the labels:
Gssoc-extd. | hacktoberfest-accepted | levels as per your convenience.

Please assign me this task so that I will make these changes.

**Comment by MD-IRFAN-RAJ** [comment]
Please Assign me this issue .

**Comment by ANSHIKA-26** [comment]
they are already visible , its WHITE
