### ISSUE TITLE
[Feat] Adding a scroll progress bar on the home tab

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#788]
The screen progress bar on the home tab will allow the user to see how much he has already scrolled through and will also enhance the UI of the webpage.
Please assign this to me under level 2

**Comment by ANSHIKA-26** [comment]
hey @Arghya-Chakraborty0812 we tried adding a progress bar , it didnt look good on the website  , so we dont want it , thanks !
