### ISSUE TITLE
Improvement in CSS part and Header

### ISSUE THREAD

**Issue by anshguptasince2004** [ANSHIKA-26/WordWise#789]
Hey there,
As I can see, there seems to be a room of improvement in the header section, the scaling and box shadow design is good but I would like to make it better with my designing skills.
The box shadow colors can be adjusted, with better scaling animation. The nav bar needs to be optimised and should also change colors with dark mode.
Also, there are some minor things on the homepage that can be improved. I would love to be assigned for this issue as a part of Gssoc-24 and Hacktober Fest.

**Comment by anshguptasince2004** [comment]
The box shadow colors can be adjusted, with better scaling animation. The nav bar needs to be optimised and should also change colors with dark mode.

**Comment by anshguptasince2004** [comment]
Hey, @ANSHIKA-26 . I went through the opened issue and I don't think there exists any issue that improves the User-Interface of the website as whole. I would like you to have a look at my stated issue description and assign the same.

**Comment by ANSHIKA-26** [comment]
@anshguptasince2004
