### ISSUE TITLE
Input Validation Issues on 'Sign Up Page'

### ISSUE THREAD

**Issue by Preethii-R** [ANSHIKA-26/WordWise#792]
### **_I have identified a few issues on the "Sign Up" page of the website that could impact user experience and data validation._**

The email input box is not validating the email format properly. It is accepting invalid email addresses such as abc@GMAIL.com, and john123@dhgfgj which should ideally be rejected as per standard email validation practices.

![Screenshot (18)](https://github.com/user-attachments/assets/c46a819e-dffb-4969-8e8e-195e3d51e4e7)

**Comment by hiteashgupta1** [comment]
@Preethii-R are you working on this

**Comment by ANSHIKA-26** [comment]
closing due to lack of reponse
