### ISSUE TITLE
[BUG]: giving pop up of error message while submitting any kind of form AND no reset button anywhere.

### ISSUE THREAD

**Issue by shreyabajaj12** [ANSHIKA-26/WordWise#794]
**Describe the bug**
In Contact us , Feedback and start writing section 
while submitting there is a pop up message saying error instead I want to add a successful message each time you fill the form and submit with a custom error message for each user name , email , text etc...
I would also like to a RESET button so that user can reset the information.

**To Reproduce**
1. Go to feedback or contact us or start writing 
2. Click on submit button
3. See error : an pop up will come showing error

**Expected behavior**
instead there should be a custom successful message each time user submits the form.
also the RESET button to reset the content

**Screenshots**
![Screenshot 2024-10-11 203622](https://github.com/user-attachments/assets/410ed77a-0ced-4821-a5f5-e2850409c715)
![Screenshot 2024-10-11 203443](https://github.com/user-attachments/assets/ce8b78ef-c29f-4cb4-a271-e145566f870a)

**Additional context**

**Comment by FarhanBijapur** [comment]
Hi, could you please assign this issue to me under GSSoC-EXT and Hacktoberfest? I'd love to work on it. Thanks!

**Comment by FarhanBijapur** [comment]
Hi, could you please assign this issue to me under GSSoC-EXT and Hacktoberfest? I'd love to work on it. Thanks!

**Comment by PulkitShubham** [comment]
@ANSHIKA-26 Ma'am kindly assign this issue to me .......I've already added this issue but that was removed by the bot
