### ISSUE TITLE
About Us Page Issue!

### ISSUE THREAD

**Issue by biplab-jha** [ANSHIKA-26/WordWise#798]
**Is your feature request related to a problem? Please describe.**
Absolutely, The about us page is just identical to Home Page but it isn't meant for it!

**Describe the solution you'd like**
I would like to design and redevelop the About us page in a new and better way..

**Describe alternatives you've considered**
A better use of CSS and adding few functionalities meant for About page..

**Additional context**
![Screenshot 2024-10-11 225821](https://github.com/user-attachments/assets/05bc6567-568b-4e0f-a275-68a156d1b445)

**Comment by biplab-jha** [comment]
No, the similar issue does not exists. Nobody is trying to work upon the complete About Page and its contents. I want to work upon it. Please see to it and assign me the task!!

**Comment by ANSHIKA-26** [comment]
#674
