### ISSUE TITLE
Integration of chatbot 

### ISSUE THREAD

**Issue by Antima2004** [ANSHIKA-26/WordWise#800]
**Is your feature request related to a problem? Please describe.**
This PR introduces the integration of a chatbot feature into the application, providing users with real-time assistance and support. The chatbot aims to improve user experience by answering common queries, guiding users through processes, and offering personalized recommendations based on user input.

**Describe the solution you'd like**
Implement a chatbot that can:
Answer FAQs and common user queries.
Guide users through different features and services offered.
Provide personalized responses and recommendations based on user data.
Improve continuously through user feedback and data analysis.

**Describe alternatives you've considered**

Using a predefined set of static responses but determined it wouldn't scale well with user needs.
Implementing third-party chatbot services, but opted for an in-house solution for better customization and data privacy.

**Comment by ANSHIKA-26** [comment]
Thank you for your interest in contributing to the project. However, the chatbot feature is already being worked on in PR #596, and we do not need another implementation at this time.

Please check the open pull requests and issues before starting any work to avoid duplicating efforts. I’ll be closing this issue now. For future contributions, we encourage you to look for areas that haven't been addressed yet and align with the project’s needs
