### ISSUE TITLE
Reponsiveness of Category Page

### ISSUE THREAD

**Issue by 2004vivek** [ANSHIKA-26/WordWise#802]
**Is your feature request related to a problem? Please describe.**
My suggestion is to make category page as responsive it is not at all responsive in screen size lesser than 1024px and also hide the navbar option in smaller size screen so that it would be pleasing to eyes

**Describe the solution you'd like**
I thought of hiding the navbar option in smaller size screen and will add the hamsburger in order to show option and i will also align all the items to it correct position

**Additional context**
![image](https://github.com/user-attachments/assets/7bf92192-9a52-40a0-a0de-5bdfad9caaab)

**Comment by ANSHIKA-26** [comment]
someone is working on the mobile responsiveness for whole website !
