### ISSUE TITLE
popular tags

### ISSUE THREAD

**Issue by AnishSahani** [ANSHIKA-26/WordWise#803]
**Describe the bug**
Popular tags should be aligned one below the another to increase the visibility 

**To Reproduce**
1. Go to WordWise.
3. Scroll down to footer section
4. See error popular tags

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-12 003853](https://github.com/user-attachments/assets/c23c977f-e221-47ba-872d-014f7d7b5952)

**Additional context**

**Comment by AnishSahani** [comment]
Assign the issue to me... So that I can resolve it

**Comment by Nikhilkumar111** [comment]
Hello @ANSHIKA-26 ,
Assign the issue to me, So that I can resolve it.

**Comment by ANSHIKA-26** [comment]
@Nikhilkumar111 ?

**Comment by ANSHIKA-26** [comment]
closing due to not response
