### ISSUE TITLE
✨adding a chatbot✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ANSHIKA-26/WordWise#804]
I want to add a chatbot which will be fine tuned for this website in particular.
@ANSHIKA-26 can you please assign me this task.

**Comment by ANSHIKA-26** [comment]
Thank you for your interest in contributing to the project. However, the chatbot feature is already being worked on in PR #596, and we do not need another implementation at this time.

Please check the open pull requests and issues before starting any work to avoid duplicating efforts. I’ll be closing this issue now. For future contributions, we encourage you to look for areas that haven't been addressed yet and align with the project’s needs
