### ISSUE TITLE
Missing "About Us" Page

### ISSUE THREAD

**Issue by snehhhcodes** [ANSHIKA-26/WordWise#809]
# Description:
The website lacks a functional "About Us" page, which is crucial for providing visitors with information about the website's purpose, mission, and team. This results in a lack of transparency and context for users who may want to learn more about the organization or project.

# Steps to Reproduce:
1.Open the index.html file of the website.
2. Run the website using Live Server.
3. In the navigation menu, click on the "About" link or section.
4. Observe that clicking the link either leads to a blank page, an error, or no content.

# Expected Behavior:
Clicking the "About Us" link should direct users to a section containing relevant details about the website, including its mission, goals, and team.

#Visuals:
[screen-capture (1).webm](https://github.com/user-attachments/assets/e27a42a5-2807-4aa2-87b4-9745b04f3dde)

**Comment by snehhhcodes** [comment]
@ANSHIKA-26 If suitable assign this issue to me

**Comment by ANSHIKA-26** [comment]
#674  exists
