### ISSUE TITLE
🛠️ Fix  : Fix Manual Slider Implementation

### ISSUE THREAD

**Issue by Rahul-AkaVector** [ANSHIKA-26/WordWise#820]
### Description
I have discovered that there is a manual slider implemented in the code, but it does not exist on the website. I would like to contribute to resolving this discrepancy.

### Steps to Reproduce
1. Go to the Home page.
2. Scroll down to the slider section.
3. Observe that the manual slider is missing from the website despite being present in the code.

### Expected Behavior
The manual slider should be visible and functional on the website.

### Actual Behavior
The manual slider exists in the code but is not displayed on the website.

### Screenshot
![{43C7FEC4-9609-4253-BD1A-7FA3E4861857}](https://github.com/user-attachments/assets/489e3f21-6c9c-45db-a53a-fb38e783f867)

### Proposed Solution
[Briefly describe how you plan to solve the issue, if you have any ideas.]

### Labels
- GSSoC
- Hacktoberfest
- Level 3

I kindly request that you add the "Level 3" label, as this is the third issue I am addressing in this repository. Thank you!

**Comment by ANSHIKA-26** [comment]
that is because the current slider works fine and is better , we dont wish to have the manual slider back , sorry , thanks for the suggestion though

**Comment by Rahul-AkaVector** [comment]
Ohkay!
