### ISSUE TITLE
[BUG]:The gmail in the footer is not hovering for any page

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ANSHIKA-26/WordWise#822]
**Describe the bug**
The email-id in the footer section is not hovering for any page

**Expected behavior**
The email-id should hover to create a better UI experience for the user.

**Screenshots**

https://github.com/user-attachments/assets/b540899e-5d66-483c-98fa-07b94ac63df5

**Additional context**
Please assign this issue to me under level1.

**Comment by ANSHIKA-26** [comment]
it doesnt need to hover , its fine as it is
