### ISSUE TITLE
Feature Enhancement: Circular Grid Image Display

### ISSUE THREAD

**Issue by snehhhcodes** [ANSHIKA-26/WordWise#823]
Introduce a circular grid image display feature that offers a fresh and engaging alternative to the traditional image slider, which is widely used across many websites. This layout will present images in a circular format, providing a modern touch that enhances user experience and interaction.

Adding visual for you so that you can check how it can be and how it is right now!!
Right now:
[screen-capture (3).webm](https://github.com/user-attachments/assets/58cd8e8f-3952-45be-b2cf-3581a5a6d001)
After Enhancement
[screen-capture (4).webm](https://github.com/user-attachments/assets/43e71397-395c-4656-b91a-9295944cb9ea)

**Comment by snehhhcodes** [comment]
if suitable assign it to me @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
the current one looks fine
