### ISSUE TITLE
Adding and styling scroll to top button in all pages

### ISSUE THREAD

**Issue by Abankita** [ANSHIKA-26/WordWise#828]
**Is your feature request related to a problem? Please describe.**
The scroll to top button is not present in all the pages. 

**Describe the solution you'd like**
I will add the scroll to top button in all the pages. Additionally I will style them with a hover effect and will add a font awesome arrow up icon for a better user experience.

**Comment by Abankita** [comment]
@ANSHIKA-26 can you please check this issue. It is unique and I will adding styling as well. If you find it suitable, can you please reopen this one and assign it to me?
Thank you!

**Comment by ANSHIKA-26** [comment]
its not unique !
