### ISSUE TITLE
[BUG]: there is no github link option in the footer->connect with us section also no twitter connection in start writing section.

### ISSUE THREAD

**Issue by shreyabajaj12** [ANSHIKA-26/WordWise#830]
**Describe the bug**
There is no where GITHUB option in the footer part -> connect with us.
Also no twitter option the footer section of start writing.

**To Reproduce**
1. Go to start writing section
2. Go to footer
3. Scroll down to footer
4. See error: no github , no twitter in connect us option.

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-12 125424](https://github.com/user-attachments/assets/39b8695b-a579-48c3-98dc-62c486949a0f)

**Additional context**

**Comment by avishek999** [comment]
assign me i'll do it

**Comment by Nikhilkumar111** [comment]
Hello , plz assign to me this issue to resolve it  , I do it quickly .

**Comment by shreyabajaj12** [comment]
@ANSHIKA-26  please assign this issue to me
