### ISSUE TITLE
Optimize Footer Design: Compact Contact Us Form and Newsletter Subscription

### ISSUE THREAD

**Issue by Ayan-Khan79** [ANSHIKA-26/WordWise#834]
I want to make the footer of our website easier to use and look better. To do this, I’ll create a smaller "Contact Us" form that only asks for the most important information. This will help users get in touch without taking up too much space. I’ll also make the "Subscribe to Newsletter" section more compact so it doesn’t crowd the footer. By improving these areas, I aim to create a cleaner and more user-friendly design that encourages visitors to engage with this website.

![image](https://github.com/user-attachments/assets/79c32c83-4876-4c99-9c97-d572e359a2d4)

@ANSHIKA-26 Please assign me this issue under gssoc hacktoberfest and level label.....

**Comment by Nikhilkumar111** [comment]
Hello @ANSHIKA-26 , 
I would like to work on this issue.

**Comment by ANSHIKA-26** [comment]
![image](https://github.com/user-attachments/assets/96b5a25e-13fb-4430-ba7e-67efed277270)
remove this from the footer as well

**Comment by Ayan-Khan79** [comment]
@ANSHIKA-26  The copyright section?

**Comment by ANSHIKA-26** [comment]
nope , just the FAQ button

**Comment by Ayan-Khan79** [comment]
@ANSHIKA-26 the new deployed code doesnt have the FAQ button...
