### ISSUE TITLE
[IMPROVEMENT] Improving contact us page to include validations before form submission

### ISSUE THREAD

**Issue by KGupta2601** [ANSHIKA-26/WordWise#835]
Describe the bug
Missing validations before the submission of contact us form.
The current code is allowing the user to submit the form even if the fields are empty and only the validation is applied for the length of the message. The validations are missing for first name,last name,email and phone number

Expected behavior
Input Validation: Add checks for all fields and email format.
Constants: Introduce a constant for the API URL.
Error Handling: Improved error handling with a dedicated function.
Separation of Concerns: Created separate functions for showing/hiding popups.
Accessibility: Considered accessibility in popup management.

Screenshots
![WhatsApp Image 2024-10-12 at 14 34 52_60d44626](https://github.com/user-attachments/assets/d854b1b0-7640-4c2d-8b3b-91bbceeea3fd)
![WhatsApp Image 2024-10-12 at 14 35 18_2111adea](https://github.com/user-attachments/assets/a6e2c22f-76f7-48e8-b6fc-20ccee7db234)
![WhatsApp Image 2024-10-12 at 14 38 44_6b8dd01a](https://github.com/user-attachments/assets/124a6d82-3d52-4936-922b-e44dc1b3a08a)

@ANSHIKA-26 Please assign me this issue along the labels of hacktoberfest and gssoc extended and level

**Comment by KGupta2601** [comment]
@ANSHIKA-26 My name is not displaying in the assignee. Kindly assign me the issue

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..

**Comment by KGupta2601** [comment]
> you can assign this issue to me..

I have created this issue and the issue is assigned on first come first serve basis so it will be assigned to me

**Comment by KGupta2601** [comment]
@ushmita4 @ANSHIKA-26 Kindly assign this issue to me

**Comment by PulkitShubham** [comment]
@ushmita4 @ANSHIKA-26 Ma'am kindly assign this issue to me.....I would like to work on it...I have already worked upon similar tasks

![image](https://github.com/user-attachments/assets/f7ecf7f0-6353-4121-aba8-808cea4b5f60)
