### ISSUE TITLE
[Feature Request] : Adding Animated Preloader

### ISSUE THREAD

**Issue by AbhijitMotekar99** [ANSHIKA-26/WordWise#836]
**Is your feature request related to a problem? Please describe.**
I often find it frustrating when navigating to pages on the website, as there can be noticeable delays in loading content, especially for larger assets. This leads to uncertainty about whether the page is loading correctly or if there is an issue, causing potential confusion for users. A loading screen without any indication can make the site feel unresponsive or poorly designed.

**Describe the solution you'd like**
I would like to implement an animated preloader that displays while the website is loading its content

## Below one is sample

https://github.com/user-attachments/assets/07dbb438-31ac-4d9e-abfb-a23be09cc22c

**Comment by Nikhilkumar111** [comment]
hello @ANSHIKA-26 ,
I would like to resolve this issue plz assign  to me this issue .
