### ISSUE TITLE
Chatbot feature

### ISSUE THREAD

**Issue by NK-Works** [ANSHIKA-26/WordWise#838]
**Describe the solution you'd like**
I want to implement a chatbot feature...

make sure to add the labels...
thanks:)

**Comment by NK-Works** [comment]
? 
last 5 issues that i have created all have been completed automatically but why i dont see the changes in the website :(

**Comment by ANSHIKA-26** [comment]
> ? last 5 issues that i have created all have been completed automatically but why i dont see the changes in the website :(

sorry? i didnt understand
