### ISSUE TITLE
Footer Fiasco: Misaligned with Navbar in Vibrant Light Mode

### ISSUE THREAD

**Issue by kekubhai** [ANSHIKA-26/WordWise#848]
**Is your feature request related to a problem? Please describe.**  
I'm frustrated when the footer in the light theme doesn't stay aligned with the navbar. The vibrant colors and overall layout feel disrupted, especially when navigating pages. This misalignment makes the UI look inconsistent and impacts the user experience negatively, making the footer appear detached from the rest of the design.

**Describe the solution you'd like**  
I’d like the footer to align perfectly with the navbar in the light theme, maintaining consistent spacing and structure. The dynamic, colorful nature of the theme should be preserved without any visual discrepancies between key elements like the navbar and footer.

**Describe alternatives you've considered**  
I’ve considered removing the footer in light mode, but that would take away from the site's design. Another option could be simplifying the layout, but that would reduce the visual appeal and limit customization.

**Additional context**  
This issue only seems to occur in the light theme. Dark theme behaves as expected. Here's a screenshot highlighting the misalignment between the footer and navbar.

---

Please assign this Issue to Me

**Comment by kekubhai** [comment]
I have thought of this design  to look perfect with the vibe of your website 
![Screenshot 2024-10-11 215353](https://github.com/user-attachments/assets/2d307acb-c494-402a-8132-ab582a4694c2)

**Comment by ANSHIKA-26** [comment]
thanks for your input but i prefer the design that we have right now

**Comment by kekubhai** [comment]
Fine then . No problem
