### ISSUE TITLE
Improve text & image alignments 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ANSHIKA-26/WordWise#851]
![Screenshot 2024-10-12 213750](https://github.com/user-attachments/assets/21b38881-8e75-404b-afd5-f543f690a156)

These texts & images under "Trending Post" are not aligned in middle, if i aligned these in middle, it would make this website look better.

I want to Fixed these issue properly. @ANSHIKA-26  please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 PR I don't think a similar problem already exists. Please check and assign me for this issue.

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1   assign me

**Comment by hiteashgupta1** [comment]
@AK261102 He has first raised issue
Ask him if he needs help

**Comment by Subhajit-2023-44** [comment]
@AK261102 Ooo its okay

**Comment by hiteashgupta1** [comment]
@Subhajit-2023-44 Do I assign him

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 ok

**Comment by Balamurugan-cyber** [comment]
assign me this task sir.

**Comment by AK261102** [comment]
please assign me this issue

**Comment by ANSHIKA-26** [comment]
@Subhajit-2023-44 ?

**Comment by Subhajit-2023-44** [comment]
> @AK261102 He has first raised issue Ask him if he needs help

....

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 ?

wait wait

**Comment by AK261102** [comment]
> please assign me this issue
@Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> > please assign me this issue
> > @Subhajit-2023-44

already done, i just forget to give PR
