### ISSUE TITLE
About Us page Fonts can be well aligned and arranged.

### ISSUE THREAD

**Issue by RohanShrivastava08** [ANSHIKA-26/WordWise#856]
![Screenshot (485)](https://github.com/user-attachments/assets/a26af8e7-14dc-4071-8998-06315047b5a6)

As, the About Us page contents needs to be aligned well and arranged in a well defined way.
Kindly, assign me this, and I will start working onto it !!

**Comment by RohanShrivastava08** [comment]
As, there is no modifications made till now, even if the issue was raised earlier.
So, I want to be assigned this issue and I will finish this issue asap !!

**Comment by ANSHIKA-26** [comment]
ask on the old issue , cannot assign it unless the old assignee says they arent working on it , its first come first serve
