### ISSUE TITLE
Navbar, Back-to-Top Button, and Scrollbar Visible During Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [ANSHIKA-26/WordWise#859]
**Describe the bug**
While the preloader is active, elements like the navbar, back-to-top button, and scrollbar are briefly visible in the background. This causes a flickering effect and compromises the preloader’s purpose, which is to prevent any page content from being shown until loading is complete.

**To Reproduce**
1. Load any page where the preloader is active.
2. Notice that the navbar, back-to-top button, and scrollbar are visible either briefly or throughout the preloader animation.
3. This issue occurs inconsistently across browsers but is especially noticeable on slower connections or when assets take longer to load.

**Expected behavior**
1. Only the preloader should be visible until the loading is complete.
2. The navbar, back-to-top button, and scrollbar should remain hidden until the preloader finishes and the page content is ready.

**Screenshots**
![Screenshot 2024-10-13 001534](https://github.com/user-attachments/assets/461515b6-8a4a-4748-aafc-364369e44235)

**Comment by AsmitaMishra24** [comment]
@ANSHIKA-26, please check this issue

**Comment by ANSHIKA-26** [comment]
work on this after we close animated preloader issue , 2 people working on preloader will cause conflicts
