### ISSUE TITLE
fixing the footer to perfect 

### ISSUE THREAD

**Issue by sahhoArjun097** [ANSHIKA-26/WordWise#86]
i can fix the footer and make the footer responsive the content get overflow .

i can add responsiveness to the footer section and make the section elements to p=be placed in the proper manner if you provide me lvl 3 i will make the footer section elements more attractive and provide animation effect to them and hover property to them and add attractive social icons buttons . 

![image](https://github.com/user-attachments/assets/73075bbc-0fbf-4e85-8e63-27da5e932dc4)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and level  .

**Comment by lakshya-pratap-singh-chauhan** [comment]
i would like to solve this issue  for you , i know how to solve this issue in best possible way.

**Comment by Shailjaa30** [comment]
please assign me this problem
