### ISSUE TITLE
Homepage contents alignment and positioning 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [ANSHIKA-26/WordWise#863]
**Describe the bug**
Misalignment of contents in the homepage which looks odd and doesn't look good 

**To Reproduce**
1. Go to 'Wordwise website'
2. Click on 'inspect'
3. Scroll down to frequency asked section''

**Expected behavior**
Contents should be justified horizontally to be in centred and makes the ui clean.

**Screenshots**
![Screenshot_2024-10-13-00-52-00-21_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/3bd8821a-51d6-45b1-aaa2-a4f97fee338e)

**Additional context**
Enhancing these components would make the ui cleaner and user friendly.

**Comment by Sarthakkashyapp** [comment]
@ANSHIKA-26 The issue is unique as far as I know and needs enhancements 
I would like to reopen this

**Comment by Sarthakkashyapp** [comment]
@ANSHIKA-26 I would like to work on this issue and enhance the overall misalignments.

**Comment by ANSHIKA-26** [comment]
i believe this is the mobile view of the website , kindly fix this after the website has been made responsive , otherwise your PR will merge with responsive PR and cause issues

**Comment by Sarthakkashyapp** [comment]
I don't think it'll effect anything @ANSHIKA-26
