### ISSUE TITLE
The Leading blog page looks cluttered.

### ISSUE THREAD

**Issue by divyansharma001** [ANSHIKA-26/WordWise#871]
The leading blog page looks cluttered and unorganised

1. Go to 'https://anshika-26.github.io/WordWise/'
2. Click on 'Leading blogs'
3. Scroll down to 'Previous post and new post section'
4. Thing are looking messed up here. The comments heading is merged into the previous and next post section. The next and previous section content is also not nicely separated

**Expected behavior**
The comments heading should look clean, bold and different. The next and previous post section should show photo on top and then text in bottom having read more option.

**Screenshots**
![image](https://github.com/user-attachments/assets/9669a50b-156f-47f1-b061-b5c2cf25bee5)

Please assign this to me and add tag for hackoctoberfest-accepted.

**Comment by divyansharma001** [comment]
I feel like the issue is unique. Can you please reopen this?

**Comment by ANSHIKA-26** [comment]
@divyansharma001 any progress ?

**Comment by divyansharma001** [comment]
working in it

**Comment by ANSHIKA-26** [comment]
@divyansharma001 ?

**Comment by ANSHIKA-26** [comment]
closing issue due to lack of response
