### ISSUE TITLE
 Improve spacing between icon and toggle switch

### ISSUE THREAD

**Issue by Nani-avidi** [ANSHIKA-26/WordWise#872]
![Screenshot 2024-10-13 110411](https://github.com/user-attachments/assets/497be0ca-4d54-41d9-b353-9c3606e246de)
I'd like to contribute to improving the UI of the toggle switch component. Currently, the spacing between the icon on the left and the toggle switch itself appears tight. I suggest increasing the horizontal gap between these elements to enhance visual separation and overall balance.

Proposed changes:
1. Increase the horizontal margin or padding between the icon and the toggle switch.
2. Consider aligning the icon vertically with the center of the toggle switch for better visual harmony.

Questions:
1. Is there a specific design system or spacing guidelines I should follow?
2. Are there any accessibility considerations to keep in mind when adjusting the spacing?

I'm happy to work on this issue as part of my GSSoC contribution. Please let me know if you need any additional information or if you'd like me to proceed with creating a pull request for this change.

**Comment by Nani-avidi** [comment]
Can you please assign level label to this issue?

**Comment by ANSHIKA-26** [comment]
Hey, we don't really wish to change the toggle
