### ISSUE TITLE
Improvements in Leading Blog Page

### ISSUE THREAD

**Issue by RushikeshGhodke** [ANSHIKA-26/WordWise#876]
**Is your feature request related to a problem? Please describe.**
Current "https://anshika-26.github.io/WordWise/blog.html#" is not consistent and there are lot of CSS bugs.
Also Some field like Author Info are repeated.
 
**Describe the solution you'd like**
I will Recreate the UIUX from scratch, It will solve the bugs, improve the design which will be responsible for all devices.

**Additional context**
Sceenshot where I faced Inconsistency and I am going to work on:
![Improvements](https://github.com/user-attachments/assets/a9b0b83d-7052-4f51-903d-ea4c99dd46d2)

**Comment by RushikeshGhodke** [comment]
> Thanks for raising this issue! However, we believe a similar issue already exists. Kindly go through all the open issues and ask to be assigned to that issue.If you believe that your issue is unique , feel free to comment and ask for it to be reopened , or you can also start a discussion regarding the same !

@ANSHIKA-26 No one working in this thing.

**Comment by ANSHIKA-26** [comment]
#871 exists
