### ISSUE TITLE
Improving Hover effect of the categories card

### ISSUE THREAD

**Issue by Anamika-garg** [ANSHIKA-26/WordWise#880]
The Hover effects are not looking nice in the categories section card. The problem is :
1. Lack of transition
2. The effect on only image

I will solve these issues

Here is the current issue video reference:

https://github.com/user-attachments/assets/250a74db-dfd0-4643-8e59-9a3267784bc9

**Comment by Anamika-garg** [comment]
The issue for categories card doesn't exist as opened. One that existed has already been closed and i still find that the hover is not really pleasant. However attaching the end result of my changes , if you find it good or would like any modifications, i will generate a PR after you open this issue

https://github.com/user-attachments/assets/4039a266-b34a-4e8f-a92d-ca28b198e6fb

**Comment by ANSHIKA-26** [comment]
this was what we had earlier , the one we have right now is okay too
