### ISSUE TITLE
ADD SEPARATE LOGIN PAGE 🥇 

### ISSUE THREAD

**Issue by isimarjitsingh** [ANSHIKA-26/WordWise#884]
**Is your feature request related to a problem? Please describe.**
The UI of home page and login page always show  standard of your website . as i observed UI of your home page is extremely good  but login section is not suitable because we always need to give separate page to login page like other websites do ex:-netflix,flipkart etc.

**Describe the solution you'd like**
we need to give separate login page to improve user experience

**Describe alternatives you've considered**
i am able to do that work as i also have a model of my login page please assign me this work if you liked this login page :)

**Additional context**
![Screenshot 2024-10-13 012459](https://github.com/user-attachments/assets/b79a4182-b251-4c51-a991-d4a2ffb5dc4e)

![Screenshot 2024-10-13 023459](https://github.com/user-attachments/assets/bff9a002-68b6-4f43-b8f2-d354387af898)

**Comment by ANSHIKA-26** [comment]
#641 is already working on login page , raise this issue after they are done
