### ISSUE TITLE
Responsive Navbar Issue

### ISSUE THREAD

**Issue by Sadab-Hussain** [ANSHIKA-26/WordWise#897]
**Describe the bug**
The navigation bar in the WordWise blog page does not display correctly on mobile devices. The right side of the navbar text is cut off, making some of the menu options partially hidden. This issue occurs when the website is viewed on smaller screens, such as on mobile phones.

**To Reproduce**
Go to the WordWise website on a mobile device or using a responsive design tool in a browser.
Navigate to the home page (e.g., /index.html).
Observe the navigation bar at the top of the page.
Notice that the right side of the navbar text is cut off, particularly the "Home" option.

**Expected behavior**
The navigation bar should fully display all menu options on mobile devices without cutting off any text. The navbar should adjust its layout to fit the screen size, ensuring that all navigation links are clearly visible and accessible.

**Screenshots**

![Screenshot 2024-10-13 144722](https://github.com/user-attachments/assets/4873b11d-fb96-4714-a0ee-4663f3da7085)

**Additional context**
Please assign this issue to me. I would like to fix it And you can checkout from screenshot also.

Thank you@ANSHIKA-26

**Comment by Sadab-Hussain** [comment]
@ANSHIKA-26 please add level Categories(1,2,3) also and assign to me i really want work on it.

**Comment by ANSHIKA-26** [comment]
someone is fixing responsiveness for whole page , ask if they need help
