### ISSUE TITLE
New Logo Suggestions

### ISSUE THREAD

**Issue by parteekxo** [ANSHIKA-26/WordWise#902]
Hey, I am Akashdeep, and i can help with the logo, here are some 
![image](https://github.com/user-attachments/assets/b986df67-be0c-4606-bb13-a1e4ec10dfc1)
![image](https://github.com/user-attachments/assets/65ae6cb1-edc0-4e9f-94a7-61758175bf16)
![image](https://github.com/user-attachments/assets/b846e4ce-98e8-4c11-b40c-880b649d4ea5)
if you want to change please assign me under the gssoc-ext and hacktoberfest label.
Thank You!

**Comment by parteekxo** [comment]
@ANSHIKA-26 which logo is better?

**Comment by ANSHIKA-26** [comment]
we are not open to logo suggestions , sorry
