### ISSUE TITLE
[FEAT]: Creating the Backend routes to create or update the Blogs.

### ISSUE THREAD

**Issue by tejasbenibagde** [ANSHIKA-26/WordWise#905]
**Is your feature request related to a problem?**
Currently we are Putting the images of fake blogs in the frontend that are not even created by the actual users or admins. I want to create the routes for creation or updation of created blogs in the backend so that we will have the real blogs instead of having the dummy ones. 

**Describe the solution you'd like**
I'll add two more routes in the backend specifically for creating and updating the created routes.

**Comment by tejasbenibagde** [comment]
@ANSHIKA-26  please asssign me to this task

**Comment by ANSHIKA-26** [comment]
just an idea , you can link it with start writing page so that every blog written can be shown on the homepage itself , feel free to use react since out backend already has express

**Comment by ANSHIKA-26** [comment]
how do you plan to do it ? @tejasbenibagde

**Comment by tejasbenibagde** [comment]
> how do you plan to do it ? @tejasbenibagde

@ANSHIKA-26 I'll be adding more routes and controllers to the current server. Once that's complete, I'll create detailed documentation explaining the purpose of each route, making it easier for a frontend engineer to integrate them through API connections. If you'd like, I can create a separate issue and pull request for that—let me know if that works for you!

**Comment by tejasbenibagde** [comment]
Hi @ANSHIKA-26,

I’ve started looking into this issue, and I noticed a few things about the project structure that I wanted to bring up.

Folder Organization: It would make things a lot easier if the frontend was in a separate folder like Client or Frontend. Right now, the code is spread out in the root directory, which can make it harder to navigate and work on different parts of the project.

Backend Folder: I see there’s a backend folder, but it doesn’t seem to be doing much. There’s some code for Login and Signup, but it looks like it’s not really functioning as intended. It might need some reworking to get it up and running.

Just wanted to share these observations! Let me know if you'd be okay with me reorganizing and fixing these issues. Looking forward to hearing your thoughts!

**Comment by ANSHIKA-26** [comment]
> Hi @ANSHIKA-26,
> 
> I’ve started looking into this issue, and I noticed a few things about the project structure that I wanted to bring up.
> 
> Folder Organization: It would make things a lot easier if the frontend was in a separate folder like Client or Frontend. Right now, the code is spread out in the root directory, which can make it harder to navigate and work on different parts of the project.
> 
> Backend Folder: I see there’s a backend folder, but it doesn’t seem to be doing much. There’s some code for Login and Signup, but it looks like it’s not really functioning as intended. It might need some reworking to get it up and running.
> 
> Just wanted to share these observations! Let me know if you'd be okay with me reorganizing and fixing these issues. Looking forward to hearing your thoughts!

hey @tejasbenibagde 
I understand the need for fixing all these issues , feel free to raise more issues for them !
I am fine with you reorganizing all of these
