### ISSUE TITLE
refactoring th UI of the about page✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ANSHIKA-26/WordWise#910]
i want to improve the UI of this page.
@ANSHIKA-26 can you please assign me this issue.

<img width="747" alt="Screenshot 2024-10-13 at 10 15 01 PM" src="https://github.com/user-attachments/assets/caaec8ce-1d60-404e-a2b8-7acf560880fb">

**Comment by ANSHIKA-26** [comment]
Issue already exists
