### ISSUE TITLE
Creating a page for Author Info

### ISSUE THREAD

**Issue by rees8** [ANSHIKA-26/WordWise#911]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/user-attachments/assets/ad1b6ad1-6a89-4f03-8533-d82468a62377)
Under the Author profile photo, I see that you've mentioned Author Info. Usually, there's a clickable link which leads to the author's home page (their bio, blogs posted so far, etc.)

**Describe the solution you'd like**

For this sample blog, I would like to create a clickable link for "Author Info" which will lead to the author's home page. With an established backend, we can keep track of the registered users and their pages, but since that is missing, I was thinking of creating a sample standalone HTML file to be displayed for now.

**Comment by rees8** [comment]
@ANSHIKA-26 I think this issue hasn't been mentioned anywhere in the currently opened issues. Kindly double-check the same and assign me this task after re-opening this issue.

**Comment by ANSHIKA-26** [comment]
i dont think we need a separate author page

**Comment by rees8** [comment]
Ok, as you see fit.
