### ISSUE TITLE
[Bug]: Alignment Issue with Card Component

### ISSUE THREAD

**Issue by Shahbaz898414** [ANSHIKA-26/WordWise#912]
**Describe the bug**
The card component in our UI is not aligning properly. The exact nature of the alignment issue is currently unclear, but it's affecting the overall layout and appearance of the page.

**Expected behavior**
The card component should be properly aligned with other elements on the page.

**Screenshots**
![image](https://github.com/user-attachments/assets/bedc2708-51b7-4757-b29f-9fffec7a89e3)

**Actual Result**

The card component is not aligning correctly, resulting in a misaligned layout.

**Comment by Shahbaz898414** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
design changed
