### ISSUE TITLE
Adding a Scrolling down button for easy scrolling

### ISSUE THREAD

**Issue by banasmita24** [ANSHIKA-26/WordWise#915]
**Is your feature request related to a problem? Please describe.**
Challenging to navigate long content-heavy pages, as scrolling can feel overwhelming and imprecise. Users may want to move through the content in a more structured way rather than continuously scrolling.

**Describe the solution you'd like**
I would like to implement a scrolling button that allows users to quickly scroll down each page with a single click. This button should be easily accessible, possibly fixed in a right side of the screen, and could feature smooth scrolling animations for a better user experience.

**Describe alternatives you've considered**
I have considered alternatives like using keyboard shortcuts for scrolling, but this may not be intuitive for all users. Additionally, implementing a scroll-to-top link at the bottom of the page could help, but it doesn't address the need for quick downward navigation.

**Additional context**
This feature would greatly enhance user experience on long pages, making navigation more fluid and user-friendly. It would be beneficial for users who are accessing content on mobile devices as well, where scrolling can be more cumbersome.

I would like to address this feature. 
Please assign this to me under gssoc-ext and hacktoberfest-accepted.
Thank you :)

**Comment by banasmita24** [comment]
There is no similar issues.

**Comment by banasmita24** [comment]
This is not an existing or a similar issue.

**Comment by ANSHIKA-26** [comment]
button not needed
