### ISSUE TITLE
Improve Theme Toggle Button Icons

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ANSHIKA-26/WordWise#921]
Replace the current day and night icons on the theme toggle button with more visually appealing and intuitive icons to enhance user experience and clarity.

![image](https://github.com/user-attachments/assets/0402c431-1346-4bcc-97be-f0377efd4aea)

**Comment by AnushkaChouhan25** [comment]
This issue is not assigned already, this is unique can you please recheck and assign it to me.

**Comment by ANSHIKA-26** [comment]
we dont want any change in toggle button :) thanks
