### ISSUE TITLE
Implement Social Media Sharing Options for Blog Articles

### ISSUE THREAD

**Issue by 13Sharad** [ANSHIKA-26/WordWise#926]
**Is your feature request related to a problem? Please describe.**

Currently, users do not have a convenient way to share blog articles on social media, which limits the exposure of the content. Without easy sharing options, articles may not reach a wider audience, reducing potential traffic to the site.

**Describe the solution you'd like**

I would like to add Social Media Sharing Buttons on each blog post, allowing users to easily share articles on popular platforms such as Twitter, Facebook, and LinkedIn. These buttons would be prominently displayed at the beginning or end of each article.

**Describe alternatives you've considered**

An alternative could be to create a shareable link that users can copy and paste. However, this method is less user-friendly and may discourage sharing compared to direct buttons.

**Additional context**

By implementing this feature, the site can benefit from increased visibility and traffic as users share valuable content with their networks. Additionally, tracking shares could provide insights into which articles resonate most with the audience.

**Comment by ANSHIKA-26** [comment]
we did have this feature , wasnt working out , how do you plan to add it ?

**Comment by Kavish-Paraswar** [comment]
i would like to work on this.

**Comment by ANSHIKA-26** [comment]
closing issue due to lack of response from anyone as to how it can be implemented !
