### ISSUE TITLE
[FEAT] : Wanna ADD Modified UI of Feedback Form

### ISSUE THREAD

**Issue by shivisingh25** [ANSHIKA-26/WordWise#927]
Is your feature request related to a problem? Please describe.
@ANSHIKA-26 , I would like to bring to your attention a small issue I encountered with the navigation functionality on the website. Currently, both the "Contact Us" and "Give Feedback" links in the navigation bar redirect to the same page [https://word-wise-4d50.onrender.com/contact_us.html].

Describe the solution you'd like
I just want to change the UI of form for better user experience and clarity, it would be ideal if each link led to its respective dedicated page, ensuring the proper distinction between contacting support and providing feedback.

Describe alternatives you've considered
Since both the "Contact Us" and "Give Feedback" options currently lead to the same page, it may be more efficient and user-friendly to keep only one of these options in the navigation bar.

Additional context
![Screenshot 2024-10-14 002327](https://github.com/user-attachments/assets/ed9448cd-f6c0-464b-809c-1ffce8d6e496)

**Comment by ANSHIKA-26** [comment]
instead of this , just revamp the feedback form completely ,

**Comment by shivisingh25** [comment]
@ANSHIKA-26 Okay
