### ISSUE TITLE
Adding google map location to the website

### ISSUE THREAD

**Issue by sahithinandikula** [ANSHIKA-26/WordWise#941]
**Is your feature request related to a problem? Please describe.**
the website does not have Google Maps location so that users can know the exact location of WorldWise

**Describe the solution you'd like**
Although location is mentioned on the website adding Google Maps location makes users locate the address even easier and faster 
**Describe alternatives you've considered**
![image](https://github.com/user-attachments/assets/f37acbb7-1e22-45a6-ad26-7b8178763406)
They can be added to the footer section of the website 
It's a great way to enhance user experience!

**Comment by sahithinandikula** [comment]
@ANSHIKA-26 I have seen all the issues and I haven't found any such issues already existing so kindly review and open this issue

**Comment by ANSHIKA-26** [comment]
hey , i dont think this website really needs a google map location service , its a blogging website !
