### ISSUE TITLE
Adding favicon to the website

### ISSUE THREAD

**Issue by sahithinandikula** [ANSHIKA-26/WordWise#943]
**Is your feature request related to a problem? Please describe.**

The website lacks a favicon . Adding a favicon can increase user engagement and Provide a visual representation of your brand in the browser tab, bookmarks, and shortcuts.

**Describe the solution you'd like**

User Experience:

It makes it easier for users to identify and locate your site among multiple open tabs.

Professionalism:

Adds a polished, professional look to your site, enhancing overall credibility.

**Comment by ANSHIKA-26** [comment]
Favicon is there
