### ISSUE TITLE
fix the alignment of about us n all the pages

### ISSUE THREAD

**Issue by Anujyadav0074** [ANSHIKA-26/WordWise#948]
**Describe the bug**
the text  alignment of the content of about us is different in different pages  which should not be the case so i would like tofix this

**To Reproduce**
1. Go to any page 
3. Scroll down to about us 
4. on different pages the alignment is different of the text 

**Expected behavior**
it should look the same on every pages

**Screenshots**
![Screenshot 2024-10-14 181120](https://github.com/user-attachments/assets/9241d877-8938-4087-8ed7-68bd0dd841f5)
![Screenshot 2024-10-14 181150](https://github.com/user-attachments/assets/1038a3ba-54e1-4906-b157-8cfe2e377731)
![Screenshot 2024-10-14 181201](https://github.com/user-attachments/assets/29c98c35-2e50-4257-8c00-7d3ee18673e9)

**Additional context**

**Comment by Anujyadav0074** [comment]
if you could please give it a level 2 because i had to change 14 files it would help me a lot

**Comment by 100nuparmar349** [comment]
//accept

**Comment by Anujyadav0074** [comment]
Brother issue assignment is on the bases of self creation this will be assigned to me

**Comment by Anujyadav0074** [comment]
//accept
