### ISSUE TITLE
Submit blog  button functionality on blog page

### ISSUE THREAD

**Issue by Devanshu1603** [ANSHIKA-26/WordWise#963]
Describe the bug
On clicking submit button in contact us page , text fields are not getting cleared , an an alert showing error is popped out.

Expected behavior
on clicking submit button the text fields should get cleared and an alert must pop out stating that your details has been submitted successfully

**Comment by Devanshu1603** [comment]
@ANSHIKA-26  please assign it to me under gssoc-extended . hactober fest accepted and with appropriate level. Will be happy to contribute.

**Comment by prishsha** [comment]
I would also like to work on this

**Comment by ANSHIKA-26** [comment]
#905 will be doing this now

**Comment by Devanshu1603** [comment]
> #905 will be doing this now

@ANSHIKA-26  Couldn't get your point . why you closed the issue . i should be assigned this issue as i raised this at first.
