### ISSUE TITLE
[Bug]: Make FAQ and Footer Sections Responsive

### ISSUE THREAD

**Issue by saurabh-dev-vns** [ANSHIKA-26/WordWise#972]
**Describe the bug**

1. The footer and FAQ sections are not responsive on smaller screens.
2. The UI of the footer does not look appealing on small screens.
3. 

**Expected behavior**

1. The page should be fully responsive, including the FAQ section and the footer.
2. The FAQ section needs to be made responsive.
3. The footer's UI should be improved and made responsive as well.

**Screenshots**
![Screenshot_20241015-061346](https://github.com/user-attachments/assets/add886aa-ee10-48fe-a4d6-4e842fdb7f88)
![Screenshot_20241015-061354](https://github.com/user-attachments/assets/60782705-5129-471c-8df2-71b25408fb20)

**Comment by saurabh-dev-vns** [comment]
@ANSHIKA-26 , please assign this issue to me.

**Comment by 100nuparmar349** [comment]
@ANSHIKA-26 , assign

**Comment by ANSHIKA-26** [comment]
#806 exists 

I'm closing this issue because it’s a duplicate. The GitHub bot clearly instructed everyone to check for existing issues before raising new ones. Ignoring this is unacceptable and adds unnecessary clutter to the repository. Please pay attention next time
