### ISSUE TITLE
SECURITY FLAW: exposure of sensitive information in the url parameters

### ISSUE THREAD

**Issue by parteekxo** [ANSHIKA-26/WordWise#983]
![image](https://github.com/user-attachments/assets/03bcf285-17e3-4a1e-9d83-375ee7e91a10)

The security flaw visible in the screenshot is the exposure of sensitive information such as a password (psw=demo) and email (email=demo%40gmail.com) in the URL parameters. This is a serious security concern for the following reasons:

    Exposure of Sensitive Data: URL parameters are often logged in browser history, server logs, and analytics tools. Since sensitive data like passwords and emails are included in the URL, they could be exposed to unintended parties or logged in an insecure way.

    Eavesdropping Risks: Even though the connection appears to be secured with HTTPS (as indicated by the lock symbol), sharing sensitive information in the URL can still be risky. For example, if someone shares the URL or it gets copied into logs, others may see the sensitive data.

    Potential CSRF Vulnerabilities: Attackers could potentially craft malicious links containing parameters to trick users into performing unintended actions if URL parameters are used insecurely.

Recommendations:

    Use POST Requests: For sensitive data like passwords and personal details, use POST requests instead of GET requests. POST data is not included in the URL and is more secure.
    Avoid Storing Sensitive Data in URLs: Never expose sensitive information such as passwords in URLs.
    Input Validation and Sanitization: Ensure proper validation and encryption of sensitive data before transmission.

**Comment by parteekxo** [comment]
@ANSHIKA-26 Thanks for taking note of the vulnerability I mentioned earlier regarding the credentials being visible in the URL during the sign-up process. Since the site is hosted on GitHub Pages, which is a static hosting platform, it lacks the ability to handle server-side processing, such as securely managing form submissions. To address this, I wanted to propose a few potential solutions that could help mitigate the issue.

One approach is to use external form handlers like Formspree or Netlify Forms. These services can manage form submissions via POST requests without exposing sensitive information in the URL. They are easy to integrate and provide a secure way to handle user data without the need for a backend.

Alternatively, if the site requires more dynamic features, migrating to a platform like Heroku, Vercel, or Netlify (with serverless functions) might be a good option. These platforms provide the ability to process form submissions securely using server-side code, ensuring that credentials are not exposed in URLs or elsewhere.

**Comment by ANSHIKA-26** [comment]
ok

**Comment by ANSHIKA-26** [comment]
you can use Netlify Forms
