### ISSUE TITLE
Add Contributor/ Team Page with real-time data fetching

### ISSUE THREAD

**Issue by Prathameshzad** [ANSHIKA-26/WordWise#984]
The Contributor/Team Page serves as a dynamic showcase of the talented individuals behind the project. By leveraging real-time data fetching, the page ensures that users always have access to the most up-to-date information about team members, fostering transparency and connection. The inclusion of search and filter options enhances usability, making it easy for visitors to find specific contributors. Through this implementation, we aim to create an engaging and informative experience that highlights the collaborative nature of the project while maintaining a modern and responsive design.

**Comment by ANSHIKA-26** [comment]
its a blogging website... a contributor page would look so weird in it , im sorry but i dont want it
