### ISSUE TITLE
Feature : Improving design for showing password strength in signup and login form

### ISSUE THREAD

**Issue by ygowthamr** [ANSHIKA-26/WordWise#985]
# 🚀 Feature: Improving Password Strength Indicator Design

## 🔍 Description
I am enhancing the password strength indicator in the signup and login forms to provide clear, real-time feedback on password quality.

## 🎯 Objectives
- Implement color-coded progress bars (e.g., red, yellow, green) for better visual feedback.
- Dynamically display password requirements as users type.
- Ensure the design is mobile-responsive and accessible.

## 🛠️ Expected Benefits
- Guide users in creating stronger passwords effortlessly.
- Provide a smoother user experience with instant feedback.
- Encourage better security practices through intuitive design

## Image references : 

![image](https://github.com/user-attachments/assets/ada8199c-62b5-4f82-97bd-0f15b5ca6399)

@ANSHIKA-26 
Please assign me this issue give me labels level3,hacktoberfest,gssoc-extd.

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Can you pls add some level to this task

**Comment by haseebzaki-07** [comment]
hey @ANSHIKA-26 Can I work on this issue??

**Comment by ygowthamr** [comment]
Hey @haseebzaki-07 i am working on it.

**Comment by NK-Works** [comment]
@ANSHIKA-26 i can wok on it if you want
