### ISSUE TITLE
Secure URL and Profile Implementation

### ISSUE THREAD

**Issue by skanarul8002** [ANSHIKA-26/WordWise#988]
**Is your feature request related to a problem? Please describe.**
Yes, currently, sensitive user information such as the name and password is visible in the URL. This poses a security risk and can potentially expose user data. Additionally, there's no proper implementation to securely display the profile of a particular user after login.

**Describe the solution you'd like**
1. Implement URL encryption or token-based authentication (such as JWT) to prevent sensitive information (like name and password) from appearing in the URL.
2. Store user session data securely using cookies or local storage, and use that data to dynamically load and display user profiles upon login.
3. Add backend validations to ensure that only authenticated users can view and modify their own profiles.

**Describe alternatives you've considered**
1. Implementing OAuth for enhanced security and user authentication.
2. Using hashed URL parameters, but this is still not as secure as removing sensitive data entirely from the URL.

**Additional context**: you can see url
![Screenshot 2024-10-15 164223](https://github.com/user-attachments/assets/982ee7ea-a643-479e-b03a-d07c93608de5)

**Comment by skanarul8002** [comment]
@ANSHIKA-26 please asssign me to this task

**Comment by ANSHIKA-26** [comment]
#983 is same
