### ISSUE TITLE
Proposal for FAQ Design Upgrade

### ISSUE THREAD

**Issue by divanshiii09** [ANSHIKA-26/WordWise#991]
## Overview
This proposal outlines the need to enhance the FAQ section of the website for improved visual appeal and user experience.

## Current Issues
While scrolling through the website and reviewing the FAQ section, I noticed several areas for improvement:
- The design has a monochromatic look that isn’t visually appealing.
- The content is fine when a user expands a question by pressing the plus sign, but the overall design feels flat, with a plain white background and black text.
- There’s no clear visual differentiation between questions and answers, making it difficult for users to navigate.

## Proposed Improvements
I would like to address these issues by incorporating the following enhancements:
- *Color Contrast:* Introduce color contrasts to differentiate each question, using colors that align with the existing website palette. This will make each question visually distinct.
- *UI/UX Enhancements:* When a user expands a question, I’ll ensure the question and answer are highlighted with a distinct background and color, creating a more engaging and user-friendly experience.

## Benefits
These enhancements will:
- Improve the overall visual appeal of the FAQ section.
- Increase user engagement by making the content easier to read and navigate.
- Enhance the overall user experience on the website.

## Conclusion
By implementing these changes, we can create a more modern and visually appealing FAQ section that improves usability and encourages user interaction.

**Comment by divanshiii09** [comment]
@ANSHIKA-26  I would love to work on this issue, please assign it to me

**Comment by ANSHIKA-26** [comment]
the background and color of the section are fine , anything else you wish to change ?
