### ISSUE TITLE
Favicon Missing or Incorrect: Icon Not Displaying in Browser Tab

### ISSUE THREAD

**Issue by ayushbhjh** [ANSHIKA-26/WordWise#993]
The favicon is not displaying correctly on the website. Instead of the expected icon, a blank icon or a default browser icon appears.

To Reproduce

Go to the website homepage (or specify the page).
Open the browser's developer tools (optional, if useful).
Check the favicon section in the browser tab.
Observe that the favicon is missing or incorrect.
Expected Behavior
The correct favicon image should be displayed in the browser tab, reflecting the website's branding.

**Comment by ayushbhjh** [comment]
Please assign this task to me

**Comment by ANSHIKA-26** [comment]
hey , its because the site on github pages doesnt show favicon ,
heres another link of the site on render , this one does show favicon
https://wordwise-k9ho.onrender.com/
