### ISSUE TITLE
Issue: Navbar CSS Styling in start.html

### ISSUE THREAD

**Issue by divanshiii09** [ANSHIKA-26/WordWise#997]
### Description
The navbar in start.html currently lacks sufficient styling, making it appear inconsistent and less polished compared to the rest of the website. This inconsistency affects the overall user experience and visual appeal of the site.

---

### Steps to Reproduce
1. Navigate to start.html.
2. Observe the navbar's styling and compare it with the navbars on other pages of the website.

---

### Expected Behavior
The navbar should have uniform styling that aligns with the design aesthetics of the complete website.

---

### Suggested Improvements
- Enhance the CSS for the navbar in start.html to match the styling of the other navbars across the site.
- Ensure that colors, fonts, padding, and margins are consistent.

---

### Screenshot
<img src="https://github.com/user-attachments/assets/cfae3618-7198-4ee8-a15d-a42c679f7d6d" alt="Navbar Screenshot" style="width: 600px;">

---

**Comment by eddy1112004** [comment]
Pls assign this task to me

**Comment by divanshiii09** [comment]
@ANSHIKA-26 I would love to work on this, please assign the issue so that I can start working on it

**Comment by divanshiii09** [comment]
> @divanshiii09 make sure the navbar is consistent across all pages

okayyy

**Comment by divanshiii09** [comment]
@ANSHIKA-26, I can see that there are four files that need updating. contact.html and signup.html don't have a nav bar, and login.html and start.html need updating for their nav bars. Can you kindly increment the level of the issue, or I can make different issue requests and mention their numbers here? You can assign them to me, and I'll make the changes.

**Comment by ANSHIKA-26** [comment]
fixed issue
